### ISSUE TITLE
How to run setNotificationReceivedHandler in background ?

### ISSUE THREAD

**Issue by lubritto** [OneSignal/OneSignal-Flutter-SDK#10]
**Description:**
I'm inserting the notification on database when i receive, but if the app is terminated the method setNotificationReceivedHandler is not called, how can i solve it ?

**Comment by Nightsd01** [comment]
@lubritto This is possible but not easy, the system (iOS) will not launch your app in the background if the app was intentionally terminated.

You would need to implement a Notification Service Extension, and use `NSUserDefaults` with a shared app group to save this information. If you do this, all of your app's push notifications will have to set `mutable_content` to `true`.

**Comment by lubritto** [comment]
How can i do that in android ?

**Comment by dasundev** [comment]
I'm getting stuck with this same prob too. Anyone found a away?
