### ISSUE TITLE
flutter onesignal can't upload to appstore 

### ISSUE THREAD

**Issue by arabnewscms** [OneSignal/OneSignal-Flutter-SDK#100]
i have application with flutter 
my bundle id like that  myappname.com.myappname
i had setup this steps one by one 
but in review Runner.ipa content 
i got this info 

> Certificate: Unknown
> Profile: None
> Symbols: Included
> Architectures: armv7 and arm64

https://documentation.onesignal.com/docs/flutter-sdk-setup
and use your repo to fix my error 
but if when prepare to upload to app store with Xcode or Application loader 
i got this message if i when validate app to upload it in my app store 
if choose automatic signing or manual the same message no different 

> Unable to process application at this time due to the following error: Invalid Provisioning Profile. The provisioning profile included in the bundle myappname.com.myappname [Payload/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal..

 
some time see the bundle with this type 
myappname.com.myappname.OneSignalNotificationServiceExtension

i don't know what happens  
[✓] Flutter (Channel master, v1.4.20-pre.2, on Mac OS X 10.13.6 17G5019, locale en-EG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    ! CocoaPods out of date (1.5.0 is recommended).
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        brew upgrade cocoapods
        pod setup
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
[!] Connected device
    ! No devices available

my flutter doctor

**Comment by arabnewscms** [comment]
my problem is solved by create a new  certificate
but i have another Error 
is 

> No architectures in the binary. Lipo failed to detect any architectures in the bundle executable

**Comment by rgomezp** [comment]
Hello,
This is not a OneSignal issue. It sounds like you're having issues with your certificate/provisioning profile. There are many resources that can help you in resolving the issue, including Apple's developer [support page](https://developer.apple.com/support/). Also, take a look at Apple's official [bug reporting page](https://developer.apple.com/bug-reporting/).

**Comment by arabnewscms** [comment]
> Hello,
> This is not a OneSignal issue. It sounds like you're having issues with your certificate/provisioning profile. There are many resources that can help you in resolving the issue, including Apple's developer [support page](https://developer.apple.com/support/). Also, take a look at Apple's official [bug reporting page](https://developer.apple.com/bug-reporting/).

thank you 
you are right send my problem to apple support to see how can fix it

**Comment by andydean565** [comment]
@arabnewscms were you able to fix this ? as im having the same issues
