### ISSUE TITLE
Custom notification sounds

### ISSUE THREAD

**Issue by wrbl606** [OneSignal/OneSignal-Flutter-SDK#101]
**Description:**
I've tried to set custom notification sounds with no luck :( I've been following your [documentation](https://documentation.onesignal.com/docs/customize-notification-sounds) about setting it on Android - I added a *.wav file to `res/raw` folder in Android project but it's not picked up and sound always falls back to the default one.

**Environment**
Flutter v1.5.4-hotfix.2 stable
OneSignal: 
```
onesignalflutter:
    git: git://github.com/jmrobles/OneSignal-Flutter-SDK.git
```

**Steps to Reproduce Issue:**
Just try to set custom notification sound on Android or iOS.

**Comment by wrbl606** [comment]
After further investigation I found out that this behavior might be a bug in OneSignal's REST API:
It turned out, that when I tried to use both `android_group` + `android_sound` or `android_group` + `android_channel_id` in one request the notification was silent. Removing the `android_group` key solved the issue, but now I have missing notification grouping feature - is there any other way to group notifications on user device?

**Comment by uj** [comment]
@wrbl606 I'm using android_group + android_sound + android_channel_id and I am receiving custom sounds.  Are you uninstalling the app on your Android between each test?  If not, remember that the app cannot automatically change the android notification settings once they have already been set if you on are Android 8 or higher.

**Comment by wrbl606** [comment]
@uj Thanks for advice - it sure did help me, but also had an issue with my Android Category in OneSignal panel: I've set up custom LED color incorrectly with `#`, like `#FFFF00FF` instead of `FFFF00FF`. After removing leading `#` everything started to work properly

**Comment by alirezat66** [comment]
I am so sorry for closing this important issue. why? this issue exists and has not been solved by anybody. I can solve it in android easily but I don't know about IOS.
