### ISSUE TITLE
Build failing after migrating to OneSignal 2.0.0

### ISSUE THREAD

**Issue by getmmg** [OneSignal/OneSignal-Flutter-SDK#110]
**Description:**
Unable to run flutter project after migrating to flutter 2.0.0 

**Environment**

**Steps to Reproduce Issue:**

1. Follow the migration guide for onesignal 2.0.0 
2. Then run the flutter project flutter run you will see the build failing

**Anything else:**

`C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\FlutterRegistrarResponder.java:4: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\OneSignalPlugin.java:4: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\OneSignalTagsController.java:3: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^`
`C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\FlutterRegistrarResponder.java:57: error: cannot find symbol
   protected void runOnMainThread(@NonNull final Runnable runnable) {
                                   ^
  symbol:   class NonNull
  location: class FlutterRegistrarResponder
C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\FlutterRegistrarResponder.java:61: error: cannot find symbol
   protected void invokeMethodOnUiThread(@NonNull final String methodName, @NonNull final HashMap map) {
                                          ^`
 ` symbol:   class NonNull
  location: class FlutterRegistrarResponder
C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\FlutterRegistrarResponder.java:61: error: cannot find symbol
   protected void invokeMethodOnUiThread(@NonNull final String methodName, @NonNull final HashMap map) {
                                                                            ^
  symbol:   class NonNull
  location: class FlutterRegistrarResponder
C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\OneSignalPlugin.java:69: error: cannot find symbol
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
                            ^
  symbol:   class NonNull
  location: class OneSignalPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\OneSignalPlugin.java:69: error: cannot find symbol
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
                                                      ^
  symbol:   class NonNull
  location: class OneSignalPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\OneSignalTagsController.java:34: error: cannot find symbol
    @NonNull private AtomicBoolean replySubmitted = new AtomicBoolean(false);
     ^
  symbol:   class NonNull
  location: class OSFlutterChangeTagsHandler
C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\OneSignalTagsController.java:87: error: cannot find symbol
    public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
                              ^
  symbol:   class NonNull
  location: class OneSignalTagsController
C:\flutter\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\OneSignalTagsController.java:87: error: cannot find symbol
    public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
                                                        ^`
 ` symbol:   class NonNull
  location: class OneSignalTagsController
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.`
`11 errors
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        39.2s`
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

I have already migrated by project to androidx 
These are the lines from my gradle.properties file 

`
org.gradle.jvmargs=-Xmx1536M
extra-gen-snapshot-options=--obfuscate
android.useAndroidX=true
android.enableJetifier=true`

Also tried running after running `flutter clean` but no success

**Comment by getmmg** [comment]
commenting the below 2 lines is building sucessfully, I am closing the issue for now, however onesignal should consider migrating to AndroidX annotation library. 
 
android.useAndroidX=true 
android.enableJetifier=true

**Comment by getmmg** [comment]
`flutter build appbundle` fails If I remove the useAndroidX and enableJetifier lines. I was able to fix it by importing the androidx equivalent.

Replace `import android.support.annotation.NonNull;` with `import androidx.annotation.NonNull;` in all the applicable .java files inside <flutter_path>\.pub-cache\hosted\pub.dartlang.org\onesignal_flutter-2.0.0\android\src\main\java\com\onesignal\flutter\

**Comment by dukaric1991** [comment]
That fixed it for me:

"Replace import android.support.annotation.NonNull; with import androidx.annotation.NonNull;"

i hope it will be updated by OneSignal team in the next update.

**Comment by leonardohklaus** [comment]
After I did this, my app not running more.

**Comment by leonardohklaus** [comment]
Solved. I delete the build folder, run on prompt "flutter clean" and voilà

**Comment by fahjan** [comment]
@leonardohklaus I faced the same issue but still not working

**Comment by jkasten2** [comment]
Thanks for reporting this! Issue is now fixed in the just released 2.0.1 version.
https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/2.0.1
