### ISSUE TITLE
dose not receive notification in release version 

### ISSUE THREAD

**Issue by fahjan** [OneSignal/OneSignal-Flutter-SDK#114]
dose not receive notification in release version 
onesignal: 2.0.1
flutter: 1.7.8+hotfix.4
os: windows 

if i use onesignal in debug, it works perfectly, but when i generate app-release.apk i dose not receive any notification

**Comment by fahjan** [comment]
sorry it is my mistake,

**Comment by gotirahul96** [comment]
Can you please tell what was the mistake i'm having the same issue .
