### ISSUE TITLE
OneSignal.appContext null, could not read OneSignal from getSharedPreferences.

### ISSUE THREAD

**Issue by Denmal1982** [OneSignal/OneSignal-Flutter-SDK#115]
when starting the application, I get an error
```dart
void main() async {
  await OneSignal.shared.consentGranted(true);
  await OneSignal.shared.init(ONE_SIGNAL, iOSSettings: {
    OSiOSSettings.autoPrompt: false,
    OSiOSSettings.inAppLaunchUrl: true
  });
  OneSignal.shared.setRequiresUserPrivacyConsent(true);
  OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.notification);

  ....
}
```
```java
W/OneSignal( 5358): OneSignal.appContext null, could not read OneSignal from getSharedPreferences.
W/OneSignal( 5358): java.lang.Throwable
W/OneSignal( 5358): 	at com.onesignal.OneSignalPrefs.getSharedPrefsByName(OneSignalPrefs.java:265)
W/OneSignal( 5358): 	at com.onesignal.OneSignalPrefs.get(OneSignalPrefs.java:241)
W/OneSignal( 5358): 	at com.onesignal.OneSignalPrefs.getBool(OneSignalPrefs.java:209)
W/OneSignal( 5358): 	at com.onesignal.OneSignal.getSavedUserConsentStatus(OneSignal.java:2113)
W/OneSignal( 5358): 	at com.onesignal.OneSignal.userProvidedPrivacyConsent(OneSignal.java:720)
W/OneSignal( 5358): 	at com.onesignal.OneSignal.provideUserConsent(OneSignal.java:966)
W/OneSignal( 5358): 	at com.onesignal.flutter.OneSignalPlugin.consentGranted(OneSignalPlugin.java:187)
W/OneSignal( 5358): 	at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:76)
W/OneSignal( 5358): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
W/OneSignal( 5358): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
W/OneSignal( 5358): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
W/OneSignal( 5358): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/OneSignal( 5358): 	at android.os.MessageQueue.next(MessageQueue.java:329)
W/OneSignal( 5358): 	at android.os.Looper.loop(Looper.java:142)
W/OneSignal( 5358): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
W/OneSignal( 5358): 	at java.lang.reflect.Method.invoke(Native Method)
W/OneSignal( 5358):at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
W/OneSignal( 5358): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
D/NetworkSecurityConfig( 5358): No Network Security Config specified, using platform default
```

`onesignal_flutter: ^2.0.1`

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale
    ru-RU)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] Connected device (1 available)
```

**Comment by jkasten2** [comment]
@Denmal1982 This is actually warning, noted by the `W/` in the logcat.

You can't call `consentGranted` before initializing the OneSignal SDK. However if you need to comply with GDPR you should also call `setRequiresUserPrivacyConsent` **before** `OneSignal.init`.
See the following documentation for more details:
https://documentation.onesignal.com/docs/flutter-sdk#section--setrequiresuserprivacyconsent-

As a result your code show look like this.

```dart
void main() async {
  OneSignal.shared.setRequiresUserPrivacyConsent(true);
  await OneSignal.shared.init(ONE_SIGNAL, iOSSettings: {
    OSiOSSettings.autoPrompt: false,
    OSiOSSettings.inAppLaunchUrl: true
  });
  OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.notification);
}

// User hit the accept button your Privacy Policy in your app.
void userAcceptedYourPrivacyPolicy() {
  await OneSignal.shared.consentGranted(true);
}
```

**Comment by Denmal1982** [comment]
@jkasten2 
thanks for the reply. The problem is different now.


`W/OneSignal( 7861): OneSignalRestClient: null Error thrown from network stack. 
W/OneSignal( 7861): java.net.SocketException: Network is unreachable
W/OneSignal( 7861): 	at java.net.PlainSocketImpl.socketConnect(Native Method)
W/OneSignal( 7861): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
W/OneSignal( 7861): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
W/OneSignal( 7861): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
W/OneSignal( 7861): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
W/OneSignal( 7861): 	at java.net.Socket.connect(Socket.java:586)
W/OneSignal( 7861): 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
W/OneSignal( 7861): 	at com.android.okhttp.Connection.connectSocket(Connection.java:196)
W/OneSignal( 7861): 	at com.android.okhttp.Connection.connect(Connection.java:172)
W/OneSignal( 7861): 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
W/OneSignal( 7861): 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
W/OneSignal( 7861): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
W/OneSignal( 7861): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
W/OneSignal( 7861): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
W/OneSignal( 7861): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
W/OneSignal( 7861): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
W/OneSignal( 7861): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
W/OneSignal( 7861): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
W/OneSignal( 7861): 	at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:177)
W/OneSignal( 7861): 	at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:44)
W/OneSignal( 7861): 	at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:108)
W/OneSignal( 7861): 	at java.lang.Thread.run(Thread.java:760)`



recently there was a problem that in Russia there is no access onesignal.com, only using vpn. Perhaps the problem is related to this

**Comment by rgomezp** [comment]
We're working on the Russia issue right now. Thanks for your patience

**Comment by Denmal1982** [comment]
> We're working on the Russia issue right now. Thanks for your patience

can you tell me the cause of the problem, why there is no access? lockdown?

**Comment by Goolpe** [comment]
@Denmal1982
https://tproger.ru/news/onesignal-ip-blocking-cause/

**Comment by rgomezp** [comment]
This has been resolved. Thanks for your patience
