### ISSUE TITLE
fatal error: module map file '...notification_permissions/notification_permissions.modulemap' not found

### ISSUE THREAD

**Issue by Mapk26** [OneSignal/OneSignal-Flutter-SDK#121]
**Description:**
I followed the steps at this link:
https://documentation.onesignal.com/docs/flutter-sdk-setup

getting this error when building from Xcode:
fatal error: module map file '/Users/myusername/Library/Developer/Xcode/DerivedData/Runner-glksfybyefkngechsmchyccvzepv/Build/Products/Debug-iphoneos/notification_permissions/notification_permissions.modulemap' not found

I don't know if the path is correct or it is looking at the wrong place.

**Environment**
Version of the OneSignal Flutter SDK: 2.0.1 installed using pub
Flutter 1.7.8+hotfix.4 
Dart  2.4.0 

I'm not using Swift

**Steps to Reproduce Issue:**

1. Installed using pub
2. followed the example code for integration
3. bulld on Android successfully
4. build in iOS failed

**Comment by Mapk26** [comment]
Ok, solved removing the notification_permissions from the OneSignal extensions target.

Sorry it was a bug not related with OneSignal.

**Comment by eowoosh** [comment]
as remove? locate?
