### ISSUE TITLE
Action button always opens app, possibility to just execute background code?

### ISSUE THREAD

**Issue by rolandbodenstaff** [OneSignal/OneSignal-Flutter-SDK#123]
**Description:**
Is it possible to provide a way to call a dart function/channel instead of opening the app when clicking on an action button in a notification? For example if you want to accept or decline a meeting request by clicking on an action button without getting the app to the foreground. For example to call the setNotificationOpenedHandler callback without actually starting the app. If this is not possible maybe a way to call native code?

**Comment by jkasten2** [comment]
@rolandbodenstaff Currently there isn't an option to not open the app for either iOS or Android today when a notification is opened.

This would first need to be added to the OneSignal native iOS and Android SDK first to support it for this flutter SDK.

I have updated this ticket as a feature request.

**Comment by rgomezp** [comment]
**Enhancement/Feature:** will close this but the request will be noted and tracked internally. Will update here if/when it is made available

**Comment by vedantrathore** [comment]
Hey @rgomezp is there any progress on this? Currently I'm looking for a way to handle some logic of my app via action buttons in the notifications. One-signal was the closest thing I found to implementing it, still need this last piece of the puzzle.

**Comment by rgomezp** [comment]
Howdy @vedantrathore ,
Unfortunately this hasn't been implemented yet. Sorry for the inconvenience.

**Comment by sbilketay** [comment]
+1

**Comment by ffactory-ofcl** [comment]
+1
We're trying to implement the "Copy 2FA code" behaviour that the default Android messages app provides. It's impractical to that the app is opened when the goal is to copy and paste something into the currently visible app.

**Comment by mirrorlink** [comment]
+1

**Comment by softhaxi** [comment]
+1

**Comment by martinralfreindl** [comment]
+1 here. 

Not being able to just run background code defeats the entire purpose of the action button. Take the Google Mail "Archive" button. The whole point of that button is that it's a short-cut. If clicking on "Archive" just opened the app, then it would be redundant...
