### ISSUE TITLE
release 2.0.2 failes on travis

### ISSUE THREAD

**Issue by ErikDohmen** [OneSignal/OneSignal-Flutter-SDK#125]
**Description:**

it seems like the last release 2.0.2 failes on Travis:
https://travis-ci.org/OneSignal/OneSignal-Flutter-SDK/builds/570050084
Just wanted to install the plugin, but as this one failed on travis I'm not sure if this is the right step to do.

**Comment by ErikDohmen** [comment]
tried a solution as per answer found here:
https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/55#issuecomment-459369818
but still doesn't work out. Next error I get is:
`[!] Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension):

- Runner (true) and OneSignalNotificationServiceExtension (false) do not both set use_frameworks!.

[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `ios` with version `10.2` on target `OneSignalNotificationServiceExtension` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

`

**Comment by rgomezp** [comment]
You need to make sure you set `use_frameworks!` on either both or none of the pod targets. You can't have it on one but not the other.

**Comment by rgomezp** [comment]
Closing due to no response
