### ISSUE TITLE
Builds fails with "Failed to list versions for com.google.android.gms:play-services-location."

### ISSUE THREAD

**Issue by thoffart** [OneSignal/OneSignal-Flutter-SDK#128]
**Description:**
Whem I build the app using "onesignal_flutter: ^2.0.2" in android, this error happens:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':app:preDebugBuild'.
> > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
>    > Could not resolve com.google.android.gms:play-services-location:[15.0.0, 16.0.0).
>      Required by:
>          project :app > com.onesignal:OneSignal:3.11.2
>       > Failed to list versions for com.google.android.gms:play-services-location.
>          > Could not list versions using M2 pattern 'https://jcenter.bintray.com/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])'.
>             > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-location/'.
>                > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-location/'. Received status code 504 from server: Gateway Time-out
>    > Could not resolve com.google.android.gms:play-services-base:[15.0.0, 16.0.0).
>      Required by:
>          project :app > com.onesignal:OneSignal:3.11.2
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
>       > Skipped due to earlier error
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 9s
> Gradle task assembleDebug failed with exit code 1
> 

and when I go to [jcenter bintray](https://jcenter.bintray.com/com/google/android/gms/) the play-services-location doesn't exist.

**Environment**
1. Flutter version: 1.7.8+hotfix.4
2. onesignal_flutter: ^2.0.2
3. the SDK was added through pubspec.yaml and in the gradle following the [docs](https://documentation.onesignal.com/docs/flutter-sdk-setup) using 

> classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'

**Comment by vvasc** [comment]
Same problem here

> * What went wrong:
> 
> Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
> 
> > Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.
> 
>    > Could not resolve com.google.android.gms:play-services-location:[15.0.0, 16.0.0).
> 
>      Required by:
> 
>          project :app > com.onesignal:OneSignal:3.11.2
> 
>       > Failed to list versions for com.google.android.gms:play-services-location.
> 
>          > Could not list versions using M2 pattern 'https://jcenter.bintray.com/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])'.
> 
>             > Could not get resource 'https://jcenter.bintray.com/com/google/android/gms/play-services-location/'.
> 
>                > Could not GET 'https://jcenter.bintray.com/com/google/android/gms/play-services-location/'. Received status code 504 from server: Gateway Time-out
> 
>    > Could not resolve com.google.android.gms:play-services-base:[15.0.0, 16.0.0).
> 
>      Required by:
> 
>          project :app > com.onesignal:OneSignal:3.11.2
>

**Comment by guyzk** [comment]
Same exact problem here.
Please fix this issue. It is delaying a critical app update to the store!

**Comment by rgomezp** [comment]
@pruanl ,
Thanks for your response. Did this fix the issue for everyone? @vvasc @guyzk @thoffart

**Comment by vvasc** [comment]
yes, it was fixed

**Comment by rgomezp** [comment]
Great. Thanks @pruanl

**Comment by realacer123** [comment]
@pruanl , thanks.. you are so good

**Comment by patelkeval936** [comment]
just run    'flutter clean'       in terminal

**Comment by AppDev1020** [comment]
* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 502 from server: Bad Gateway




Same problem here Please Fix this isssue..

**Comment by AppDev1020** [comment]
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-location:16.+.

**Comment by Nishit1997** [comment]
i'm getting same error
