### ISSUE TITLE
one signal flutter  openhandler

### ISSUE THREAD

**Issue by harithany** [OneSignal/OneSignal-Flutter-SDK#132]
I try to handler notification when tap and try with this code but not work 

OneSignal.shared
        .setNotificationOpenedHandler((OSNotificationOpenedResult result) {
      // will be called whenever a notification is opened/button pressed.
       Navigator.pushNamed(context, '/setting');
    });

**Comment by rizalashidiq97** [comment]
`use Navigator.of(context).pushNamed(...)`

**Comment by rgomezp** [comment]
Hello, please follow our issue template. Thank you
