### ISSUE TITLE
Xcode linker error on building flutter created iOS project

### ISSUE THREAD

**Issue by Pradeepkn** [OneSignal/OneSignal-Flutter-SDK#134]
**Description:**

I have built a flutter application and everything is working fine in android.
On trying to build an iOS application, I always end up getting the above error.
ld: library not found for -lFMDB

I configured flutter and the application is built in a windows machine and the app works in android.
I cloned the project and tried to run on a mac using xcode.

ran the following command in terminal
flutter build ios.

Everything is fine in the terminal. But on building using Xcode, I am getting the above error.
Please help.

**Environment**

**Comment by rgomezp** [comment]
Hello, please follow our issue template. Thank you
