### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method setTimestampsInSnapshotsEnabled(Z)Lcom/google/firebase/firestore/FirebaseFirestoreSettings

### ISSUE THREAD

**Issue by topeomot2** [OneSignal/OneSignal-Flutter-SDK#141]
**Description:**

I am using the flutter plugin, and in addition to this i am using both cloud firestore and cloud function plugins. Without the onesignal pluging, the Cloud firestore plugin works well.

When i introduce the onesignal flutter sdk into the gradle file as required, I start getting the following error and the app crashes.

[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoSuchMethodError: No virtual method setTimestampsInSnapshotsEnabled(Z)Lcom/google/firebase/firestore/FirebaseFirestoreSettings$Builder; in class Lcom/google/firebase/firestore/FirebaseFirestoreSettings$Builder; or its super classes (declaration of 'com.google.firebase.firestore.FirebaseFirestoreSettings$Builder' appears in /data/app/com.ionicframework.buypowerapp334891-6JdNlBtr1nXUlUjcfKQrKA==/base.apk)

**Environment**

I am using 

cloud_firestore: ^0.12.9+4
 firebase_core: ^0.4.0
 cloud_functions: ^0.4.1+1
onesignal_flutter: ^2.0.2

and in my android gradle file

```
implementation 'com.onesignal:OneSignal:3.11.4'
````

**Steps to Reproduce Issue:**

  1. Install the OneSignal Flutter SDK using pub into your project
  2. Initialize the SDK using OneSignal.shared.init(your_app_id)
  3. run the following code

```
FirebaseAnalytics analytics = FirebaseAnalytics();
  final Firestore firestore = Firestore();
  await firestore.settings(timestampsInSnapshotsEnabled: true);
  var collection =firestore.collection('remoteConfigs');
  var querySnapshot = await collection.getDocuments();
```

**Anything else:**

The ios side works well, the crash happens when i try to run the app in android.

**Comment by rgomezp** [comment]
Can you please include your gradle file?

**Comment by jkasten2** [comment]
@topeomot2 
Please confirmed you have add the following to the very top (Line:1 ) of your `android/app/build.gradle`
```gradle
buildscript {
    repositories {
        // ...
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
    }
    dependencies {
        // ...
        // OneSignal-Gradle-Plugin
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```
This is noted in step 4 of the setup guide.
https://documentation.onesignal.com/docs/flutter-sdk-setup#section-4-add-the-onesignal-gradle-plugin-android-

**Comment by topeomot2** [comment]
It is fixeed. I added 

```
implementation 'com.google.firebase:firebase-firestore:19.0.0'
```

to app/build.gradle

**Comment by rgomezp** [comment]
Great to hear. Thanks for the update
