### ISSUE TITLE
getPermissionSubscriptionState(): subscribed false on iOS

### ISSUE THREAD

**Issue by enricobenedos** [OneSignal/OneSignal-Flutter-SDK#142]
**Description:**

When I try to ask if the current device/user is subscribed to notifications the library return me false but it is no correct 

**Environment**

I'm using `Flutter 1.9.1+hotfix.2` and `onesignal_flutter: ^2.0.0`

**Steps to Reproduce Issue:**

1. 
```
OneSignal.shared.init(appId, iOSSettings: {
      OSiOSSettings.autoPrompt: true,
      OSiOSSettings.inAppLaunchUrl: true
    });
```
2.
```
OneSignal.shared
        .setInFocusDisplayType(OSNotificationDisplayType.notification);
```
3.
```
bool _requiresConsent = await OneSignal.shared.requiresUserPrivacyConsent();
```
4.
 ```
await OneSignal.shared.consentGranted(true);
        //Set subscription
        OneSignal.shared.setSubscription(true);
```
5.
```
static Future<bool> isSubscribed() async {
    OSPermissionSubscriptionState _subInfo;
    try {
      _subInfo = await OneSignal.shared.getPermissionSubscriptionState();
    } catch (e) {
      return false;
    }
    return _subInfo.subscriptionStatus.subscribed;
  }
```

On iOS the `subscribed` property is false but the device receives notifications without problems.

**Anything else:**

I'm using iOS 12.4.1 on iPad 2018

**Comment by rgomezp** [comment]
Hello,
This issue should be resolved. It was a backend issue. Can you please confirm you are no longer seeing this?

**Comment by enricobenedos** [comment]
Thank you @rgomezp, now it seems to be solved. 
Tested on flutter `1.9.1+hotifx.4`, `iPadOS 13.1.2` and OneSignal SDK `onesignal_flutter: ^2.1.0`. 
Unfortunately seems that with this version of SDK the `setExternalUserId()` is broken on iOS. I will open a new issue after some tests
