### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by dheerajbred** [OneSignal/OneSignal-Flutter-SDK#143]
This is not an issue.
I have been using this flutter plugin for 1 month. Everything is working well. 

This is my _initState_ code in my _myhomepage.dart_
```

@override
  void initState() {
    super.initState();
    _fetchData(1);
    _internetChecker();
    
    OneSignal.shared.init("********************************************", iOSSettings: {
          OSiOSSettings.autoPrompt: false,
          OSiOSSettings.inAppLaunchUrl: true,
          
        });
    OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.notification);


    initDynamicLinks();
  }
```

I want to add a feature to the app setting page where user can choose to enable or disable notifications within the app. I have a separate _settings.dart_ page where I want to set the control to receive notifications. How can I do this?

Thanks

**Comment by enricobenedos** [comment]
Check the [setSubscription()](https://documentation.onesignal.com/docs/flutter-sdk#section--setsubscription-) method on OneSignal SDK documentations. 
You can simply disable notification using

`await OneSignal.shared.setSubscription(true);`

**Comment by rgomezp** [comment]
Thanks for answering @enricobenedos

**Comment by elmissouri16** [comment]
@rgomezp  is this the right behavior when setSubscription(false) and setSubscription(true) its will not receive the notification until you restart the app

**Comment by reisvini** [comment]
Update:

Canceling or Resubscribing to Push Notifications has changed:

New methods: 

`await OneSignal.User.pushSubscription.optOut();`

OR

`await OneSignal.User.pushSubscription.optIn();`

**Comment by Emranul-Islam** [comment]
@reisvini thanks brother you saved my day :)

**Comment by eliasayele** [comment]
@reisvini 

Thanks a lot.
