### ISSUE TITLE
User don't subscribe on Audience list

### ISSUE THREAD

**Issue by VictorCamargo** [OneSignal/OneSignal-Flutter-SDK#145]
**Description:**

Just installed onesignal_flutter package, following the instructions. When I run the application on my physical device I get an error message and the user device don't subscribe on One Signal Audience list. I'm getting the message "Player not found. Request body did not contain a device_type field"

**Environment**

onesignal_flutter: ^2.1.0

[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.13.6 17G8030, locale en-PT)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

**Steps to Reproduce Issue:**

1. Installed onesignal package
2. Run the app

**Anything else:**

```
W/OneSignal( 4302): OneSignalRestClient: POST RECEIVED JSON: {"errors":["Player not found. Request body did not contain a device_type field, so a new player could not be automatically created."]}
W/OneSignal( 4302): Failed last request. statusCode: 400
W/OneSignal( 4302): response: null
```

**Comment by mortenholmgaard** [comment]
I get the same error but just on the Android SDK.

**Comment by rgomezp** [comment]
Howdy,
Is this still happening for you guys? This should be fixed by now

**Comment by VictorCamargo** [comment]
> Howdy,
> Is this still happening for you guys? This should be fixed by now

This seems to have worked after uninstalling the app and installing it again. But my fear is if this can happen to my users.

I am using the latest version of OneSignal.

**Comment by rgomezp** [comment]
@VictorCamargo ,
This would have happened to your users if and only if they uninstalled and re-installed your app within a specific two day window around two weeks ago, which is unlikely. It's likely you only saw it because you were testing (building, rebuilding, etc...)

**Comment by skysea** [comment]
I get the same error, is there a solution?
