### ISSUE TITLE
I can't subscribe

### ISSUE THREAD

**Issue by malikdoksoz** [OneSignal/OneSignal-Flutter-SDK#148]
Android sdk 28
Flutter 1.9.1+hotfix4
I tried with the code in the example folder.

OneSignal: lastest version

`
V/OneSignal( 3162): Initializing the OneSignal Flutter SDK (2.0.0)
E/OneSignal( 3162): Cannot change requiresUserPrivacyConsent() from TRUE to FALSE
V/OneSignal( 3162): OneSignal SDK initialization delayed, user privacy consent is set to required for this application.
I/flutter ( 3162): 'trigger_3' key trigger value: three
I/flutter ( 3162): Setting consent to true
I/flutter ( 3162): Setting state
E/OneSignal( 3162): Cannot change requiresUserPrivacyConsent() from TRUE to FALSE
I/OneSignal( 3162): Restoring notifications
D/OneSignal( 3162): registerUser:registerForPushFired:false, locationFired: true, remoteParams: null, appId: 3b020ad0-88e3-44de-bd44-068cb8edb39c
D/OneSignal( 3162): Starting request to get Android parameters.
D/OneSignal( 3162): OneSignalRestClient: Making request to: https://onesignal.com/api/v1/apps/3b020ad0-88e3-44de-bd44-068cb8edb39c/android_params.js
I/OneSignal( 3162): Querying DB for notifs to restore: created_time > 1569366187 AND dismissed = 0 AND opened = 0 AND is_summary = 0 AND expire_time > 1569970987
D/NetworkSecurityConfig( 3162): No Network Security Config specified, using platform default
I/flutter ( 3162): SUBSCRIPTION STATE CHANGED: {
I/flutter ( 3162):   "from": "{
I/flutter ( 3162):   "subscribed": false,
I/flutter ( 3162):   "userSubscriptionSetting": false,
I/flutter ( 3162):   "pushToken": null,
I/flutter ( 3162):   "userId": null
I/flutter ( 3162): }",
I/flutter ( 3162):   "to": "{
I/flutter ( 3162):   "subscribed": false,
I/flutter ( 3162):   "userSubscriptionSetting": true,
I/flutter ( 3162):   "pushToken": null,
I/flutter ( 3162):   "userId": null
I/flutter ( 3162): }"
I/flutter ( 3162): }
V/OneSignal( 3162): OneSignalRestClient: After con.getResponseCode to: https://onesignal.com/api/v1/apps/3b020ad0-88e3-44de-bd44-068cb8edb39c/android_params.js
D/OneSignal( 3162): OneSignalRestClient: Successfully finished request to: https://onesignal.com/api/v1/apps/3b020ad0-88e3-44de-bd44-068cb8edb39c/android_params.js
D/OneSignal( 3162): OneSignalRestClient: GET RECEIVED JSON: {"awl_list":{},"android_sender_id":"667581731164","chnl_lst":[],"outcomes":{"direct":{"enabled":false},"indirect":{"notification_attribution":{"minutes_since_displayed":1440,"limit":10},"enabled":false},"unattributed":{"enabled":false}}}
D/OneSignal( 3162): OneSignalRestClient: Response has etag of W/"7751202b8b524669e03d9a197758216a" so caching the response.
E/OneSignal( 3162): 'Google Play services' app not installed or disabled on the device.
D/OneSignal( 3162): registerUser:registerForPushFired:true, locationFired: true, remoteParams: com.onesignal.OneSignalRemoteParams$2@33ad268, appId: 3b020ad0-88e3-44de-bd44-068cb8edb39c
I/OneSignal( 3162): Error getting Google Ad id:
I/OneSignal( 3162): com.google.android.gms.common.GooglePlayServicesNotAvailableException
I/OneSignal( 3162): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.zzc(Unknown Source:86)
I/OneSignal( 3162): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.start(Unknown Source:17)
I/OneSignal( 3162): 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source:47)
I/OneSignal( 3162): 	at com.onesignal.AdvertisingIdProviderGPS.getIdentifier(AdvertisingIdProviderGPS.java:45)
I/OneSignal( 3162): 	at com.onesignal.OneSignal.registerUserTask(OneSignal.java:1289)
I/OneSignal( 3162): 	at com.onesignal.OneSignal.access$1700(OneSignal.java:77)
I/OneSignal( 3162): 	at com.onesignal.OneSignal$7.run(OneSignal.java:1272)
I/OneSignal( 3162): 	at java.lang.Thread.run(Thread.java:764)
D/OneSignal( 3162): OneSignalRestClient: Making request to: https://onesignal.com/api/v1/players
D/OneSignal( 3162): OneSignalRestClient: POST SEND JSON: {"app_id":"3b020ad0-88e3-44de-bd44-068cb8edb39c","device_os":"9","timezone":10800,"language":"en","sdk":"031104","sdk_type":"flutter","android_package":"app.net.faloji","device_model":"Android SDK built for x86_64","game_version":1,"net_type":0,"carrier":"Android","rooted":true,"device_type":1,"notification_types":-7}
V/OneSignal( 3162): OneSignalRestClient: After con.getResponseCode to: https://onesignal.com/api/v1/players
D/OneSignal( 3162): OneSignalRestClient: Successfully finished request to: https://onesignal.com/api/v1/players
D/OneSignal( 3162): OneSignalRestClient: POST RECEIVED JSON: {"success":true,"id":"20155767-de12-4288-9ad4-f0933a9ae743"}
D/OneSignal( 3162): doCreateOrNewSession:response: {"success":true,"id":"20155767-de12-4288-9ad4-f0933a9ae743"}
I/OneSignal( 3162): Device registered, UserId = 20155767-de12-4288-9ad4-f0933a9ae743
I/flutter ( 3162): SUBSCRIPTION STATE CHANGED: {
I/flutter ( 3162):   "from": "{
I/flutter ( 3162):   "subscribed": false,
I/flutter ( 3162):   "userSubscriptionSetting": true,
I/flutter ( 3162):   "pushToken": null,
I/flutter ( 3162):   "userId": null
I/flutter ( 3162): }",
I/flutter ( 3162):   "to": "{
I/flutter ( 3162):   "subscribed": false,
I/flutter ( 3162):   "userSubscriptionSetting": true,
I/flutter ( 3162):   "pushToken": null,
I/flutter ( 3162):   "userId": "20155767-de12-4288-9ad4-f0933a9ae743"
I/flutter ( 3162): }"
I/flutter ( 3162): }
I/flutter ( 3162): Prompting for Permission
E/OneSignal( 3162): promptPermission() is not applicable in Android
I/flutter ( 3162): Accepted permission: null
I/flutter ( 3162): Getting permissionSubscriptionState
D/OneSignal( 3162): OneSignalRestClient: Making request to: https://onesignal.com/api/v1/notifications/
D/OneSignal( 3162): OneSignalRestClient: POST SEND JSON: {"buttons":[{"icon":null,"id":"id1","text":"test1"},{"icon":null,"id":"id2","text":"test2"}],"contents":{"en":"this is a test from OneSignal's Flutter SDK"},"headings":{"en":"Test Notification"},"ios_attachments":{"id1":"http:\/\/cdn1-www.dogtime.com\/assets\/uploads\/gallery\/30-impossibly-cute-puppies\/impossibly-cute-puppy-2.jpg"},"big_picture":"http:\/\/cdn1-www.dogtime.com\/assets\/uploads\/gallery\/30-impossibly-cute-puppies\/impossibly-cute-puppy-2.jpg","include_player_ids":["20155767-de12-4288-9ad4-f0933a9ae743"],"app_id":"3b020ad0-88e3-44de-bd44-068cb8edb39c"}
V/OneSignal( 3162): OneSignalRestClient: After con.getResponseCode to: https://onesignal.com/api/v1/notifications/
D/OneSignal( 3162): OneSignalRestClient: Successfully finished request to: https://onesignal.com/api/v1/notifications/
D/OneSignal( 3162): OneSignalRestClient: POST RECEIVED JSON: {"id":"","recipients":0,"errors":{"invalid_player_ids":["20155767-de12-4288-9ad4-f0933a9ae743"]}}
D/OneSignal( 3162): HTTP create notification success: {"id":"","recipients":0,"errors":{"invalid_player_ids":["20155767-de12-4288-9ad4-f0933a9ae743"]}}
E/flutter ( 3162): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(OneSignal, Encountered an error attempting to post notification: {"id":"","recipients":0,"errors":{"invalid_player_ids":["20155767-de12-4288-9ad4-f0933a9ae743"]}}, {recipients: 0, id: , errors: {invalid_player_ids: [20155767-de12-4288-9ad4-f0933a9ae743]}})
[38;5;244mE/flutter ( 3162): #0      StandardMethodCodec.decodeEnvelope[39;49m
[38;5;244mE/flutter ( 3162): #1      MethodChannel.invokeMethod[39;49m
E/flutter ( 3162): <asynchronous suspension>
[38;5;248mE/flutter ( 3162): #2      OneSignal.postNotification[39;49m
E/flutter ( 3162): <asynchronous suspension>
[38;5;248mE/flutter ( 3162): #3      _OneSignalViewState._handleSendNotification[39;49m
E/flutter ( 3162): <asynchronous suspension>
[38;5;244mE/flutter ( 3162): #4      _InkResponseState._handleTap[39;49m
[38;5;244mE/flutter ( 3162): #5      _InkResponseState.build.<anonymous closure>[39;49m
[38;5;244mE/flutter ( 3162): #6      GestureRecognizer.invokeCallback[39;49m
[38;5;244mE/flutter ( 3162): #7      TapGestureRecognizer._checkUp[39;49m
[38;5;244mE/flutter ( 3162): #8      TapGestureRecognizer.acceptGesture[39;49m
[38;5;244mE/flutter ( 3162): #9      GestureArenaManager.sweep[39;49m
[38;5;244mE/flutter ( 3162): #10     GestureBinding.handleEvent[39;49m
[38;5;244mE/flutter ( 3162): #11     GestureBinding.dispatchEvent[39;49m
[38;5;244mE/flutter ( 3162): #12     GestureBinding._handlePointerEvent[39;49m
[38;5;244mE/flutter ( 3162): #13     GestureBinding._flushPointerEventQueue[39;49m
[38;5;244mE/flutter ( 3162): #14     GestureBinding._handlePointerDataPacket[39;49m
[38;5;244mE/flutter ( 3162): #15     _rootRunUnary  (dart:async/zone.dart:1136:13)[39;49m
[38;5;244mE/flutter ( 3162): #16     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)[39;49m
[38;5;244mE/flutter ( 3162): #17     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)[39;49m
[38;5;244mE/flutter ( 3162): #18     _invoke1  (dart:ui/hooks.dart:263:10)[39;49m
[38;5;244mE/flutter ( 3162): #19     _dispatchPointerDataPacket  (dart:ui/hooks.dart:172:5)[39;49m
E/flutter ( 3162):
`

**Comment by andrefcferreira** [comment]
I am in the same situation after upgrading to Flutter 1.9

**Comment by malikdoksoz** [comment]
It wasn't because I used a Google emulator without the api.

**Comment by MustafaGamalAbbas** [comment]
What was the problem be? 
@malikdoksoz

**Comment by zain1629** [comment]
Is this issue fixed? i am getting the same issue with react native

**Comment by dineshreddy1995** [comment]
Any solution?

**Comment by jkasten2** [comment]
This part of the error in the log seems to be the root cause:
`E/OneSignal( 3162): 'Google Play services' app not installed or disabled on the device.`

If you are seeing this exact error in the logcat on your Android emulator make sure you are testing on one the comes with Google Play services. If this is a real device you may have to open the "Play Store" once to get it activated.
If you continue to see the same error go to all apps on your device a search for 'Google Play services' to ensure it is not disabled.

**Comment by wahyu-handayani** [comment]
Hi I am getting the same issue, is there any solution for flutter
