### ISSUE TITLE
Open page with argument when notification open with custom data

### ISSUE THREAD

**Issue by royrakesh** [OneSignal/OneSignal-Flutter-SDK#159]
**Description:**

I am sending one additional data (example post_id) with notification. when notification is open i am able to parse the Json data and able to get the value of post_id. Now i am unable to navigate to PostPage (which accepts an argument postid) as context is not available there. 

**Environment**
 onesignal_flutter: ^2.1.0

**Steps to Reproduce Issue:**

  1. Install the OneSignal Flutter SDK using pub into your project
  2. Initialize the SDK using OneSignal.shared.init(your_app_id)
  3. Create  a class to init os http://prntscr.com/pkfpxp and then call it inside main.dart http://prntscr.com/pkfqj5 , my PostPage accept argument http://prntscr.com/pkfvc5

```
λ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.15-pre.95, on Microsoft Windows [Version 10.0.17763.775], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] VS Code (version 1.39.2)
[√] Connected device (1 available)

• No issues found!
```

**Comment by rgomezp** [comment]
If the additional data is arriving successfully, this means that the issue is not related to OneSignal. Are you seeing any errors/warnings in the console?

**Comment by royrakesh** [comment]
There is no error, can you give me some reference where we can use the additional   data to navigate to other page with argument. ( people may need this feature when they want to open notification in app and the redirect to a page like a single post page with an ID ).

* not a bug though its a must have feature for app.

**Comment by rgomezp** [comment]
Unfortunately, this is a Flutter-specific question. There are plenty of resources that you can check out for help on setting up routing for your app: https://medium.com/coding-with-flutter/my-favourite-list-of-flutter-resources-523adc611cbe
