### ISSUE TITLE
NotificationReceivedHandler is not running when app is terminated (android and ios)

### ISSUE THREAD

**Issue by lubritto** [OneSignal/OneSignal-Flutter-SDK#16]
NotificationReceivedHandler is not running when app is terminated (android and ios)

**Comment by Nightsd01** [comment]
The system will not launch apps in the background if they were terminated by the user - this is a system restriction.

In other cases you can use `content-available`, look here for more info: 
https://documentation.onesignal.com/docs/silent-notifications

PS: Please do not post one line issues.
