### ISSUE TITLE
Create notification for Segments?

### ISSUE THREAD

**Issue by gusargentina** [OneSignal/OneSignal-Flutter-SDK#164]
This is not an issue, i want to know if there is a way to specify which segments to send to, and, optionally, which ones you don't.  Like "active users" or "subscribed users".
At the moment i am first sending a request to get the list of players into a List and then using that in playerIds: 
but it would great to just create a notification for a segment instead of specifying each playerid. 

OSCreateNotification(
        playerIds: playerIdList,        
        content: descripcion,
        heading: titulo,)

**Comment by rgomezp** [comment]
Yes, take a look at our REST API [docs](https://documentation.onesignal.com/reference#create-notification)

**Comment by asadhameed87** [comment]
Can you please tell me how you are requesting all the player ids from OneSignal ?
