### ISSUE TITLE
Notification Received event not working when app is exited / force-quit

### ISSUE THREAD

**Issue by anil-sookshum** [OneSignal/OneSignal-Flutter-SDK#165]
Is it possible to execute any function when the notification is received? Working fine when the app is in foreground and background but not working when the app is closed or not opened.

**Comment by doanbh** [comment]
Same issue

My start was a splash screen, but when I closed the app, and sent a notification from our server, then the user touched the notification, I wanted to redirect the user to another screen, not right splash screen, I use dart to do this, it works fine with Android but not iOS

**Comment by freshcodestechnology** [comment]
I need to execute dart code on Notification Received (for inserting notification data/Payload into SQFlite Database) even if application is not active (Cleared).

It works fine when application is active or on notification tap when application is not active but without tapping notification when application is not active then it doesn't works.

**Comment by rgomezp** [comment]
Unfortunately not, this is a limitation of [iOS](https://documentation.onesignal.com/docs/ios-native-sdk#section-receiving-notifications)
