### ISSUE TITLE
Navigate the screen when the application is closed, does not work on iOS

### ISSUE THREAD

**Issue by doanbh** [OneSignal/OneSignal-Flutter-SDK#167]
My start was a splash screen, but when I closed the app, and sent a notification from our server, then the user touched the notification, I wanted to redirect the user to another screen, not right splash screen, I use dart to do this, it works fine with Android but not iOS.

**Comment by chrystoffer** [comment]
Could you show an example of how you developed this on android? I need

**Comment by rgomezp** [comment]
Please reach out to our support channel at OneSignal.com for these types of questions
