### ISSUE TITLE
Duplicate Symbols found issue

### ISSUE THREAD

**Issue by GadepalliAditya1998** [OneSignal/OneSignal-Flutter-SDK#169]
I was getting previously framework not found error. Which i fixed it by adding the missing frameworks that prevented the build in Linker frameworks of the xcode->Targets->One Signal Extension.

Later I am getting this error while building for ios with one signal integration.

duplicate symbol found in 
        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kServiceInfoFileType in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _OBJC_IVAR_$_FIROptions._deepLinkURLScheme in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kServiceInfoFileName in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRIsAnalyticsCollectionDeactivated in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRIsMeasurementEnabled in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRIsAnalyticsEnabled in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRIsAnalyticsCollectionEnabled in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRIsSignInEnabled in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _OBJC_IVAR_$_FIROptions._editingLocked in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRDatabaseURL in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRAndroidClientID in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRClientID in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRProjectID in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRGCMSenderID in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _OBJC_IVAR_$_FIROptions._appGroupID in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRGoogleAppID in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRLibraryVersionID in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRTrackingID in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    duplicate symbol _kFIRBundleID in:

        <ApplicationDirectoryPath>/build/ios/Debug Development-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIROptions.o)

    ld: 295 duplicate symbols for architecture arm64

    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not build the precompiled application for the device.

Error launching application on Keka iphone 5s.

**Comment by rgomezp** [comment]
Please follow our issue template

**Comment by rgomezp** [comment]
Hello, please follow our issue template so we can better assist you
