### ISSUE TITLE
Does this plugin use advertisingIdentifier?

### ISSUE THREAD

**Issue by lifenautjoe** [OneSignal/OneSignal-Flutter-SDK#172]
We're trying to submit our app for revision. We do not use the Apple advertisingIdentifier for any purpose nor serve ads on the platform. However we have noted that the line does exist in the iOS OneSignal SDK accessing the advertisingIdentifier.

Does including this plugin in my app will get our app forever banned from the AppStore because it uses the Apple advertisingIdentifier?

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/12737509/68796912-e6a75680-0653-11ea-9d9d-0fea9a14d32d.png">

**Comment by lifenautjoe** [comment]
For reference, this is where advertisingIdentifier exists in the iOS plugin 

https://github.com/OneSignal/OneSignal-iOS-SDK/blob/72cb08ed24e8be4f3ad0e9c95c00e7dd575808a1/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L1533

**Comment by rgomezp** [comment]
Hi there, OneSignal does not use the IDFA unless you have another plugin that requires it. You can remove the AdSupport.framework or Advertising.framework if it was added to your project by mistake.

If you need it for another plugin / SDK please answer Apple’s questions based on the plugin that requires it.

Cheers

**Comment by EffyCoder** [comment]
@lifenautjoe how did you solve this?

`my-app% grep -lr "advertisingIdentifier" * | grep -v .svn | grep -v .md

ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Versions/A/OneSignal
ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/Versions/Current/OneSignal
ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal`

I too have found this.
@rgomezp how can I remove these framework. I want one signal sdk but not the IDFA. Please help me resolve this.

**Comment by rgomezp** [comment]
@EffyCoder ,
Hello, we just answered this same question in this [thread](https://github.com/OneSignal/react-native-onesignal/issues/1029#issuecomment-680301337). Please take a look and let us know if you have any further questions. Enjoy!
