### ISSUE TITLE
Invoke Flutter methods from the extended notification service

### ISSUE THREAD

**Issue by gary6lin** [OneSignal/OneSignal-Flutter-SDK#174]
Hi, I am trying to use an extended notification service in my app, so I can do something when I receive a remote notification while the app is in the background or removed from the task manager.

However, there is no callback handler in the OneSignal Flutter plugin for the "didReceive" method in UNNotificationServiceExtension.

As stated in the documentation, "setNotificationReceivedHandler" will only be called when the app is in the foreground.

Is there any way to invoke a method in Flutter from UNNotificationServiceExtension? So I can keep the business logic in the main Flutter app.

Thanks.

**Comment by rgomezp** [comment]
Hello,
You're looking for the **Notification Received Handler**:

The sdk calls this method when the app receives a notification while in focus only. If you need this to be called when your app is in the background, `set content_available` to `true` when you create your notification. The "force-quit" state (i.e app was swiped away) is not currently supported.

You can read more [here](https://documentation.onesignal.com/docs/sdk-reference#section-notification-received-handler). Enjoy!
