### ISSUE TITLE
Use with AdMob app dies.

### ISSUE THREAD

**Issue by hayasisuny-web** [OneSignal/OneSignal-Flutter-SDK#178]
Use with AdMob app dies.

package : firebase_admob

**Comment by jkasten2** [comment]
@hayasisuny-web Please provide the following details so we can investigate the issue.
1. Exact version of firebase_admob
2. Which version of iOS and/or Android does it crash on
3. Provide a crash log
   - Android (use logcat)
   - iOS (Run with Xcode to get the log)
4. Exact steps to reproduce.
   - Does it require to AdMob to be setup or just added as a dependency

**Comment by hayasisuny** [comment]
sample source link
http://dyacryl.iwinv.net/1.zip
http://dyacryl.iwinv.net/2.zip

**Comment by rgomezp** [comment]
This is not a valid issue submission. Please follow our issue template in order for us to be able to help you
