### ISSUE TITLE
iOS - Build error with GoogleDataTransport

### ISSUE THREAD

**Issue by Ahmedtaha123** [OneSignal/OneSignal-Flutter-SDK#183]
i got this error when i run my app in ios

/Users/jaadara/Desktop/cicr_lib_final/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:221:26: error: no known class method for selector 'unarchivedObjectOfClass:fromData:error:'
          [NSKeyedUnarchiver unarchivedObjectOfClass:[GDTCORStorage class] fromData:data error:&error];
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/jaadara/Desktop/cicr_lib_final/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:243:39: error: no known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'
          NSData *data = [NSKeyedArchiver archivedDataWithRootObject:self
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/jaadara/Desktop/cicr_lib_final/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m:262:37: error: no known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'
        NSData *data = [NSKeyedArchiver archivedDataWithRootObject:self

and my pod file

# Using a CDN with CocoaPods 1.7.2 or later can save a lot of time on pod installation, but it's experimental rather than the default.
# source 'https://cdn.cocoapods.org/'

# Uncomment this line to define a global platform for your project
# platform :ios, '10.3'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  #use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
#install! 'cocoapods', :disable_input_output_paths => true

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
pod 'Firebase/Core'
install! 'cocoapods', :disable_input_output_paths => true

and i work in xcode 10.3
and i follow all steps in one signal guide in this link to setup one signal sdk
https://documentation.onesignal.com/docs/flutter-sdk-setup
 
i tried allot of times but no any solution 
any help please.

**Comment by jkasten2** [comment]
@Ahmedtaha123 The error is pointing to a compile error with `GoogleDataTransport` that doesn't look related to OneSignal.

If the problem only happens after adding OneSignal please provide exact steps on reproducing the issue with a new Flutter project.

**Comment by callumclift** [comment]
@Ahmedtaha123 i'm getting a similar issue, did you find a fix for this?

**Comment by rgomezp** [comment]
This doesn't seem to be a OneSignal issue. If you can provide information that says otherwise I'll happily reopen this issue
