### ISSUE TITLE
clearOneSignalNotifications

### ISSUE THREAD

**Issue by Denmal1982** [OneSignal/OneSignal-Flutter-SDK#184]
please tell me how to remove all notifications.

**Comment by dukaric1991** [comment]
Just about to ask the same question. When the user has notification/s from the app, and if he goes straight to the app i should be able to clear all notifications from this app :)

**Comment by hcaz** [comment]
It would be good to see something added to support this

**Comment by musathegeek** [comment]
How to cancel a notification based on the notification Id. In the documentation, there is support fo JAVA, but not in the flutter

**Comment by mubasshir** [comment]
any solution to this?

**Comment by ducnmhn** [comment]
any plan to do this ?

**Comment by jarjut** [comment]
is it already available ?

try this
```dart
OneSignal.shared.clearOneSignalNotifications();
```
