### ISSUE TITLE
How to generate mobileprovision for OneSignal extension

### ISSUE THREAD

**Issue by rok5ek** [OneSignal/OneSignal-Flutter-SDK#187]
**Description:**
I'm trying to generate a .mobileprovision for OneSignal extension. Currently I generated a new certificate with the https://onesignal.com/provisionator, my new certificate with was generated with type "Apple Push Services". How can I now create a provisioning profile for OneSignal extension?

(your description here)

**Environment**

1. Version 2.0.2

**Steps to Reproduce Issue:**

1. Create certificate with https://onesignal.com/provisionator

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@rok5ek No need to create a .mobileprovision file or a push cert for extension target since it is part of the same app. No need to add capabilities to the extension either, only the main target needs them.

**Comment by malvinpratama** [comment]
any solutions? @jkasten2 @rok5ek 
i got this error
![image](https://user-images.githubusercontent.com/45458498/123618308-460aa800-d832-11eb-89a6-887443a28621.png)
