### ISSUE TITLE
can't find Capabilitie Push Notification into Xcode

### ISSUE THREAD

**Issue by fabianogadenz** [OneSignal/OneSignal-Flutter-SDK#188]
Hello, I came across a difficulty. My app is working perfectly on Android, today I'm migrating to iOS.
Following the setup [guide steps ](https://documentation.onesignal.com/docs/flutter-sdk-setup), into step 3 i can't find Capabilitie Push Notification.

Options that appear to me:

- Data Protection.
- Fonts.
- HealthKit.
- HomeKit.
- Inter-App Audio.
- Keychain Sharing.
- Maps.
- Sign in with Apple.
- Wireless Acessory Configuration.

Does anyone know what I may be doing wrong?

My XCode Version: 11.2.1.
  onesignal_flutter: ^2.2.0

**Comment by fabianogadenz** [comment]
I think the issue may be because my developer application with apple is being processed. Can anyone confirm me if this is true?

**Comment by jkasten2** [comment]
@fabianogadenz "Push Notifications" capabilities are only possible if you have a paid Apple developer account. Please provide details on the exact errors if you still have an issue after this.
