### ISSUE TITLE
Support Send to a specific segment, send based on Filter/Tags in mobile sdk 

### ISSUE THREAD

**Issue by asapJ** [OneSignal/OneSignal-Flutter-SDK#191]
**Description:**

https://documentation.onesignal.com/reference#create-notification

The link above shows how ```createNotification``` can be tweaked to support sending notification to a specific segment of users, send based on Filter/Tags. But the current ```creatNotification``` method only exposes sending by playerId. 

Can this features (specifying segment/tags) be support via the mobile sdk?

PS: when player ID is omitted, OneSignal returns an error stating that either playerID, segments or tags be supplied. But the sdk only currently supports via playerId. 

If there is an existing way to achieve this, please point me to it and I will close the issue.

**Environment**
1. OneSignal version: 2.3.1
2. Flutter sdk: 1.12.x

**Comment by jkasten2** [comment]
@asapJ For security reasons you can only target by player_id. If you need to target devices in other ways you will need to make a call from your app to your back-end, from your server you can than make a REST API call where it is safe. 

The error you are seeing with other options is the response directly from the OneSignal REST API. We will look into adding a SDK specific error so this isn't misleading. Thanks.
