### ISSUE TITLE
Can't use service extensions

### ISSUE THREAD

**Issue by MrTarantula** [OneSignal/OneSignal-Flutter-SDK#192]
**Description:**

I have installed the SDK and it works. I then followed the [instructions](https://documentation.onesignal.com/docs/service-extensions) to add the notification extender service in Android.

**Environment**

1. Latest OneSignal SDK (2.3.1)
2. Added through pubspec.yaml
3. OneSignal works without extension

**Steps to Reproduce Issue:**

1. Install OneSignal in pubspec.yaml
2. Follow instructions to setup SDK
3. Add example service extension

**Anything else:**

```
[+25628 ms] C:\Users\me\myapp\android\app\src\main\java\com\myorg\myapp\MyNotifications.java:6: error: cannot find symbol
[   +1 ms]    protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
[        ]                                               ^
[        ]   symbol:   class OSNotificationReceivedResult
[        ]   location: class MyNotifications
[        ] 1 error
[  +77 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileDevDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 25s
Gradle task assembleDevDebug failed with exit code 1
Exited (sigterm)

```

**Comment by MrTarantula** [comment]
I figured it out. It looks like the examples omit several needed imports, along with being outdated (no AndroidX). I use VS Code with no Java extensions installed so I wasn't getting the errors. I opened in Android Studio and immediately got reference errors. An update to step 3 of [the instructions](https://documentation.onesignal.com/docs/service-extensions#section-notification-extender-service) would look something like this:

```java
package com.myorg.myapp;

import androidx.core.app.NotificationCompat;
import com.onesignal.OSNotificationDisplayedResult;
import com.onesignal.OSNotificationReceivedResult;
import com.onesignal.NotificationExtenderService;
import java.math.BigInteger;

public class NotificationExtenderExample extends NotificationExtenderService {
   @Override
   protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
      OverrideSettings overrideSettings = new OverrideSettings();
      overrideSettings.extender = new NotificationCompat.Extender() {
         @Override
         public NotificationCompat.Builder extend(NotificationCompat.Builder builder) {
            // Sets the background notification color to Green on Android 5.0+ devices.
            return builder.setColor(new BigInteger("FF00FF00", 16).intValue());
         }
      };

      OSNotificationDisplayedResult displayedResult = displayNotification(overrideSettings);
      //Log.d("OneSignalExample", "Notification displayed with id: " + displayedResult.androidNotificationId);

      return true;
   }
}
```

**Comment by ajonno** [comment]
brilliant thank you

**Comment by mikechoch** [comment]
Closing as @MrTarantula figured out it

**Comment by faithomotoso** [comment]
I also have this problem and I don't know how to resolve it. I keep getting unable to resolve symbol making it impossible to extend the class

**Comment by MohitGupta121** [comment]
Same issue but my this import **com.onesignal.NotificationExtenderService**;
 Not not fixed, its showing error 
And all other onsignal. Objects
I try latest dependency of Onsignal, old and from documentation but its still not fixed.

What I'll do please help to resolve this
