### ISSUE TITLE
Should I add this configuration code?

### ISSUE THREAD

**Issue by tapkain** [OneSignal/OneSignal-Flutter-SDK#194]
In the official firebase_messaging repo there's a step for iOS to app this code to the Flutter app delegate

```
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
```

is this true for OneSignal also?

**Comment by jkasten2** [comment]
@tapkain This step isn't needed for OneSignal, the OneSignal SDK automatically sets up the `UNUserNotificationCenter` for you.
