### ISSUE TITLE
How disable location tracking for iOS

### ISSUE THREAD

**Issue by callumclift** [OneSignal/OneSignal-Flutter-SDK#196]
Is there a setting you can use to disable flutter onesignal from storing a users location point? This way if a user doesn't enable location services i'll still be able to send them push notifications.

I'm using the latest version of onsignal for flutter installed in my pubspec: onesignal_flutter: ^2.3.1

**Comment by rgomezp** [comment]
Take a look at the OneSignal [documentation](https://documentation.onesignal.com/docs/flutter-sdk#section--setlocationshared-)
