### ISSUE TITLE
请问可以在中国大陆使用么？

### ISSUE THREAD

**Issue by byteslaves** [OneSignal/OneSignal-Flutter-SDK#198]
你好。
请问可以在中国大陆使用吗？中国的绝大部分安卓都是去谷歌魔改版，各品牌都有自己的推送服务器，而且所有关于谷歌的服务都被屏蔽了，就连flutter都都要使用镜像站。

**Comment by jkasten2** [comment]
> **Can I use it in mainland China?**
Hello there.
Can I use it in mainland China? Most of the Androids in China are modified by Google Magic. Each brand has its own push server, and all Google services are blocked. Even Flutter uses mirror stations.
*From Google translate*

OneSignal will work in mainland China for iOS and Kindle FireOS devices. It won't work for Android devices as OneSignal requires a connection to Google's FCM service which is blocked by China. Also most phones sold in mainland China do not have the require "Google Play services" app installed which is required as well.

OneSignal doesn't support any other push gateways other than FCM for Android.

**Comment by byteslaves** [comment]
> > **Can I use it in mainland China?**
> > Hello there.
> > Can I use it in mainland China? Most of the Androids in China are modified by Google Magic. Each brand has its own push server, and all Google services are blocked. Even Flutter uses mirror stations.
> > _From Google translate_
> 
> OneSignal will work in mainland China for iOS and Kindle FireOS devices. It won't work for Android devices as OneSignal requires a connection to Google's FCM service which is blocked by China. Also most phones sold in mainland China do not have the require "Google Play services" app installed which is required as well.
> 
> OneSignal doesn't support any other push gateways other than FCM for Android.

@jkasten2 Thank you, this is really a pity

**Comment by Hotcapsicum** [comment]
Can I use it in mainland China for microsoft edge? edge use web-push by WNS ， and WNS is able to use in China
