### ISSUE TITLE
Subscription status is always false

### ISSUE THREAD

**Issue by gaojuanjuan** [OneSignal/OneSignal-Flutter-SDK#202]
ios:
![image](https://user-images.githubusercontent.com/14133759/72659690-b0dd7000-39fe-11ea-9ba5-29837d1a2179.png)

**Comment by andrefcferreira** [comment]
Are you using the `OneSignal.shared.setSubscription(true)` method?

**Comment by andrefcferreira** [comment]
I use to store locally the user preferences, on init i check if the user preferences and setSubscription(Boolean {user.preferences.notifications}). I hope it helps you :)

**Comment by wahyu-handayani** [comment]
> ios: ![image](https://user-images.githubusercontent.com/14133759/72659690-b0dd7000-39fe-11ea-9ba5-29837d1a2179.png)

I have the same case like yours, did you find any solution ?
