### ISSUE TITLE
Problem when notification receive 

### ISSUE THREAD

**Issue by bal3m** [OneSignal/OneSignal-Flutter-SDK#203]
I installed OneSignal in my WordPress blog to send notification to my Flutter app when new post added and it works fine, but my problem is when i click on received notification it redirect me to the post on my blog website, not my app, So i need some help hear to make it opened the app when i click on received notification.
Thanks.

**Comment by andrefcferreira** [comment]
Hello! Are you sending the URL as aditionalData or as Launch URL?
How is your setNotificationOpenedHandler defined? Could you share it with us?

**Comment by bal3m** [comment]
Hello! Thank you for your response, I'm not using any configuration in the data that comes to me, the notification comes from OneSignal plugin from my WordPress blog, And in my flutter app i used the default configuration that i followed from OneSignal documentation of Flutter installation, So that's the cod i used in my app:
///////////////////////////////////////////////////////////////////////////////////////
 OneSignal.shared.setNotificationReceivedHandler((OSNotification notification) {
	// will be called whenever a notification is received
});

OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {
  // will be called whenever a notification is opened/button pressed.
});

OneSignal.shared.setPermissionObserver((OSPermissionStateChanges changes) {
	// will be called whenever the permission changes
	// (ie. user taps Allow on the permission prompt in iOS)
});

OneSignal.shared.setSubscriptionObserver((OSSubscriptionStateChanges changes) {
	// will be called whenever the subscription changes 
	//(ie. user gets registered with OneSignal and gets a user ID)
});

OneSignal.shared.setEmailSubscriptionObserver((OSEmailSubscriptionStateChanges emailChanges) {
	// will be called whenever then user's email subscription changes
	// (ie. OneSignal.setEmail(email) is called and the user gets registered
});

// For each of the above functions, you can also pass in a 
// reference to a function as well:

void _handleNotificationReceived(OSNotification notification) {
  
}

void main() {
  OneSignal.shared.setNotificationReceivedHandler(_handleNotificationReceived);
}
///////////////////////////////////////////////////////

**Comment by bal3m** [comment]
Ooooooah!!! 
I found it and it's work.
this is the solution 
https://documentation.onesignal.com/docs/web-push-wordpress-faq#section-sending-notifications-only-to-mobile-apps-not-browsers
