### ISSUE TITLE
App closed notification click issue

### ISSUE THREAD

**Issue by Chunlee17** [OneSignal/OneSignal-Flutter-SDK#204]
/CONTRIBUTING.md
-->

**Description:**
app closed, click on notificaiton then setNotificationOpenedHandler get called before main app even start, this cause abnormal behavior

**Environment**
1. onesignal_flutter: ^2.3.2
2. using pub

**Steps to Reproduce Issue:*
1 .on setNotificationOpenedHandler use global navigator key to push to route on notification click 
2. Force close the app
3. Send notificaiton
4. click on the notificaiton
5. App open, setNotificationOpenedHandler get called then it navigate to the route you defined, the route pop automatically that make you navigate back to initial route

**Comment by rgomezp** [comment]
Howdy,
I'm not really sure what you mean here. Can you please try rephrasing?

**Comment by rgomezp** [comment]
Closing due to no response
