### ISSUE TITLE
The badge number for iOS does not increment after adding the firebase plugins for flutter.

### ISSUE THREAD

**Issue by superakabo** [OneSignal/OneSignal-Flutter-SDK#205]
**Description:**
The badge number for iOS does not increment after adding most of the Firebase plugins for flutter. I noticed this after adding Firebase Dynamic Links and Firebase Authentication plugins. Without these Firebase plugins, everything works well. 

Notifications I send use: 
"ios_badgeType": "Increase",
"ios_badgeCount": 1,

I have also added the OneSignalNotification extension, configured App Groups, Push Notification and Background Modes.

**Environment**
Firebase Flutter Plugins:
firebase_core: ^0.4.3+2
firebase_analytics: ^5.0.9
firebase_auth: ^0.15.4
cloud_firestore: ^0.13.0+1
firebase_storage: ^3.1.1
firebase_dynamic_links: ^0.5.0+9
firebase_crashlytics: ^0.1.2+4

OneSignal Flutter Plugin:
onesignal_flutter: ^2.3.2

The iOS Podfile contains:
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.12.5', '< 3.0'
end

Flutter Doctor Output:
[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.14.6 18G95, locale en-GB)
    • Flutter version 1.13.6 at /../../../Flutter/sdk
    • Framework revision 659dc8129d (5 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /../.../../Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone • iOS 12.4.1

**Steps to Reproduce Issue:**
<!--
  Example:

1.  Create a new Flutter Project.

2.  Configure the project to use OneSignal Flutter - iOS.

3.  Add the following Flutter Firebase Plugins:
     firebase_core: ^0.4.3+2
     firebase_analytics: ^5.0.9
     firebase_auth: ^0.15.4
     cloud_firestore: ^0.13.0+1
     firebase_storage: ^3.1.1
     firebase_dynamic_links: ^0.5.0+9
     firebase_crashlytics: ^0.1.2+4

4.  Attempt to receive a push notification by creating a notification with these parameters this for example
   {
	"app_id": "xxxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxx",
	"contents": {"en": "This is the body of the notification"},
	"headings": {"en": "This is the title of the notification"},
	"ios_badgeType": "Increase",
	"ios_badgeCount": 1,
	"included_segments": ["All"]
}

The App runs successfully, the notification is received but the badge number does not increment
when the app is in the background.

**Comment by rgomezp** [comment]
Howdy,
Can you double check how you set up app groups? Please go back through the setup steps and make sure the names match, etc...

**Comment by superakabo** [comment]
> Howdy,
> Can you double check how you set up app groups? Please go back through the setup steps and make sure the names match, etc...

I have gone through all the steps in the documentation and still does not work.
Anyway, I am in communication with Jon from OneSignal about this issue.

**Comment by superakabo** [comment]
It work now after updating to iOS 13.3.1
