### ISSUE TITLE
Add web push support

### ISSUE THREAD

**Issue by TobiasHeidingsfeld** [OneSignal/OneSignal-Flutter-SDK#207]
I would use OneSignal Flutter the second it supports web push notifications. Any plans for that?

**Comment by jkasten2** [comment]
@TobiasHeidingsfeld We have a separate Javascript [OneSignal-Website-SDK](https://github.com/OneSignal/OneSignal-Website-SDK) to support Web Push Notifications.
See the [OneSignal Web Push Quickstart](https://documentation.onesignal.com/docs/web-push-quickstart) to get started.

As far as directly adding Web push support to this Flutter SDK, there are no near term plans to due so. You will need to add the dedicated OneSignal Web SDK.

**Comment by harithany** [comment]
up

**Comment by GSamuel** [comment]
I am currently using flutter for creating an android / ios / web  based app.
Would really love support for Flutter Web. https://flutter.dev/web

**Comment by lukepighetti** [comment]
With Flutter Web getting closer to stable, any chance you guys would reconsider?

**Comment by rodion-m** [comment]
Flutter Web supporting is really needed feature and it became more actual each new day. @jkasten2 I think you should reopen the issue to let people at least vote for that.

**Comment by danielgomezrico** [comment]
@jkasten2 any ideas if it will be supported?

**Comment by MoacirSchmidt** [comment]
does OneSignal-Website-SDK support flutter web?
