### ISSUE TITLE
Push notification is not shown as dialog when app is open

### ISSUE THREAD

**Issue by figengungor** [OneSignal/OneSignal-Flutter-SDK#208]
**Description:**

With version 2.0.2 I was able to see a dialog when a push notification is received if app is open. But with latest version 2.3.3, I'm not able to see that dialog. May I ask what changed?

**Environment**

onesignal_flutter: ^2.3.3

**Steps to Reproduce Issue:**

1. Just use version 2.3.3
2. Send a push notification when app is open.

**Comment by jkasten2** [comment]
@figengungor The default should still be as an alert dialog. However we highly recommend using the following so a notification is always shown instead.

```dart
OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.notification);
```
https://documentation.onesignal.com/docs/flutter-sdk#section-set-in-focus-display-type
