### ISSUE TITLE
setNotificationOpenedHandler can't go on specific mobile app news

### ISSUE THREAD

**Issue by mrdulal** [OneSignal/OneSignal-Flutter-SDK#211]
All things goes well on this.. Notification also appear but when user tap on notification of news it will redirect to web instead for app specific news details.. 

any help would be appreciate.

**Comment by dcdiogo** [comment]
Some time ago I had same behavior. What I did was remove launchUrl from payload.

**Comment by mrdulal** [comment]
@dcdiogo how you remove lunchUrl from payload. Please do paste the some code here too. I am still stuck.

**Comment by dcdiogo** [comment]
Just keep field empty

![image](https://user-images.githubusercontent.com/22935056/76957805-3beebf80-68f5-11ea-9d9e-cf7af324db36.png)

**Comment by mrdulal** [comment]
yeah i do but if notification come from wordpress to onesignal and onesignal to android app then ? 

It will automatically show U: URL on payload. 

is there any way to remove that ?

**Comment by dcdiogo** [comment]
@mrdulal Sorry, I never worked with wordpress before. My payload come from cURL inside PHP code, so I build on my own. But, when you tell "show URL on payload", ok, no problem if it is empty, like:
```
{
...
"launchUrl":"",
...
}
```

But, reviewing my code, I remember to have problems when app is minimazed (I clicked on notification, but nothing happens). I'm developping in Flutter, then I did a channel, between Flutter and native Android code, like this:

Android part => MainActivity.java:
```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        new MethodChannel(getFlutterEngine().getDartExecutor().getBinaryMessenger(), CHANNEL).setMethodCallHandler(
                new MethodChannel.MethodCallHandler() {
                    @Override
                    public void onMethodCall(MethodCall call, MethodChannel.Result result) {
                        if (call.method.equals("iniciarAppSeEstiverMinimizado")) {
                            if (call.hasArgument("oferta_id")) {
                                int ofertaId = call.argument("oferta_id");

                                Object activityToLaunch = MainActivity.class;
                                Intent intent = new Intent(getApplicationContext(), (Class<?>) activityToLaunch);
                                intent.putExtra("ID_OFERTA", ofertaId); // Set your ID as a Intent Extra
                                intent.setFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT | Intent.FLAG_ACTIVITY_NEW_TASK);
                                startActivity(intent);
                                result.success("OK");
                            } else {
                                result.success("NOK");
                            }
                        }
                    }
                });
    }
```

Flutter part (invoke Android Method to bring App to Foreign), after initialize OneSignal:
```
OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult action) async {
      if (action.notification.payload.additionalData.containsKey("oferta_id")) {
        int ofertaId = action.notification.payload.additionalData["oferta_id"];
        String response = "";
        try {
          Map<String, int> params = {"oferta_id": 20};
          final String result = await MyApp.platform.invokeMethod("iniciarAppSeEstiverMinimizado", params);
          response = result;
        } on PlatformException catch (e) {
          response = "Failed to Invoke: '${e.message}'.";
        }
        if (response == "OK") {
          await navigatorKey.currentState
              .push(new MaterialPageRoute(builder: (context) => new OfertaPage.fromId(ofertaId)))
              .catchError((onError) {
            print(onError.hashCode);
            print(onError.toString());
          });
        }
    });
```

Notes: Not tested on IOS yet.

**Comment by jkasten2** [comment]
@mrdulal Another option is to set `web_url` instead of `url`, this means the url will only be sent for WebPush and not to mobile app channels.
https://documentation.onesignal.com/reference#create-notification

To do this for WordPress is you can customize the notification that would sent from the OneSignal-WordPress-Plugin by following this guide.
https://documentation.onesignal.com/docs/web-push-wordpress-faq#section-sending-web-and-mobile-notifications-together-with-word-press
