### ISSUE TITLE
'Google Play services' returned SERVICE_NOT_AVAILABLE error. Current retry count: 0

### ISSUE THREAD

**Issue by gaojuanjuan** [OneSignal/OneSignal-Flutter-SDK#213]
: java.io.IOException: SERVICE_NOT_AVAILABLE
I/OneSignal( 1298): 	at com.google.firebase.iid.zzr.zza(Unknown Source:66)
I/OneSignal( 1298): 	at com.google.firebase.iid.zzr.zza(Unknown Source:79)
I/OneSignal( 1298): 	at com.google.firebase.iid.zzu.then(Unknown Source:4)
I/OneSignal( 1298): 	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
I/OneSignal( 1298): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
I/OneSignal( 1298): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
I/OneSignal( 1298): 	at java.lang.Thread.run(Thread.java:784)

**Comment by jkasten2** [comment]
@gaojuanjuan The "SERVICE_NOT_AVAILABLE" error indicates something wrong with the "Google Play services" app on the device or the device can't get a connection to Google's servers. See https://github.com/OneSignal/OneSignal-Android-SDK/issues/620#issuecomment-418225336 for more details.
