### ISSUE TITLE
setEmail takes a lot to end and ends with an InterruptedException

### ISSUE THREAD

**Issue by Tomi-15** [OneSignal/OneSignal-Flutter-SDK#214]
**Description:**
This is my code in Flutter:

```
await OneSignal.shared.init("9f63d8bc-1afc-43dc-adb9-a6fc424c084a");
await OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.notification);
await OneSignal.shared.consentGranted(true);
await OneSignal.shared.promptUserForPushNotificationPermission();
await OneSignal.shared.setExternalUserId(userId);
    OneSignal.shared.setEmail(email: userEmail)
    .then((result) {
      appLogger.information("OneSignal email ready.");
    }).catchError((error) {
      appLogger.error("OneSignal email set failed. Error: ${error.toString()}");
    });
```

The OneSignal.shared.setEmail never ends. But, sometimes it ends with a:

```W/System.err(26026): java.lang.InterruptedException
W/System.err(26026): 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1248)
W/System.err(26026): 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:344)
W/System.err(26026): 	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:384)
W/System.err(26026): 	at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run(OneSignalSyncServiceUtils.java:236)
W/System.err(26026): 	at java.lang.Thread.run(Thread.java:919)```

**OneSignal version:**
^2.3.4

**Comment by rikiyanuar** [comment]
I have the same problem
I use `onesignal_flutter: ^2.3.4`

this is my code in main.dart
> OneSignal.shared.setRequiresUserPrivacyConsent(true);
var settings = {
  OSiOSSettings.autoPrompt: true,
  OSiOSSettings.promptBeforeOpeningPushUrl: true,
};
await OneSignal.shared.init("key", iOSSettings: settings);
OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.alert);

this is the logs

> W/System.err(20617): java.lang.InterruptedException
W/System.err(20617):    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1218)
W/System.err(20617):    at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:312)
W/System.err(20617):    at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:355)
W/System.err(20617):    at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run(OneSignalSyncServiceUtils.java:236)
W/System.err(20617):    at java.lang.Thread.run(Thread.java:760)

flutter doctor -v

> [✓] Flutter (Channel unknown, v1.10.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.1 at /home/xxxxxx/flutter
    • Framework revision ce45c2d3e6 (6 months ago), 2019-09-06 20:11:41 -0400
    • Engine revision b9ce2500d9
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)
>[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/xxxxxx/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/xxxxxx/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.
>[✓] Android Studio (version 3.4)
    • Android Studio at /home/xxxxxx/Documents/android-studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
>[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /opt/idea-IC-182.3684.101
    • Flutter plugin version 26.0.3
    • Dart plugin version 182.3569.4
>[✓] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

**Comment by jkasten2** [comment]
@Tomi-15 Thanks for reporting. We have a fix for the `setEmail` not setting or resolving it's Future on Android in PR #223 that will be included in the next release.

@Tomi-15 @rikiyanuar The `: java.lang.InterruptedException` isn't a specific issue with `setEmail`. Could you please provide more details on how to reproduce the crash? Please create a new issue for this other problem.
