### ISSUE TITLE
App crash on latest version

### ISSUE THREAD

**Issue by jonataslaw** [OneSignal/OneSignal-Flutter-SDK#217]
**Description:**
App crash with error:

```
java.lang.InterruptedException
W/System.err(26262): 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1244)
W/System.err(26262): 	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:336)
W/System.err(26262): 	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:384)
W/System.err(26262): 	at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run(OneSignalSyncServiceUtils.java:236)
W/System.err(26262): 	at java.lang.Thread.run(Thread.java:798)
```

I am using onesignal_flutter version 2.3.4
And that error started showing up in the last few months, but now I have thousands of crash reports in the playstore because of him.

**Comment by yacinegithub** [comment]
Same isssue with flutter onesignal_flutter: ^2.3.4

**Comment by jkasten2** [comment]
@jonataslaw @yacinegithub Can you provide the following details from the crash reports?
1. Error message after "java.lang.InterruptedException"
2. Steps to reproduce if you can do so on your test device.
3. Full stacktrace of all threads.

**Comment by yacinegithub** [comment]
@jonataslaw i am sorry but just to sure
**1-** _W/System.err(31044): java.lang.InterruptedException
W/System.err(31044):    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1244)
W/System.err(31044):    at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:336)
W/System.err(31044):    at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:384)
W/System.err(31044):    at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run(OneSignalSyncServiceUtils.java:236)
W/System.err(31044):    at java.lang.Thread.run(Thread.java:764)_
**2-** i don't know what you meant with "Steps to reproduce if you can do so on your test device".
**3-** did you mean with full stacktrace of allthreads-> this command "./gradlew build --stacktrace" or just get only those ofone_signal .

**Comment by jkasten2** [comment]
Thanks for the additional details.

The logs indicate that OneSignal is catching the `java.lang.InterruptedException` error and logging it as informational. This isn't causing any crashes. However this indicates that there is unsynced data to onesignal.com that the SDK is unable to update as you noted it shows up every 5 minutes.

Based on the log you have given it seems this is the adb logcat from your device.

Can you runnin the following?
```sh
adb shell
dumpsys jobscheduler | grep com.onesignal
```

This well help debug why the Job is being stopped.

**Comment by yacinegithub** [comment]
laurel_sprout:/ $ dumpsys jobscheduler | grep com.onesigna
  JOB #u0a137/2071862118: f4bbb55 **mawada.net.app**/com.onesignal.SyncJobService
    u0a137 tag=*job*/mawada.net.app/com.onesignal.SyncJobService
      Service: mawada.net.app/com.onesignal.SyncJobService
  JOB #u0a215/2071862118: c61db0 **com.tawsseel.tawsseelapp**/com.onesignal.SyncJobService
    u0a215 tag=*job*/com.tawsseel.tawsseelapp/com.onesignal.SyncJobService
      Service: com.tawsseel.tawsseelapp/com.onesignal.SyncJobService
       -18m50s853ms   START: #u0a215/2071862118 com.tawsseel.tawsseelapp/com.onesignal.SyncJobService
       -18m50s825ms  STOP-P: #u0a215/2071862118 com.tawsseel.tawsseelapp/com.onesignal.SyncJobService canceled
        -6m24s038ms   START: #u0a215/2071862118 com.tawsseel.tawsseelapp/com.onesignal.SyncJobService
        -6m24s014ms  STOP-P: #u0a215/2071862118 com.tawsseel.tawsseelapp/com.onesignal.SyncJobService canceled
        -1m21s178ms   START: #u0a215/2071862118 com.tawsseel.tawsseelapp/com.onesignal.SyncJobService
        -1m21s052ms  STOP-P: #u0a215/2071862118 com.tawsseel.tawsseelapp/com.onesignal.SyncJobService canceled
          -45s920ms   START: #u0a215/2071862118 com.tawsseel.tawsseelapp/com.onesignal.SyncJobService
          -45s898ms  STOP-P: #u0a215/2071862118 com.tawsseel.tawsseelapp/com.onesignal.SyncJobService canceled
laurel_sprout:/ $

The first app **mawada** is an app that i installed in my phone.
The second app **Tawssel** is the app am developping.

**Comment by j574144** [comment]
same here, I'm using onesignal_flutter: ^2.3.4.

My implementation code and as error I have  ` W/System.err(31044): java.lang.InterruptedException`

```
 await OneSignal.shared.init(env.config['ONE_SIGNAL_APP_KEY'],
        iOSSettings: {
          OSiOSSettings.autoPrompt: false,
          OSiOSSettings.inAppLaunchUrl: true
        });
    final oneSignalSubsState =
        await OneSignal.shared.getPermissionSubscriptionState();
    await OneSignal.shared
        .setInFocusDisplayType(OSNotificationDisplayType.notification);

OneSignal.shared
          .setNotificationReceivedHandler((OSNotification notification) {
        authProv.showPushOSNotification(notification);
      });
```

**Comment by rgomezp** [comment]
Howdy, 
Thanks for your patience. Is this issue still appearing even on the latest version 2.4.1?

**Comment by rgomezp** [comment]
It sounds like this issue has since been resolved. Please upgrade to 2.5.0

**Comment by j574144** [comment]
Hi. still happen with 2.5.0
`
W/System.err( 3022): java.lang.InterruptedException
W/System.err( 3022): 	at java.lang.Object.wait(Native Method)
W/System.err( 3022): 	at java.lang.Object.wait(Object.java:422)
W/System.err( 3022): 	at java.lang.Thread.join(Thread.java:1270)
W/System.err( 3022): 	at com.onesignal.OneSignalRestClient.makeRequest(OneSignalRestClient.java:118)
W/System.err( 3022): 	at com.onesignal.OneSignalRestClient.putSync(OneSignalRestClient.java:95)
W/System.err( 3022): 	at com.onesignal.UserStateSynchronizer.doPutSync(UserStateSynchronizer.java:315)
W/System.err( 3022): 	at com.onesignal.UserStateSynchronizer.internalSyncUserState(UserStateSynchronizer.java:245)
W/System.err( 3022): 	at com.onesignal.UserStateSynchronizer.syncUserState(UserStateSynchronizer.java:213)
W/System.err( 3022): 	at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:98)
W/System.err( 3022): 	at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run(OneSignalSyncServiceUtils.java:246)
W/System.err( 3022): 	at java.lang.Thread.run(Thread.java:764)
`

**Comment by rgomezp** [comment]
Howdy,
Thanks. Could anyone provide us with a link to a project that reproduces the issue? Or if it is easy to reproduce with your production app, please include a link to the app with reproduction instructions. Cheers

**Comment by rgomezp** [comment]
Closing due to no response
