### ISSUE TITLE
Is this plugin working with flutter_local_notifications?

### ISSUE THREAD

**Issue by tapkain** [OneSignal/OneSignal-Flutter-SDK#222]
Hello dear developers, can this plugin be integrated with flutter_local_notifications? If no, do you plan to add this feature soon? Thanks.

**Comment by jkasten2** [comment]
If you use `flutter_local_notifications@0.9.0` or newer you must follow their extra steps for it to be compatible with other notification plugins.
See https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/197#issuecomment-590153195 for details on this.

**Comment by kbokarius** [comment]
@jkasten2 what are the extra steps? It's not clear based on that comment. There are two links, neither of which have instructions for the changes required. It looks like flutter_local_notifications has been changed to be compatible with Firebase, and there are no additional instructions for how it could be made to work with OneSignal.
