### ISSUE TITLE
Security alert  Your app contains exposed Google Cloud Platform (GCP) API keys

### ISSUE THREAD

**Issue by quynhapl** [OneSignal/OneSignal-Flutter-SDK#224]
**Description:**

Hello guys,
We having the same warning mentioned in the issue below. Is there an update planned in the next coming days to fixed it for Flutter SDK?
https://github.com/OneSignal/OneSignal-Android-SDK/issues/966

**Environment**

> onesignal_flutter: ^2.3.4

**Steps to Reproduce Issue:**
Try to submit update on android console application. Getting this warning.
![Screen Shot 2020-03-27 at 11.47.44 AM.png](https://2.pik.vn/2020b209f486-8b3f-46b4-bea3-debaac9be50a.png)

**Comment by Zeeshan0201** [comment]
@quynhapl found any solution for this in flutter package?  and  fix has been implemented in the [OneSignal-Android-SDK version 3.13.0 ](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.13.0) used by this SDK.

**Comment by jkasten2** [comment]
This has been fixed in the 2.4.0 release
https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/2.4.0
