### ISSUE TITLE
Can't access additional data when app was being swiped away

### ISSUE THREAD

**Issue by ercadev** [OneSignal/OneSignal-Flutter-SDK#235]
**Description:**
So I'm developing an app which receives pushes and should open a specific page based on data {'post': 234} for example. 
This works when app is open or is just recently closed. 
When app is "swiped away" or have been closed after not using in a while I cant access the data.

I've read many issues with same problem but none of them have helped me with a solution or in which way I should go.

Should this be possible with just the packaged installed? Maybe I just set something up wrong
If not, could this be solved by writing a Service Extension [like here](https://documentation.onesignal.com/docs/service-extensions) ?
I've no experience in kotlin or swift so really don't want to write a service extension if it's not going to solve the problem

**Environment**
Android
1. Package version:   `onesignal_flutter: ^2.3.1`

**Steps to Reproduce Issue:**

1. App Is "swiped away"
2. App receive notification and user clicks
3. Cant access Additional data

**Comment by rgomezp** [comment]
Howdy, are you seeing this in Android and iOS?

**Comment by ercadev** [comment]
both iOS and android.
I solved android by writing platform-specific code. Haven't figured out iOS yet but I think i'll get there. I was planning to share documentation how to implement it when I get iOS to work.

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience.

Do you have any further information to provide that could help us either solve the issue or better document how to handle it?

**Comment by ercadev** [comment]
I think the documentation could be more clear on how to implement the notification extender on Android. I'll close this issue now and below is how i solved it for anyone who run into the same problem. Feel free to re-open if the discussion about the documentation will take place here.

This is my `MainActivity.kt`

```
import com.onesignal.NotificationExtenderService.OverrideSettings
import com.onesignal.OSNotificationReceivedResult
import com.onesignal.NotificationExtenderService
import androidx.core.content.ContextCompat.getSystemService

import io.flutter.plugin.common.MethodChannel




class MainActivity: FlutterActivity() {
    private val CHANNEL = "YOUR_IDENTIFIER/noti"
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler{ call, result ->
            if (call.method == "getPostId") {
                var res = PostData.postId
                result.success(res)
            }
        }
    }

}

class NotificationExtenderExample : NotificationExtenderService() {
    override fun onNotificationProcessing(receivedResult: OSNotificationReceivedResult): Boolean {

        val title = receivedResult.payload.additionalData["post"]
        PostData.setPost(receivedResult.payload.additionalData.getString("post"))
        return false
    }
}

object PostData {
    var postId = ""
    fun setPost(id: String) {
        postId = id
    }
}

```

**Comment by rgomezp** [comment]
Thank you for the details

**Comment by anthonycuervo23** [comment]
any solution on how to get the data when app is closed for android and ios?

**Comment by sampatsharma143** [comment]
@ercadev  thanks for sharing the code for android part can you share the code for flutter part as well 
thank you.
