### ISSUE TITLE
The proper sequence of init callbacks on Android matters

### ISSUE THREAD

**Issue by tapkain** [OneSignal/OneSignal-Flutter-SDK#237]
**Description:**
In code
```
OneSignal.shared.init ...
OneSignal.shared.setNotificationOpenedHandler ...
```
RESULT - handler is not working

Setup of handlers should be before init, no clear specification in Android docs (maybe bug?)

**Environment**
onesignal_flutter: ^2.4.0
implementation 'com.onesignal:OneSignal:3.13.1'

**Comment by rgomezp** [comment]
Howdy,
Unfortunately, you aren't providing enough information for us to be able to help you successfully. What are your reproduction steps? Can you include a log from when a notification is opened?

**Comment by rgomezp** [comment]
Closing due to no response
