### ISSUE TITLE
iOS device not getting subscribed

### ISSUE THREAD

**Issue by saratSubramaniam** [OneSignal/OneSignal-Flutter-SDK#238]
Hello, can any one help me with iOS notifications? (Version onesignal_flutter 2.4.0)

```
OneSignal.shared.setLogLevel(
      OSLogLevel.verbose,
      OSLogLevel.none
    );

    await OneSignal.shared.setRequiresUserPrivacyConsent(true);

    var settings = {
      OSiOSSettings.autoPrompt: true,
      OSiOSSettings.promptBeforeOpeningPushUrl: true
    };

    // NOTE: Replace with your own app ID from https://www.onesignal.com
    await OneSignal.shared.init(
      "<app-id>",
      iOSSettings: settings
    );

    await OneSignal.shared.consentGranted(true);

    OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.notification);
```

Above is how my flutter part looks like.

And below is my Podfile

```
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
end
```

I'm testing on an iPhone (13.3.1). The device does not get registered/subscribed as I can see in the One Signal dashboard (All Users).
I'm not sure how to get the full log from the device, if that is required.

Note - In some scenario which I haven't properly understood yet, the device got registered and I could send a test notification to confirm the certificates etc are alright.
Now I deleted the device from One Signal to continue testing my actual scenario.

**Comment by rgomezp** [comment]
Howdy,
I think our support channel at OneSignal.com would be a better way to get help.

You can get a log by following the steps in our [troubleshooting guide.](https://documentation.onesignal.com/docs/troubleshooting-ios)

**Comment by EjazAmir** [comment]
hey, did you found any solution?

**Comment by dineshreddy1995** [comment]
Any solution?

**Comment by jkasten2** [comment]
@dineshreddy1995 I recommend checking out the following guide:
https://documentation.onesignal.com/docs/all-users-are-shown-as-not-subscribed

If the above doesn't help please create a new issue with that you have tried so far and exactly what you are seeing with any errors and other details.
