### ISSUE TITLE
Could not resolve com.google.android.gms:play-services-ads-identifier:[15.0.0, 16.0.99].

### ISSUE THREAD

**Issue by rakib205** [OneSignal/OneSignal-Flutter-SDK#248]
### Description:
I am facing this error. I have checked the issues and no fix found.

### Errors I have found : 
```
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Could not determine the dependencies of task ':app:preDebugBuild'.                                                 
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.                          
   > Could not resolve com.google.android.gms:play-services-ads-identifier:[15.0.0, 16.0.99].                      
     Required by:                                                                                                  
         project :app > com.onesignal:OneSignal:3.13.2                                                             
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.                           
         > Unable to load Maven meta-data from https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
                  > Remote host closed connection during handshake                                                 
   > Could not resolve com.google.android.gms:play-services-base:[10.2.1, 16.1.99].                                
     Required by:                                                                                                  
         project :app > com.onesignal:OneSignal:3.13.2                                                             
      > Failed to list versions for com.google.android.gms:play-services-base.                                     
         > Unable to load Maven meta-data from https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-base/maven-metadata.xml'.
                  > Remote host closed connection during handshake                                                 
      > Failed to list versions for com.google.android.gms:play-services-base.                                     
         > Unable to load Maven meta-data from https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-base/maven-metadata.xml'.
                  > Remote host closed connection during handshake                                                 
      > Failed to list versions for com.google.android.gms:play-services-base.                                     
         > Unable to load Maven meta-data from https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://storage.googleapis.com/download.flutter.io/com/google/android/gms/play-services-base/maven-metadata.xml'.
                  > Remote host closed connection during handshake                                                 
   > Could not resolve com.google.firebase:firebase-iid:[17.0.4].                                                  
     Required by:                                                                                                  
         project :app > com.google.firebase:firebase-messaging:17.3.4                                              
      > Failed to list versions for com.google.firebase:firebase-iid.                                              
         > Unable to load Maven meta-data from https://storage.googleapis.com/download.flutter.io/com/google/firebase/firebase-iid/maven-metadata.xml.
            > Could not get resource 'https://storage.googleapis.com/download.flutter.io/com/google/firebase/firebase-iid/maven-metadata.xml'.
               > Could not GET 'https://storage.googleapis.com/download.flutter.io/com/google/firebase/firebase-iid/maven-metadata.xml'.
                  > Remote host closed connection during handshake                                                 
                                                                                                                   
* Try:                                                                                                             
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                                                                   
* Get more help at https://help.gradle.org                                                                         
                                                                                                                   
BUILD FAILED in 6m 13s   
```

### My build.gradle
    buildscript {
        ext.kotlin_version = '1.3.21'
        repositories {
            google()
            jcenter()
        }
    
        dependencies {
            classpath 'com.android.tools.build:gradle:3.3.1'
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            classpath 'com.google.gms:google-services:4.3.2'
        }
    }
    
    allprojects {
        repositories {
            google()
            jcenter()
        }
    }
    
    rootProject.buildDir = '../build'
    subprojects {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
    subprojects {
        project.evaluationDependsOn(':app')
    }
    
    task clean(type: Delete) {
        delete rootProject.buildDir
    }
    `
    
    ### My app level build.gradle
    
    `buildscript {
        repositories {
            // ...
            maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
        }
        dependencies {
            // ...
            // OneSignal-Gradle-Plugin
            classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.2, 0.99.99]'
        }
    }
    
    apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
    
    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withReader('UTF-8') { reader ->
            localProperties.load(reader)
        }
    }
    
    def flutterRoot = localProperties.getProperty('flutter.sdk')
    if (flutterRoot == null) {
        throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
    }
    
    def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
    if (flutterVersionCode == null) {
        flutterVersionCode = '1'
    }
    
    def flutterVersionName = localProperties.getProperty('flutter.versionName')
    if (flutterVersionName == null) {
        flutterVersionName = '1.0'
    }
    
    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
    
       def keystoreProperties = new Properties()
       def keystorePropertiesFile = rootProject.file('key.properties')
       if (keystorePropertiesFile.exists()) {
           keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
       }
    
       android {
        compileSdkVersion 28
    
        sourceSets {
            main.java.srcDirs += 'src/main/kotlin'
        }
    
        lintOptions {
            disable 'InvalidPackage'
        }
    
        defaultConfig {
            // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
            applicationId "mrblab.wallpaper_app"
            minSdkVersion 16
            targetSdkVersion 28
            multiDexEnabled true
            versionCode flutterVersionCode.toInteger()
            versionName flutterVersionName
            testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        }
    
           signingConfigs {
           release {
               keyAlias keystoreProperties['keyAlias']
               keyPassword keystoreProperties['keyPassword']
               storeFile file(keystoreProperties['storeFile'])
               storePassword keystoreProperties['storePassword']
           }
       }
       buildTypes {
           release {
               signingConfig signingConfigs.release
               shrinkResources false
               zipAlignEnabled false
               minifyEnabled false
           }
       }
    }
    
    flutter {
        source '../..'
    }
    
    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
        implementation 'com.android.support:multidex:1.0.3'
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'androidx.test:runner:1.1.1'
        androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
        
        
    }
    
    apply plugin: 'com.google.gms.google-services'

**Comment by gz-ang** [comment]
I'm currently having the same issue, the app wouldn't even build. For my case this happens while I was trying to add firebase dynamic link service to my app. it will build properly if i disable the google service plugin at the app level gradle.

**Comment by rgomezp** [comment]
Howdy @rakib205 @gz-ang 
Apologies for the delay. Are you still experiencing the issue?

Please also make sure you are using the latest version of the [OneSignal Gradle Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin)

**Comment by enricobenedos** [comment]
I was experiencing this issue after updating to `firebase_core: ^0.5.2+1` and `firebase_analytics: ^6.2.0`. I was able to build an appbundle on release mode but I was not able to debug the app on Android Simulator.

I solved as advised by @rgomezp updating from 

`classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.6, 0.99.99]'`

to

`classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.9, 0.99.99]'`

in my `app/build.gradle`

**Comment by WaheedHussainHaans** [comment]
Changing onesignal gradle plugin version didnt work for me any solution to this please

**Comment by rgomezp** [comment]
Howdy @WaheedHussainHaans ,
Did you make sure to sync your gradle in Android Studio? Please provide more info

**Comment by doanbh** [comment]
> Changing onesignal gradle plugin version didnt work for me any solution to this please

You can try [https://stackoverflow.com/a/68295157/9405238](url).

**Comment by MuhammedRefaat** [comment]
I've updated to the latest releases and tried all the offered solutions, nothing works, it was working before but suddenly that happened

**Comment by AteqEjaz** [comment]
Same issue for me - Not able to build at all  even in debug mode 

    FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:preDebugBuild'.      
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-base:[10.2.1, 16.1.99].
     Required by:                                                       
         project :app > com.onesignal:OneSignal:3.15.1                  
      > Failed to list versions for com.google.android.gms:play-services-base.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-base/maven-metadata.xml'. Received status code 403 from server: Forbidden
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org

**Comment by jkasten2** [comment]
This is now fixed and is part of the [OneSignal-Flutter-SDK 3.2.8 Release](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.2.8), this SDK no longer refers to `jcenter()` and uses `mavenCentral()` instead to solve this issue.
