### ISSUE TITLE
Getting Error on User Permission

### ISSUE THREAD

**Issue by harpreet9629** [OneSignal/OneSignal-Flutter-SDK#250]
V/OneSignal(28371): Initializing the OneSignal Flutter SDK (2.2.0)
E/OneSignal(28371): Cannot change requiresUserPrivacyConsent() from TRUE to FALSE
V/OneSignal(28371): OneSignal SDK initialization delayed, user privacy consent is set to required for this application.
E/OneSignal(28371): promptPermission() is not applicable in Android
I/flutter (28371): null

**Environment**
Version 2.2.0
pubspec.yaml

**Steps to Reproduce Issue:**

1.  Setup onesignal into main.dart as per documentation.
2. But still getting this error don't know why 
3. I m running app in debug mode.

**Comment by khalid-al-shehri** [comment]
I had same issue, did you solve it ?

**Comment by khalid-al-shehri** [comment]
I solved it.

You should use these methods in initState() :
initPlatformState(); 
_handleConsent();

And use this method if you want to register extirnal ID (user Id from your database ):
_handleSetExternalUserId();

Enjoy with onesignal 👍

**Comment by mfouadegy** [comment]
same problem `Cannot change requiresUserPrivacyConsent() from TRUE to FALSE`

**Comment by radhen-thirstydevs** [comment]
@mfouadegy
 `await OneSignal.shared.setRequiresUserPrivacyConsent(true);`
try this method to solve that error .
i resolved so try must............

**Comment by IMRISHABH08** [comment]
> @mfouadegy
> `await OneSignal.shared.setRequiresUserPrivacyConsent(true);`
> try this method to solve that error .
> i resolved so try must............

@mfouadegy it won't work me !

**Comment by IMRISHABH08** [comment]
@harpreet9629  did you get the solution ?

**Comment by harpreet9629** [comment]
Yes

**Comment by IMRISHABH08** [comment]
> Yes

please do share !

**Comment by AhmedBenCheikh** [comment]
remove this code and upgrade the version to 3.2.7, it works with me

OneSignal.shared.promptUserForPushNotificationPermission().then((accepted) {
      print("Accepted permission: $accepted");
     });

**Comment by FeifanChang** [comment]
I solved it .

1. update onsignal sdk version to 3.2.7 (flutter)

2. add` consentGranted(true) ` before setAppId() methods

```dart
await OneSignal.shared.consentGranted(true);

await OneSignal.shared.setAppId(ONE_SIGNAL_APP_ID);
```

It work for me.

this is the official link : 

https://pub.dev/documentation/onesignal_flutter/latest/onesignal_flutter/OneSignal/consentGranted.html
