### ISSUE TITLE
Send push to specific user

### ISSUE THREAD

**Issue by d-apps** [OneSignal/OneSignal-Flutter-SDK#251]
Is it possible to send push to specific user only using his UUID?

```
"app_id": "$CLIENT_ANDROID_APP_ID",
        "headings": {"en": title},
        "contents": {"en": content},
        "uuid": ["$uuid"]
```

**Comment by rgomezp** [comment]
Howdy,
Good question. Yes! you can use our `include_player_ids` or `include_external_user_ids` parameters as noted in our [documentation](include_external_user_ids).

Enjoy!
