### ISSUE TITLE
Background and Voip notification

### ISSUE THREAD

**Issue by ziasultan2** [OneSignal/OneSignal-Flutter-SDK#252]
Is there any way to configure voip and background notification with OneSignal

**Comment by rgomezp** [comment]
Howdy,
Yes! Great question.

Please take a look at our following documentation:
1) [Data & Background Notifications](https://documentation.onesignal.com/docs/data-notifications)
2) [VoIP Notifications](https://documentation.onesignal.com/docs/voip-notifications)
    - [Changes to VoIP with iOS 13](https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/)

Hope this helps. 

Enjoy!
