### ISSUE TITLE
Keep OneSignalNotificationServiceExtension version and build up-to-date

### ISSUE THREAD

**Issue by royibernthal** [OneSignal/OneSignal-Flutter-SDK#253]
In order to add the App Groups capability for OneSignal on IOS, it's required to create a new target named OneSignalNotificationServiceExtension.

Unlike the Runner target, OneSignalNotificationServiceExtension's version and build are not updated automatically according to the info specified in pubspec.yaml.

How I do I keep them up-to-date automatically as well? I suppose it should somehow be done in the Podfile?

The reason I care about it is because the App Store keeps warning me about it everytime I upload a build, unless I manually keep both targets' version and build in sync.

**Comment by rgomezp** [comment]
Howdy,
The NSE should be added via the Podfile as noted by our [Flutter Setup Docs](https://documentation.onesignal.com/docs/flutter-sdk-setup). For the `pod`, note the use of version ranges. Consider adding `pod update` to your build process. 

Hope this helps.

Enjoy!

**Comment by royibernthal** [comment]
Hey, sorry for the late reply, apparently I missed the notification of your reply.

I did actually add the POD script and followed every step in your docs, yet the version is never up-to-date automatically when I want to build the app, so I have to set it manually.

Is there a specific step in your docs you believe I missed? Could you please refer me to it?

**Comment by caiogranero** [comment]
Hi @royibernthal , did you fixed this?

I'm having the same problem and i also created a issue #303
