### ISSUE TITLE
OSPermissionSubscriptionState.subscriptionStatus.userId is always null at first time awaiting state

### ISSUE THREAD

**Issue by figengungor** [OneSignal/OneSignal-Flutter-SDK#262]
**Description:**
OSPermissionSubscriptionState.subscriptionStatus.userId is always null at first time awaiting state. Why is that?

**Environment**

1. What version of the OneSignal Flutter SDK are you using?
2.5.0

**Steps to Reproduce Issue:**

  1. After integrating  and initializing OneSignal, print the user id and see how it comes null when app is launched first time
```
    OSPermissionSubscriptionState state =
        await OneSignal.shared.getPermissionSubscriptionState();
    String pushUserId = state.subscriptionStatus.userId;
    print(pushUserId);
```

**Comment by rgomezp** [comment]
Howdy,
Please see this [thread](https://github.com/OneSignal/OneSignal-Android-SDK/issues/749#issuecomment-497188781) for an explanation.

Enjoy!
