### ISSUE TITLE
Yes, take a look at our REST API [docs](https://documentation.onesignal.com/reference#create-notification)

### ISSUE THREAD

**Issue by uvlek** [OneSignal/OneSignal-Flutter-SDK#263]
Yes, take a look at our REST API [docs](https://documentation.onesignal.com/reference#create-notification)

_Originally posted by @rgomezp in https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/164#issuecomment-551283433_

It is not solving

**Comment by rgomezp** [comment]
Howdy,
Thanks for your question. However, I'm not sure exactly what you need help with. Perhaps reaching out to our support channel at OneSignal.com would better suit your needs in this case.

Thanks for using OneSignal.

Enjoy!
