### ISSUE TITLE
Delayed notifications not working

### ISSUE THREAD

**Issue by robertohuertasm** [OneSignal/OneSignal-Flutter-SDK#267]
**Description:**
Whenever you try to send a delayed notification it will be sent right away. The problem seems to be a typo in the generated json. Instead of `delayed_option` the current version of the SDK is using `delay_option`.  As this is a mandatory property, even if we set `deliveryTimeOfDay`, it won't work.

(your description here)

**Environment**
OneSignal SDK 2.5.0
Android & iOS

**Steps to Reproduce Issue:**
1. Use the example app
2. Add a new option to send a scheduled notification by adding 
```dart
delayedOption: OSCreateNotificationDelayOption.timezone,
deliveryTimeOfDay: '1:205PM',
```
3. The notification is sent right away.

The expected behavior would be to wait until the `deliveryTimeOfDay`.

I tested it by changing the name of the property in the json and it works. I'm preparing a PR with the changes.

**Comment by rgomezp** [comment]
Howdy Roberto,
Thank you so much for the contribution. We will review this as soon as possible.
