### ISSUE TITLE
gradle error finding play-services-location 

### ISSUE THREAD

**Issue by fabiancrx** [OneSignal/OneSignal-Flutter-SDK#278]
**Description:**
while running `flutter run` on the example app held in this repository the following error is returned:
```
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':onesignal_flutter:javaPreCompileDebug'.                                                
> Could not resolve all files for configuration ':onesignal_flutter:debugCompileClasspath'.                        
   > Could not find play-services-location.jar (com.google.android.gms:play-services-location:16.0.0).             
     Searched in the following locations:                                                                          
         https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/16.0.0/play-services-location-16.0.0.jar
          
```
It is a problem resolving it's dependencies, and the url          `https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/16.0.0/play-services-location-16.0.0.jar` returns 404.
I faced this issue while trying to add onesignal to my flutter project and then was able to reproduce it with in the example app.

**Environment**
flutter doctor output:
```
[✓] Flutter (Channel stable, v1.17.0, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
Note:  I use IntelliJ IDEA for development.
  onesignal_flutter: ^2.6.0

**Steps to Reproduce Issue:**

Example 1:

1. Try to `flutter run ` in the example folder

Example 2:
1. Add to pubspec `onesignal_flutter: ^2.6.0`
2. `flutter packages get`
3. `flutter run`

**Anything else:**

Note that I'm aware this is a problem with the dependencies that is why i tried to get it working with the example app just for it to fail again.
Any help will be kindly appreciated.

**Comment by erickhaendel** [comment]
Hi, i had the same problem, but resolved now.
Solution : https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/27#issuecomment-428011934 
you need use the android sdk's configuration on onesignal

**Comment by rgomezp** [comment]
@erickhaendel ,
Thank you for the solution. Enjoy!
