### ISSUE TITLE
receive a message but not open on display

### ISSUE THREAD

**Issue by jheimesilveirazup** [OneSignal/OneSignal-Flutter-SDK#279]
I would like a way to receive the onesignal message, but you can’t show me the notification on the display, while the app is closed.

if there is a way for me to send the push and only if the app is open, the user receives the message already solves me.

**Comment by rgomezp** [comment]
Howdy,
I'm sorry I didn't understand the question. In either case, please direct any support questions to our OneSignal official support channel at OneSignal.com. (Look for the chat bubble).

Thank you for your understanding.
