### ISSUE TITLE
Cannot run pod install for IOS

### ISSUE THREAD

**Issue by rlee1990** [OneSignal/OneSignal-Flutter-SDK#28]
**Description:**

1. What version of the OneSignal Flutter SDK are you using?
1.0.2

When I run pod install after adding
`target 'OneSignalNotificationServiceExtension' do
   s.dependency 'OneSignalDynamic', '>= 2.8.8', '< 3.0'
end`

to pod file a receive this error

`[!] Invalid `Podfile` file: undefined local variable or method `s' for #<Pod::Podfile:0x00007fc695418260>.`

**Environment**
<!-- Example:

**Comment by Nightsd01** [comment]
I am not sure where you got that `Podfile` line from? It should be this:

```ruby
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalDynamic', '>= 2.8.8', '< 3.0'
end
```

What you currently have would be invalid syntax

**Comment by rlee1990** [comment]
I copied that from the docs on the onesignal site @Nightsd01

**Comment by Nightsd01** [comment]
@rlee1990 Gotcha! Looks like our docs were invalid. Updated our documentation - apologies that you encountered this problem, thank you.
