### ISSUE TITLE
iOS not receiving data notifications

### ISSUE THREAD

**Issue by edlea** [OneSignal/OneSignal-Flutter-SDK#280]
**Description:**

I have integrated the OneSignal package in my Flutter app. On iOS and Android I can receive regular notifications and see messages displayed on device.

If I attach additional data to the message, my Dart `setNotificationReceivedHandler` gets called in the Flutter app.

But on iOS, that only works if I also have a body to my message; i.e. a notification is displayed to the user. On Android, I can set "content available" and the data is sent to the app without showing a notification.

This is not the case on iOS. Reading the UNNotificationServiceExtension documentation, this seems to be expected behaviour. But should these notifications not be handled by an AppDelegate method instead and still work?

**Environment**

OneSignal Flutter version 2.6.0
Added via pub

**Steps to Reproduce Issue:**

1. Follow instructions to set up OneSignal Flutter SDK on iOS
1. Send a notification with no body, but content available set and additional data fields
1. No Dart handlers fire; no debug printed to console

**Comment by rgomezp** [comment]
Howdy,
Apologies for the delay. Are you still encountering the issue?

You should also be setting `content_available` to true if you want to receive [background notifications](https://documentation.onesignal.com/docs/data-notifications) on iOS. See that documentation for more information.

Note that if notification events will only run if the app is in the foreground or is being brought into the foreground (e.g: if the app is open or if the notification was tapped to open).

Hopefully this helps.

Cheers

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by andydean565** [comment]
I am also having this issue on ios, I am receiving the notification but none of the flutter notifications are firing on the flutter side.

followed the implementation guide and the functions are firing on android 

any advice?

**Comment by edlea** [comment]
I ended up switching to Firebase, with an intention to revisit this again but never did. OneSignal doesn’t add enough value, over Firebase for my use case, to get it working.
