### ISSUE TITLE
Access to notification group permission

### ISSUE THREAD

**Issue by jheimesilveirazup** [OneSignal/OneSignal-Flutter-SDK#281]
Is there a way to know if a notification group's permission within the application?
an example is this group that is in print, I want to be able to know if it is selected or not.

![print](https://user-images.githubusercontent.com/63818444/87493634-9558c800-c623-11ea-9f1c-c76e19f13ca9.jpg)

**Comment by brenno951** [comment]
o have same question

![image](https://user-images.githubusercontent.com/59089584/87578575-f9729f00-c6aa-11ea-8e09-c1a540cb0d6e.png)

**Comment by jheimesilveirazup** [comment]
have any solution for this problem?

**Comment by rgomezp** [comment]
Howdy,
It is possible to access the the Android group's permission setting from the app. However, our SDK doesn't have an API for it. 

If you would like, you can try writing some native code by following [this thread](https://stackoverflow.com/questions/46928874/android-oreo-notifications-check-if-specific-channel-enabled).

Hope this helps. Enjoy!
