### ISSUE TITLE
Error when build or archive iOS with Xcode 

### ISSUE THREAD

**Issue by caiogranero** [OneSignal/OneSignal-Flutter-SDK#282]
**Description:**
I follow the flutter sdk setup in my app, but my app has `use_frameworks!` in the Podfile so i follow [this](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/53#issuecomment-516876885) comment and add `use_frameworks!` at the `target OneSignalNotificationServiceExtension`, this made my project build in command line with:  `fluter build ios --release --flavor prod` but when i try to archive or build the project with XCode i got the `Framework not found FBLPromises` error. I also have installed firebase packages via pub.dev.

**Environment**

OneSignal flutter: ^2.4.1
Flutter version: 1.17.5

**Steps to Reproduce Issue:**

1. Follow the setup tutorial: https://documentation.onesignal.com/docs/flutter-sdk-setup 
2. Set use_frameworks! on podfile
3. Open XCode and try to build or archive.

**Anything else:**

I tried to remove the `use_framewoks!` from my podfile but i got error on flutter_device_locale package, i don't use this package directly but maybe some of my packages uses. If i know how, i could try unistall it.

Someone can help me? I already spent one day with this problem :'(

**Comment by rgomezp** [comment]
Howdy,
It sounds like you may be working in the `.xcodeproj` instead of the `.xcworkspace` that is generated after you run `pod install`.

Can you please check this?

Cheers

**Comment by caiogranero** [comment]
Hi, i deleted the project folder and clone again from repository then follow again the tutorial and now works, thank you :)
