### ISSUE TITLE
Why ios app is automatically getting delivery quietly notification permission on default?

### ISSUE THREAD

**Issue by newbieflutter** [OneSignal/OneSignal-Flutter-SDK#283]
I have an app using one signal as the notification backend. What I notice is that on ios I automatically get the permission as deliver quitely. I want it to be on default as not having any permission and I want to ask for the permission? What changes must I make on this ?

**Comment by rgomezp** [comment]
Howdy!
It sounds like you have turned on Provisional Push Notifications: https://documentation.onesignal.com/docs/ios-customizations

You can easily turn those off, if you are still having issues, please contact support@onesignal.com and provide your OneSignal app id, this question would be best addressed there.
