### ISSUE TITLE
Issues using OneSignal with Firebase OTP

### ISSUE THREAD

**Issue by konewltd** [OneSignal/OneSignal-Flutter-SDK#284]
**Description:**

I am using Firebase messaging as the OTP for login and sign up system in my application. Recently, I tried to add a push notification function to my app, so I followed all the documentation for setting up OneSignal in my project. The push notification system works fine on both IOS and Android Platform. However, I found that my **Firebase OTP stopped working on IOS only** after installing OneSignal. Whenever I try to request for SMS message, it will then popped up a dialog saying `If app delegate swizzling is disabled, remote notifications received by UIApplicationDelegate need to be forwarded to FIRAuth's canHandleNotifcation: method.`

I have tried to add
`<key>FirebaseAppDelegateProxyEnabled</key>
<false/>`
to my Info.plist
and
`if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}`
to my AppDelegate.swift. Still, nothing is happening. May I ask how to resolve such issue?

**Environment**

1. What version of the OneSignal Flutter SDK are you using?
onesignal_flutter: ^2.6.0
2. How did you add the SDK to your project (eg. pub)
flutter pub get

**Steps to Reproduce Issue:**

Use OneSignal with Firebase messaging for OTP .

**Anything else:**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-HK)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.47.2)
[✓] Connected device (2 available)

**Comment by konewltd** [comment]
After trying to resolve this problem for a week, I finally found this solution which works for me.
In AppDelegate.swift,
`import UIKit
import Flutter
import Firebase
import FirebaseAuth
import UserNotifications
import FirebaseInstanceID

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
        FirebaseApp.configure()
        GeneratedPluginRegistrant.register(with: self)
        if #available(iOS 10.0, *) {
          UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
        }
        return true
  }
    override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        let firebaseAuth = Auth.auth()
        firebaseAuth.setAPNSToken(deviceToken, type: AuthAPNSTokenType.unknown)

    }
    override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        let firebaseAuth = Auth.auth()
        if (firebaseAuth.canHandleNotification(userInfo)){
            print(userInfo)
            return
        }

    }
}`

**Comment by mustakimpawle** [comment]
@konewltd  Facing the same problem. Which version of Firebase auth are you using in your project.
