### ISSUE TITLE
Android api level 30 notifcation problem

### ISSUE THREAD

**Issue by mamonraab** [OneSignal/OneSignal-Flutter-SDK#287]
**Description:**
when i set target sdk and  compileSdkVersion   to 30  notifcations delay and some times not received at all
while when i  set them to api level 28 everything work fine

i use 
onesignal_flutter: ^2.6.0

flutter doctor

flutter doctor -v
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows
    [Version 10.0.18362.959], locale ar-IQ)
    • Flutter version 1.17.5 at C:\flutter
    • Framework revision 8af6b2f038 (6 weeks ago), 2020-06-30
      12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK
    version 29.0.2)
    • Android SDK at C:\Users\SecOps\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\SecOps\AppData\Local\Programs\Microsoft
      VS Code
    • Flutter extension version 3.13.2

**Comment by mamonraab** [comment]
why no one check my issue

**Comment by rgomezp** [comment]
Howdy,
Please follow our issue template and provide the missing info so we can better assist you. Thanks.

**Comment by mamonraab** [comment]
the documentation in your website is old
after fallowing these it work perfectly

https://github.com/OneSignal/OneSignal-Gradle-Plugin

**Comment by rgomezp** [comment]
Howdy @mamonraab ,
Can you please point us to the specific page you were looking at in our documentation? Cheers

---

@tyang1 for visibility

**Comment by mamonraab** [comment]
the none working out dated  documentation is https://documentation.onesignal.com/docs/flutter-sdk-setup

the working one 
https://github.com/OneSignal/OneSignal-Gradle-Plugin

**Comment by rgomezp** [comment]
@mamonraab ,
The gradle set up instructions are identical between the two pages other than the version number but it's given as a range anyway so that wouldn't be a problem.

What is the discrepancy you are referring to? Thanks

**Comment by mamonraab** [comment]
the https://documentation.onesignal.com/docs/flutter-sdk-setup
reffer to put the code all iin "  Add the following to the very top (Line:1 ) of your android/app/build.gradle "

while the working oen reffer to put code in two deffrent places
1-   root build.gradle, under buildscript,  

and 
2-   to the top of your app/build.gradle

**Comment by rgomezp** [comment]
Howdy,
The `apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'` part has to be in the `app/build.gradle`
The `buildscript` block can go in either, it doesn't matter. If omit the `buildscript` completely then it will just fail to find `onesignal-gradle-plugin`  when it tries to apply plugin and the build error will tell you that. This is not an issue. You may have attributed the fix to the change but it was likely something else.
