### ISSUE TITLE
Navigate to specific screen in my Flutter app.

### ISSUE THREAD

**Issue by bal3m** [OneSignal/OneSignal-Flutter-SDK#288]
**Description:**
I installed OneSignal flutter plugin from 8 months ago to get a notification from my WordPress website when adding new post, since I install it I faced a problem to navigate to specific screen to see the new post when I clicked on the notification.
I did all the steps, and to be more clear I added the filter to get the WordPress post ID and write it as well as save it in mu_plugin on my web host after I followed your documentation.
Please help me to fix it as soon as possible.
Thanks.

**Comment by rgomezp** [comment]
Howdy, 
Please follow our issue template when opening an issue in Github.

For this particular issue, I would encourage you to please reach out through our official support channel. Thank you.
