### ISSUE TITLE
Not subscribe in release apk, only debug mode.

### ISSUE THREAD

**Issue by leigado** [OneSignal/OneSignal-Flutter-SDK#291]
**Description:**
Users are not subscribing in release mode, only in debug mode, the problem isn't identified

**Environment**
 Example:
1 - onesignal_flutter: ^2.6.1
2 - Adding by flutter pub get

**Steps to Reproduce Issue:**

1. Create a new project
1. Install the OneSignal Flutter SDK using pub into your project
1. Configure android/app/build.gradle

![image](https://user-images.githubusercontent.com/62335539/91317873-f500d200-e790-11ea-8980-7330d95560c9.png)

1. Initialize the SDK using OneSignal.shared.init(your_app_id) in main.dart
1. Run the flutter build apk --split-per-abi && flutter install

 How to reproduce run this code:  [ https://github.com/leigado/test-issue-onesignal ](https://github.com/leigado/test-issue-onesignal )

**Comment by findevapplications** [comment]
any updates here?
How did you solve the problem?

**Comment by DanRyan11** [comment]
I'm having the same problem, any way to fix the problem?

**Comment by wahyu-handayani** [comment]
I have the same problem, is there any update ? @DanRyan11 did you find any solution ?

**Comment by ChoyCheeWei** [comment]
@DanRyan11 @wahyu-handayani i have the same problem, any solution for this?
