### ISSUE TITLE
Could not send last request, device is offline

### ISSUE THREAD

**Issue by adukale** [OneSignal/OneSignal-Flutter-SDK#295]
**Description:**
Getting below error: 
`D/OneSignal(30892): OneSignalRestClient: Making request to: https://api.onesignal.com/apps/b2f7f966-d8cc-11e4-bed1-df8f05be55ba/android_params.js
I/OneSignal(30892): OneSignalRestClient: Could not send last request, device is offline. Throwable: java.net.ConnectException`

**Environment**

1. What version of the OneSignal Flutter SDK are you using?
SDK 2.5.0
1. How did you add the SDK to your project (eg. pub)
pub

**Steps to Reproduce Issue:**

1. Cloned example app from SDK and run

**Anything else:**

Tried with VPN also, the result is same. Unable to access the URL.

**Comment by ZeBigDuck** [comment]
Same here,

Not working on a real device but it's working in emulator.

**Comment by jkasten2** [comment]
The `java.net.ConnectException` could be from a number of networking issues. I recommend making sure you can access https://onesignal.com from a browser on the device to narrow down the issue. Provide more details if you have them and we can follow up.
