### ISSUE TITLE
Crash No such service ComponentInfo com.onesignal.SyncJobService

### ISSUE THREAD

**Issue by safeDev15** [OneSignal/OneSignal-Flutter-SDK#296]
**Description:**

When I open the android print spooler using  "printing" plugin with version: 3.6.0, the app crashes and the debug console show that message. If I remove onesignal_flutter plugin that error don't happen. How can I solve? thank you!

**Environment**

1. Version of the onesignal_flutter plugin: 2.6.1
1. Device: SUNMI V2

**Steps to reproduce:**

1. Install the OneSignal Flutter SDK using pub into your project
1. Initialize the SDK using OneSignal.shared.init(your_app_id) using this code:

   var settings = {
      OSiOSSettings.autoPrompt: false,
      OSiOSSettings.promptBeforeOpeningPushUrl: true
    };

```
var result = await OneSignal.shared.init(apiId, iOSSettings: settings);
OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);
OneSignal.shared.setRequiresUserPrivacyConsent(false);
```

```
var status = await OneSignal.shared.getPermissionSubscriptionState();
playerID = status.subscriptionStatus.userId;
```

```
print('ONESIGNAL USER ID: $playerID');
return playerID;
```

(crash stacktraces, as well as any other information here)

D/OneSignal( 3877): FocusTimeProcessorUnattributed:saveUnsentActiveTime: 477
D/OneSignal( 3877): FocusTimeProcessorUnattributed:getUnsentActiveTime: 477
V/OneSignal( 3877): scheduleSyncTask:SYNC_AFTER_BG_DELAY_MS: 30000
V/OneSignal( 3877): scheduleSyncServiceAsJob:atTime: 30000
E/AndroidRuntime( 3877): FATAL EXCEPTION: FocusHandlerThread
E/AndroidRuntime( 3877): Process: com.officinedelturismo.ast_controllo, PID: 3877
E/AndroidRuntime( 3877): java.lang.IllegalArgumentException: No such service ComponentInfo{com.officinedelturismo.ast_controllo/com.onesignal.SyncJobService}
E/AndroidRuntime( 3877): 	at android.os.Parcel.readException(Parcel.java:1688)
E/AndroidRuntime( 3877): 	at android.os.Parcel.readException(Parcel.java:1637)
E/AndroidRuntime( 3877): 	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
E/AndroidRuntime( 3877): 	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
E/AndroidRuntime( 3877): 	at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob(OneSignalSyncServiceUtils.java:177)
E/AndroidRuntime( 3877): 	at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask(OneSignalSyncServiceUtils.java:125)
E/AndroidRuntime( 3877): 	at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask(OneSignalSyncServiceUtils.java:75)
E/AndroidRuntime( 3877): 	at com.onesignal.FocusTimeController$FocusTimeProcessorBase.syncUnsentTimeOnBackgroundEvent(FocusTimeController.java:256)
E/AndroidRuntime( 3877): 	at com.onesignal.FocusTimeController$FocusTimeProcessorUnattributed.sendTime(FocusTimeController.java:122)
E/AndroidRuntime( 3877): 	at com.onesignal.FocusTimeController$FocusTimeProcessorBase.sendUnsentTimeNow(FocusTimeController.java:245)
E/AndroidRuntime( 3877): 	at com.onesignal.FocusTimeController$FocusTimeProcessorBase.addTime(FocusTimeController.java:238)
E/AndroidRuntime( 3877): 	at com.onesignal.FocusTimeController$FocusTimeProcessorBase.access$200(FocusTimeController.java:196)
E/AndroidRuntime( 3877): 	at com.onesignal.FocusTimeController.giveProcessorsValidFocusTime(FocusTimeController.java:82)
E/AndroidRuntime( 3877): 	at com.onesignal.FocusTimeController.appBackgrounded(FocusTimeController.java:53)
E/AndroidRuntime( 3877): 	at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1264)
E/AndroidRuntime( 3877): 	at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:263)
E/AndroidRuntime( 3877): 	at android.os.Handler.handleCallback(Handler.java:836)
E/AndroidRuntime( 3877): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime( 3877): 	at android.os.Looper.loop(Looper.java:203)
E/AndroidRuntime( 3877): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience.

This is an interesting issue I haven't quite seen before. Are you using the [OneSignal Gradle Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin/) as well?

**Comment by safeDev15** [comment]
> Howdy,
> Thanks for your patience.
> 
> This is an interesting issue I haven't quite seen before. Are you using the [OneSignal Gradle Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin/) as well?

Yes!

**Comment by nan-li** [comment]
Hi @safeDev15,

I apologize for the late response. Was this ever resolved for you?
