### ISSUE TITLE
Add support to change language

### ISSUE THREAD

**Issue by anderscheow** [OneSignal/OneSignal-Flutter-SDK#30]
Currently the SDK used device language, but my application is a multilingual app, but yet it retain the device language. Hence, I wanted to have the ability to change OneSignal language code

**Comment by Nightsd01** [comment]
@anderscheow We are currently tracking this feature request in our iOS native repo here: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/400

This is something we plan to support but I cannot yet provide a timeline, we will be adding this feature at some point probably within a few weeks or months.

**Comment by Lawati97** [comment]
@anderscheow I was wondering what was your approach to that? was it using tags and segments?
