### ISSUE TITLE
Flutter background notification is not working in iOS

### ISSUE THREAD

**Issue by Tushark690** [OneSignal/OneSignal-Flutter-SDK#301]
**Description:**
 I have developed an application on flutter. when I am releasing this app on android, everything is working fine. but when I am trying to release on iOS everything is working fine, but when the app is in the background notification doesn't arrive on iOS. But As soon as click on the app to launch, a notification arrives.

I have read every single line of https://pub.dev/packages/firebase_messaging and applied everything at least 10 times.
But every time I get a similar result.

And after reading a lot about the fcm on android and iOS I found a reason which may cause this error: -

Notification on iOS - onMessage -Notification is delivered to system tray. When the user clicks on it to open app onResume fires.

**Data Message on iOS - onMessage - Message is stored by FCM and delivered to the app via onMessage when the app is brought back to the foreground.**

The above situation is happening (Data Message on iOS).

But I want the Notification on iOS. 

So I tried to change my payload as iOS want https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html

But this also doesn't help.

I have searched a lot on StackOverflow and Github. They have similar problems but not able to find the solution.

Below is the Firebase Messaging configuration code.

```
final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
  _firebaseMessaging.subscribeToTopic('all');
  _firebaseMessaging.configure(
    onBackgroundMessage: Platform.isIOS ? null : myBackgroundMessageHandler,
      onMessage: (Map<String, dynamic> message) async {
      showNotification(message);
        completer.complete(message);
      },
    onLaunch: (message) async {
      print("onLaunch: $message");
//      showNotification(message["data"]["title"],message["data"]["body"]);
    },
    onResume: (message) async {
      print("onResume: $message");
//      showNotification(message["data"]["title"],message["data"]["body"]);
    },
  );
  await _firebaseMessaging.requestNotificationPermissions(
      const IosNotificationSettings(
          sound: true, badge: true, alert: true, provisional: false));
  _firebaseMessaging.onIosSettingsRegistered
      .listen((IosNotificationSettings settings) {
    print("Settings registered: $settings");
  });
  _firebaseMessaging.getToken().then((String token) {
    print("Push Messaging token: $token");
    // Push messaging to this token later
  });
```

Below is my AppDelegate.m code in Object-C

```
#import "AppDelegate.h"
#import "GeneratedPluginRegistrant.h"
@import Firebase;

@implementation AppDelegate

* (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [FIRApp configure];
 if (@available(iOS 10.0, *)) {
   [UNUserNotificationCenter currentNotificationCenter].delegate = (id<UNUserNotificationCenterDelegate>) self;
 }
 [GeneratedPluginRegistrant registerWithRegistry:self];
 [[UIApplication sharedApplication] registerForRemoteNotifications];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
@end
```

And <key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
	<key>FirebaseScreenReportingEnabled</key>
	<true/>

I added this to my info.plist.

And also, in Xcode, I added the capability of background modes and Push Notification and also checked the Background fetch and remote notifications in background modes.

and when I'm creating the key from developer.apple.com, i also checked the push notification in that.

I tried the payload: -

{
 "to" : "/topics/all",
 "notification" : null,
 "data" : {
 "title" : key1[1],
 "body" : "Bhav Updated for : \n" + string
 }
 }

{
 "to" : "/topics/all",
 "data" : null,
 "notification" : {
 "title" : key1[1],
 "body" : "Bhav Updated for : \n" + string
 }
 }

{
 "to" : "/topics/all",
 "notification" : {
 "title" : key1[1],
 "body" : "Bhav Updated for : \n" + string
 }
 }

I found many issues as similar to mine. but no solution works.

Please HELP!!!

**Comment by nan-li** [comment]
Hi @Tushark690,

I apologize for the very late reply. I see you are using `firebase_messaging` plugin. Are you also using OneSignal?

**Comment by emawby** [comment]
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen

**Comment by d-nghia** [comment]
Im also having this problem using both firebase_messaging and OneSignal

 the function FirebaseMessaging.onBackgroundMessage(_onBackgroundMessage); doesnt go in to _onBackgroundMessage when receive notification on the background
