### ISSUE TITLE
Change CFBundleVersion from NotificationServiceExtension

### ISSUE THREAD

**Issue by caiogranero** [OneSignal/OneSignal-Flutter-SDK#303]
**Description:**
Hi,

I have configured in my application OneSignal, so I need to create a Notification Service Extension on my iOS project.

The problem is that, when I publish my app on Apple Store, Im getting this error:

> ITMS-90473: CFBundleVersion Mismatch - The CFBundleVersion value '15' of extension 'Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex' does not match the CFBundleVersion value '147' of its containing iOS application 'Runner.app'.

Im building the project with FastLane, this is my publish script:

```
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_number = number_of_commits(all: true)

    Dir.chdir ".." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "pub", "get")
      sh("flutter", "build", "ios", "--obfuscate", "--split-debug-info=logs", "--release", "-t", "lib/main_prod.dart", "--build-number=#{build_number}")
    end

    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_method: 'app-store', silent: true)
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
```

My question is: What should I do to flutter build, change the CFBundleVersion from my ServiceExtension? 

Thank you :)

**Environment**

1. onesignal_flutter version: 2.4.1
1. flutter version: Flutter 1.20.4 • channel stable

**Comment by KoofNG** [comment]
The CFBundleVersion value '15' of extension 'Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex' must be the same with CFBundleVersion value '147' of its containing iOS application 'Runner.app'.

That is the CFBundleVersion value of Runner App and the OneSignalNotificationExtension must be the same.

**Comment by caiogranero** [comment]
Yes, but how do i change CFBundleVersion from OneSignalNotificationExtension together with Runner App? I'm using `flutter build --build-number` but this updates only Runner.

**Comment by KoofNG** [comment]
You can easily change it from your Xcode fields.

**Comment by caiogranero** [comment]
Ok, but what if I don't want to have to open Xcode everytime I release a new version? Im using fast lane to automatically update my flutter version

**Comment by KoofNG** [comment]
Since you are using the --build-number as a parameter or argument for the Runner App, you would have to configure the OneSignalNotificationExtension also that same way, so it would change each time you run the command.

**Comment by caiogranero** [comment]
hum, thank you. But how can i do this?

**Comment by KoofNG** [comment]
flutter build --build-number
Do you know where the --build-number argument is passed in your code

**Comment by caiogranero** [comment]
Yes, i'm doing --build-number=#{build_number} in fastfile, i put they in the question. But when i use --build-number, just update Runner App and not OneSignalNotificationExtension.

**Comment by akifarhan** [comment]
Any update on this? I'm having the same problem too. It's so tedious to keep on update the version and build number manually

**Comment by caiogranero** [comment]
Not yet @akifarhan :(

I'm just ignoring apple warnings for now.

**Comment by rwrz** [comment]
This is what I have done on my Flutter project. Get the build and version numbers (after a `flutter build ios`), then set them again using increment.
```ruby
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_number = get_build_number(xcodeproj: "Runner.xcodeproj")
    version_number = get_version_number(xcodeproj: "Runner.xcodeproj", target: 'Runner')
    increment_build_number(xcodeproj: "Runner.xcodeproj", build_number: build_number)
    increment_version_number(xcodeproj: "Runner.xcodeproj", version_number: version_number)
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end
```

**Comment by boris93** [comment]
> Not yet @akifarhan :(
> 
> I'm just ignoring apple warnings for now.

I think this is relevant: https://github.com/flutter/flutter/issues/66900#issuecomment-707325905

**Comment by emawby** [comment]
@boris93 Good find that appears to resolve the issue. If that solution does not work feel free to reopen!

**Comment by ernesto** [comment]
The https://github.com/flutter/flutter/issues/66900#issuecomment-707325905 doesn't resolves the onesignal problem with automatic builds. Changing the configurations breaks the onesignal extension build in adhoc and app store (arm64 issue).
