### ISSUE TITLE
Not a OneSignal formatted Bundle. No 'custom' field in the bundle.

### ISSUE THREAD

**Issue by sherifhasan** [OneSignal/OneSignal-Flutter-SDK#305]
**Description:**
When trying to receive notification sent from my server I received this error in android studio console 
**Note:** 
I removed the ids for devices in android & iOS and appId from the issue here but I included them in my code
The notification sent from server 
`{
"include_android_reg_ids":[
],
"include_ios_tokens":[
],
"headings":{
"en":"طلب جديد في قائمة الانتظار"
},
"data":{
"date-time-utc":"9/27/2020 3:07:06 PM",
"type":"new-pending-order",
"order-id":"1181",
"customer-id":"507",
"click_action":"FLUTTER_NOTIFICATION_CLICK"
}
}`

This my code 
[Example app](https://github.com/sherifhasan/FlutterSamples/tree/master/Notifications/one_signal)

**Environment**

1.  onesignal_flutter: ^2.0.0
1. I followed flutter sdk setup  from one signal [(Setup)](https://documentation.onesignal.com/docs/flutter-sdk-setup)

 -->

**Steps to Reproduce Issue:**

1. Install the OneSignal Flutter SDK using pub into your project
1. Initialize the SDK using OneSignal.shared.init(your_app_id)
1. Attempt to receive a push notification

**Comment by nan-li** [comment]
Hi @sherifhasan,

I apologize for the lack of response. 

Was this ever resolved for you? Do you remember what was the error that you received in Android Studio?
