### ISSUE TITLE
Onesignal segment usage - tag deletion does not occur.

### ISSUE THREAD

**Issue by sketchuprzr** [OneSignal/OneSignal-Flutter-SDK#307]
I am using Onesignal ^ 2.6.1 version with pub in flutter.

My problem is as follows;
My application has the "user_type": "vip" tag.
some users can have this tag with a specified method (sendtag).

I want to remove this tag of some users. I delete the "x" user from the Onesignal / audience / All users panel. But when the user starts the application, it comes back with the "vip" tag on the panel.

should come with the standard segment when a deleted user arrives.

In the sdk library (documentation) I could not find a title related to this.

![image](https://user-images.githubusercontent.com/60021696/95915024-3dab3380-0daf-11eb-8aab-521114688406.png)

When the application started, I wanted to query if the user has a tag. If the user is not registered in the system (ie deleted) I wanted to delete the tag data from the application cache.

I tried a solution like this but it didn't work.

**Comment by nan-li** [comment]
Hi @sketchuprzr,

I am very sorry for the lack of response. Was this ever resolved for you?

The SDK has changed a lot since October 2020, so this may not be relevant anymore.
