### ISSUE TITLE
query the segments of a user

### ISSUE THREAD

**Issue by hectorvillag** [OneSignal/OneSignal-Flutter-SDK#308]
Hello, I need to know in which segments is a user, but I have not found anything useful to know that, someone knows how to get them?

**Comment by rgomezp** [comment]
Howdy,
There is no way to do this currently. It sounds like what you may want to do is add tags to the user. You can then easily query the tags associated with that user by calling `getTags`.

You can read more about tags [here](https://documentation.onesignal.com/docs/sdk-reference#gettags-method).

Hope this helps. Enjoy!
