### ISSUE TITLE
When will method openedHandler invoked exactly ?

### ISSUE THREAD

**Issue by bagus-repository** [OneSignal/OneSignal-Flutter-SDK#309]
**Description:**

Correct me, when notification opened it will open the apps with normally (run main.dart navigate to initialRoute of the apps). So I have this code for handle opened notification, it will navigate to initialRoute with arguments.

<pre><code>static void handleNotification(OSNotificationOpenedResult result) {
    NavigationService _navigationService = locator<NavigationService>();
    if (result.notification.payload.additionalData.length > 0) {
      print('openedhandler');
      var data = result.notification.payload.additionalData;
      String page = data['page'] ?? null;
      print(data['data']);

```
  if (page == 'news') {
    print(page);
    try {
      if (_navigationService.navigatorKey.currentState != null) {
        News news =
            News.fromJson(new Map<String, dynamic>.from(data['data']));
        print('ok');
        _navigationService.navigatorKey.currentState.pushNamed('/',
            arguments: SplashScreenPageArguments(
                redirect: true, page: 'newsdetail', data: news));
      } else {
        print('can\'t get navigatorKey');
      }
    } catch (e) {
      print(e.toString());
    }
  }
}
```

  }</code></pre>

From above code the behavior is, when app starts it will go to initialRoute and then handler invoked, because I push to '/' this will load initialRoute twice and broke the navigations.

So if I navigate to another page from the handler, I can not figure out when will the page pushed to the navigations stack ?
Example : In the initialRoute screen I have a check and navigate to another screen `'/' -> 'a'`, sometimes the pushed screen (b) from handler can be `'/' -> 'b' -> 'a' or '/' -> 'b' -> 'a'`

<pre><code>
if (token != null) {
        if (widget.arguments != null) {
          if (widget.arguments.redirect) {
            Navigator.of(context).pushReplacementNamed(widget.arguments.page,
                arguments: widget.arguments.data);
          } else {
            Navigator.of(context).pushReplacementNamed('/layout',
                arguments: ScreenArguments(stringData: token));
          }
        } else {
          Navigator.of(context).pushReplacementNamed('/layout',
              arguments: ScreenArguments(stringData: token));
        }
      } else {
        Navigator.of(context).pushReplacementNamed('/login');
      }
</code></pre>

So how to push screen from handler after all navigation from intialRoute done ?

**Environment**

1. Flutter 1.20.3
1. onesignal_flutter: ^2.6.1
1. Android and iOS
**Steps to Reproduce Issue:**

1. Make initialRoute (/) that Navigate to another screen (a) without user interaction (can using Future.delayed)
1. Make openedHandler and push screen with navigator key (b)
1. Click the notification

**Anything else:**

Any better way appreciated !

**Comment by rgomezp** [comment]
Howdy @bagus-repository ,
Thank you for your question.

I cannot speak to the best way to perform routing in your Flutter app. However, I did notice that your code snippet doesn't actually ever call `OneSignal`. It sounds like you just need to make sure that you are appropriately setting the routing handler by following our instructions in the OneSignal documentation.

Are you initializing OneSignal in your `main.dart` file?

It should look something like:
```dart
OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {
  // will be called whenever a notification is opened/button pressed.
});
```

The opened handler will fire when the notification is tapped on. You can then use notification data passed in through additionalData to know how to route the user.

You can read more about the notification opened handler [here](https://documentation.onesignal.com/docs/sdk-reference#notification-opened-handler).

I hope that helps!
