### ISSUE TITLE
Different version for the compile  and runtime classpath

### ISSUE THREAD

**Issue by Denmal1982** [OneSignal/OneSignal-Flutter-SDK#31]
when you try to bould apk:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preReleaseBuild'.
> Android dependency 'com.google.android.gms:play-services-base' has different version for the compile (12.0.1) and runtime (15.0.1) classpath. You should manually set the same version via DependencyReso
lution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 

flutter doctor -v
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale ru-RU)
    • Flutter version 0.9.4 at C:\flutter
    • Framework revision f37c235c32 (6 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Connected devices
    ! No devices available

tell me where and what to fix!!! pls

**Comment by Nightsd01** [comment]
@Denmal1982 Can you post your pubspec? It would be helpful to see what other dependencies you are using.

**Comment by Nightsd01** [comment]
@Denmal1982 Also, please try our new release (1.0.3) and let me know if the issue still occurs

**Comment by Denmal1982** [comment]
> @ Denmal1982 Можете ли вы разместить свой pubspec? Было бы полезно посмотреть, какие другие зависимости вы используете.

**Comment by Denmal1982** [comment]
> @ Denmal1982 Также, пожалуйста, попробуйте наш новый выпуск (1.0.3) и дайте мне знать, если проблема все еще возникает

figured out what was the reason, the problem was solved by adding code to the top android/app/build/gradle , 

buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}
