### ISSUE TITLE
Could not resolve all files for configuration ':onesignal_flutter:debugCompileClasspath'.

### ISSUE THREAD

**Issue by erfanegtfi** [OneSignal/OneSignal-Flutter-SDK#310]
**onesignal_flutter: ^2.6.1**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':onesignal_flutter:javaPreCompileDebug'.
> Could not resolve all files for configuration ':onesignal_flutter:debugCompileClasspath'.
   > Could not find cardview.jar (androidx.cardview:cardview:1.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/cardview/cardview/1.0.0/cardview-1.0.0.jar
 Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 Get more help at https://help.gradle.org

**Environment**

Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (6 days ago) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2

**Comment by rgomezp** [comment]
Howdy,
Please make sure to follow our issue template when creating an issue like this so that we can better assist you.

Thank you for your understanding.
