### ISSUE TITLE
Onesignal flutter has deprecated methods and documentation(setup guide) is out of date

### ISSUE THREAD

**Issue by davidAg9** [OneSignal/OneSignal-Flutter-SDK#311]
### warning from flutter log 
`WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
Connecting to VM Service at ws://127.0.0.1:61480/KDQgEVcAUPI=/ws
ERROR: HTTP Request (OSRequestRegisterUser) must contain app_id parameter
Request <OSRequestRegisterUser: 0x6000039ac570> fail result error Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}
ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}
ERROR: Encountered error during email registration with OneSignal: (null)
`

For some reason when I send notification they don't arrive on the phone

**Comment by EjazAmir** [comment]
any solution found?

**Comment by davidAg9** [comment]
no unfortunately

**Comment by EjazAmir** [comment]
> no unfortunately

Im receiving inapp messages in my ios app, but unable to receive push notification? any hack?

**Comment by rgomezp** [comment]
Howdy,
Please make sure to follow our issue template guide when creating a new issue so that we can better assist you. Thank you for understanding.

Duplicate of https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/68
