### ISSUE TITLE
Issue while receiving push notification is ios

### ISSUE THREAD

**Issue by EjazAmir** [OneSignal/OneSignal-Flutter-SDK#312]
Hi, I have implemented onesignal in flutter, im receiving inapp messages but unable to receive push notifications. Working fine on android. Kindly share any solution, i have cross checked the ios implementation and all is goood.

**Comment by rgomezp** [comment]
Howdy,
Please make sure to follow our issue template so we can better assist you. Alternatively, reach out to our support channel at OneSignal.com for free setup assistance from our support team.

Cheers
