### ISSUE TITLE
handleNotificationOpened in iOS when sending background notification

### ISSUE THREAD

**Issue by MuhammedRefaat** [OneSignal/OneSignal-Flutter-SDK#314]
**Description:**

Due to my app inquiry to have background processing when receiving a notification in iOS, I've set the notifications as iOS background notifications using content_available and contents, and according to the documentation, I've added remote notification listener in AppDelegate.swift, and since then, I'm receiving the notification through that listener but OneSignal flutter methods `handleReceivedNotification` and `handleOpenedNotification` are never called.

in `AppDelegate.swift`:

```
    application.registerForRemoteNotifications();

    override func application(_ application: UIApplication,
    didReceiveRemoteNotification userInfo: [AnyHashable : Any],
    fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void){
        // Notification received here
    }
```

in Flutter:

```
    OneSignal.shared.pauseInAppMessages(false);
    OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);
    OneSignal.shared.setNotificationOpenedHandler(handleOpenedNotifications);
    OneSignal.shared
        .setNotificationReceivedHandler((OSNotification notification) {
         handleReceivedNotifications(notification);
    });
```

And If I didn't register the remote notification in AppDelegate, the background notifications are never handled and no processing can be done in the background.

On the other hand, I've tried to unset the listeners at Flutter side and set it at iOS native side in AppDelegate:

```
    let notificationReceivedBlock: OSHandleNotificationReceivedBlock = { notification in
        print("Received Notification - \(String(describing: notification?.payload.notificationID)) - \(String(describing: notification?.payload.title))")
    }
    
    let notificationOpenedBlock: OSHandleNotificationActionBlock = { result in
       // This block gets called when the user reacts to a notification received
       let payload: OSNotificationPayload = result!.notification.payload

       var fullMessage = payload.body
        print("Message = \(String(describing: fullMessage))")

       if payload.additionalData != nil {
         if payload.title != nil {
             let messageTitle = payload.title
                print("Message Title = \(messageTitle!)")
          }

          let additionalData = payload.additionalData
          if additionalData?["actionSelected"] != nil {
            fullMessage = fullMessage! + "\nPressed ButtonID: \(String(describing: additionalData!["actionSelected"]))"
          }
       }
    }
```

but nothing changed, even the app logs coming as the same.

**Environment**

1. Flutter (Channel stable, 1.20.2)
1. OneSignal: onesignal_flutter: ^2.4.0
1. Device (iPhone 6 Plus OS 12.3)

**Steps to Reproduce Issue:**

1.  Installing the app on iOS device with receive and open handlers are being set through the app + remote notification receiver in iOS `AppDelegate.swift` class.
1. Sending a notification with contents and with content_available flag set to 1
1. Flutter receivers are never called when receiving/opening the notification despite remote notification receiver called in `AppDelegate.swift` class.

**The app logs when receiving the notification:**

```
VERBOSE: oneSignalRemoteSilentNotification:UserInfo:fetchCompletionHandler:
VERBOSE: notificationReceived called! foreground: YES isActive: YES opened: NO
VERBOSE: handleNotificationReceived lastMessageID: [MESSAGE_ID] displayType: 2
VERBOSE: onesignalUserNotificationCenter:willPresentNotification:withCompletionHandler: Fired!
VERBOSE: notificationReceived called! foreground: YES isActive: YES opened: NO
```

**The app logs once trying to open the notification:**

```
VERBOSE: onesignalUserNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: Fired!
VERBOSE: notificationReceived called! foreground: YES isActive: NO opened: YES
VERBOSE: HTTP Request (OSRequestSubmitNotificationOpened) with URL: https://api.onesignal.com/notifications/[MESSAGE_ID], with parameters: {
  "opened" : true,
  "player_id" : "[PLAYER_ID]",
  "app_id" : "[APP_ID]",
  "device_type" : 0
}
VERBOSE: handleNotificationOpened called! foreground: YES notificationId: [MESSAGE_ID]
displayType: 2
VERBOSE: network response (OSRequestSubmitNotificationOpened): {
    success = 1;
}
```

**Comment by Jeasmine** [comment]
Hey, @MuhammedRefaat thank you for all the information! We are working on a new major release that changes the way we are handling notifications. You can take a look at https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/313 . But for background notification handling you will need to still create it from the native side.
