### ISSUE TITLE
FlutterRegistrarResponder.java line 8

### ISSUE THREAD

**Issue by hectorvillag** [OneSignal/OneSignal-Flutter-SDK#315]
I have many crashes with the same error in firebase crashlytics

I think this error happens when the sdk tries to get the tags

In my project I use: 

> **Flutter: 1.17.5**
> **onesignal_flutter: 2.5.0**

![image](https://user-images.githubusercontent.com/23240517/99440603-6c4f8900-28dc-11eb-9223-f5244b471b59.png)

I found this issue, but I think the problem persists [Issue](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/190)

**Comment by nan-li** [comment]
Hi @hectorvillag,

Sorry for the delayed response. Your crash does seem to be related to the linked issue you mention.

The PR https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/258 to fix that was released with [version `2.6.0`](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/2.6.0), but you mention you are on version `2.5.0`. I think this may be the issue.

I will close this issue then, but please reach out if you are experiencing any problems.
