### ISSUE TITLE
Unhandled Exception: PlatformException(OneSignal, Encountered an error updating tags (-1)

### ISSUE THREAD

**Issue by longdratech** [OneSignal/OneSignal-Flutter-SDK#316]
**Unhandled Exception: PlatformException(OneSignal, Encountered an error updating tags (-1): You must initialize OneSignal before modifying tags!Moving this operation to a pending task queue., null, null)**
I received an error while running in release mode. However, when running in debug mode, nothing happens.
![image](https://user-images.githubusercontent.com/48413548/99613378-0a149680-2a4a-11eb-9461-8c610268af85.png)
I have setup 
![image](https://user-images.githubusercontent.com/48413548/99613478-34665400-2a4a-11eb-9d27-41eb8d6f7f69.png)
and call in main
![image](https://user-images.githubusercontent.com/48413548/99613555-54961300-2a4a-11eb-95ba-aaa559f42d21.png)
send tag
![image](https://user-images.githubusercontent.com/48413548/99613596-6972a680-2a4a-11eb-84cf-a3aa98f88cc6.png)
Called in BloC
![image](https://user-images.githubusercontent.com/48413548/99613638-7a231c80-2a4a-11eb-9391-214a05fa8f6c.png)

**Comment by phucho236** [comment]
same problem
#358

**Comment by emawby** [comment]
Hello are you still experiencing this issue on the latest version of the SDK?

**Comment by lavinov-mercury** [comment]
@emawby Hi! Around a week ago we started receiving such events in Sentry. It affects only Android users

**Comment by emawby** [comment]
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen
