### ISSUE TITLE
External User ID not updating

### ISSUE THREAD

**Issue by varunkumarmedam** [OneSignal/OneSignal-Flutter-SDK#318]
When I am trying to update ExternalUserID using setExternalUserID() I found, it doens't updating the data.

**Comment by jrahma** [comment]
Same problem

**Comment by varunkumarmedam** [comment]
> Same problem

Whenever this is not updated an exception will rise. We are handling the exception as a temporary solution.

**Comment by jrahma** [comment]
> > Same problem
> 
> Whenever this is not updated an exception will rise. We are handling the exception as a temporary solution.

How do you capture the exception?  I am not getting any errors!

**Comment by jrahma** [comment]
oh Ok I am getting this:

2021-04-15 22:53:04.030 Mawaqeet.iOS[940:162784] WARNING: Attempted to set external user id, but  is already set

but how come it was already set and I have no external user ID on OneSignal portal users' report?

**Comment by emawby** [comment]
I apologize for the late reply. This was a bug in our iOS native SDK that Flutter uses and should be fixed in the latest version. If this is still an issue for you please reopen!
