### ISSUE TITLE
Null-Safety?

### ISSUE THREAD

**Issue by Bwolfs2** [OneSignal/OneSignal-Flutter-SDK#319]
When we will be prepare to use Null-Saftey with OneSignal?

**Comment by LuisGrt** [comment]
I am commenting on this since I am waiting for the null-safety support for a while now.

**Comment by sunderee** [comment]
Similar here, this is the only package that is not null safe in our production code.

**Comment by nrubel** [comment]
Any update on this?

**Comment by renysh** [comment]
Please help with them
