### ISSUE TITLE
iOS SDK is not updated 

### ISSUE THREAD

**Issue by danielgomezrico** [OneSignal/OneSignal-Flutter-SDK#322]
On 2.6.1 Release the internal dependencies are a little bit old.

```
Native Android (3.15.3) and iOS (2.15.2) SDKs
```

Any chance that this is updated?

**Comment by jkasten2** [comment]
@danielgomezrico Thanks for reporting, we updated to the latest native libraries and pushed out a 2.6.2 release shortly after you open this issue.
https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/2.6.2
