### ISSUE TITLE
IMPORTANT!:No Documentation update preventing Smooth integration to new version 

### ISSUE THREAD

**Issue by davidAg9** [OneSignal/OneSignal-Flutter-SDK#323]
I am having a hard time including one signal into my flutter, and updating a project I have because there is no documentation for the latest version on one signal ; and it keeps giving me Error warning as follows :

`onesignal_flutter (from `.symlinks/plugins/onesignal_flutter/ios`) was resolved to 2.6.2, which depends on OneSignal (= 2.16.1)Specs satisfying the `OneSignal, OneSignal (= 2.`

I also want to know if OneSignal plans on us using older version of their sdk

**Comment by jkasten2** [comment]
@davidAg9 Thanks for reporting. It looks like your error got cut off when copy and pasting it here. Could you edit your issue with the full error and reply here when updated?

2.6.2 of this `onesignal_flutter` should be pointing at `OneSignal` on cocoapods at version 2.16.1. This is the latest 2.x.x version of the `OneSignal-iOS-SDK`.

We will be releasing a `onesignal_flutter` 3.0.0-beta1 soon that will be updated to `OneSignal-iOS-SDK` 3.0.0, but the 2.x.x should continue building.

**Comment by davidAg9** [comment]
pardon for the rather late reply but as you stated "2.6.2 of this onesignal_flutter should be pointing at OneSignal on cocoapods at version 2.16.1. This is the latest 2.x.x version of the OneSignal-iOS-SDK."
<img width="1398" alt="Screenshot 2020-12-22 at 6 31 15 PM" src="https://user-images.githubusercontent.com/56321266/102921205-e3e87900-4483-11eb-8c40-e3f04ac58f5c.png">


but you see cocoapods version 2.16.1 doesn't seem  appear there;instead 3.0.1 is existing instead


`target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end`
**As per your current documentation states we should do in the podfile ... and since the version specified is higher I tried lowering the version number but the same error occurs each time** 

### Error

<img width="1139" alt="Screenshot 2020-12-22 at 6 38 19 PM" src="https://user-images.githubusercontent.com/56321266/102921782-e0092680-4484-11eb-9884-9380e424f488.png">
