### ISSUE TITLE
Distinguish between FCM and HCM push tokens

### ISSUE THREAD

**Issue by rostopira** [OneSignal/OneSignal-Flutter-SDK#325]
**Description:**
I need to get pushToken and send it to my backend.
However current implementation `OneSignal.shared.pushToken` just gives token, and I can't detect if it's FCM or HCM.

**Environment**
`onesignal_flutter: 2.6.2`
Installed via pub

**Steps to Reproduce Issue:**

```
OneSignal.shared.pushToken
```

**Comment by sejr1996** [comment]
Use this code:
final OSPermissionSubscriptionState status = await OneSignal.shared.getPermissionSubscriptionState();
   return status.subscriptionStatus.pushToken;

**Comment by jkasten2** [comment]
@rostopira Thanks for the feedback. We will look into adding the type in the future

**Comment by rostopira** [comment]
@jkasten2 I use OneSignal only for time insensitive notifications, but in now-or-never cases own implementation works much faster then OneSignal.
Are you accepting PR's? I can do that, but don't know on which branch it should be based, since there are major release pending
