### ISSUE TITLE
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Fi

### ISSUE THREAD

**Issue by wangxingxing123654** [OneSignal/OneSignal-Flutter-SDK#326]
[!] The `OneSignalNotificationServiceExtension [Debug]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `OneSignalNotificationServiceExtension [Release]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `OneSignalNotificationServiceExtension [Profile]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.profile.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

ios 14.2 , mac big sur,

**Comment by jkasten2** [comment]
@wangxingxing123654 I believe upgrading to CocoaPods 1.10, then running `pod deintegrate` and `pod install` should solve the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` warning.
https://stackoverflow.com/a/63648164/1244574

You can the remove `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` from your `Podfile` which should remove this warning.

I also notice you have the following in the title but it is cut off.
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Fi

Please reply with the full error if you are still seeing an issue with this part.

**Comment by emawby** [comment]
closing for now. If this is still an issue please reopen
