### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by chenxilu0505** [OneSignal/OneSignal-Flutter-SDK#327]
Does this plugin support Android phones in Mainland China now?

**Comment by jkasten2** [comment]
@chenxilu0505 Yes, we support devices that have HMS (Huawei Mobile Services) which will work in Mainland China. See the setup instructions bellow to support Huawei devices:
https://documentation.onesignal.com/docs/huawei-flutter-sdk-setup

If you require support for other push channels / provides let us know.
