### ISSUE TITLE
IOS crashed after update

### ISSUE THREAD

**Issue by ChiHwe** [OneSignal/OneSignal-Flutter-SDK#329]
Environment: Flutter
onesignal flutter version: 2.3.4 

The apps immediately crashed after user update the app when they open it, and i have checked the log, it is due to the Onesignal issue, Anyone can help on it? What is this exception regarding ? How can i solve this issue? below are the crash log.

<img width="1274" alt="Screenshot 2021-01-06 at 10 11 48 AM" src="https://user-images.githubusercontent.com/24539251/103721059-b6fd9f80-5007-11eb-8b61-1f0e6253c961.png">

**Comment by emawby** [comment]
@ChiHwe I apologize for the late reply. This was an issue in our iOS native SDK and is fixed in new versions.
