### ISSUE TITLE
Failed to set placeholder attributtes

### ISSUE THREAD

**Issue by irvine5k** [OneSignal/OneSignal-Flutter-SDK#332]
## Version
```yaml
onesignal_flutter: 2.6.1
```

## Description

When configure `CFBundleVersion` at One Signal `info.plist` to get `FLUTTER_BUILD_NUMBER` build fails.

`CFBundleShortVersionString` with `FLUTTER_BUILD_NAME `works. Also the same env variables at the Runner `info.plist` works.

With this error I have to change the version at each new deploy.

Error 

```txt
Unable to install /Users/x/x/app-flutter/build/ios/iphonesimulator/Runner.app on CA3FED41-0DEB-4FA6-93E2-6941E27A5AB4. This is sometimes caused by a malformed plist file:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=IXErrorDomain, code=2):
Failed to create plugin placeholder for /Users/x/x/app-flutter/build/ios/iphonesimulator/Runner.app/PlugIns/OneSignalNSE.appex
Failed to create promise.
Underlying error (domain=IXErrorDomain, code=2):
	Failed to set placeholder attributes com.cingulo.app.OneSignalNSE
	Failed to create promise.
  Command: xcrun simctl install CA3FED41-0DEB-4FA6-93E2-6941E27A5AB4 /Users/x/x/app-flutter/build/ios/iphonesimulator/Runner.app
Error launching application on iPhone SE (2nd generation).
```

- - -
Keys at plist

```txt
<key>CFBundleShortVersionString</key>
<string>$(FLUTTER_BUILD_NAME)</string>
<key>CFBundleVersion</key>
<string>$(FLUTTER_BUILD_NUMBER)</string>
```

- - -
Xcode

![image](https://user-images.githubusercontent.com/32758755/104050117-da217e00-51c4-11eb-9264-42b1c1c6e73c.png)

- - -
Podfile

```txt
target 'OneSignalNSE' do
  use_frameworks!
  pod 'OneSignal', '>= 2.15.2', '< 3.0'
end
```

**Comment by emawby** [comment]
@irvine5k Can you clarify which plist you are changing? Are you trying to change the plist for your Notification Service Extension or for the OneSignal framework? You should not be changing the plist for the OneSignal framework

**Comment by emawby** [comment]
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen

**Comment by Sirojiddin10** [comment]
I have the following error:
`Unable to install /Users/x/x/x-app/build/ios/iphonesimulator/Runner.app on 213F4BE7-1245-46B5-9C69-8EF2B94BC81F. This is sometimes caused by a malformed plist file:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=IXErrorDomain, code=2):
Simulator device returned an error for the requested operation.
Failed to create promise.
Underlying error (domain=IXErrorDomain, code=2):
	Failed to create app extension placeholder for /Users/x/x/x-app/build/ios/iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex
	Failed to create promise.
  Command: /usr/bin/arch -arm64e xcrun simctl install 213F4BE7-1245-46B5-9C69-8EF2B94BC81F /Users/x/x/x-app/build/ios/iphonesimulator/Runner.app
Error launching application on iPhone 15 Pro Max.`

A week ago it was running properly. Now I have the following. What should I do?

**Comment by Abdktefane** [comment]
> I have the following error: `Unable to install /Users/x/x/x-app/build/ios/iphonesimulator/Runner.app on 213F4BE7-1245-46B5-9C69-8EF2B94BC81F. This is sometimes caused by a malformed plist file: ProcessException: Process exited abnormally: An error was encountered processing the command (domain=IXErrorDomain, code=2): Simulator device returned an error for the requested operation. Failed to create promise. Underlying error (domain=IXErrorDomain, code=2): Failed to create app extension placeholder for /Users/x/x/x-app/build/ios/iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex Failed to create promise. Command: /usr/bin/arch -arm64e xcrun simctl install 213F4BE7-1245-46B5-9C69-8EF2B94BC81F /Users/x/x/x-app/build/ios/iphonesimulator/Runner.app Error launching application on iPhone 15 Pro Max.`
> 
> A week ago it was running properly. Now I have the following. What should I do?

same is happening to me
any idea how to solve it ? @Sirojiddin10
