### ISSUE TITLE
Not able to update email using Method setEmail 

### ISSUE THREAD

**Issue by geekmindztej** [OneSignal/OneSignal-Flutter-SDK#333]
**Description:**

I am using Onesignal-flutter-sdk 2.6.1. Below is the scenario's for better understanding.

1] Installed a new app -> Login with email -> SetEmail is working in one signal. -> Logout using Method logoutEmail
2] Logout from app -> ReLogin with another email -> SetEmail is not updating the on the one signal, while i am getting email set successfully in the response.

**Environment**

**Steps to Reproduce Issue:**

1] Installed a new app -> Login with email -> SetEmail is working in one signal. -> Logout using Method logoutEmail
2] Logout from app -> ReLogin with another email -> SetEmail is not updating the on the one signal, while i am getting email set successfully in the response.

**Anything else:**

(crash stacktraces, as well as any other information here)

![Screenshot 2021-01-12 at 2 33 48 AM](https://user-images.githubusercontent.com/18075389/104283823-20a20180-547f-11eb-8087-51895976c23e.png)

![Screenshot 2021-01-12 at 2 36 11 AM](https://user-images.githubusercontent.com/18075389/104283890-38798580-547f-11eb-96e5-3b0c6a3c04fe.png)

**Comment by emawby** [comment]
@geekmindztej I apologize for the very late response. Are you still experiencing this issue?

**Comment by emawby** [comment]
Closing this issue for now. Please reopen if you are still experiencing this problem
