### ISSUE TITLE
Custom notification sound not playing on Flutter in release APK

### ISSUE THREAD

**Issue by gadishimwe** [OneSignal/OneSignal-Flutter-SDK#335]
**Description:**

I've added custom notification sound in my flutter app(only android) and I followed the documentation to do so. The problem I'm having is that the sound is playing in debug apk, but not in release one.

**Environment**

* Version: 2.6.2
* Installed it via pub

Any help will be highly much appreciated. Thanks

**Comment by rostopira** [comment]
This is due resource shrinking. You can disable it or force-keep your sound file: https://stackoverflow.com/questions/5848761/how-can-i-force-proguard-to-keep-my-xml-resource-file

**Comment by gadishimwe** [comment]
Thank you very much @rostopira. You really saved me

**Comment by JuanFCVal** [comment]
> Muchas gracias @rostopira . Realmente me salvaste

Hola, podrías explicar exactamente como lo solucionaste? Tengo el mismo problema y no he entendido aún como solucionarlo.
