### ISSUE TITLE
Hide/Block Push Notification in Foreground

### ISSUE THREAD

**Issue by mingosnunes** [OneSignal/OneSignal-Flutter-SDK#336]
Hi,

Is possible to hide/block push notifications with the app in foreground based on a condition?

For example, if one user is inside a chat page should not show notifications of new messages for that chat but still show notifications from other chats.

I could not find anything on the documentation about this but I think is possible to do it on native android/ios.

Thanks!

**Comment by RodrigoSMarques** [comment]
Did you make it?
I have the same problem.

**Comment by mingosnunes** [comment]
This feature is available in the [null-safety](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/357) version. 
Still on beta.

**Comment by RodrigoSMarques** [comment]
> This feature is available in the [v3 & null-safety](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/357) version.
> Still on beta.

Do you know how to tell me the name of the method?

```dart 
setNotificationWillShowInForegroundHandler
```

**Comment by mingosnunes** [comment]
I think so. Follow this migration [guide](https://documentation.onesignal.com/docs/step-by-step-flutter-2x-to-300-upgrade-guide)

**Comment by RodrigoSMarques** [comment]
Very good. This was exactly what I needed.

https://documentation.onesignal.com/docs/flutter-30-api-reference#setnotificationwillshowinforegroundhandler-function

Thank You.
