### ISSUE TITLE
when app is teminated , we can received the notification, but 【 OneSignal.shared         .setNotificationOpenedHandler】 cannot be executed

### ISSUE THREAD

**Issue by wangxingxing123654** [OneSignal/OneSignal-Flutter-SDK#337]
**Description:**

when app is teminated , we can received the notification, but 【 OneSignal.shared         .setNotificationOpenedHandler】 cannot be executed

**Comment by MeAtPros** [comment]
I got this error "remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification"

**Comment by rodruiz** [comment]
> I got this error "remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification"

Got the same message.

**Comment by agarwalrohit2503** [comment]
Any fixes to this problem ?

**Comment by wrteam02** [comment]
Got the same message.
-----------------------
remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification

**Comment by andredealmei** [comment]
same here

**Comment by syahnurizal** [comment]
Having the same issue. anyone found a solution for this?

**Comment by apoorvpandey0** [comment]
Same issue

**Comment by esentis** [comment]
Any updates on that ?

**Comment by emawby** [comment]
Closing as a duplicate of #540 which has more recent discussion

**Comment by emmadedayo** [comment]
remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification
who can help with this?
