### ISSUE TITLE
Flutter Black screen when launch for 1s in iOS 14.2 later

### ISSUE THREAD

**Issue by vukhacbiet** [OneSignal/OneSignal-Flutter-SDK#339]
**Description:**
My Application have been black screen, about 1 second before splash image show.
When i uninstall OneSignal package, this issue disappear.

**Environment**

1. What version of the OneSignal Flutter SDK are you using: 2.6.2
1. How did you add the SDK to your project: Flutter Pub

**Comment by smappinc** [comment]
hey, did u manage to solve this?
