### ISSUE TITLE
iOS 12.0 / 12.1 not supported ?

### ISSUE THREAD

**Issue by sjmcdowall** [OneSignal/OneSignal-Flutter-SDK#35]
**Description:**

Your README.md indicates this is only tested  to iOS 11.3.  So is 12.0 / 12.1 not supported? Or just not tested or -- tested but the README.md is out of date?

**Environment**

N/A

**Steps to Reproduce Issue:**

N/A

**Comment by Nightsd01** [comment]
@sjmcdowall Good observation. Our readme is out of date - we've tested our Flutter SDK with iOS 12/12.1 and it works fine! I'll update our documentation - thanks!
