### ISSUE TITLE
Its possible setNotificationReceivedHandler work in background?

### ISSUE THREAD

**Issue by jeffersonmello** [OneSignal/OneSignal-Flutter-SDK#352]
Its possible setNotificationReceivedHandler work in background?

**Comment by LuisGrt** [comment]
I tried to do this as well in one of my projects. After some research, I managed setting up the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) for both platforms.

**Comment by jeffersonmello** [comment]
> I tried to do this as well in one of my projects. After some research, I managed setting up the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) for both platforms.

Thanks for you reply, then i need write code native for Android and for iOS

**Comment by AkashMi5** [comment]
> > I tried to do this as well in one of my projects. After some research, I managed setting up the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) for both platforms.
> 
> Thanks for you reply, then i need write code native for Android and for iOS

Hi, I am trying to get One Signal notifications in background using Service Extensions link you have shared from One Signal documentation, however, without success. Could you provide native code for Android and iOS if it is possible for you.

**Comment by jeffersonmello** [comment]
> > > I tried to do this as well in one of my projects. After some research, I managed setting up the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) for both platforms.
> > 
> > 
> > Thanks for you reply, then i need write code native for Android and for iOS
> 
> Hi, I am trying to get One Signal notifications in background using Service Extensions link you have shared from One Signal documentation, however, without success. Could you provide native code for Android and iOS if it is possible for you.

Yes sure, but dont have the code for iOS, only for Android, when iOS code fineshed i post in this the issue, if someone have code for iOS please share with us :)

**Comment by LuisGrt** [comment]
> > > I tried to do this as well in one of my projects. After some research, I managed setting up the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) for both platforms.
> > 
> > 
> > Thanks for you reply, then i need write code native for Android and for iOS
> 
> Hi, I am trying to get One Signal notifications in background using Service Extensions link you have shared from One Signal documentation, however, without success. Could you provide native code for Android and iOS if it is possible for you.

Sure, but that will depend on what do you want to do with the notification. For example I am storing it right after on a SQLite database. I don't know what functionality you want to give to your application.

I was having the issue that the notification was lost if the app was in background or not even running and the user dismiss the notification alert. I needed a way to catch it and storing no matter if the app is running or not.

**Comment by jeffersonmello** [comment]
> > > > I tried to do this as well in one of my projects. After some research, I managed setting up the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) for both platforms.
> > > 
> > > 
> > > Thanks for you reply, then i need write code native for Android and for iOS
> > 
> > 
> > Hi, I am trying to get One Signal notifications in background using Service Extensions link you have shared from One Signal documentation, however, without success. Could you provide native code for Android and iOS if it is possible for you.
> 
> Sure, but that will depend on what do you want to do with the notification. For example I am storing it right after on a SQLite database. I don't know what functionality you want to give to your application.
> 
> I was having the issue that the notification was lost if the app was in background or not even running and the user dismiss the notification alert. I needed a way to catch it and storing no matter if the app is running or not.

I need this, i need save my notification in sqlite db used in sqfentity on flutter, you have code saving in sqlite for ios?

**Comment by AkashMi5** [comment]
> > > > I tried to do this as well in one of my projects. After some research, I managed setting up the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) for both platforms.
> > > 
> > > 
> > > Thanks for you reply, then i need write code native for Android and for iOS
> > 
> > 
> > Hi, I am trying to get One Signal notifications in background using Service Extensions link you have shared from One Signal documentation, however, without success. Could you provide native code for Android and iOS if it is possible for you.
> 
> Sure, but that will depend on what do you want to do with the notification. For example I am storing it right after on a SQLite database. I don't know what functionality you want to give to your application.
> 
> I was having the issue that the notification was lost if the app was in background or not even running and the user dismiss the notification alert. I needed a way to catch it and storing no matter if the app is running or not.

I am also storing the received notifications in sqlite, it is working perfectly fine when app is open or just closed but when I swipe away the app from recent apps, it does not work. Notification sent from the One Signal does not come in the sqlite db and we lose it forever.

**Comment by AkashMi5** [comment]
> > > > I tried to do this as well in one of my projects. After some research, I managed setting up the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) for both platforms.
> > > 
> > > 
> > > Thanks for you reply, then i need write code native for Android and for iOS
> > 
> > 
> > Hi, I am trying to get One Signal notifications in background using Service Extensions link you have shared from One Signal documentation, however, without success. Could you provide native code for Android and iOS if it is possible for you.
> 
> Sure, but that will depend on what do you want to do with the notification. For example I am storing it right after on a SQLite database. I don't know what functionality you want to give to your application.
> 
> I was having the issue that the notification was lost if the app was in background or not even running and the user dismiss the notification alert. I needed a way to catch it and storing no matter if the app is running or not.

![notification1](https://user-images.githubusercontent.com/46740417/111064034-e8975900-84d7-11eb-8e9d-58438bf4c82b.jpg)
![notification2](https://user-images.githubusercontent.com/46740417/111064039-ef25d080-84d7-11eb-8c07-653efc0a56e5.jpg)
![notifications3](https://user-images.githubusercontent.com/46740417/111064052-f9e06580-84d7-11eb-8157-203364e364fa.jpg)

In the main.dart file, in the setNotificationReceivedHandler I am calling the function to insertOrUpdate function on the database on receiving the notification. How I can call this from native android?

**Comment by AkashMi5** [comment]
> > > > > I tried to do this as well in one of my projects. After some research, I managed setting up the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) for both platforms.
> > > > 
> > > > 
> > > > Thanks for you reply, then i need write code native for Android and for iOS
> > > 
> > > 
> > > Hi, I am trying to get One Signal notifications in background using Service Extensions link you have shared from One Signal documentation, however, without success. Could you provide native code for Android and iOS if it is possible for you.
> > 
> > 
> > Sure, but that will depend on what do you want to do with the notification. For example I am storing it right after on a SQLite database. I don't know what functionality you want to give to your application.
> > I was having the issue that the notification was lost if the app was in background or not even running and the user dismiss the notification alert. I needed a way to catch it and storing no matter if the app is running or not.
> 
> ![notification1](https://user-images.githubusercontent.com/46740417/111064034-e8975900-84d7-11eb-8e9d-58438bf4c82b.jpg)
> ![notification2](https://user-images.githubusercontent.com/46740417/111064039-ef25d080-84d7-11eb-8c07-653efc0a56e5.jpg)
> ![notifications3](https://user-images.githubusercontent.com/46740417/111064052-f9e06580-84d7-11eb-8157-203364e364fa.jpg)
> 
> In the main.dart file, in the setNotificationReceivedHandler I am calling the function to insertOrUpdate function on the database on receiving the notification. How I can call this from native android?

@jeffersonmello Can you help with this for the android?

**Comment by jeffersonmello** [comment]
> > > > > > I tried to do this as well in one of my projects. After some research, I managed setting up the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) for both platforms.
> > > > > 
> > > > > 
> > > > > Thanks for you reply, then i need write code native for Android and for iOS
> > > > 
> > > > 
> > > > Hi, I am trying to get One Signal notifications in background using Service Extensions link you have shared from One Signal documentation, however, without success. Could you provide native code for Android and iOS if it is possible for you.
> > > 
> > > 
> > > Sure, but that will depend on what do you want to do with the notification. For example I am storing it right after on a SQLite database. I don't know what functionality you want to give to your application.
> > > I was having the issue that the notification was lost if the app was in background or not even running and the user dismiss the notification alert. I needed a way to catch it and storing no matter if the app is running or not.
> > 
> > 
> > ![notification1](https://user-images.githubusercontent.com/46740417/111064034-e8975900-84d7-11eb-8e9d-58438bf4c82b.jpg)
> > ![notification2](https://user-images.githubusercontent.com/46740417/111064039-ef25d080-84d7-11eb-8c07-653efc0a56e5.jpg)
> > ![notifications3](https://user-images.githubusercontent.com/46740417/111064052-f9e06580-84d7-11eb-8157-203364e364fa.jpg)
> > In the main.dart file, in the setNotificationReceivedHandler I am calling the function to insertOrUpdate function on the database on receiving the notification. How I can call this from native android?
> 
> @jeffersonmello Can you help with this for the android?

I need finish my solution complety in android native, when finished, i post in this issue

**Comment by AkashMi5** [comment]
> > > > > > > I tried to do this as well in one of my projects. After some research, I managed setting up the [Service Extensions](https://documentation.onesignal.com/docs/service-extensions) for both platforms.
> > > > > > 
> > > > > > 
> > > > > > Thanks for you reply, then i need write code native for Android and for iOS
> > > > > 
> > > > > 
> > > > > Hi, I am trying to get One Signal notifications in background using Service Extensions link you have shared from One Signal documentation, however, without success. Could you provide native code for Android and iOS if it is possible for you.
> > > > 
> > > > 
> > > > Sure, but that will depend on what do you want to do with the notification. For example I am storing it right after on a SQLite database. I don't know what functionality you want to give to your application.
> > > > I was having the issue that the notification was lost if the app was in background or not even running and the user dismiss the notification alert. I needed a way to catch it and storing no matter if the app is running or not.
> > > 
> > > 
> > > ![notification1](https://user-images.githubusercontent.com/46740417/111064034-e8975900-84d7-11eb-8e9d-58438bf4c82b.jpg)
> > > ![notification2](https://user-images.githubusercontent.com/46740417/111064039-ef25d080-84d7-11eb-8c07-653efc0a56e5.jpg)
> > > ![notifications3](https://user-images.githubusercontent.com/46740417/111064052-f9e06580-84d7-11eb-8157-203364e364fa.jpg)
> > > In the main.dart file, in the setNotificationReceivedHandler I am calling the function to insertOrUpdate function on the database on receiving the notification. How I can call this from native android?
> > 
> > 
> > @jeffersonmello Can you help with this for the android?
> 
> I need finish my solution complety in android native, when finished, i post in this issue

Hi brother, any luck with it?

**Comment by emawby** [comment]
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen

**Comment by phucvinh-hub** [comment]
I am currently facing the same issue, can anyone tell me how to get background notifications when an app is in the background or killed?
