### ISSUE TITLE
Builds fails with "Failed to list versions for com.google.firebase:firebase-messaging"

### ISSUE THREAD

**Issue by berkayoruc** [OneSignal/OneSignal-Flutter-SDK#353]
**Description:**
I checked similar issues but they cannot help me. Also, I did `flutter clean` command. When I build the app using "onesignal_flutter: ^2.0.0" in android, this error happens:

```
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.firebase:firebase-messaging:[15.0.0, 16.0.0).
     Required by:
         project :app > com.onesignal:OneSignal:3.15.6
      > Failed to list versions for com.google.firebase:firebase-messaging.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/firebase/firebase-messaging/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/firebase/firebase-messaging/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/firebase/firebase-messaging/maven-metadata.xml'.
                  > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 6m 16s
Exception: Gradle task assembleDebug failed with exit code 1

```

**Environment**

1. Flutter version: 1.22.2
1. onesignal_flutter: ^2.0.0
1. the SDK was added through pubspec.yaml and in the gradle following the docs using

android -> build.gradle

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        mavenLocal()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

android -> app -> build.gradle

    buildscript {
        repositories {
            // ...
            maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal
        }
        dependencies {
            // ...
            // OneSignal-Gradle-Plugin
            classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.6, 0.99.99]'
        }
    }
    
    apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
    
    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withReader('UTF-8') { reader ->
            localProperties.load(reader)
        }
    }
    
    def flutterRoot = localProperties.getProperty('flutter.sdk')
    if (flutterRoot == null) {
        throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
    }
    
    def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
    if (flutterVersionCode == null) {
        flutterVersionCode = '5'
    }
    
    def flutterVersionName = localProperties.getProperty('flutter.versionName')
    if (flutterVersionName == null) {
        flutterVersionName = '0.0.5'
    }
    
    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
    
    def keystoreProperties = new Properties()
    def keystorePropertiesFile = rootProject.file('key.properties')
    if (keystorePropertiesFile.exists()) {
        keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
    }
    
    android {
        compileSdkVersion 29
    
        sourceSets {
            main.java.srcDirs += 'src/main/kotlin'
        }
    
        lintOptions {
            disable 'InvalidPackage'
        }
    
        defaultConfig {
            // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
            applicationId "com.hexaapps.hazturk_depremler"
            minSdkVersion 16
            targetSdkVersion 29
            versionCode flutterVersionCode.toInteger()
            versionName flutterVersionName
        }
    
        signingConfigs {
            release {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
                storePassword keystoreProperties['storePassword']
            }
        }
    
        buildTypes {
            release {
                // TODO: Add your own signing config for the release build.
                // Signing with the debug keys for now, so `flutter run --release` works.
                signingConfig signingConfigs.release
            }
        }
    }
    
    flutter {
        source '../..'
    }
    
    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
        implementation platform('com.google.firebase:firebase-bom:26.3.0')
    }

**Comment by berkayoruc** [comment]
I don't know why, but I just restart my computer and problem solved

**Comment by kopianan** [comment]
> I solved this issue with this solution if you do upgrade to Gradle 6.0 this will fix the build issue . To upgrade Gradle update the version number in your project's gradle\wrapper\gradle-wrapper.properties file.
> 
> distributionUrl=https://services.gradle.org/distributions/gradle-6.7.1-all.zip
> 
> as mentioned here [OneSignal/OneSignal-Gradle-Plugin#94 (comment)](https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/94#issuecomment-626399384)

I Fix with this solution too. thankyou dude
