### ISSUE TITLE
How can I modify the com.onesignal:OneSignal:3.15.7 dependancy?

### ISSUE THREAD

**Issue by uj** [OneSignal/OneSignal-Flutter-SDK#355]
**Description:**
I need to make a custom modification to the com.onesignal:OneSignal api dependency that is referenced in build.gradle of OneSignal-Flutter-SDK.

I changed it from
api 'com.onesignal:OneSignal:3.15.7'
to
api 'com.github.xxxx:OneSignal-Android-SDK:master-SNAPSHOT' (which I cloned in github)

This works, in that it compiles, but then later in the build it is missing a lot of items.

com.onesignal:OneSignal actually contains more than just OneSignal-Android-SDK, it is a package of a lot of things, and so there are a lot of dependency errors after building now.

How can I go about this?  Or, how I can build com.onesignal:OneSignal ?

Specifically, I just need to completely remove the res/anim folder.

**Comment by pr-1** [comment]
Are you facing something like this ? @uj 

`
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.onesignal:OneSignal:3.15.7.
     Required by:
         project :app > project :onesignal_flutter
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error
      > Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

`

**Comment by Jeasmine** [comment]
@uj, is this still a problem?
