### ISSUE TITLE
HMS does not call setNotificationReceivedHandler and setNotificationOpenedHandler.

### ISSUE THREAD

**Issue by kuccilim** [OneSignal/OneSignal-Flutter-SDK#356]
**Description:**
Setup follow by this [guide](https://documentation.onesignal.com/docs/flutter-sdk-setup#step-5---initialize-the-onesignal-sdk-all-platforms), but both `setNotificationReceivedHandler` and `setNotificationOpenedHandler` doesn't invoke when notification received, tested with app **killed**, app put to **background** and app **opening**.

**Environment**

1. pubspec version: `onesignal_flutter: ^2.6.2`
1. Android Device without GMS. (Huawei Nova 7i)

FCM did invoke the callback functions.

Thank you.

**Comment by hugoquintalcr** [comment]
How did you fix the problem of unscrbe users (Invalid project number)?

**Comment by MeAtPros** [comment]
Any update in that threat ? I got this issue "remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification"

**Comment by MeAtPros** [comment]
When I click on the push notification, setNotificationOpenedHandler should be called
```
OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {
    try {
      ReceiveNotification.instance.addPushData(result.notification);
    }
    catch(e) {
      print('e : ' + e.toString());
    }
  });
```

Unfortunately, this does not happen and I get the error below

```
I/WM-WorkerWrapper( 7882): Worker result FAILURE for Work [ id=eacb68a2-f7f4-4dd6-9be0-785162b87877, tags={ com.onesignal.OSNotificationRestoreWorkManager$NotificationRestoreWorker } ]
W/OneSignal( 7882): FusedLocationApi.requestLocationUpdates failed!
W/OneSignal( 7882): java.lang.NullPointerException: Calling thread must be a prepared Looper thread.
W/OneSignal( 7882): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source)
W/OneSignal( 7882): 	at com.google.android.gms.internal.location.zzq.requestLocationUpdates(Unknown Source)
W/OneSignal( 7882): 	at com.onesignal.GMSLocationController$FusedLocationApiWrapper.requestLocationUpdates(GMSLocationController.java:198)
W/OneSignal( 7882): 	at com.onesignal.GMSLocationController$LocationUpdateListener.init(GMSLocationController.java:181)
W/OneSignal( 7882): 	at com.onesignal.GMSLocationController$LocationUpdateListener.<init>(GMSLocationController.java:165)
W/OneSignal( 7882): 	at com.onesignal.GMSLocationController.onFocusChange(GMSLocationController.java:117)
W/OneSignal( 7882): 	at com.onesignal.LocationController.onFocusChange(LocationController.java:326)
W/OneSignal( 7882): 	at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1203)
W/OneSignal( 7882): 	at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:282)
W/OneSignal( 7882): 	at java.lang.Thread.run(Thread.java:762)
```

**Comment by kuccilim** [comment]
I had found the problem was due to **Message Type** was not set to **Data**.

**Comment by MeAtPros** [comment]
@kuccilim What do you mean?

**Comment by kuccilim** [comment]
I think you should open a new issue and describe what problem you're facing, provide proper development detail so others can help you.

This issue will be closed because solution had provided. 
https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/356#issuecomment-808227329
