### ISSUE TITLE
Intercept OneSignal logging?

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [OneSignal/OneSignal-Flutter-SDK#361]
**Description:**

I would like to be able to intercept various OneSignal logging like:
`I/OneSignal( 8607): Failed to get Android parameters, trying again in 60 seconds.`

The idea being I could catch this and log it inside my app for easy troubleshooting.

Is there a way to do this?

**Environment**

Flutter SDK 2.6.2

**Comment by Jeasmine** [comment]
Hey @TheMeanCanEHdian, unfortunately, this is not possible since the logs are not exceptions. They are intended for debug mode only. You should use the callback responses to get success and fail messages.

**Comment by TheMeanCanEHdian** [comment]
Can any clarification be provided here please? I imagine others would benefit from the ability to capture and log OneSignal registration success and failures.
