### ISSUE TITLE
Issue with Huawei and not being able to subscribe

### ISSUE THREAD

**Issue by Lawati97** [OneSignal/OneSignal-Flutter-SDK#365]
**Description:**

For some reason, my android users are able to subscribe to OneSignal but Huawei users cannot, and am not certain why

this is my code for calling OneSignal

`import` 'package:onesignal_flutter/onesignal_flutter.dart';
class OneSignalNotificationService {
  `Future<void> initOneSignal() async {

```
OneSignal.shared.setLogLevel(OSLogLevel.info, OSLogLevel.none);
```

```
OneSignal.shared.setRequiresUserPrivacyConsent(false);
```

```
var status = await OneSignal.shared.getPermissionSubscriptionState();
```

```
OneSignal.shared.promptUserForPushNotificationPermission();
```

```
await OneSignal.shared.init("XXXXXXXXXXXXXXXXXXXX",
    iOSSettings: {
      OSiOSSettings.autoPrompt: false,
      OSiOSSettings.inAppLaunchUrl: false
    });
```

```
OneSignal.shared
    .setInFocusDisplayType(OSNotificationDisplayType.notification);
```

```
OneSignal.shared
    .setNotificationReceivedHandler((OSNotification notification) {
  print(
      " Received notification: \n${notification.jsonRepresentation().replaceAll("\\n", "\n")}");
});
```

```
OneSignal.shared.setNotificationOpenedHandler((openedResult) {
  print('Notification Recieved');
});
```

```
await OneSignal.shared
    .promptUserForPushNotificationPermission(fallbackToSettings: true);}}
```

**Environment**

onesignal_flutter: ^2.6.3
am using Flutter 2.0.1

**Comment by hussenIbrahim** [comment]
I am facing the same issue.
How did you solve it ?

**Comment by Lawati97** [comment]
@hussenIbrahim go to Huawei developer and enable the in-app messaging and notification and make sure to connect the SHA-256

**Comment by hussenIbrahim** [comment]
already enabled and SHA-256 is added but until now can't subscribe 

`I/flutter (29038): SUBSCRIPTION STATE CHANGED: {
I/flutter (29038):   "from": "{
I/flutter (29038):   "subscribed": null,
I/flutter (29038):   "userSubscriptionSetting": true,
I/flutter (29038):   "pushToken": null,
I/flutter (29038):   "userId": null
I/flutter (29038): }",
I/flutter (29038):   "to": "{
I/flutter (29038):   "subscribed": null,
I/flutter (29038):   "userSubscriptionSetting": true,
I/flutter (29038):   "pushToken": null,
I/flutter (29038):   "userId": "353ee337-3aa2-43b5-afab-11b62d06d82"
I/flutter (29038): }"
I/flutter (29038): }`

**Comment by Lawati97** [comment]
@hussenIbrahim 
Have you connected your token to the android project?  and have you completed this
https://documentation.onesignal.com/docs/huawei-sdk-setup
https://documentation.onesignal.com/docs/huawei-flutter-sdk-setup

**Comment by ririlya94** [comment]
> @hussenIbrahim Have you connected your token to the android project? and have you completed this https://documentation.onesignal.com/docs/huawei-sdk-setup https://documentation.onesignal.com/docs/huawei-flutter-sdk-setup

Hi there currently I follow all the steps here and still can't subscribe. May I know if you test this project on the huawei physical devices or cloud debugging? Because currently I test this project on cloud debugging
