### ISSUE TITLE
Player id always return null

### ISSUE THREAD

**Issue by wmla419** [OneSignal/OneSignal-Flutter-SDK#368]
(your description here)

**Environment**

What version of the OneSignal Flutter SDK are you using?
onesignal_flutter: ^2.6.3

My Code:

```
OneSignal.shared.getPermissionSubscriptionState().whenComplete(() => {
          OneSignal.shared.getPermissionSubscriptionState().then((value) {
            var playerId = value.subscriptionStatus?.userId;
            print('playerId ' + playerId);
          }),
        });
```

It always return null for the player id, any idea why?

**Comment by rushikeshpawar398** [comment]
did you find any solution ???

**Comment by wmla419** [comment]
> did you find any solution ???

No, still waiting the official to reply

**Comment by Lawati97** [comment]
Try this 
var status = await OneSignal.shared.getPermissionSubscriptionState();
var playerId = status.subscriptionStatus.userId;
print('playerId ${playerId} ');

**Comment by wmla419** [comment]
still return null

> Try this
> var status = await OneSignal.shared.getPermissionSubscriptionState();
> var playerId = status.subscriptionStatus.userId;
> print('playerId ${playerId} ');

still return null sometimes

**Comment by Lawati97** [comment]
@wmla419  try this but the only concern is that if the user is new then it won't work if you found a way to fix kindly keep me posted

var status = await OneSignal.shared.getPermissionSubscriptionState();
    var oneSignalJson = status.subscriptionStatus.jsonRepresentation();
    Map<String, dynamic> user = jsonDecode(oneSignalJson);
    playerId = user['userId'];

**Comment by wmla419** [comment]
I found a temporary solution to make sure player id returns something instead of null. Here is the code.


```    
var playerId = null;
while (playerId == null) {
        var status = await OneSignal.shared.getPermissionSubscriptionState();
        playerId = status.subscriptionStatus.userId;
        print('playerId: $playerId ');
 }
```

> @wmla419 try this but the only concern is that if the user is new then it won't work if you found a way to fix kindly keep me posted I have a couple of concern about this method but hope it helps
> 
> var status = await OneSignal.shared.getPermissionSubscriptionState();
> var oneSignalJson = status.subscriptionStatus.jsonRepresentation();
> Map<String, dynamic> user = jsonDecode(oneSignalJson);
> var playerId = user['userId'];
> 
> and make sure that you are using a future method

**Comment by Lawati97** [comment]
> > @wmla419 try this but the only concern is that if the user is new then it won't work if you found a way to fix kindly keep me posted I have a couple of concern about this method but hope it helps
> > var status = await OneSignal.shared.getPermissionSubscriptionState();
> > var oneSignalJson = status.subscriptionStatus.jsonRepresentation();
> > Map<String, dynamic> user = jsonDecode(oneSignalJson);
> > var playerId = user['userId'];
> > and make sure that you are using a future method
> 
> I found a temporary solution to make sure player id returns something instead of null. Here is the code.
> 
> ```
> var playerId = null;
> while (playerId == null) {
>         var status = await OneSignal.shared.getPermissionSubscriptionState();
>         playerId = status.subscriptionStatus.userId;
>         print('playerId: $playerId ');
>  }
> ```

My concern is that if there will be any slowdown in the application or not if we are using this method

**Comment by wmla419** [comment]
> My conc

I guess it depends. For me, I didn't feel any slowdown in my application, you may give it a try and let me know. I think this is the best solution for now if you need to store the player id in your database.

**Comment by Lawati97** [comment]
> > My conc
> 
> I guess it depends. For me, I didn't feel any slowdown in my application, you may give it a try and let me know. I think this is the best solution for now if you need to store the player id in your database.

I started using the method that you mentioned and wrapped it in a future so I don't get the lag while running the application
