### ISSUE TITLE
Problem with HMS (Huawei Mobile Services)

### ISSUE THREAD

**Issue by hugoquintalcr** [OneSignal/OneSignal-Flutter-SDK#369]
I have a huawei p40 lite without GMS (Google message services) to use firebase, so I´m using one signal to use push notifications with my huawei, but when I want to send notifications my active user says invalid google project number, It´s because I don´t have google in my huawei phone, but I was checking your library and you are using only google services, can you help me?

**Comment by jkasten2** [comment]
@hugoquintalcr This SDK does support Huawei (HMS) push notifications. There are some additional steps you need to follow noted below:
https://documentation.onesignal.com/docs/huawei-flutter-sdk-setup

Let us know where you are seeing the "invalid google project number" error if the above does not help.

**Comment by hugoquintalcr** [comment]
I solved it, thank you..

**Comment by jkasten2** [comment]
@hugoquintalcr Good to hear, what specific issues gave you most the trouble? Would like to hear your feedback on the setup process and troubleshooting steps.
