### ISSUE TITLE
Pub dart page should have link to the GitHub repo

### ISSUE THREAD

**Issue by sjmcdowall** [OneSignal/OneSignal-Flutter-SDK#37]
**Description:**

Pub Dart (Flutter) packages generally (almost always) have a link to the GitHub repo in the "About" section .   The one for OneSignal does not.  Would be handy to have that .. 

https://pub.dartlang.org/packages/onesignal

**Environment**

N/A

**Steps to Reproduce Issue:**

N/A

**Comment by Nightsd01** [comment]
@sjmcdowall I've looked at our pubspec (and other popular Flutter packages) and for the life of me I cannot find a way to actually _put_ our GitHub repo link on our package page. If you know how to do it please feel welcome to make a PR

**Comment by sjmcdowall** [comment]
@Nightsd01 - PR submitted
