### ISSUE TITLE
how to  custom onesignal push notification icons ??

### ISSUE THREAD

**Issue by wangxingxing123654** [OneSignal/OneSignal-Flutter-SDK#371]
https://documentation.onesignal.com/docs/customize-notification-icons#how-to-add-default-icons

there are no flutte versions, so
i try to make ic_stat_onesignal_default icons, and put them into 
android/app/src/main/res/drawable-mdpi/ (24x24)
android/app/src/main/res/drawable-hdpi/ (36x36)
android/app/src/main/res/drawable-xhdpi/ (48x48)
android/app/src/main/res/drawable-xxhdpi/ (72x72)
android/app/src/main/res/drawable-xxxhdpi/ (96x96)
android/app/src/main/res/drawable-xxxhdpi/ (256x256) (Large Icon)

but it didnot worked ,just as white ring bell.

**Comment by meek2100** [comment]
Add this code to android/app/src/main/AndroidManifest.xml.

`
        <meta-data
            android:name="com.onesignal.messaging.default_notification_icon"
            android:resource="@drawable/ic_stat_onesignal_default" />

        <meta-data
            android:name="com.onesignal.NotificationAccentColor.DEFAULT"
            android:value="FFD700" />
`

Then add ic_stat_onesignal_default.png files to: 
android/app/src/main/res/drawable-mdpi/ (24x24)
android/app/src/main/res/drawable-hdpi/ (36x36)
android/app/src/main/res/drawable-xhdpi/ (48x48)
android/app/src/main/res/drawable-xxhdpi/ (72x72)
android/app/src/main/res/drawable-xxxhdpi/ (96x96)
android/app/src/main/res/drawable-xxxhdpi/ (256x256) (Large Icon)

**Comment by Jeasmine** [comment]
Hey @wangxingxing123654, was this solved?

**Comment by Jeffy503** [comment]
working ! Thanks. @meek2100
