### ISSUE TITLE
does not call setNotificationReceivedHandler and setNotificationOpenedHandler.

### ISSUE THREAD

**Issue by MeAtPros** [OneSignal/OneSignal-Flutter-SDK#372]
When I click on the push notification, setNotificationOpenedHandler should be called

```
OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {
    try {
      ReceiveNotification.instance.addPushData(result.notification);
    }
    catch(e) {
      print('e : ' + e.toString());
    }
  });
```

Unfortunately, this does not happen and I get the error below

```
I/WM-WorkerWrapper( 7882): Worker result FAILURE for Work [ id=eacb68a2-f7f4-4dd6-9be0-785162b87877, tags={ com.onesignal.OSNotificationRestoreWorkManager$NotificationRestoreWorker } ]
W/OneSignal( 7882): FusedLocationApi.requestLocationUpdates failed!
W/OneSignal( 7882): java.lang.NullPointerException: Calling thread must be a prepared Looper thread.
W/OneSignal( 7882): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source)
W/OneSignal( 7882): 	at com.google.android.gms.internal.location.zzq.requestLocationUpdates(Unknown Source)
W/OneSignal( 7882): 	at com.onesignal.GMSLocationController$FusedLocationApiWrapper.requestLocationUpdates(GMSLocationController.java:198)
W/OneSignal( 7882): 	at com.onesignal.GMSLocationController$LocationUpdateListener.init(GMSLocationController.java:181)
W/OneSignal( 7882): 	at com.onesignal.GMSLocationController$LocationUpdateListener.<init>(GMSLocationController.java:165)
W/OneSignal( 7882): 	at com.onesignal.GMSLocationController.onFocusChange(GMSLocationController.java:117)
W/OneSignal( 7882): 	at com.onesignal.LocationController.onFocusChange(LocationController.java:326)
W/OneSignal( 7882): 	at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1203)
W/OneSignal( 7882): 	at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:282)
W/OneSignal( 7882): 	at java.lang.Thread.run(Thread.java:762)
```

**Comment by kuccilim** [comment]
What is your dev enviroment? Running with emulator or real device with HMS/GMS ?

**Comment by MeAtPros** [comment]
@kuccilim Real device

**Comment by MeAtPros** [comment]
notifications come to me without a problem, but when I tap on notifications being in the application or outside of it, the notification does not start handler

**Comment by kuccilim** [comment]
Please refer official [docs](https://documentation.onesignal.com/docs/links#deep-linking-with-additional-data).

Only notification with additional data will be called.

**Comment by MeAtPros** [comment]
@kuccilim even the execution of such primitive code does not start, and every time I click on notifications.

 OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {
    print('super: ' + result.toString());
});

**Comment by MeAtPros** [comment]
pubspec.yaml : onesignal_flutter: ^3.0.0-beta1

environment:
  sdk: ">=2.11.0 <3.0.0"

 dependencies {
        classpath 'com.android.tools.build:gradle:4.0.2'
        classpath 'com.google.gms:google-services:4.3.5'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.10'
    }

implementation 'com.onesignal:OneSignal:4.2.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.guava:guava:27.0.1-android'

**Comment by MeAtPros** [comment]
**Everything works fine** on onesignal_flutter: ^2.6.3

implementation 'com.onesignal:OneSignal:3.15.7'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.guava:guava:27.0.1-android'

classpath 'com.android.tools.build:gradle:4.0.2'
        classpath 'com.google.gms:google-services:4.3.5'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

**Comment by MeAtPros** [comment]
@Jeasmine @mikechoch @mpillar Could you look at this issue?

**Comment by MeAtPros** [comment]
@Jeasmine @mikechoch @mpillar Any update ?

**Comment by Jeasmine** [comment]
@MeAtPros, could you provide us with the SDK version that you are using and having this issue? Thanks!

**Comment by MeAtPros** [comment]
@Jeasmine Flutter 2.11

**Comment by Jeasmine** [comment]
@MeAtPros, did https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.0.0-beta2 fix the problem for you?

**Comment by binish784** [comment]
i am getting error this, same senario as @MeAtPros - recieved the notification but on tap, the setNotificationOpenedHandler  not being called 
Starting OneSignal initialization!
No class found, not setting up OSRemoteNotificationReceivedHandler

**Comment by Lawati97** [comment]
Am facing the same error with only Huawei devices when i send a notification with data this function setNotificationReceivedHandler is no used

**Comment by MeAtPros** [comment]
Not solved...

**Comment by MeAtPros** [comment]
@Jeasmine  It's really a joke, or something ... quite a serious failure hangs in the production and no one will correct it

**Comment by Lawati97** [comment]
@MeAtPros in my case everything ended up working fine! 

But am using 
One Signal 2.6.3
Flutter 1.22.6

**Comment by 1996SEJR** [comment]
I have the same problem, on a huawei p20 lite

**Comment by Jeasmine** [comment]
Hey @MeAtPros, we have tested this with the example app on Android and Huawei devices, we are not reproducing the problem. I see that the error is trying to access the location. Can you disable the location and send the log for when you receive the notification and try to open it? Also, could you provide your OneSignal configuration? I appreciate any help you can provide.

**Comment by Jeasmine** [comment]
Hey @1996SEJR, would you be able to send me more information about the problem you are facing? setNotificationOpenedHandler is not called?  For an Android or a Huawei notification? with which notification configuration?  I appreciate any help you can provide.

**Comment by emawby** [comment]
Closing for now. If this is still an issue feel free to reopen
