### ISSUE TITLE
Can no longer distribute app with Validation Error "Found an unexpected Mach-O header code: 0x72613c2" on flutter master

### ISSUE THREAD

**Issue by joshbenaron** [OneSignal/OneSignal-Flutter-SDK#373]
Hey,

This is the same issue as [#166 ](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/166)
I want to run `flutter build ipa --bundle-sksl flutter_01.sksl.json` (due to compilation jank) but when I try to distribute it I get the same error.

I've tried all the current fixes, but I still get the same error when running that command. I can't use xcode directly because I need to bundle the sksl JSON file into an ipa file.

Do you have any ideas?

Thanks,
Josh

**Comment by emawby** [comment]
@joshbenaron sorry for the late reply is this still an issue for you?
