### ISSUE TITLE
Error when building and archiving iOS build - Flutter 2.0.3

### ISSUE THREAD

**Issue by lucasratske** [OneSignal/OneSignal-Flutter-SDK#374]
**Description:**
I upgraded my flutter to the new version and when I tried to build with --release flag I got some errors, I already update the package to the 3.0.0-beta1.

I think it can be a compability issue with firebase... I don't know yet.

Link OneSignalNotificationServiceExtension (arm64) 0.4 seconds
`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FlutterStandardTypedData", referenced from:
      objc-class-ref in firebase_remote_config(FLTFirebaseRemoteConfigPlugin.o)
  "_OBJC_CLASS_$_FlutterError", referenced from:
      objc-class-ref in firebase_core(FLTFirebasePlugin.o)
      objc-class-ref in firebase_dynamic_links(FLTFirebaseDynamicLinksPlugin.o)
      objc-class-ref in onesignal_flutter(OSFlutterCategories.o)
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in firebase_analytics(FLTFirebaseAnalyticsPlugin.o)
      objc-class-ref in firebase_core(FLTFirebaseCorePlugin.o)
      objc-class-ref in firebase_dynamic_links(FLTFirebaseDynamicLinksPlugin.o)
      objc-class-ref in firebase_remote_config(FLTFirebaseRemoteConfigPlugin.o)
      objc-class-ref in onesignal_flutter(OSFlutterOutcomeEventsController.o)
      objc-class-ref in onesignal_flutter(OneSignalPlugin.o)
      objc-class-ref in onesignal_flutter(OSFlutterTagsController.o)
      ...
  "_FlutterMethodNotImplemented", referenced from:
      -[FLTFirebaseAnalyticsPlugin handleMethodCall:result:] in firebase_analytics(FLTFirebaseAnalyticsPlugin.o)
      -[FLTFirebaseCorePlugin handleMethodCall:result:] in firebase_core(FLTFirebaseCorePlugin.o)
      -[FLTFirebaseDynamicLinksPlugin handleMethodCall:result:] in firebase_dynamic_links(FLTFirebaseDynamicLinksPlugin.o)
      -[FLTFirebaseRemoteConfigPlugin handleMethodCall:result:] in firebase_remote_config(FLTFirebaseRemoteConfigPlugin.o)
      -[OSFlutterOutcomeEventsController handleMethodCall:result:] in onesignal_flutter(OSFlutterOutcomeEventsController.o)
      -[OneSignalPlugin handleMethodCall:result:] in onesignal_flutter(OneSignalPlugin.o)
      -[OSFlutterTagsController handleMethodCall:result:] in onesignal_flutter(OSFlutterTagsController.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Environment**
onesignal_flutter: ^3.0.0-beta1
firebase: ^9.0.0
  firebase_analytics: ^7.1.1
  firebase_core: ^1.0.0
  firebase_dynamic_links: ^0.8.0
  firebase_remote_config: ^0.9.0-dev.1
Flutter 2.0.3

**Steps to Reproduce Issue:**

1. Install the OneSignal Flutter SDK using pub into your project
1. Initialize the SDK using OneSignal.shared.setAppId(your_app_id)
1. use promptUserForPushNotificationPermission() and setNotificationWillShowInForegroundHandler(onReceive)
1. use setNotificationOpenedHandler(onOpen);

**Anything else:**
![image](https://user-images.githubusercontent.com/8642078/113575997-2417d580-95f5-11eb-9a88-ec70280777d3.png)

**Comment by nickscamara** [comment]
I am getting the same issue here.

**Comment by nickscamara** [comment]
Any solutions? @lucasratske

**Comment by lucasratske** [comment]
> 
> 
> Any solutions? @lucasratske

Nope, still waiting... I've tried a lot of changes and nothing works

**Comment by nickscamara** [comment]
Same here... well let's wait! Thanks

**Comment by Holofox** [comment]
Solution:
1. Go to `Runner` ->` Info`.
2. Go to the `Configurations` category.
3. Expand all your configurations.

Replace the following configurations for your service:

1. ` Debug` -> `Runner` ->`OneSignalServiceExtension` -> `Pods-OneSignalServiceExtension.debug`.

2. `Release` ->` Runner` -> `OneSignalServiceExtension` ->` Pods-OneSignalServiceExtension.release `.

3. `Profile` ->` Runner` -> `OneSignalServiceExtension` ->` Pods-OneSignalServiceExtension.profile `.

This goes for all your extensions in the application.

Close Xcode and then run the following command in a terminal:
```shell script
flutter clean; rm ios/Podfile.lock pubspec.lock; rm -rf ios/Pods ios/Runner.xcworkspace; flutter run
```

**Comment by phcs971** [comment]
Thanks @Holofox, this fixed it for us

**Comment by lucasratske** [comment]
Thanks @Holofox, you rocks

**Comment by nickscamara** [comment]
Thanks! But what do I replace those configurations with?

**Comment by rovkinmax** [comment]
I have the same issue. I spent two days to research and as a result - recreate ios folder.
But when I add one signal extension I got this problem. And now I don't understand how I should set up this configuration
<img width="1066" alt="Снимок экрана 2021-05-04 в 16 51 26" src="https://user-images.githubusercontent.com/3259038/116999680-64a06700-acf9-11eb-92fa-5234813665cc.png">

**Comment by nickscamara** [comment]
Same here @rovkinmax, I do no understand how to set that configuration to make it work. I tried it all and nothing...

**Comment by TheKurdishProgrammer** [comment]
sorry to renew this, but mine still not working, i have tried the mentioned solution, recreated iOS folder, recreated pod, clean build.
can someone please provide another solution?
