### ISSUE TITLE
Push ID not available on Android on first launch

### ISSUE THREAD

**Issue by rostopira** [OneSignal/OneSignal-Flutter-SDK#38]
**Description:**
On first app start 

(your description here)

**Environment**
Using onesignal-1.0.3 from pub
Issue is reproduced on Samsung Galaxy S8+ with android 8.0.0 on first start
If I restart app it works fine

**Steps to Reproduce Issue:**
  1. Install the OneSignal Flutter SDK using pub into your project
  2. Initialize the SDK using:
```dart
      await OneSignal.shared.init("3db4f756-89a0-408e-bc97-28ba44a5ea8e",
          iOSSettings: { OSiOSSettings.inFocusDisplayOption: "none"});
      OneSignal.shared.setNotificationReceivedHandler((notification) {
        print("Received notification ${notification.payload.additionalData}");
      });
      OneSignal.shared.setSubscriptionObserver((sub) {
        updateSelf();
      });
```
  3. No OneSignal push ID received as a result

**Logcat:**

> 12-05 15:41:01.050 26547-26547/app.babymonitor W/OneSignal: Both GCM & FCM Libraries detected! Please remove the deprecated GCM library.
> 12-05 15:41:01.109 26547-26952/app.babymonitor I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
>     (HTTPLog)-Static: isSBSettingEnabled false:
> 12-05 15:41:01.171 26547-26547/app.babymonitor W/System.err: java.lang.NoSuchMethodException: onOSSubscriptionChanged [class com.onesignal.LocationGMS$FusedLocationApiWrapper]
> 12-05 15:41:01.175 26547-26547/app.babymonitor W/System.err:     at java.lang.Class.getMethod(Class.java:2068)
>         at java.lang.Class.getDeclaredMethod(Class.java:2047)
> 12-05 15:41:01.176 26547-26547/app.babymonitor W/System.err:     at com.onesignal.OSObservable.notifyChange(OSObservable.java:77)
>         at com.onesignal.OSSubscriptionChangedInternalObserver.fireChangesToPublicObserver(OSSubscriptionChangedInternalObserver.java:46)
>         at com.onesignal.OneSignal.addSubscriptionObserver$392b2122(OneSignal.java:2639)
>         at com.onesignal.flutter.OneSignalPlugin.addObservers(OneSignalPlugin.java:117)
> 12-05 15:41:01.177 26547-26547/app.babymonitor W/System.err:     at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:1111)
>         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
>         at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
>         at android.os.MessageQueue.nativePollOnce(Native Method)
>         at android.os.MessageQueue.next(MessageQueue.java:325)
>         at android.os.Looper.loop(Looper.java:142)
> 12-05 15:41:01.178 26547-26547/app.babymonitor W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6938)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
> 12-05 15:41:01.186 26547-26547/app.babymonitor W/System.err: java.lang.NoSuchMethodException: onOSPermissionChanged [class com.onesignal.BundleCompatFactory]
> 12-05 15:41:01.187 26547-26547/app.babymonitor W/System.err:     at java.lang.Class.getMethod(Class.java:2068)
>         at java.lang.Class.getDeclaredMethod(Class.java:2047)
>         at com.onesignal.OSObservable.notifyChange(OSObservable.java:77)
>         at com.onesignal.OSPermissionChangedInternalObserver.fireChangesToPublicObserver(OSPermissionChangedInternalObserver.java:52)
> 12-05 15:41:01.188 26547-26547/app.babymonitor W/System.err:     at com.onesignal.OneSignal.addPermissionObserver$2c67a2d4(OneSignal.java:2602)
>         at com.onesignal.flutter.OneSignalPlugin.addObservers(OneSignalPlugin.java:119)
>         at com.onesignal.flutter.OneSignalPlugin.onMethodCall(OneSignalPlugin.java:1111)
>         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
> 12-05 15:41:01.188 26547-26547/app.babymonitor W/System.err:     at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
>         at android.os.MessageQueue.nativePollOnce(Native Method)
> 12-05 15:41:01.189 26547-26547/app.babymonitor W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:325)
>         at android.os.Looper.loop(Looper.java:142)
>         at android.app.ActivityThread.main(ActivityThread.java:6938)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
> 12-05 15:41:01.190 26547-26547/app.babymonitor W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
> 12-05 15:41:01.219 26547-26594/app.babymonitor I/flutter: Instance of 'OSPermissionSubscriptionState'
> 12-05 15:41:01.220 26547-26594/app.babymonitor I/flutter: null
> 12-05 15:41:01.508 26547-26974/app.babymonitor W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
> 12-05 15:41:01.510 26547-26571/app.babymonitor W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
> 12-05 15:41:01.511 26547-26571/app.babymonitor I/FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
>     [FirebaseAuth:] Preparing to create service connection to gms implementation
> 12-05 15:41:01.779 26547-26973/app.babymonitor W/System.err: java.lang.NoSuchMethodException: onOSSubscriptionChanged [class com.onesignal.LocationGMS$FusedLocationApiWrapper]
>         at java.lang.Class.getMethod(Class.java:2068)
> 12-05 15:41:01.780 26547-26973/app.babymonitor W/System.err:     at java.lang.Class.getDeclaredMethod(Class.java:2047)
>         at com.onesignal.OSObservable.notifyChange(OSObservable.java:77)
>         at com.onesignal.OSSubscriptionChangedInternalObserver.fireChangesToPublicObserver(OSSubscriptionChangedInternalObserver.java:46)
>         at com.onesignal.OSSubscriptionChangedInternalObserver.changed(OSSubscriptionChangedInternalObserver.java:33)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.onesignal.OSObservable.notifyChange(OSObservable.java:95)
> 12-05 15:41:01.781 26547-26973/app.babymonitor W/System.err:     at com.onesignal.OSSubscriptionState.setPushToken(OSSubscriptionState.java:84)
>         at com.onesignal.OneSignal$3.complete(OneSignal.java:814)
>         at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:99)
>         at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
>         at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
>         at java.lang.Thread.run(Thread.java:764)
> 12-05 15:41:07.207 26547-27038/app.babymonitor I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
> 12-05 15:41:07.208 26547-27038/app.babymonitor I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
> 12-05 15:41:07.419 26547-27039/app.babymonitor W/System.err: java.lang.NoSuchMethodException: onOSSubscriptionChanged [class com.onesignal.LocationGMS$FusedLocationApiWrapper]
> 12-05 15:41:07.420 26547-27039/app.babymonitor W/System.err:     at java.lang.Class.getMethod(Class.java:2068)
>         at java.lang.Class.getDeclaredMethod(Class.java:2047)
>         at com.onesignal.OSObservable.notifyChange(OSObservable.java:77)
>         at com.onesignal.OSSubscriptionChangedInternalObserver.fireChangesToPublicObserver(OSSubscriptionChangedInternalObserver.java:46)
> 12-05 15:41:07.421 26547-27039/app.babymonitor W/System.err:     at com.onesignal.OSSubscriptionChangedInternalObserver.changed(OSSubscriptionChangedInternalObserver.java:33)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.onesignal.OSObservable.notifyChange(OSObservable.java:95)
>         at com.onesignal.OSSubscriptionState.setUserId(OSSubscriptionState.java:71)
>         at com.onesignal.OneSignal.updateUserIdDependents(OneSignal.java:2100)
> 12-05 15:41:07.422 26547-27039/app.babymonitor W/System.err:     at com.onesignal.UserStatePushSynchronizer.updateIdDependents(UserStatePushSynchronizer.java:135)
>         at com.onesignal.UserStateSynchronizer$5.onSuccess(UserStateSynchronizer.java:362)
>         at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:208)
> 12-05 15:41:07.423 26547-27039/app.babymonitor W/System.err:     at java.lang.Thread.run(Thread.java:764)
> 12-05 15:41:51.954 26547-26547/app.babymonitor I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
> 12-05 15:43:07.519 26547-26581/app.babymonitor I/System.out: (HTTPLog)-Static: isSBSettingEnabled false

**Comment by rostopira** [comment]
Actually, on second run exception is thrown too, but push id is available

**Comment by rostopira** [comment]
Nope, not a lib issue, my fault

**Comment by kttailor** [comment]
@rostopira 
How did you fix this issue? I am facing similar issue in Android app.

**Comment by jkasten2** [comment]
@kttailor If you are still running into the issue I recommend creating a new issue with your full logcat like rostopira did
