### ISSUE TITLE
Grandfathered Bintray dependency for Maven is preventing build

### ISSUE THREAD

**Issue by lucygeneric** [OneSignal/OneSignal-Flutter-SDK#387]
**Description:**
The onesignal plugin is failing to build due to a dependency on the expired bintray repository.  This repo expired May 1.

```
Could not resolve com.google.android.gms:play-services-base:[10.2.1, 16.1.99].
     Required by:
         project :app > com.onesignal:OneSignal:3.15.7
      > Failed to list versions for com.google.android.gms:play-services-base.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-base/maven-metadata.xml'. Received status code 403 from server: Forbidden
```

**Environment**

`onesignal_flutter: ^2.6.3` 

```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
        google()
    }

    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.10, 0.99.99]'
    }
}
```

Using gradlew `distributionUrl=https://services.gradle.org/distributions/gradle-5.6.4-all.zip`

Versions
```
buildscript {
    repositories {
        google()
        jcenter()
    }

    ext.kotlin_version = '1.3.0' // Must use 1.3.0 or higher.
    ext {
        compileSdkVersion   = 29                // or higher
        targetSdkVersion    = 29                // or higher
        appCompatVersion    = "1.1.0"           // or higher
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.4'
        classpath 'com.google.gms:google-services:4.3.5'
    }
}
```

At this stage I don't know if my configuration is out of date or a specific bug - although I have other libs compiling from maven and OneSignal is where it falls over. I am not able to find anyone else with this issue and the bintray grandfathering has been known for quite some time so I suspect myself??

**Comment by MichaelCadavillo** [comment]
Also experiencing this exact same issue now.. 
This also happened a few days back but after about a day the issue was gone.
Now the issue occurs again.

**Comment by fooshyangsong** [comment]
Yes, please help

**Comment by zevain** [comment]
Exactly the same issue with mine.

**Comment by charlieuki** [comment]
Is it related to the jcenter sunsetting on May 1st?

**Comment by jkasten2** [comment]
`com.google.android.gms:play-services-base` should be pulling from ` google()` since you have it before `jcenter()` but your error includes `https://google.bintray.com/` so it seems it is still trying to find it on jcenter.

Can you try following this guide to switch to `mavenCentral()`?
https://onesignal.com/blog/android-migrate-jcenter-to-maven-central/
_It is written in the context of a native Android app but Flutter contains the same `build.gradle` files you can edit_

**Comment by Harrizontal** [comment]
Same :(

@jkasten2 I followed the guide and im still facing this issue.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.android.gms:play-services-ads-identifier:[15.0.0, 16.0.99].
     Required by:
         project :app > com.onesignal:OneSignal:3.15.7
      > Failed to list versions for com.google.android.gms:play-services-ads-identifier.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-ads-identifier/maven-metadata.xml'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
     Required by:
         project :app > com.google.android.gms:play-services-location:15.0.1
         project :app > com.google.android.gms:play-services-places-placereport:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-basement.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-basement/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-basement/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-basement/maven-metadata.xml'. Received status code 403 from server: Forbidden
   > Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
     Required by:
         project :app > com.google.android.gms:play-services-location:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-tasks.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 52s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by aliefalhadi** [comment]
> `com.google.android.gms:play-services-base` should be pulling from ` google()` since you have it before `jcenter()` but your error includes `https://google.bintray.com/` so it seems it is still trying to find it on jcenter.
> 
> Can you try following this guide to switch to `mavenCentral()`?
> https://onesignal.com/blog/android-migrate-jcenter-to-maven-central/
> _It is written in the context of a native Android app but Flutter contains the same `build.gradle` files you can edit_

it works, thanks

**Comment by lucygeneric** [comment]
awesome, thanks - I hadn't found the migration guide 🤘

**Comment by ChiHwe** [comment]
Anyone solve the issue? I am unable to build the project due to this issue.

**Comment by fooshyangsong** [comment]
> `com.google.android.gms:play-services-base` should be pulling from ` google()` since you have it before `jcenter()` but your error includes `https://google.bintray.com/` so it seems it is still trying to find it on jcenter.
> 
> Can you try following this guide to switch to `mavenCentral()`?
> https://onesignal.com/blog/android-migrate-jcenter-to-maven-central/
> _It is written in the context of a native Android app but Flutter contains the same `build.gradle` files you can edit_

Yes it works, I replace the jcenter() and replace with mavenCentral() and  Sync Gradle by pressing "Sync Now" in Android Studio

**Comment by ChiHwe** [comment]
> > `com.google.android.gms:play-services-base` should be pulling from ` google()` since you have it before `jcenter()` but your error includes `https://google.bintray.com/` so it seems it is still trying to find it on jcenter.
> > Can you try following this guide to switch to `mavenCentral()`?
> > https://onesignal.com/blog/android-migrate-jcenter-to-maven-central/
> > _It is written in the context of a native Android app but Flutter contains the same `build.gradle` files you can edit_
> 
> Yes it works, I replace the jcenter() and replace with mavenCentral() and Sync Gradle by pressing "Sync Now" in Android Studio

Hi , May i know where you sync Gradle? can step by step guide ? Sorry and thanks

**Comment by dovahkrid** [comment]
> `com.google.android.gms:play-services-base` should be pulling from ` google()` since you have it before `jcenter()` but your error includes `https://google.bintray.com/` so it seems it is still trying to find it on jcenter.
> 
> Can you try following this guide to switch to `mavenCentral()`?
> https://onesignal.com/blog/android-migrate-jcenter-to-maven-central/
> _It is written in the context of a native Android app but Flutter contains the same `build.gradle` files you can edit_

already replaced jcenter() with mavenCentral(), did `gradlew --refresh-dependencies` but still not work.

```
> Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
     Required by:
         project :app > com.google.android.gms:play-services-location:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-tasks.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml'. Received status code 403 from server: Forbidden

```

**Comment by dovahkrid** [comment]
> > `com.google.android.gms:play-services-base` should be pulling from ` google()` since you have it before `jcenter()` but your error includes `https://google.bintray.com/` so it seems it is still trying to find it on jcenter.
> > Can you try following this guide to switch to `mavenCentral()`?
> > https://onesignal.com/blog/android-migrate-jcenter-to-maven-central/
> > _It is written in the context of a native Android app but Flutter contains the same `build.gradle` files you can edit_
> 
> already replaced jcenter() with mavenCentral(), did `gradlew --refresh-dependencies` but still not work.
> 
> ```
> > Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
>      Required by:
>          project :app > com.google.android.gms:play-services-location:15.0.1
>       > Failed to list versions for com.google.android.gms:play-services-tasks.
>          > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml.
>             > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml'.
>                > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml'. Received status code 403 from server: Forbidden
> ```

Oh it works now. Maybe after replaced things, need to wait a liitle bit.

**Comment by fooshyangsong** [comment]
> > > `com.google.android.gms:play-services-base` should be pulling from ` google()` since you have it before `jcenter()` but your error includes `https://google.bintray.com/` so it seems it is still trying to find it on jcenter.
> > > Can you try following this guide to switch to `mavenCentral()`?
> > > https://onesignal.com/blog/android-migrate-jcenter-to-maven-central/
> > > _It is written in the context of a native Android app but Flutter contains the same `build.gradle` files you can edit_
> > 
> > 
> > already replaced jcenter() with mavenCentral(), did `gradlew --refresh-dependencies` but still not work.
> > ```
> > > Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
> >      Required by:
> >          project :app > com.google.android.gms:play-services-location:15.0.1
> >       > Failed to list versions for com.google.android.gms:play-services-tasks.
> >          > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml.
> >             > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml'.
> >                > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-tasks/maven-metadata.xml'. Received status code 403 from server: Forbidden
> > ```
> 
> Oh it works now. Maybe after replaced things, need to wait a liitle bit.

yes, you might to need to wait awhile for it to load finish

**Comment by hendi-2020** [comment]
> `com.google.android.gms:play-services-base` should be pulling from ` google()` since you have it before `jcenter()` but your error includes `https://google.bintray.com/` so it seems it is still trying to find it on jcenter.
> 
> Can you try following this guide to switch to `mavenCentral()`?
> https://onesignal.com/blog/android-migrate-jcenter-to-maven-central/
> _It is written in the context of a native Android app but Flutter contains the same `build.gradle` files you can edit_

It works. Thank you!

**Comment by ChiHwe** [comment]
It WORKS, Thanks for Everyone!!!!
