### ISSUE TITLE
Customizing my own in-app notification

### ISSUE THREAD

**Issue by Lawati97** [OneSignal/OneSignal-Flutter-SDK#388]
**Description:**

I am wondering if it is possible to be able to control over how the in-app notification looks like? (So something that is firebase messaging used to do -> inMessage, onLaunch...)? Note: all of the notification will be  sent through an API

**Environment**

Currently using onesignal_flutter V2.6.2
The SDK was added through pub

**Comment by jkasten2** [comment]
@Lawati97 Could you provide more details on the customization you would like to do?

Some things that are unclear to me:
> control over how the in-app notification looks like? (So something that is firebase messaging used to do -> inMessage, onLaunch...)?

Could you expand on the kind of changes you would like to make and how you need to look? I do not know what the "inMessage, onLaunch...)" function you are referring to is. Could you reply with a link to documentation on it?
