### ISSUE TITLE
LaunchUrl always return null

### ISSUE THREAD

**Issue by EDnny12** [OneSignal/OneSignal-Flutter-SDK#392]
OneSignal beta always return null in android,

OneSignal.shared
        .setNotificationOpenedHandler((OSNotificationOpenedResult result) {
      final String? launch = result.notification.launchUrl;

    });

Select different app/web launchUrl, then always launchUrl return null,

- Some devices work fine, but not all

**Comment by SergioQuinonez** [comment]
I have the same issue with the beta 😞

**Comment by Jeasmine** [comment]
Hey all, thanks for reporting this!. We already found the problem and fix it. The fix will be available on the next release!

**Comment by Jeasmine** [comment]
The fix has been released on beta 4! If you are still facing problems or issues, please open a new issue. Thanks again for reporting!
