### ISSUE TITLE
How to filter certain push notifications on Flutter?

### ISSUE THREAD

**Issue by oguzhandurmaz** [OneSignal/OneSignal-Flutter-SDK#393]
I want to filter some push notification and hide from user according to condition. For example: in additional data there is isShow: false and if isShow is false, i dont want to show notification and if true, show notification.

I tried `OneSignal.shared.setSubscription(false)` but this function prevents to receive all notification but i want to show isShow: true notification only.

Is there any handler for to do like below? Or Is there any way to do this?

```
OneSignal.shared.setNotificationReceivedHandler((OSNotification notification) {

    var additionalData = openedResult.notification.payload.additionalData;
    if(!additionalData["isShow"]){
         //Dont Show This Notification
    }
});
```

**Comment by Jeasmine** [comment]
Hey @oguzhandurmaz, thanks for your question! This feature has been implemented under the major release. Please check https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/357 for more information. We encourage you to try our beta!
