### ISSUE TITLE
Flutter Build Failed ld: framework not found Pods_OneSignalNotificationServiceExtension

### ISSUE THREAD

**Issue by tomcajot** [OneSignal/OneSignal-Flutter-SDK#395]
**Description:**

I'm trying to build my app but it keeps telling me this:
```
ld: framework not found Pods_OneSignalNotificationServiceExtension
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The project is launching when I just run it with xcode, however trying flutter run doesn't work.

**Environment**

I'm using OneSignal version ^3.0.0-beta3, however I have the same issue with ^3.0.0-beta2 and ^2.6.3.

**Steps to Reproduce Issue:**

1. Install OneSignal
2. Setup OneSignal
3. Run project

**Anything else:**

Flutter logs: 
```
** BUILD FAILED **
The following build commands failed: MergeSwiftModule normal arm64
Ld /Users/tomcajot/Library/Developer/Xcode/DerivedData/Runnergaznkqtdggvnhwcqaqracoohrvfm/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objectsnormal/x86_64/Binary/OneSignalNotificationServiceExtension normalx86_64(2 failures)
```
```
ld: in /Users/tomcajot/Desktop/banana_mobile/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/tomcajot/Desktop/banana_mobile/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by emawby** [comment]
Hello, can you please provide your podfile and the frameworks and libraries included in your OneSignalNotificationServiceExtension target?

**Comment by tomcajot** [comment]
Hi, I'm sorry but I couldn't wait anymore so I re-installed flutter.

**Comment by tomcajot** [comment]
This is my podfile:

`
platform :ios, '9.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 3.0.0', '< 4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target| 
    flutter_additional_ios_build_settings(target)
  end
end
`

and these are the libraries and frameworks included in my OneSignalNotificationServiceExtension target:
<img width="540" alt="Screenshot 2021-05-21 at 09 53 10" src="https://user-images.githubusercontent.com/33400705/119102490-5dc46480-ba1a-11eb-9787-62f7258bddfe.png">

**Comment by tomcajot** [comment]
I also just reinstalled flutter and xcode, but the issue still persists.

**Comment by tomcajot** [comment]
I also just removed the iOS folder and restarted the setup from https://documentation.onesignal.com/docs/flutter-sdk-setup.
But it still doesn't work :/

**Comment by tomcajot** [comment]
What is under frameworks is pretty weird though, they are both red :/

<img width="265" alt="Screenshot 2021-05-21 at 14 59 37" src="https://user-images.githubusercontent.com/33400705/119141111-2ae39600-ba45-11eb-9c28-7aa28c7ed5cc.png">

**Comment by MohammedAlimoor** [comment]
same problem

**Comment by hkhars** [comment]
I've finally found the solution.
We need to add "arm64" from Any IOS Simulator SDK under "Excluded Architecture"  for iOS from "OneSignalNotificationServiceExtension" target.

- Open Xcode.
- Select "OneSignalNotificationServiceExtension"
- Go to Build Settings
- Under Architectures -> Excluded Architecture, add "arm64" for all Debug, Profile and Release

See screenshot for your reference: 
![image](https://user-images.githubusercontent.com/17302783/119497768-9c855200-bd6d-11eb-9ed9-3ae61c0c83ea.png)

**Comment by cschellhas** [comment]
Hi, I solved it by adding the following to OneSignalServiceExtension:

![Bildschirmfoto 2021-05-26 um 13 10 22](https://user-images.githubusercontent.com/8872802/119650158-c6994b80-be23-11eb-86d4-2e0cb84a334a.png)

**Comment by tomcajot** [comment]
@cschellhas your answer didn't work for me, but I just tried downgrading flutter back to 2.0.6 and that worked!
