### ISSUE TITLE
Flutter OneSignal not Archive

### ISSUE THREAD

**Issue by garaving** [OneSignal/OneSignal-Flutter-SDK#40]
**Description:**

since i added onesignal i can not Archive the app anymore 👎 

After a thousand and thousand attempts, I managed to start the app on the simulator, on the physical device now i can not archive.

**Environment**
[✓] Flutter (Channel master, v1.0.1-pre.17, on Mac OS X 10.14.1 18B75, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.0)
[✓] Connected device (1 available)

**Steps to Reproduce Issue:**

1. install as on tutorial OneSignal
2. modify pod
3. add OneSignalNotificationServiceExtension
4. etc.

5. flutter run -d (simulator) 
6. flutter run -d (iphone) 
7. flutter build ios --debug 
8. flutter build ios --release 
[
ISSUE
ld: warning: directory not found for option '-L/Users/user/development/project/beeing/build/ios/Release-iphoneos/map_view'
    ld: warning: directory not found for option '-L/Users/user/development/project/beeing/build/ios/Release-iphoneos/onesignal'
    ld: warning: directory not found for option '-L/Users/user/development/project/beeing/build/ios/Release-iphoneos/path_provider'
    ld: warning: directory not found for option '-L/Users/user/development/project/beeing/build/ios/Release-iphoneos/shared_preferences'
    ld: warning: directory not found for option '-L/Users/user/development/project/beeing/build/ios/Release-iphoneos/sqflite'
    ld: warning: directory not found for option '-L/Users/user/development/project/beeing/build/ios/Release-iphoneos/url_launcher'
    ld: library not found for -lmap_view
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
]

9. open xcode prj and run on iphone 
10. open xcode prj and archive 
[
ISSUE
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/Runner-goniqgujdqkwjpcrkbgqqkznjuce/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/FMDB'
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/Runner-goniqgujdqkwjpcrkbgqqkznjuce/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/MTBBarcodeScanner'
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/Runner-goniqgujdqkwjpcrkbgqqkznjuce/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/barcode_scan'
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/Runner-goniqgujdqkwjpcrkbgqqkznjuce/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/image_picker'
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/Runner-goniqgujdqkwjpcrkbgqqkznjuce/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/map_view'
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/Runner-goniqgujdqkwjpcrkbgqqkznjuce/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/onesignal'
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/Runner-goniqgujdqkwjpcrkbgqqkznjuce/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/path_provider'
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/Runner-goniqgujdqkwjpcrkbgqqkznjuce/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/shared_preferences'
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/Runner-goniqgujdqkwjpcrkbgqqkznjuce/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/sqflite'
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/Runner-goniqgujdqkwjpcrkbgqqkznjuce/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/url_launcher'
ld: library not found for -lFMDB
clang: error: linker command failed with exit code 1 (use -v to see invocation)
]

**Comment by Nightsd01** [comment]
@garaving when I look at your build log, it seems to be an issue with a dependency using FMDB. Our SDK does not use FMDB. 

Can you post your Podfile?

**Comment by garaving** [comment]
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

target 'OneSignalNotificationServiceExtension' do
  #use_frameworks!
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
  #pod 'OneSignalDynamic','>= 2.9.3', '< 3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

**Comment by Nightsd01** [comment]
@garaving your Podfile looks fine. That build error isn't related to OneSignal...it's an issue with FMDB.

I would suspect that one of your dependencies is using SQLite in some way. As to why this issue only happens after you add OneSignal to your project, your guess is as good as mine, but the actual error itself is unrelated to our SDK.

**Comment by Nightsd01** [comment]
I've closed the issue since the error isn't related to our SDK but I'll continue to try and help you.

Can you build and run successfully using the Xcode project itself? What version of Xcode are you using?

**Comment by janniklind** [comment]
I have seen this a couple of times regarding OneSignal for Flutter. The error has nothing to do with OneSignal. I think it is simply because many Flutter developers still needs to learn some things regarding iOS native development.

The problem happens because the OneSignal extensions reference libraries added to Flutter's main target (Runner). The reason for this is because the base configuration for the Project is using the same config file as the Runner target. And the OneSignal target inherits from it.

To solve it do the following:

Select the Project (not targets), then select the Info tab, Expand Configurations, and for both Debug and Release set the configuration file for the Runner project to None. 

Now try to build and it should succeed.

I hope you will get it resolve now.

@Nightsd01 - I only tag you here, so you will see it, I think it will help a lot of your Flutter users.
