### ISSUE TITLE
2.6.4 breaks ios

### ISSUE THREAD

**Issue by AntonyLeons** [OneSignal/OneSignal-Flutter-SDK#405]
**Description:**
```
CocoaPods could not find compatible versions for pod "OneSignal":
  In snapshot (Podfile.lock):
    OneSignal (= 2.16.3)

  In Podfile:
    onesignal_flutter (from `.symlinks/plugins/onesignal_flutter/ios`) was resolved to 2.6.4, which depends on
      OneSignal (= 2.16.5)

Specs satisfying the `OneSignal (= 2.16.3), OneSignal (= 2.16.5)` dependency were found, but they required a higher minimum deployment target

```
increasing the target to 14.5 does not help

**Environment**
2.6.4 causes issue

**Steps to Reproduce Issue:**
run `pod install` / compile for IOS

**Comment by jkasten2** [comment]
@AntonyLeons It looks like your `Podfile.lock` didn't get updated when you upgraded OneSignal. I believe running `pod update OneSignal` should update this for you and resolve the issue.

**Comment by AntonyLeons** [comment]
@jkasten2 thank you, that seems to have solved it
