### ISSUE TITLE
NotificationOpenedHandler restarts App on Android - v3.0.0

### ISSUE THREAD

**Issue by mingosnunes** [OneSignal/OneSignal-Flutter-SDK#407]
Hi,

I have a problem with `setNotificationOpenedHandler` trigger on version 3.0.0 (stable) with android (IOS works as expected.

The app runs the handler logic normally but after that, the App restarts and I have this error on the logs:

`I/WM-WorkerWrapper(32084): Worker result FAILURE for Work [ id=5967e7aa-e7c5-41e9-a594-4005a69d9add, tags={ com.onesignal.OSNotificationRestoreWorkManager$NotificationRestoreWorker } ]`

This happens always with the app in the background and sometimes in the foreground.
This error is critical because every navigation you did on that handler gets deleted because of the restart.

Infomation:
Flutter 2.2.1 
Tested on -> Android 10.3.11 & Android 9
One Signal version 3 & 3-beta 3 & 3-beta4

Thanks,
Domingos Nunes

**Comment by aayush0208** [comment]
Same issue is happening with Android: 

    `OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {
      try{
        print(result.notification.additionalData.isNotEmpty?result.notification.additionalData.toString():"null json");

        if(result.notification.additionalData != null)
          {
              if(jobId !=  null || jobId.isNotEmpty){
                Helper.saveToSharedPrefrences(Constants.job_id, jobId, Constants.STRING);
                navigatorKey.currentState.push(new MaterialPageRoute(builder: (context)=> JobDetails()));
              }else{
                navigatorKey.currentState.push(new MaterialPageRoute(builder: (context)=> NotificationScreen()));
              }
          }
      }catch(e)
      {
        e.toString();
      }
    });`
  


Fluter doctor -v command

[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-GB)
    • Flutter version 2.2.1 at /Users/apple/Downloads/flutter
    • Framework revision 02c026b03c (13 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Redmi 5 (mobile) • 4732d3187ce5 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)     • chrome       • web-javascript • Google Chrome 91.0.4472.77

! Doctor found issues in 2 categories.

**Comment by apjinfosolution** [comment]
try adding this in AndroidManifest

<meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />

**Comment by apjinfosolution** [comment]
<meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />

**Comment by apjinfosolution** [comment]
try adding this in Android menifest

- <meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />

**Comment by apjinfosolution** [comment]
"<meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />"

**Comment by apjinfosolution** [comment]
> <meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />

**Comment by apjinfosolution** [comment]
`<meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />`

**Comment by apjinfosolution** [comment]
try adding this in menifest
`<meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />`

**Comment by fguillen-tejera** [comment]
This worked for me:

in AndroidManifest.xml set your Activity launchMode to singleTask should fix this:
```
<activity
  ......
  android:launchMode="singleTask"
  >
```

**Comment by lailai0715** [comment]
> This worked for me:
> 
> in AndroidManifest.xml set your Activity launchMode to singleTask:
> 
> ```
> <activity
>   ......
>   android:launchMode="singleTask"
>   >
> ```

Worked for me also, thank you!

**Comment by simonkoeck** [comment]
In my case the problem was that setNotificationOpenedHandler was called inside an async function.

Doesn*t work:
`
static void registerNotificationOpenedHandler(
      Function(OSNotificationOpenedResult result) cb) async {
    OneSignal.shared.setNotificationOpenedHandler((openedResult) {
      cb(openedResult);
    });
  }
`
Works:
`
static void registerNotificationOpenedHandler(
      Function(OSNotificationOpenedResult result) cb) {
    OneSignal.shared.setNotificationOpenedHandler((openedResult) {
      cb(openedResult);
    });
  }
`

**Comment by fogaiht** [comment]
> This worked for me:
> 
> in AndroidManifest.xml set your Activity launchMode to singleTask:
> 
> ```
> <activity
>   ......
>   android:launchMode="singleTask"
>   >
> ```

It's work for me too, thanks a lot <3

**Comment by emawby** [comment]
@mingosnunes did the workarounds in this thread resolve the issue or is it still occurring?
