### ISSUE TITLE
error when build in ios

### ISSUE THREAD

**Issue by alib1989** [OneSignal/OneSignal-Flutter-SDK#408]
hello 
i got this error when builld in ios
how can solve it
my 
one signal is 3.0.0

<img width="277" alt="Screen Shot 2021-06-07 at 1 35 36 AM" src="https://user-images.githubusercontent.com/29424884/120942330-ec322900-c730-11eb-8c23-9223636dedbf.png">

**Comment by MrTarantula** [comment]
I'm receiving the same error.

**Comment by nickscamara** [comment]
Same still...

**Comment by emawby** [comment]
This issue is more thoroughly discussed in #414 so I am closing this one as a duplicate
