### ISSUE TITLE
Build app on iOS simulator 

### ISSUE THREAD

**Issue by AlirezaDaryani** [OneSignal/OneSignal-Flutter-SDK#409]
I used version 3.0.0 in my app, after that I can run app with xcode on simulator but Android studio can’t run on simulator .

This is my flutter doctor :

[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)

this is error log on android studio.
`    ld: in /ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)`

After this error i open xcode and click on run and it run on simulator with no error.

What is the problem?

**Comment by honeylauncher** [comment]
I have the same problem

**Comment by dazuaz** [comment]
@AlirezaDaryani 
I was able to run it on the Simulator by setting the following

<img width="927" alt="Screen Shot 2021-06-09 at 10 59 27 AM" src="https://user-images.githubusercontent.com/5804634/121379253-d891e880-c911-11eb-910e-cb6ef65e5688.png">

**Comment by AlirezaDaryani** [comment]
@dazuaz  
I do this in xcode and app run in xcode on simulator, but not work for android studio.

**Comment by dazza5000** [comment]
How do you make this fix permanent?
