### ISSUE TITLE
remoteNotificationReceived call back Is newer called on Android platform

### ISSUE THREAD

**Issue by VadimBliz** [OneSignal/OneSignal-Flutter-SDK#410]
Notifications works just fine, but callback is never called(both killed state and background)

I've add NotificationServiceExtension with content

package com.notifications.test

import android.content.Context
import android.util.Log
import com.onesignal.OSMutableNotification
import com.onesignal.OSNotification
import com.onesignal.OSNotificationReceivedEvent
import com.onesignal.OneSignal.OSRemoteNotificationReceivedHandler
import org.json.JSONObject

class NotificationServiceExtension : OSRemoteNotificationReceivedHandler {
    override fun remoteNotificationReceived(context: Context, notificationReceivedEvent: OSNotificationReceivedEvent) {
        val notification: OSNotification = notificationReceivedEvent.notification

        val mutableNotification: OSMutableNotification = notification.mutableCopy()
        mutableNotification.setExtender { builder -> builder.setColor(0xf4802e) }
        val data: JSONObject = notification.additionalData
        Log.i("OneSignalExample", "Received Notification Data: $data")

        notificationReceivedEvent.complete(mutableNotification)
    }
}

In manifest I've add 
`            <meta-data android:name="com.onesignal.NotificationServiceExtension"
                       android:value="com.notifications.test.NotificationServiceExtension"/>
`

my flutter doctor -v output
[✓] Flutter (Channel unknown, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale ru-UA)
    • Flutter version 2.0.6 at /Users/elereman/flutter
    • Framework revision 1d9032c7e1 (6 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/elereman/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_291.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] Connected device (4 available)
    • Pixel 2 XL (mobile)     • 802KPDT1544554                       • android-arm64  • Android 11 (API 30)
    • iPhone 12 mini (mobile) • 9C4A14F0-7E50-4851-B1E9-DBDF4183A015 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)         • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 91.0.4472.77

! Doctor found issues in 1 category.

**Comment by MingSern** [comment]
@VadimBliz Hi, how did you solve this?
