### ISSUE TITLE
Execution failed for task  app:processDebugManifest

### ISSUE THREAD

**Issue by pierre-gancel** [OneSignal/OneSignal-Flutter-SDK#416]
Thanks for providing and maintaining this life saver notifications package.
After migrating to the 3.0.0 I sometimes encounter this issue :  
_'build failed with an exception.'
Execution failed for task  app:processDebugManifest_
This is probably caused by a missing config on my side.

> * What went wrong:                                                      
> Execution failed for task ':app:processDebugManifest'.                  
> > com.android.manifmerger.ManifestMerger2$MergeFailureException: java.io.FileNotFoundException: /Users/pierre/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-3.0.0/android/build/intermediates/library_manifest/debug/AndroidManifest.xml (No such file or directory)
> 
>

**Comment by saulogpacifico** [comment]
> Thanks for providing and maintaining this life saver notifications package.
> After migrating to the 3.0.0 I sometimes encounter this issue :
> _'build failed with an exception.' Execution failed for task app:processDebugManifest_
> This is probably caused by a missing config on my side.
> 
> > * What went wrong:
> >   Execution failed for task ':app:processDebugManifest'.
> > 
> > > com.android.manifmerger.ManifestMerger2$MergeFailureException: java.io.FileNotFoundException: /Users/pierre/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-3.0.0/android/build/intermediates/library_manifest/debug/AndroidManifest.xml (No such file or directory)

I changed the line ext.kotlin_version = '1.3.50' to ext.kotlin_version = '1.4.21' in the path 'android/build.gradle' and for me it worked fine

**Comment by pierre-gancel** [comment]
Thanks for the suggestion, it is already set at : ext.kotlin_version = '1.4.21'

**Comment by emawby** [comment]
@pierre-gancel I cannot reproduce this issue are you still experiencing it? Could you provide an example project that has this issue?

**Comment by pierre-gancel** [comment]
Sorry it is OK now it seems, this can be close, thank you for support

Le lun. 9 août 2021 à 20:37, Elliot Mawby ***@***.***> a
écrit :

**Comment by RangasamyEswaran** [comment]
What went wrong:
Execution failed for task ':webview_flutter:processDebugManifest'.
> Failed to calculate the value of task ':webview_flutter:processDebugManifest' property 'packageOverride'.
   > Failed to query the value of property 'applicationId'.
      > org.xml.sax.SAXParseException; systemId: file:/C:/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.13/android/src/main/AndroidManifest.xml; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
