### ISSUE TITLE
[ANDROID]On click the notification, the app will restart instead of resume

### ISSUE THREAD

**Issue by lailai0715** [OneSignal/OneSignal-Flutter-SDK#417]
**Description:**
Anyone faced this before, this issue exist in my android emulator and Huawei phone with gms installed

**Environment**
1. onesignal_flutter: 3.0.0
2. Flutter sdk 2.2.2

**Comment by MeAtPros** [comment]
Related with: https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/372 
We've had the same problem for weeks now, nobody at OneSignal wants to fix it

**Comment by lailai0715** [comment]
> Related with: https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/372 
> We've had the same problem for weeks now, nobody at OneSignal wants to fix it

Do your testing device have gms installed?

**Comment by 1996SEJR** [comment]
I have the same problem, on a huawei p20 lite

**Comment by jkasten2** [comment]
Could you provide the following details.
1. Android versions
2. Device models
3. Does tapping on the app icon from the Android home screen also restart the app?
4. Any custom configurations to the main Activity?

**Comment by fernando-gomes** [comment]
Same problem here using onesignal_flutter: 3.0.0 and Flutter SDK 2.2.2. Details:

1. Android 8.1 and Android 10
2. Motorola Moto G 5S and POCO M3
3. No, it resumes, as expected
4. No, empty MainActivity.kt

**Comment by Jeasmine** [comment]
> Same problem here using onesignal_flutter: 3.0.0 and Flutter SDK 2.2.2. Details:
> 
> 1. Android 8.1 and Android 10
> 2. Motorola Moto G 5S and POCO M3
> 3. No, it resumes, as expected
> 4. No, empty MainActivity.kt

Thanks for the response. At Manifest lvl, which launch mode do you have configured for the MainActivity?

**Comment by fernando-gomes** [comment]
Sorry Jeasmine, I was using "singleTop" when "singleTask" is the correct mode to get this behavior. My bad, I completely forgot about the launchMode... Thank you!

**Comment by Jeasmine** [comment]
Hey @fernando-gomes, changing from "singleTask" to "singleTop" solve the problem for you?

**Comment by fernando-gomes** [comment]
> Hey @fernando-gomes, changing from "singleTask" to "singleTop" solve the problem for you?

It's the opposite, I was using the default "singleTop" and the app always restarted when selecting a notification. Changing it to "singleTask" solved the problem.

**Comment by Jeasmine** [comment]
Oh, that's weird. You shouldn't need the "singleTask", and changing to that type of launch mode might end in different problems for you.  Is this happening for you only on those devices? Or is this happening on every device running your application?

**Comment by fernando-gomes** [comment]
"singleTop" works fine using versions of onesignal_flutter below 3.0.0. I've tested on Samsung, Motorola and Xiaomi devices, all with the same result. On 3.0.0 only with "singleTask" the app will resume after selecting a notification, otherwise it will restart the app.

**Comment by Jeasmine** [comment]
Gotcha, thanks for the information and being so fast responding. I will make a custom app and try to reproduce the problem.

**Comment by jkasten2** [comment]
This issue is now fixed in [3.2.5](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.2.5).
