### ISSUE TITLE
onesignal setup problem

### ISSUE THREAD

**Issue by mamun358** [OneSignal/OneSignal-Flutter-SDK#420]
Any one here who can tell what is the mistake or where should i put my onesignal id.here is my some code from app source code.

OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.notification);

    if(model.blocks.settings.onesignalAppId.isNotEmpty) {

      var settings = {
        OSiOSSettings.autoPrompt: false,
        OSiOSSettings.promptBeforeOpeningPushUrl: true
      };

      await OneSignal.shared.init(
          model.blocks.settings.onesignalAppId, //add your OneSignal app Id
          iOSSettings: {
            OSiOSSettings.autoPrompt: false,
            OSiOSSettings.inAppLaunchUrl: false
          }
      );

      OneSignal.shared.setRequiresUserPrivacyConsent(true);

      OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {

        print("Opened notification: \n${result.notification.jsonRepresentation().replaceAll("\\n", "\n")}");

      });

      var status = await OneSignal.shared.getPermissionSubscriptionState();

      model.oneSignalPlayerId = status.subscriptionStatus.userId;

      model.apiProvider.post('/wp-admin/admin-ajax.php?action=mstore_flutter_update_user_notification', {'onesignal_user_id': model.oneSignalPlayerId});
    }

**Comment by Jeasmine** [comment]
Hye @mamun358! Which version of the SDK are you using? If you are using 3.x.x, the docs are still not fully updated, so you will need to follow https://documentation.onesignal.com/docs/flutter-sdk-3xx-setup. I hope this helps, and sorry for the trouble!

**Comment by mamun358** [comment]
onesignal sdk : 2.6.1

**Comment by Jeasmine** [comment]
Hey @mamun358, I missed you answeer. That version is an old one. I would recommend you to use 3.x.x versions. Since they are after the major release that includes bug fixing and SDK improvements, let me know if with the 3.x.x you are still having problems initializing the SDK

**Comment by emawby** [comment]
@mamun358 Are you still having issues with the setup?
