### ISSUE TITLE
heads-up notifiactions

### ISSUE THREAD

**Issue by hatemragab** [OneSignal/OneSignal-Flutter-SDK#421]
how to show heads-up notifiactions like 
https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up
i use 3.0.0 version

**Comment by Santi92** [comment]
@hatemragab It is only a configuration issue, here is the same case solved:  https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/425#event-4968472724
