### ISSUE TITLE
No profiles for 'com.xxx.xxx.OneSignalNotificationServiceExtension' were found

### ISSUE THREAD

**Issue by malvinpratama** [OneSignal/OneSignal-Flutter-SDK#422]
**Description:**
![image](https://user-images.githubusercontent.com/45458498/123705471-2eaed780-d891-11eb-84b6-cdf8d1df0a66.png)

![image](https://user-images.githubusercontent.com/45458498/123705408-1b037100-d891-11eb-82ba-c2f79f035c22.png)

I got this error if my runner signing provisioning profile with manual profile (no automatically manage singing).
In tutorial https://documentation.onesignal.com/docs/flutter-sdk-setup doesn't have information if runner signing with manual profile. 
Should I create manual provisioning profile for extension ? and what be required for that ?

**Comment by nixcode1** [comment]
@malvinpratama How id you solve this error?

**Comment by Miko2x** [comment]
did you solve the issue? @nixcode1

**Comment by chuanpham** [comment]
@Miko2x did you solve the issue? Thanks!
