### ISSUE TITLE
Error Heads-up notification is not displayed in Android

### ISSUE THREAD

**Issue by Santi92** [OneSignal/OneSignal-Flutter-SDK#425]
**Description:***

**Error Heads-up notification is not displayed in Android**: 
When I update version 3.0.0 oneSignal on Android the [Heads-up notification](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up
) is not displayed, but on IOS it is working fine.

**Environment**

flutter doctor
 ``` bash
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.2.3 20D91 darwin-x64, locale en-CO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)
 ```

 pubspec
 ```yaml
 name: xxxxxx
 description: xxxxx
 
 environment:
  sdk: 2.13.3
  flutter: 2.2.2
  
  dependencies:
  flutter:
    sdk: flutter

  onesignal_flutter: ^3.0.0

 ```

**Steps to Reproduce Issue:**

  1. Create a notification at https://app.onesignal.com/apps/xxx/notifications/newt
  2. Send notification
  3. When it arrives  only sounds and is not displaying [Heads-up notification ](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up
) when the user is using the smart phone.
    
  
  **Setup OneSignal:**
  
   ```dart
     Future<void> init() async {
    await OneSignal.shared.setLogLevel(OSLogLevel.error, OSLogLevel.none);
    await OneSignal.shared.setRequiresUserPrivacyConsent(false);

     _initListeners();

     await OneSignal.shared.setAppId(_oneSignalAppId);
  }
 
 
 void _initListeners() {
    OneSignal.shared.setNotificationWillShowInForegroundHandler((event) {
      event.complete(event.notification);

      final payload = event.notification;

      final properties = _mapPropertiesForAnalytics(payload);


      handleReceive(payload.additionalData);
    });
 }
   ```
  SEARCH EXISTING ISSUES FOR relating to the same topic but not describing : https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/421
  
 Please help me :white_frowning_face:

**Comment by jennantilla** [comment]
Have you set up categories for Android?

With Android 8+ you must add these custom features through notification Categories aka Channels. You can set these in the Settings > Messaging tab.

You will want to set the Importance to Urgent to accomplish this.

More information on Android Categories here: https://documentation.onesignal.com/docs/android-notification-categories

**Comment by Santi92** [comment]
Yes, thank you very much. 🥇 
If, as I was sending it from one signal, I did not have it configured.

fixed.
