### ISSUE TITLE
Error generating build to upload to TestFlight

### ISSUE THREAD

**Issue by macortesn** [OneSignal/OneSignal-Flutter-SDK#426]
**Description:**

I am using fastlane to create the releases of my application. I already integrated onesginal correctly and running the application in debug mode works, but when trying to create the build with fastlane I have the following error:

```
.../Library/Developer/Xcode/DerivedData/Runner-cchwofxasspufwdjnojjjjoftsbp/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh
/Users/valiu_dev_1/flutter/packages/flutter_tools/bin/xcode_backend.sh

Command PhaseScriptExecution failed with a nonzero exit code
```
I read that maybe it could be because of the target that is added for OnesignalNotifcationServiceExtension. Does anyone know how I can solve it? Thanks!

**Environment**

```
onesignal_flutter: ^3.0.0

Flutter (Channel stable, 2.2.2, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-CO)
    • Flutter version 2.2.2 at /Users/dev/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1
```

**Comment by emawby** [comment]
@macortesn Most of the fixes I am seeing for this issue are in regards to cleaning derived data and making sure to run from a clean slate. There isn't enough information here to determine what the cause of this could be, but if you have an example project with the issue I would be happy to look at it.

**Comment by macortesn** [comment]
Apparently the problem was that, something in my development environment was causing problems. Thanks!
