### ISSUE TITLE
Unable to load Maven meta-data

### ISSUE THREAD

**Issue by bagus-repository** [OneSignal/OneSignal-Flutter-SDK#428]
**Description:**
Run and build failed with this errors :
`      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 403 from server: Forbidden`

**Environment**

1. onesignal_flutter: ^2.3.2
2. pub.dev

**Steps to Reproduce Issue:**

1. Add the dependency at pubspec.yaml
2. Follow installation guide from OneSignal Flutter
3. Run or build your app

**Comment by BarbaraLest** [comment]
try updating the distributionUrl to "distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip" or some other newer version. It worked for me.

**Comment by bagus-repository** [comment]
> try updating the distributionUrl to "distributionUrl=https://services.gradle.org/distributions/gradle-6.5-bin.zip" or some other newer version. It worked for me.

Thanks that worked but when publishing new release the app crash because of another plugin (image_picker), I think this time I have to upgrade to Null Safety

**Comment by sourabhmahale** [comment]
Did anyone find a solution? because I also get this error
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-messaging:[19.0.0, 22.0.99].
     Required by:
         project :app > project :onesignal_flutter > com.onesignal:OneSignal:4.6.3
      > Failed to list versions for com.google.firebase:firebase-messaging.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/firebase/firebase-messaging/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/firebase/firebase-messaging/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/firebase/firebase-messaging/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by amirbios** [comment]
It did not work for me and I still have the following errors...

`
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':firebase_messaging:generateDebugRFile'.
> Could not resolve all task dependencies for configuration ':firebase_messaging:debugRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-iid:[20.0.1].
     Required by:
         project :firebase_messaging > com.google.firebase:firebase-messaging:20.0.1
      > Failed to list versions for com.google.firebase:firebase-iid.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/firebase/firebase-iid/maven-metadata.xml.

* Get more help at https://help.gradle.org`

**Comment by Srikanthjava972** [comment]
@fukemy @BarbaraLest @bagus-repository I'm experiencing below error, i tried all the above solutions but none of them worked. 

**Error log**
_Build file '/Users/xxxx/Downloads/workspace/xxx/platforms/android/app/build.gradle' line: 598
A problem occurred configuring project ':app'.
Could not GET 'https://jcenter.bintray.com/com/google/firebase/firebase-iid/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1.
_

**Comment by Alonsso** [comment]
> @fukemy @BarbaraLest @bagus-repository I'm experiencing below error, i tried all the above solutions but none of them worked.
> 
> **Error log** _Build file '/Users/xxxx/Downloads/workspace/xxx/platforms/android/app/build.gradle' line: 598 A problem occurred configuring project ':app'. Could not GET 'https://jcenter.bintray.com/com/google/firebase/firebase-iid/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
> 
> Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1. _

same problem, I switch jcentral() to mavenCentral() in android/build.gradle but it seems to still serching in those servers, now I'm getting the next log:

`Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.google.firebase:firebase-iid:[20.0.1].       
     Required by:                                                       
         project :app > project :firebase_messaging > com.google.firebase:firebase-messaging:20.0.1
      > Failed to list versions for com.google.firebase:firebase-iid.   
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/google/firebase/firebase-iid/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/google/firebase/firebase-iid/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/google/firebase/firebase-iid/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
`

**Comment by yanivamram** [comment]
I think the Jcenter.bintray.com is deprecated
See here:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by Aexonic-Abhishek** [comment]
Facing the same issue with below error:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.webkit:android-jsc:+.
     Required by:
         project :app
      > Failed to list versions for org.webkit:android-jsc.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml'.
               > Read timed out

**Comment by pradeepdev001** [comment]
Unable to load Maven meta-data from https://jcenter.bintray.com/com/android/support/support-v4/maven-metadata.xml.

**Comment by CCB-cerivera** [comment]
Error in this moment:

Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.webkit:android-jsc:+.
     Required by:
         project :app
      > Failed to list versions for org.webkit:android-jsc.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/org/webkit/android-jsc/maven-metadata.xml'.
               > Read timed out

**Comment by Alonsso** [comment]
I have found a solution here https://github.com/flutter/flutter/issues/94400#issuecomment-995258623 the updgrade takes some time but it seems pretty good

**Comment by CCB-cerivera** [comment]
is solved now

**Comment by pradeepdev001** [comment]
Yes Thanks & RegardsPradeep ***@***.***+91-9670038997 | 9838947705 From: Cristhian RiveraSent: Tuesday, January 18, 2022 3:01 AMTo: OneSignal/OneSignal-Flutter-SDKCc: pradeepdev001; CommentSubject: Re: [OneSignal/OneSignal-Flutter-SDK] Unable to load Maven meta-data (#428) is solved now—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

**Comment by vijayvaghela72** [comment]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.razorpay:checkout:1.6.+.
     Required by:
         project :app > project :razorpay_flutter
      > Failed to list versions for com.razorpay:checkout.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml'.
               > Read timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org







today i am facing same issue recently .
