### ISSUE TITLE
setExternalUserId Not present in 1.0.3

### ISSUE THREAD

**Issue by fvenegaszeke** [OneSignal/OneSignal-Flutter-SDK#43]
**Description:**

In the 1.0.3 version of the plugin installed using pub, the function setExternalUserId is not present, but is listed in the official documentation [Link](https://documentation.onesignal.com/docs/flutter-sdk#section--setexternaluserid-). 
did you plan to release a new version with this function included soon?

**Comment by rgomezp** [comment]
Hi! The new release will be pushed in the next few hours. Thanks for your patience
