### ISSUE TITLE
IOS: No such module 'One Signal'

### ISSUE THREAD

**Issue by gabrielvictorjs** [OneSignal/OneSignal-Flutter-SDK#435]
**Description:**

NotificationService.swift doesn't recognize `import OneSignal` using `pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'`.

**Environment**

`onesignal_flutter: ^3.1.0`

**Steps to Reproduce Issue:**

Just follow steps 3.7 and 3.9 from [docs](https://documentation.onesignal.com/v8.0/docs/flutter-sdk-setup)

**Comment by emawby** [comment]
@gabrielvictorjs in your podfile.lock what is the resolved version of the OneSignalXCFramework? Also what are the values under `Other Linker Flags` in the Build Settings for your OneSignalNotificationServiceExtension target?

**Comment by rafampessoa** [comment]
@gabrielvictorjs same problem here. I'm getting this issue after update flutter 1.22 to 2.0. I have tried a lot of things :( . Have you found a workaround? 
![Screen Shot 2021-07-29 at 09 51 41](https://user-images.githubusercontent.com/73262862/127495358-51efa372-b619-44a3-9ab5-02690dbd9c19.png)

![Screen Shot 2021-07-29 at 09 49 53](https://user-images.githubusercontent.com/73262862/127494988-1b378402-a8e3-4333-b576-25a217604173.png)

![Screen Shot 2021-07-29 at 09 49 20](https://user-images.githubusercontent.com/73262862/127494662-84e17427-e06a-4f8c-b397-e6fd3e71569e.png)

**Comment by emawby** [comment]
@rafampessoa Your issue should be resolved if you upgrade to the latest OneSignal flutter sdk version 3.1.0. The method it is complaining about was not available in the version of the onesignal flutter SDK you are trying to sue (this is a confusing bit of our documentation we are working on).

**Comment by joaoarmando** [comment]
@gabrielvictorjs Same here! Did you got it?

**Comment by joaoarmando** [comment]
Well, I got it! Sharing it here in case anyone faces this trouble in the future...

The thing was that in my  

> Runner > Targets > OneSignalNotificationServiceExtension > Developmet Info

I was set for IOS 14.5.2 and **it must be IOS 10.0** since I was running a higher version I thought that wouldn't be a problem to have a higher version, but, in my case, the problem was here.

**Comment by ArslanAsghar123** [comment]
Hey guys, I am also facing the same error(No such module 'OneSignal') and also (Stored properties cannot be marked potentially unavailable with '@available').
 it happened when I update my Xcode to the latest version(14.0).

how I get rid of these errors:

=> firstly I update my Pod file  version too (platform: ios, '13.0')
=> iOS Deployment Target in the Build Settings tab to 13 
=> minimum deployment target to also 13
=> run pod update && pod install in terminal

after this I solve (No such module 'OneSignal') error like this;

# add this line in the pod file  
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'

  target 'OneSignalNotificationServiceExtension' do
    use_frameworks!
    pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  end

=> run pod update && pod install in terminal
it works for me as I tried many solutions already
