### ISSUE TITLE
Unable to setAppId() and getDeviceState() properly

### ISSUE THREAD

**Issue by lailai0715** [OneSignal/OneSignal-Flutter-SDK#436]
**Description:**
After update onesignal_flutter from 3.0.0 to 3.1.0, app can't get Player ID from my devices anymore, the log from OneSingnal keep showing this after calling OneSignal.shared.setAppId("xxxxxxxxxxxxxx") ->

V/OneSignal( 8471): Initializing the OneSignal Flutter SDK (2.2.0)
W/OneSignal( 8471): appContext set, but please call setAppId(appId) with a valid appId to complete OneSignal init!
V/OneSignal( 8471): setAppId called with id:xxxxxxxxx-xxxxxxxxxxx changing id from: null
V/OneSignal( 8471): Starting OneSignal initialization!
V/OneSignal( 8471): No class found, not setting up OSRemoteNotificationReceivedHandler
V/OneSignal( 8471): OneSignal SDK initialization delayed, waiting for remote params.

java.net.SocketTimeoutException: failed to connect to api.onesignal.com/175.139.142.25 (port 443) from /10.0.2.16 (port 44788) after 60000ms
W/OneSignal( 8471): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:190)
W/OneSignal( 8471): 	at libcore.io.IoBridge.connect(IoBridge.java:134)
W/OneSignal( 8471): 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
W/OneSignal( 8471): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
W/OneSignal( 8471): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
W/OneSignal( 8471): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
W/OneSignal( 8471): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
W/OneSignal( 8471): 	at java.net.Socket.connect(Socket.java:621)
W/OneSignal( 8471): 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
W/OneSignal( 8471): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
W/OneSignal( 8471): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
W/OneSignal( 8471): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
W/OneSignal( 8471): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
W/OneSignal( 8471): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
W/OneSignal( 8471): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
W/OneSignal( 8471): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
W/OneSignal( 8471): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
W/OneSignal( 8471): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
W/OneSignal( 8471): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
W/OneSignal( 8471): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
W/OneSignal( 8471): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
W/OneSignal( 8471): 	at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:183)
W/OneSignal( 8471): 	at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:44)
W/OneSignal( 8471): 	at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:112)
W/OneSignal( 8471): 	at java.lang.Thread.run(Thread.java:923)
I/OneSignal( 8471): Failed to get Android parameters, trying again in 40 seconds.

**Environment**
1. onesignal_flutter: ^3.1.0
2. Flutter SDK: 2.2.3
3. Devices: Android Emulator, Samsung Galaxy S21 Ultra
4. environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.15.0
  cached_network_image: ^3.0.0
  provider: ^5.0.0
  http: ^0.13.3
  intl: ^0.17.0
  location: ^4.3.0
  shared_preferences: ^2.0.5
  flutter_easyloading: ^3.0.0
  fluttertoast: ^8.0.7
  flutter_html: ^2.0.0
  flutter_signin_button: ^2.0.0
  get_it: ^7.1.3
  connectivity: ^3.0.3
  country_code_picker: ^2.0.1
  pin_code_fields: ^7.1.0
  carousel_slider: ^4.0.0-nullsafety.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  flutter_launcher_icons: ^0.9.0
  animations: ^2.0.0
  url_launcher: ^6.0.4
  image_picker: ^0.8.0+4
  flutter_image_compress: ^1.0.0
  path_provider: ^2.0.2
  path: ^1.8.0
  image_cropper: ^1.4.1
  webview_flutter: ^2.0.8
  package_info_plus: ^1.0.3

  onesignal_flutter: ^3.1.0
  barcode_widget: ^2.0.1
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

**Comment by emawby** [comment]
@lailai0715 I apologize for the late reply are you still experiencing this issue?

**Comment by lailai0715** [comment]
> @lailai0715 I apologize for the late reply are you still experiencing this issue?

Hi, it's worked after I import the google-service.json file. Not why it's required Firebase setup to work. Or is it safe to remove it now?

**Comment by emawby** [comment]
@lailai0715 You shouldn't need that file and I don't know how that would affect the error log from this issue, but you could try removing it and seeing if you still get the issue (unless you are using other firebase services that require that file of course)
