### ISSUE TITLE
setNotificationWillShowInForegroundHandler but for background

### ISSUE THREAD

**Issue by MiranKm** [OneSignal/OneSignal-Flutter-SDK#437]
**Description:**

setNotificationWillShowInForegroundHandler works only when the app is in focus is there a way to not show a certain notification when the app is in the background? 

I looked around a lot and didn't find anything, if there isn't a way to do that could this issue be turned into a feature request

I've linked this on stackoverflow someone else had this issue but it seems it worked for their case 
[Reference](https://stackoverflow.com/questions/67575965/is-it-possible-to-filter-certain-push-notifications-on-flutter)

**Comment by malvinpratama** [comment]
i have same problem.
if use sdk < 3.0.0 it's work with setNotificationReceivedHandler.
in setNotificationReceivedHandler you can handle the data even if the app is out of focus.
but in setNotificationWillShowInForegroundHandler your app must be in focus.
i don't know it's an SDK issue or the documentation to handle cases like this doesn't exist but can handle cases like this.

**Comment by WillowWisp** [comment]
Kinda weird that this isn't supported, especially since it was supported in the past. Does anyone know the reason why they removed this?

**Comment by hugoyair** [comment]
You must use setNotificationOpenedHandler because you are background, so, when you press to the notification that listener called setNotificationOpenedHandler will listen it and enter to the listener. setNotificationWillShowInForegroundHandler  is used when you are into to your app not outside

**Comment by emawby** [comment]
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen
