### ISSUE TITLE
Archive fails to build in Xcode

### ISSUE THREAD

**Issue by willvlad** [OneSignal/OneSignal-Flutter-SDK#44]
Read through all the similar issues and agree with other posters that the Onesignal Flutter IOS docs need to be updated and/or corrected. At the moment, they are not sufficient to make Onesignal usable for a flutter project in IOS.

I've followed them to the letter and can't make the archive of my flutter project build. Errors seem to be around 
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

It built archives fine without Onesignal. I've created and re-created provisioning profiles to add groups, created the onesignal group, added and re-added certificates, did numerous pod installs, disabled and enabled BITCODE in Xcode, linked binary with libraries, yet nothing seems to satisfy the archive to build...

Before giving up completely on Onesignal - if anyone has managed to get your actual flutter project to use Onesignal AND archive in IOS - can you share your steps please as the official docs are unfortunately either incomplete or incorrect

**Comment by Nightsd01** [comment]
@willvlad can you post the full error as well as your Podfile?

**Comment by willvlad** [comment]
@Nightsd01 I've had to completely roll back my project to before I started doing the onesignal stuff so don't have the exact Xcode error messages anymore, but they were very brief and not too useful - just something along the lines of various libraries not found `clang: error: linker command failed with exit code 1 (use -v to see invocation)` - and quite similar to what the other posters have put in their tickets. 

The podfile was done exactly as per your instructions - your code was just above post_install. 

What would really help is if you could just take any hello world flutter project and document all the steps what you would be taking to make it work with your plugin on ios, also bearing in mind that not many flutter developers know the ins and outs of xcode or ios. The steps in the docs at the moment might be enough for an ios developer, but judging by how many people are having the same issue, they are either not complete or not 100% clear for someone working just with flutter

**Comment by Nightsd01** [comment]
@willvlad I’m afraid that’s not super helpful. We’ve got a lot of clients running out Flutter SDK sand few of them have such an issue, and when they do it’s generally a configuration issue that is unique to your project structure & dependencies. 

Can you please go ahead and try to reproduce the issue so we can at least know what your actual error message is...?

**Comment by willvlad** [comment]
You can easily reproduce this failure by simply taking any basic flutter project and following your current steps. If you do manage to archive, it'd be helpful to understand the exact steps. At a minimum, taking a basic flutter project will improve the docs from the current position and would be really helpful for anyone thinking of using your service.

**Comment by Nightsd01** [comment]
I (and many companies that use our Flutter SDK) can build and archive projects just fine. If you cannot even post your full error message, please don’t post it.

**Comment by willvlad** [comment]
Brad - that's really good to hear that many flutter apps managed to use your SDK for IOS. I'd be interested in having a look at a single one where someone has implemented your SDK on IOS - this would actually answer all of my questions without having to bother you. Do you happen to know at least one with code visible somewhere? 

Generally, as it's your repo, it's up to you if you act on users' suggestions to improve your docs or ignore them. I've been trying to give you feedback that the current docs are confusing and it'd be great if you could just follow them yourself and thus make them easier to follow for us your potential users. If you tried to follow them yourself now, you'd see that they not quite crystal clear, at least not for someone not too familiar with ios or xcode. For example, consider the following: 

Under 2.10 of https://documentation.onesignal.com/docs/flutter-sdk-setup you are redirecting us to https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup where under 1 you again re-direct to https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension. There you ask amongst others to do the following:

Add the OneSignal dependency under your project name target as well as OneSignalNotificationServiceExtension target like below.

```target 'project_name' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end```

This snippet is different from what you said to add under 2.7 of the first link AND if followed it throws an error ` The target `Runner` is declared twice for the project `Runner.xcodeproj`.` So we have to refactor it and insert the first part of the code in the already existing target 'Runner' do to eliminate the error.

Going on, you ask under 4 of the same page to add following OneSignal initialization code to AppDelegate:

```
#import <OneSignal/OneSignal.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
   // Replace '11111111-2222-3333-4444-0123456789ab' with your OneSignal App ID.
   [OneSignal initWithLaunchOptions:launchOptions
                              appId:@"11111111-2222-3333-4444-0123456789ab"
   				 handleNotificationAction:nil
                            settings:@{kOSSettingsKeyAutoPrompt: @false}];
   OneSignal.inFocusDisplayType = OSNotificationDisplayTypeNotification;
   
   // Recommend moving the below line to prompt for push after informing the user about
   //   how your app will use them.
   [OneSignal promptForPushNotificationsWithUserResponse:^(BOOL accepted) {
        NSLog(@"User accepted notifications: %d", accepted);
   }];
    
   return YES;
}
```

Well, this code can't be just added verbatim as there is already a return and an end in that file:

```
#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [GeneratedPluginRegistrant registerWithRegistry:self];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

@end
```

So we have to refactor this snippet too and to find out how, we go and check what you've done yourselves in your Example app in this repo. To our great surprise, we see your own AppDelegate file doesn't even have this snippet! So is it optional then or what?

Ok, we plough on and go under OneSignalNotificationServiceExtension target, which is now complaining that 
```
Provisioning profile "XXX" has app ID "com.xxx.xxx.ios", which does not match the bundle ID "com.xxx.xxx.ios.OneSignalNotificationServiceExtension".
```
Of course, it doesn't match! -- you've specifically asked us to set up a different bundle ID ending with OneSignalNotificationServiceExtension for your extension. Whereas the provisioning profile had been set up on the developer.apple portal as for our app whose bundle ID is com.xxx.xxx.ios. How are we supposed to set it up to also for your extension? The docs are silent on that too... 
Do we re-factor the bundle id and remove the OneSignalNotificationServiceExtension? If we do, we get that Linker error I mentioned earlier:

```
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/FirebaseAuth'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/FirebaseCore'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/FirebaseDatabase'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/FirebaseFirestore'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/FirebaseStorage'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/Protobuf'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/cloud_firestore'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/firebase_analytics'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/firebase_auth'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/firebase_core'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/firebase_storage'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/flutter_full_pdf_viewer'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/flutter_search_panel'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/flutter_webview_plugin'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/gRPC-C++'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/gRPC-Core'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/nanopb'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/onesignal'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/path_provider'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/share'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/shared_preferences'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/url_launcher'
ld: warning: directory not found for option '-L/Users/vv/Library/Developer/Xcode/DerivedData/Runner-fctfrdgkismgyoeuppvemohenvrj/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/webview_flutter'
ld: library not found for -lFirebaseAuth
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
If we don't, we can't even start the archiving as the provisioning profile has only one bundle id...

So as you can see, all the above adds up to a very convoluted process, hence my genuine request to you to follow your own docs and document on a step by step basis what you did or didn't do in xcode and developer portal to actually archive any flutter project ios build. 

Trust this clarifies at least some of the issues. Now it's up to you if you want to improve the docs accordingly or ignore it all. I wanted to use your sdk, but it simply doesn't work in flutter/ios so I'm fine with either option you choose - there is always Firebase Cloud Message itself to use for those of us building apps in flutter. thanks

**Comment by Nightsd01** [comment]
@willvlad I’m gonna have to defend our docs here: I’m sorry to say it but when I look at the stuff you’re talking about it’s written pretty clearly. 

When you follow the link to set up App Groups, it says to add the notification service extension ***“if you haven’t already done so”***. Perhaps you missed that part?

You should also be able to enable automatic provisioning for the Extensions Service and that should solve your issue with provisioning. In the screenshot in our docs, automatic provisioning is enabled. 

I’ll make some adjustments to our docs to make it easier to follow for folks who aren’t as familiar with Xcode, especially since most Flutter devs really don’t need to be very familiar with it.

**Comment by willvlad** [comment]
@Nightsd01 I'm glad you're going to amend your docs.

I did see that comment, but how is one supposed to know whether this is the same or a different action that is being required? Perhaps, you need to have a clarification that this part is not applicable for those coming from Flutter.

Re. automatic provisioning - it doesnt work unfortunately if xcode doesn't have a physical apple device registered, which is the case for many flutter devs. So a non-automatic provisioning workaround is needed for this to work.

Trust this clarifies. Thanks

**Comment by willvlad** [comment]
@Nightsd01 
Did the above answer clarify the issue? Any ETA on the update? 
If there is no way for your service to work with non-automatic provisioning, then there is probably little point for us to wait for your docs to be updated.
