### ISSUE TITLE
App does not start on iOS simulator

### ISSUE THREAD

**Issue by enricobenedos** [OneSignal/OneSignal-Flutter-SDK#440]
**Description:**

From `OneSignalSDK >3.0.0` it is impossible to start my app on iOS simulator.

**Environment**

**Steps to Reproduce Issue:**

1. Install the OneSignal Flutter SDK using pub into your project and using OneSignal online docs
2. Initialize the SDK using OneSignal.shared.init(your_app_id)
3. Start the app on iOS simulator

**Anything else:**

```
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
lib/main.dart:1
Xcode build done.                                            5.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    OneSignalXCFramework-dlcocwugqjdcsifchfhaxqmqcthw
    ld: in /Users/enrico/Projects/myapp_app/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/enrico/Projects/myapp_app/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    OneSignalXCFramework-dlcocwugqjdcsifchfhaxqmqcthw
2
    Command CompileSwift failed with a nonzero exit code
    OneSignalXCFramework-dlcocwugqjdcsifchfhaxqmqcthw
    Command CompileSwift failed with a nonzero exit code
    OneSignalXCFramework-dlcocwugqjdcsifchfhaxqmqcthw
```

Are we sure that OneSignal documentation is updated? It is not the first time that the documentation does not correspond with the OneSignal example app. 
For example from OneSignal online docs:
```
3.7 Close the Xcode project. In the /ios directory of your project, open the Podfile and add the following to the bottom (just above any post_install logic):

Podfile

target 'OneSignalNotificationServiceExtension' do
  #use_frameworks!
  pod 'OneSignal', '>= 3.0.0', '< 4.0'
end
```
on your sample app:
```
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '3.5.3'
end
```
Which is the correct way?

Thanks

**Comment by gabrielvictorjs** [comment]
I have the same problem :(, when I use `'OneSignalXCFramework'` XCode shows "No such module 'One Signal'"

**Comment by gabrielvictorjs** [comment]
@Jeasmine help us!!

**Comment by emawby** [comment]
@enricobenedos Hello what Cocoapods version are you using?

You can indeed use the XCFramework pod instead. When doing so make sure to run pod cache clean and pod repo update before install. You can try adding arm64 to excluded frameworks for your targets in Xcode as well, but I do not need to do so in my project.

```
target 'OneSignalNotificationServiceExtension' do
  #use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end
```

**Comment by enricobenedos** [comment]
Hello @emawby,

I'm now using `OneSignalXCFramework` but I need to better test it. At the moment I'm using my Windows machine but I think I've the last pod version on my mac (1.10.1).

I think that OneSignal team need to update the docs because there are some discrepancies. Months have passed from >=3.0.0 release and docs are already not updated. This cause a lot of time wasted by developers.

**Comment by rafampessoa** [comment]
The same issue here :(  Only works if I run by xcode if i use flutter run command I'm getting the same error

**Comment by emawby** [comment]
@rafampessoa This is probably because the command line and xcode are running 2 different build configurations. I would try seeing if there are differences between the build config you are running in Xcode vs command line, and trying to resolve the differences.

If that doesn't seem to be the case please provide your podfile and flutter version!

**Comment by ahmetakil** [comment]
We also have the same issue we can run from xcode but flutter run fails 

flutter version: Flutter 2.2.0 • channel stable and using  onesignal_flutter: ^3.1.0 (pubspec.lock also has the same version)

podfile: 
`
  target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '3.4.3'
end
`

Error log from flutter run:
` ld: in ..../ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal(OneSignal-arm64-master.o), building for iOS Simulator, but linking in object file built for iOS, file '...../ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal'`

**Comment by ahmetakil** [comment]
Using podfile `target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end` fixed the issue.

**Comment by emawby** [comment]
@ahmetakil I am glad it is resolved!
