### ISSUE TITLE
Huawei phone(without google) when in debug mode able subscribed, no generate to release APK failed to get subsribe

### ISSUE THREAD

**Issue by ChiHwe** [OneSignal/OneSignal-Flutter-SDK#441]
**Description:**
I using Huawei Phone(without Google) connect to my Laptop , and using the Android studio to install the app(debug) directly to 
the phone, after the app started, it will able to subscribed to Onesignal, 

However, the release APK (which i submit to App gallery) , there is NOT. not sure what happen  

**Environment**
<!-- Example:
1. Onesignal Version : 2.6.4
.

**Comment by ririlya94** [comment]
@ChiHwe May I know how you solve this problem?
