### ISSUE TITLE
The notification works well on iOS but delays too much in Android.

### ISSUE THREAD

**Issue by phuhungtran** [OneSignal/OneSignal-Flutter-SDK#444]
**Description:**
My app used to receive notifications very quickly.
Starting about 2 months ago my app started having this problem. 
I tried send notifications from Back-end and from New Push Notification on OneSignal site but the result is the same.
The notification works well sometimes but Most of the time, it works so slowly.
The delay time is about 20min, sometimes I can not receive the notification.
I thought the reason is I'm using Free Plan but OneSignal Supporter told that the notification service in Paid Plan won't send/receive faster than Free Plan.

**Environment**
I was using onesignal_flutter: ^2.6.0 and got this issue then I change the version to 3.1.0 and it still takes many minutes to receive a notification.
I'm using Flutter (Channel stable, 2.2.2, on macOS 11.3.1 20E241 darwin-x64, locale en-US).

**Steps to Reproduce Issue:**
1. I follow this site to setup: https://documentation.onesignal.com/docs/flutter-sdk-setup.
2. Attempt to receive a push notification.

**Comment by jkasten2** [comment]
@phuhungstdio Could you provide the following details:
* Device models
* Android versions
* Could you list all the notification options uses / payload? Any images included on the notification?
* Does setting the notification priority to High effect the delay time?
* Logcat from the device(s) have the issue.

**Comment by phuhungstdio** [comment]
It

> @phuhungstdio Could you provide the following details:
> 
> * Device models
> * Android versions
> * Could you list all the notification options uses / payload? Any images included on the notification?
> * Does setting the notification priority to High effect the delay time?
> * Logcat from the device(s) have the issue.

It happens on Xiaomi Note note 7 (Android 10), Xiaomi Note note 8 (Android 10), Samsung Galaxy S9+ (Android 10) and some other device of my users.
I think it just the delay issue so it don't need logcat.

**Comment by emawby** [comment]
@phuhungstdio Do your notifications contain any media attachments such as images? Can you provide an example payload? 
A device log will be useful for us to try to understand what is happening once the notification has arrived on the device.

**Comment by emawby** [comment]
@phuhungtran I am closing the issue, but if this is still a problem for you please let us know!
