### ISSUE TITLE
setLocationShared

### ISSUE THREAD

**Issue by haind261099** [OneSignal/OneSignal-Flutter-SDK#447]
- I have an issue when i starting the Flutter app, i got black screen and can't do anything. 

- My AppDelegate.swift:
import UIKit
import OneSignal

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
  
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: 
[UIApplication.LaunchOptionsKey: Any]?) -> Bool {
  
  // Remove this method to stop OneSignal Debugging 
  OneSignal.setLogLevel(.LL_VERBOSE, visualLevel: .LL_NONE)

  // OneSignal initialization
  OneSignal.setLocationShared(false)
  OneSignal.initWithLaunchOptions(launchOptions, appId: "7b2461b1-c18d-4d78-9875-a58c42971119")

  // promptForPushNotifications will show the native iOS notification permission prompt.
  // We recommend removing the following code and instead using an In-App Message to prompt for notification permission (See step 8)
  OneSignal.promptForPushNotifications(userResponse: { accepted in
    print("User accepted notifications: \(accepted)")
  })

   return true
}
  
// Remaining contents of your AppDelegate Class...
}

- My response: 
VERBOSE: Calling OneSignal create/on_session                            
VERBOSE: Not sending location with 'on_session' request payload, setLocationShared is false or lastLocation is null
VERBOSE: HTTP Request (OSRequestRegisterUser) with URL: https://api.onesignal.com/players/d6b7a954-25e3-48da-a24b-c14e45ee2f62/on_session, with parameters: {
  "app_id" : "7b2461b1-c18d-4d78-9875-a58c42971119",                    
  "net_type" : 0,                                                       
  "test_type" : 1,                                                      
  "device_type" : 0,                                                    
  "sdk" : "021605",                                                     
  "identifier" : "e5cad8f68b3a62f76866339f3275446e7355148f6922c7df37e5249026eaa5c8",
  "language" : "vi-VN",                                                 
  "device_os" : "14.4.2",                                               
  "game_version" : "1",                                                 
  "timezone" : 25200,                                                   
  "ad_id" : "058FF4B0-48F7-4683-84F6-4832547A9016",                     
  "notification_types" : 31,                                            
  "carrier" : "Mobifone",                                               
  "device_model" : "iPhone9,4"                                          
}                                                                       
[Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 86 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 86 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}
VERBOSE: network response (OSRequestGetIosParams): {                    
    outcomes =     {                                                    
        direct =         {                                              
            enabled = 0;                                                
        };                                                              
        indirect =         {                                            
            enabled = 0;                                                
            "notification_attribution" =             {                  
                limit = 10;                                             
                "minutes_since_displayed" = 60;                         
            };                                                          
        };                                                              
        unattributed =         {                                        
            enabled = 0;                                                
        };                                                              
    };                                                                  
    "receive_receipts_enable" = 0;                                      
    "uses_provisional_auth" = 0;                                        
}                                                                       
VERBOSE: network response (OSRequestRegisterUser): {                    
    id = "d6b7a954-25e3-48da-a24b-c14e45ee2f62";                        
    success = 1;                                                        
}                                                                       
Request <OSRequestRegisterUser: 0x2839b1a10> success result {           
    id = "d6b7a954-25e3-48da-a24b-c14e45ee2f62";                        
    success = 1;                                                        
}                                                                       
VERBOSE: on_session result: {                                           
    push =     {                                                        
        id = "d6b7a954-25e3-48da-a24b-c14e45ee2f62";                    
        success = 1;                                                    
    };                                                                  
}                                                                       
VERBOSE: getNotificationTypes:mSubscriptionStatus: -1                   
VERBOSE: getNotificationTypes:mSubscriptionStatus: -1          

- Can anybody fix this issue?? Thanks for your help!!

**Comment by haind261099** [comment]
> @haind261099 Hello! Does removing the OneSignal initialization code resolve the screen being black? The title of this issue is setLocationShared, but I am not sure how that relates to the issue you have posted. Can you please clarify?

**Comment by haind261099** [comment]
> @haind261099 Hello! Does removing the OneSignal initialization code resolve the screen being black? The title of this issue is setLocationShared, but I am not sure how that relates to the issue you have posted. Can you please clarify?

Yes, when i removed OneSignal initialization code, my app run immediately.
I try to add OneSignal.setLocationShared(false) to Swift but not true. My debug logs setLocationShared error like that so i think that is the main error.
And one more error is about CoreTelephony, i haven't met that error before

**Comment by emawby** [comment]
@haind261099 I am not able to reproduce this issue and have not heard of it before. Are you able to provide a sample app that has this issue?

**Comment by haind261099** [comment]
> @haind261099 I am not able to reproduce this issue and have not heard of it before. Are you able to provide a sample app that has this issue?

**Comment by D2Wirexia** [comment]
Has anyone managed to fix the problem with turning off geolocation, because apple requires me to give permission for it, but I don't want to collect this data...

`
static Future<void> init() async {
    await OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);
    await OneSignal.shared.setAppId(appId);
    await OneSignal.shared.disablePush(false);
    await OneSignal.shared.setLanguage(languageCode);
    await OneSignal.shared.setLocationShared(false);
}
`
