### ISSUE TITLE
iOS - setNotificationOpenedHandler and setNotificationWillShowInForegroundHandler not working

### ISSUE THREAD

**Issue by mahmut** [OneSignal/OneSignal-Flutter-SDK#449]
Hello,

setNotificationOpenedHandler and setNotificationWillShowInForegroundHandler not working on ios.

in logs
VERBOSE: Notification opened handler set successfully
VERBOSE: Notification will show in foreground handler set successfully

but when i sent notification not handling methods.

iOS: 14.7
package version 3.1.0

**Comment by emawby** [comment]
@mahmut How are you sending the notifications? Are you using any other SDKs like firebase in your project?

**Comment by mahmut** [comment]
I'm sending from onesignal panels.  i am using firebase analytics

**Comment by emawby** [comment]
@mahmut Hello can you let me know if the fix I posted in [this issue](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/348) helps?

**Comment by zeucxb** [comment]
Same problem here.

**Comment by mahmut** [comment]
I solved my problem. I was using a location tracking plugin in the background, that plugin was blocking it.

One of your plugins may be blocking yours.
