### ISSUE TITLE
HMS core exist in flutter plugin?

### ISSUE THREAD

**Issue by AlirezaDaryani** [OneSignal/OneSignal-Flutter-SDK#453]
**Description:**

The analysis of the App shows that there is some HMS services.

Are these for your SDK?

I do not implemented HMS for this flutter app.

**Comment by AlirezaDaryani** [comment]
Or
How to remove HMS from your library?
I need to do it in my app.

**Comment by emawby** [comment]
@AlirezaDaryani Our Huawei support requires your app to add the Huawei service dependencies so you should not be seeing those services being used unless your app or another 3rd party service added it. Maybe you might be seeing references to Huawei in our code?

**Comment by emawby** [comment]
@AlirezaDaryani I am closing this for now. If this is still an issue for you feel free to reopen.
