### ISSUE TITLE
Icon was not displayed on notification. White square displayed istead!

### ISSUE THREAD

**Issue by derik83** [OneSignal/OneSignal-Flutter-SDK#46]
**Here is my icon:**
![ic_stat_onesignal_default](https://user-images.githubusercontent.com/44380095/50589543-60dd4b00-0e87-11e9-8e1a-807cab9038d8.png)
I used Image Asset tool in android studio to make this icon.

**pubspec.yaml**
dependencies:
  flutter_webview_plugin: ^0.3.0+2
  onesignal: ^1.0.0
  flutter:
    sdk: flutter

**In AndroidManifest.xml**
`         <meta-data android:name="ic_stat_onesignal_default" android:value="@drawable/ic_stat_onesignal_default" />`
`        <meta-data android:name="com.onesignal.ic_stat_onesignal_default" android:value="@drawable/ic_stat_onesignal_default" />`

**in C#**
public MessageData(OneSignalMessenger data)
            {
                this.app_id = data.sender.appId;
                this.headings = new { en = data.title };
                this.subtitle = new { en = data.subtitle };
                this.contents = data.contents;
                this.include_player_ids = data.include_player_ids;
                this.included_segments = data.included_segments;
                this.url = data.url;
                this.small_icon = "ic_stat_onesignal_default";
            }

I don't know what went wrong! 
I have no idea to fix this error!

Please help me. Thank you so much in advance!

**Comment by jkasten2** [comment]
@derik83 You will need to make your black background on your notification icon transparent for it to show correctly on the Android device. I recommend using [Android Asset Studio](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_onesignal_default) to make sure you have correctly edited your icon as what you see here is how it will look on the device.

See the following for full details on generating notification icons.
https://documentation.onesignal.com/docs/customize-notification-icons#section-1-generate-icons

**Comment by derik83** [comment]
Thank you all!
I have got it working by using transparent/white png as notification Icon and the logo as small_icon.
