### ISSUE TITLE
Error in access  nested object in notification.additionalData

### ISSUE THREAD

**Issue by hussenIbrahim** [OneSignal/OneSignal-Flutter-SDK#461]
i get _InternalLinkedHashMap<Object?, Object?>' is not a subtype of type 'Map<String, dynamic> error  when try to access  receiver object
`"data": {
    "message": "test message",
    "id": 1628326377128,
    "type": "CHAT_MESSAGE",
    "receiver": {
        "username": "defaultsupplier",
        "user_type": "Supplier",
    }
}`

**Comment by emawby** [comment]
@hussenIbrahim thank you for the report I am looking into this to ensure our JSON Decoding always gets the correct type

**Comment by emawby** [comment]
@hussenIbrahim This is working for me when posting the notification via our API, but it does not work when sending it via the dashboard. Are you using the API for this? If so can you post your API call (with IDs removed)?

**Comment by hussenIbrahim** [comment]
> @hussenIbrahim This is working for me when posting the notification via our API, but it does not work when sending it via the dashboard. Are you using the API for this? If so can you post your API call (with IDs removed)?

Thanks 
i solved it by  encode  when send and and decode on receive

this is the body 
`{
    "app_id": "APP_ID",
    "include_external_user_ids": [
        "ID"
    ],
    "data": {
        "message": "Hello",
        "id": 1628326377128,
        "type": "CHAT_MESSAGE",
        "receiver": {
            "id": "ID",
            "username": "defaultsupplier",
            "user_type": "Supplier",
            "message": "Hello",
            "person": {
                "id": 1,
                "name": "Default Supplier",
                "gender": true,
                "created_at": "2021-08-05 03 49 27 PM"
            }
        },
        "person": {
            "id": 1,
            "name": "Default Supplier",
            "gender": true,
            "created_at": "2021-08-05 03 49 27 PM"
        },
        "conversationsModel": {
            "id": "a5a07b96-e2e2-4248-884f-0ee12d845964",
            "username": "defaultsupplier",
            "user_type": "Supplier",
            "message": null,
            "person": {
                "id": 1,
                "name": "Default Supplier",
                "gender": true
            }
        }
    },
    "headings": {
        "en": "Default Driver",
        "ar": "Default Driver"
    },
    "contents": {
        "en": "Hello",
        "ar": "Hello"
    }
}`

**Comment by hussenIbrahim** [comment]
> @hussenIbrahim This is working for me when posting the notification via our API, but it does not work when sending it via the dashboard. Are you using the API for this? If so can you post your API call (with IDs removed)?

Thanks
i solved it by encode when send and and decode on receive

this is the body
`{ "app_id": "APP_ID", "include_external_user_ids": [ "ID" ], "data": { "message": "Hello", "id": 1628326377128, "type": "CHAT_MESSAGE", "receiver": { "id": "ID", "username": "defaultsupplier", "user_type": "Supplier", "message": "Hello", "person": { "id": 1, "name": "Default Supplier", "gender": true, "created_at": "2021-08-05 03 49 27 PM" } }, "person": { "id": 1, "name": "Default Supplier", "gender": true, "created_at": "2021-08-05 03 49 27 PM" }, "conversationsModel": { "id": "ID", "username": "defaultsupplier", "user_type": "Supplier", "message": null, "person": { "id": 1, "name": "Default Supplier", "gender": true } } }, "headings": { "en": "Default Driver", "ar": "Default Driver" }, "contents": { "en": "Hello", "ar": "Hello" } }`
