### ISSUE TITLE
Error #import <OneSignal/OneSignal.h> file not found.

### ISSUE THREAD

**Issue by newbieflutter** [OneSignal/OneSignal-Flutter-SDK#469]
Hi,
   I am getting this error #import <OneSignal/OneSignal.h> on ios says file not found ? Here is what my steps are.
    I am using the latest plugin version in pubspec.yaml that is onesignal_flutter: 3.2.1. Next thing I followed all the steps given in this link https://documentation.onesignal.com/docs/flutter-sdk-setup. I followed each step accordingly. Below is my podfile
```
# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```
Next I followed this link to debug too
https://documentation.onesignal.com/docs/troubleshooting-flutter. I have done pod deintegrate and pod install many times. I have even deleted the whole project and recreate also giving the same issue.  What else can I do to overcome this error or any debugging further I need ? Thank you.

**Comment by newbieflutter** [comment]
Hi its in the NotificationServiceExtension. Ok let me try your settings and suggestion too,

**Comment by DavideArena** [comment]
Hello, actually i've the same problem. I already tried to put the Pods_YourTarget.framework in the Frameworks and Libraries section as suggested by @emawby, but i'm still getting the same error **#import <OneSignal/OneSignal.h> 'OneSignal/OneSignal.h' file not found**

![image](https://user-images.githubusercontent.com/75489599/133298110-834d326e-af04-46b2-b2b0-bf6cd1a2d021.png)

Actually i'm using the OneSignal SDK version 3.2.3. @newbieflutter did you solve the problem in some way?

Thanks

**Comment by emawby** [comment]
@DavideArena You need to include in the Podfile for your NotificationServiceExtension target. The image you linked looks like its only the pods for you main app target.

**Comment by jkasten2** [comment]
Closing do to inactivity

**Comment by danuprakoso26** [comment]
> Hi, we have the similar issue.
> 
> Frameworks and Libraries for OneSignal target <img alt="image" width="764" src="https://user-images.githubusercontent.com/56012379/223448162-7c91b9ca-4af1-40e5-84eb-9f971bd69213.png">
> 
> Runpath Search Paths for OneSignal target <img alt="image" width="729" src="https://user-images.githubusercontent.com/56012379/223447951-b050e7c2-38c7-4184-a8b8-520f8840652a.png">
> 
> Please let us know if there's any additional info needed. Thanks.

any updates? did you find a solution?
