### ISSUE TITLE
framework not found Pods_OneSignalNotificationServiceExtension Flutter 2.2.3 

### ISSUE THREAD

**Issue by 3dluis** [OneSignal/OneSignal-Flutter-SDK#472]
When compiling via Xcode, the following error is occurring.

`Ld ~/appNotification/ios/build/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/armv7/Binary/OneSignalNotificationServiceExtension normal armv7 (in target 'OneSignalNotificationServiceExtension' from project 'Runner')
    cd ~/appNotification/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target armv7-apple-ios10.2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -L~/appNotification/ios/build/Debug-iphoneos -F~/appNotification/ios/build/Debug-iphoneos -F~/appNotification/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework -F~/appNotification/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework -filelist ~/appNotification/ios/build/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/armv7/OneSignalNotificationServiceExtension.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker ~/appNotification/ios/build/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/armv7/OneSignalNotificationServiceExtension_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fapplication-extension -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker ~/appNotification/ios/build/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/armv7/OneSignalNotificationServiceExtension.swiftmodule -ObjC -framework CoreGraphics -framework OneSignal -framework SystemConfiguration -framework UIKit -framework UserNotifications -framework WebKit -e _NSExtensionMain -framework Pods_OneSignalNotificationServiceExtension -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker ~/appNotification/ios/build/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/armv7/OneSignalNotificationServiceExtension_dependency_info.dat -o ~/appNotification/ios/build/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/armv7/Binary/OneSignalNotificationServiceExtension

ld: framework not found Pods_OneSignalNotificationServiceExtension
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Environment
OneSignal: 3.4.3
onesignal_flutter: 3.1.0
Flutter 2.2.3 • channel stable 
Framework • revision f4abaa0735 (8 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

<img width="418" alt="Screen Shot 2021-08-28 at 11 19 20 AM" src="https://user-images.githubusercontent.com/1660989/131222724-6dc7138c-057e-4ae2-ae6b-cf1ab0528434.png">

<img width="782" alt="Screen Shot 2021-08-28 at 11 20 52 AM" src="https://user-images.githubusercontent.com/1660989/131222776-705d10c6-bb2c-4d27-8bdd-7ff0f006364b.png">

<img width="632" alt="Screen Shot 2021-08-28 at 11 22 34 AM" src="https://user-images.githubusercontent.com/1660989/131222795-04630b35-956f-4f60-8bdd-0d319b5eb8fc.png">

**Comment by emawby** [comment]
@3dluis thank you for reaching out. Your build settings screen shot is helpful, but if you could show your "Framework Search Paths" under the Search Paths group that is the place where the Cocoapods frameworks are linked to your project. 

Did you start encountering this issue after upgrading to a new version or is this your first time implementing OneSignal in the project?

**Comment by jkasten2** [comment]
@3dluis Could you also attach your `Podfile`?

**Comment by ernesto** [comment]
I fix the Archive problem changing the iOS Deployment Target of OneSignalExtension to same version of my Runner App (12.1):

![Screen Shot 2021-09-01 at 03 03 44](https://user-images.githubusercontent.com/210907/131620165-c6f19277-b3d7-4274-8763-52069ab03e5b.png)

**Comment by rigoarriaza** [comment]
same problem, any news?

**Comment by emawby** [comment]
@rigoarriaza Hello could you please show the contents of your podfile for the NotificationServiceExtension target?

**Comment by flutterdev9715** [comment]
I am also stuck on the same issue. Anyone can help?

My podfile is below.
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
end

**Comment by L-Salazar** [comment]
So i've manage to get through this:

- Set both Excluded Architectures in **Runner** and **OneSignalNotificationExtension** with: **arm64, i386**

<img width="1023" alt="print1" src="https://user-images.githubusercontent.com/65926010/143505285-76c7a40d-cfb8-47d4-b4ba-a6fe507c782a.png">

<img width="1026" alt="print2" src="https://user-images.githubusercontent.com/65926010/143505298-97cf7b7f-3b6e-4011-99b4-98e454c72bbf.png">

In Podfile add:

`
config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET' config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'
config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"  
`

<img width="850" alt="print3" src="https://user-images.githubusercontent.com/65926010/143505625-76786cb2-2190-4e70-b684-f68c31c7a753.png">

That's all, hope that helps someone.

Flutter version: 2.5.3 - Stable Channel
One Signal plugin version: 3.2.7
