### ISSUE TITLE
While i updating onesignal update i get the error like this

### ISSUE THREAD

**Issue by capecomtest** [OneSignal/OneSignal-Flutter-SDK#475]
CocoaPods could not find compatible versions for pod "OneSignalXCFramework":
      In snapshot (Podfile.lock):
        OneSignalXCFramework (< 4.0, = 3.6.2, >= 3.4.3)

      In Podfile:
        OneSignalXCFramework (< 4.0, >= 3.4.3)

        onesignal_flutter (from `.symlinks/plugins/onesignal_flutter/ios`) was resolved to 3.2.3, which depends on
          OneSignalXCFramework (= 3.7.0)

    Specs satisfying the `OneSignalXCFramework (< 4.0, >= 3.4.3), OneSignalXCFramework (< 4.0, = 3.6.2, >= 3.4.3), OneSignalXCFramework (= 3.7.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by capecomtest** [comment]
CocoaPods could not find compatible versions for pod "OneSignalXCFramework":
  In Podfile:
    onesignal_flutter (from `.symlinks/plugins/onesignal_flutter/ios`) was resolved to 3.2.3, which depends on
      OneSignalXCFramework (= 3.7.0)

None of your spec sources contain a spec satisfying the dependency: `OneSignalXCFramework (= 3.7.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by capecomtest** [comment]
try this:
sudo arch -x86_64 gem install ffi

arch -x86_64 pod install

 arch -x86_64 pod install --repo-update

**Comment by wilz05** [comment]
Got the same issue, ran 
```
cd ios/
pod repo update
rm -rf Podfile.lock Pods
pod install
```

 seems to be working for me
