### ISSUE TITLE
Getting this Error while publishing on app store

### ISSUE THREAD

**Issue by capecomtest** [OneSignal/OneSignal-Flutter-SDK#477]
ITMS-90512: Invalid sdk value - The value provided for the sdk portion of LC_VERSION_MIN_IPHONEOS in Runner.app/Frameworks/OneSignal.framework/OneSignal is 15.0 which is greater than the maximum allowed value of 14.7.

**Comment by emawby** [comment]
@capecomtest This was an issue with version 3.2.2 due to the iOS dependency being compiled with a beta version of Xcode tools. The 3.2.3 version fixes this issue!
