### ISSUE TITLE
In-App Messages dont show images, just text and buttons.

### ISSUE THREAD

**Issue by ernesto** [OneSignal/OneSignal-Flutter-SDK#478]
**Description:**
Trying to test In-App Messages with default templates, no one works as expected. The exemples .gifs or .jpgs is not showing in apps (Android and iOS)

The 

**Environment**

OneSignal Flutter SDK: 
`onesignal_flutter: ^3.2.3`

**Steps to Reproduce Issue:**

  1. Install the OneSignal Flutter SDK using pub into your project
  2. Initialize the SDK using OneSignal.shared.init(your_app_id)
  3. Attempt to receive a in-app message
  4. In-App Message appears, but without image. (Issue occurs in Android and iOS)

**Anything else:**

Screenshot:
![14ab341c-8eaf-4816-b413-e2ea06c12fa1](https://user-images.githubusercontent.com/210907/131951336-39292d2c-b7c0-438d-8cc6-40ff0ae01bcf.jpeg)

**Comment by ernesto** [comment]
Any news?

**Comment by emawby** [comment]
@ernesto Hello does this happen on all device types and all images?

**Comment by ernesto** [comment]
> @ernesto Hello does this happen on all device types and all images?

Yes, Android and iOS devices. Also, this issue don't show no any error in the logs. Same effect with .gif and .jpeg images.

**Comment by emawby** [comment]
@ernesto Odd I am not able to reproduce this issue. It looks like you are using one of the template IAMs from the dashboard which should work fine. Do you have an example app that has this issue that I could look at?

**Comment by ernesto** [comment]
Ok, I will provide one

**Comment by ernesto** [comment]
In the last builds, error doesn't occurs anymore.
