### ISSUE TITLE
Upgrade to use Flutter embedding V2

### ISSUE THREAD

**Issue by westy92** [OneSignal/OneSignal-Flutter-SDK#480]
**Description:**

A red warning when building:

```
The plugin `onesignal_flutter` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will
remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

**Environment**

**Steps to Reproduce Issue:**

1. Install the OneSignal Flutter SDK using pub into your project
2. Build with latest Flutter (2.5.0)

**Anything else:**

**Comment by HeynSekk** [comment]
Me too. Today, when I run flutter pub get command, it show that your plugin use a deprecated API of Android embedding and the author of the plugin need to migrate it to Android V2 embedding. It say Flutter may remove those deprecated API in the future.

Here is the web page it redirected me.
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

So do you have a plan to migrate your plugin? If yes, how long might we have to wait?

Anyway, thanks for your plugin. It is very useful and I use it in my Flutter project.

I will be looking forward to your reply. Have a great day.

**Comment by jesselpereira** [comment]
Same issue.

**Comment by mhatout** [comment]
hope for a fix soon

**Comment by TheAlphamerc** [comment]
Getting same warning while compiling the project. I am using `onesignal_flutter: ^3.2.3` and `Flutter 2.5.0 • channel stable`

```sh
The plugin `onesignal_flutter` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
exit code 0
```

**Comment by mamonraab** [comment]
same here

**Comment by minhbaovn1210** [comment]
Hope some savior help soon.

**Comment by tayyipozr** [comment]
👍

**Comment by ryanaidilp** [comment]
Same here

**Comment by joehenrique7** [comment]
O mesmo, alguém saberia se irão atender essa demanda, qual o tempo médio?

**Comment by gireeshkottayam** [comment]
Same Warning !

The plugins `facebook_audience_network, flutter_statusbarcolor_ns, flutter_webview_plugin, notification_permissions, onesignal_flutter, sms_autofill` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated   
APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by luis901101** [comment]
Hi. I just made a [PR 486](https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/486) with the v2 embedding migration.
In the mean time if you can use:
```yaml
onesignal_flutter: #^3.2.3
    git:
      url: https://github.com/luis901101/OneSignal-Flutter-SDK.git
      ref: migrate_android_embedding_v2
```

**Comment by gucciroddman** [comment]
> Hi. I just made a [PR 486](https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/486) with the v2 embedding migration.
> In the mean time you can use:
> 
> ```yaml
> onesignal_flutter: #^3.2.3
>     git:
>       url: https://github.com/luis901101/OneSignal-Flutter-SDK.git
>       ref: migrate_android_embedding_v2
> ```

Hi, I'm facing issues with the following plugins too ( facebook_audience_network, flutter_statusbarcolor_ns,
flutter_webview_plugin, sms_autofill` ) how can i get it to work? i use the above code for one signal and it's working. thank you

**Comment by luis901101** [comment]
@gucciroddman all of that plugins should migrate to android v2 embedding anytime soon. Anyway you can use these plugins without problem… the message you see is just a Deprecate warning, Flutter team will not do a breaking change like that in the near future… I hope…

**Comment by AlirezaDaryani** [comment]
🧐

**Comment by gucciroddman** [comment]
My app isn't loading network images from my website, nothing display it
displays "not decoding error"

**Comment by joaobaronisilva** [comment]
same here

**Comment by giullianocht** [comment]
Same here

**Comment by depeiwang** [comment]
插眼，如果修好了请踢我一脚，谢谢🙏

**Comment by muhammadsaddamnur** [comment]
Yuhuuu same here

**Comment by imasubmarine** [comment]
Same here

**Comment by OHeroJ** [comment]
same here
