### ISSUE TITLE
remove notification with  OneSignal.shared.removeNotification

### ISSUE THREAD

**Issue by toanpzo** [OneSignal/OneSignal-Flutter-SDK#484]
when click notification and opened it then notification was remove from android. I want remove notification when I send notificationid from app.  I user OneSignal.shared.removeNotification
<img width="823" alt="Screen Shot 2021-09-10 at 11 06 29" src="https://user-images.githubusercontent.com/86187224/132798162-77b2c559-696b-4628-a0bd-2cc3411c30ed.png">

**Comment by shampooeyes** [comment]
the OneSignal notificationId is not an int, its a string. So there's no way to call this method as you can't get a notificationId as an int?

**Comment by nan-li** [comment]
Ah I see your question, thanks for clarifying.

For this method, it needs the Android notification integer ID, which is different from the OneSignal notification ID: [documentation here](https://documentation.onesignal.com/docs/flutter-30-api-reference#new-functions). Sorry that this is unclear.

This can be found by calling `notification.androidNotificationId`.
