### ISSUE TITLE
V2 Embed Warning ! can you please help ?

### ISSUE THREAD

**Issue by gireeshkottayam** [OneSignal/OneSignal-Flutter-SDK#485]
The plugins `facebook_audience_network, flutter_statusbarcolor_ns, flutter_webview_plugin, notification_permissions, onesignal_flutter, sms_autofill` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated   
APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by nan-li** [comment]
Hi @gireeshkottayam  thanks for reporting, I saw your comment in Issue #480 so closing due to duplicate issue.
