### ISSUE TITLE
#import <OneSignal/OneSignal.h>

### ISSUE THREAD

**Issue by vmwsree** [OneSignal/OneSignal-Flutter-SDK#49]
I am having this issue, I cannot remove use_framework! line since I already use another plugin in swift which requires. "use_framework!" line.

Xcode's output:
↳
In file included from /Users/vivekmohan/Work/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.0.3/ios/Classes/OneSignalCategories.m:28:
/Users/vivekmohan/Work/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.0.3/ios/Classes/OneSignalCategories.h:28:9: fatal error: 'OneSignal/OneSignal.h' file not found
#import <OneSignal/OneSignal.h>
^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

I use another swift plugin flutter_razorpay

**Comment by Nightsd01** [comment]
@vmwsree there is already an issue open for this (#21). It is an issue with Cocoapods and there’s unfortunately not much we can do about it on our end. We have discovered the cause of the issue in Cocoapods and we plan to issue a PR in the near future.
