### ISSUE TITLE
The plugin `onesignal_flutter` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by magdydy** [OneSignal/OneSignal-Flutter-SDK#492]
The plugin `onesignal_flutter` uses a deprecated version of the Android embedding.
flutter v 2.5

**Comment by danielgomezrico** [comment]
This issue duplicates https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/480

**Comment by AmbujaAK** [comment]
I am too getting the same issue, Any work around to fix this issue ?

**Comment by emawby** [comment]
closing as duplicate #480
