### ISSUE TITLE
OneSignalNotificationServiceExtension version and build numbers are not updated automatically

### ISSUE THREAD

**Issue by cihadturhan** [OneSignal/OneSignal-Flutter-SDK#495]
**Description:**
I received the following warning from apple
> ITMS-90473: CFBundleShortVersionString Mismatch - The CFBundleShortVersionString value '1.0' of extension 'Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex' does not match the CFBundleShortVersionString value '1.0.1' of its containing iOS application 'Runner.app'.

But I remember I've read somewhere that the target `OneSignalNotificationServiceExtension`s version number and build number should be updated automatically. Seems like it's left empty:

![image](https://user-images.githubusercontent.com/3739536/137459726-c379b37f-78d0-40b0-8ed0-4451b0142680.png)

**Environment**
`Service Extension's Info.plist`
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>OneSignalNotificationServiceExtension</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>NSExtension</key>
	<dict>
		<key>NSExtensionPointIdentifier</key>
		<string>com.apple.usernotifications.service</string>
		<key>NSExtensionPrincipalClass</key>
		<string>NotificationService</string>
	</dict>
</dict>
</plist>
```

Am I missing something?

**Comment by risingphoenixin** [comment]
<img width="1211" alt="Screenshot 2023-10-23 at 11 44 27 AM" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/145992962/09498ced-8d4f-401b-84f0-e98885703030">

I don't see the version and build number in the latest Xcode. I opened through the workspace file, but I still cannot.

**Comment by emawby** [comment]
@risingphoenixin it looks like you are not on the info tab in that screenshot.
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen
