### ISSUE TITLE
postNotificationWithJson  Authorization: Basic not working

### ISSUE THREAD

**Issue by bugrevealingbme** [OneSignal/OneSignal-Flutter-SDK#498]
My Code: 
  var response = await OneSignal.shared.postNotificationWithJson(
    {

      "Authorization": "Basic x",
      "include_external_user_ids": ['ac51e474-46d2-4ee0-93df-6f791ed120bc'],
      "headings": {
        "en": 'Update available!',
      },
      "contents": {
        "en": "$version released for your device!",
      },
    },
  );

I have:

W/OneSignal(31469): OneSignalRestClient: POST RECEIVED JSON: {"errors":["Please include a case-sensitive header of Authorization: Basic \u003cYOUR-REST-API-KEY-HERE\u003e or Bearer token=\"\u003cYOUR-REST-API-KEY-HERE\u003e\" with a valid REST API key."],"reference":["https://documentation.onesignal.com/docs/accounts-and-keys#section-keys-ids"]}
W/OneSignal(31469): HTTP code: 400 create notification failed
W/OneSignal(31469): {"errors":["Please include a case-sensitive header of Authorization: Basic \u003cYOUR-REST-API-KEY-HERE\u003e or Bearer token=\"\u003cYOUR-REST-API-KEY-HERE\u003e\" with a valid REST API key."],"reference":["https://documentation.onesignal.com/docs/accounts-and-keys#section-keys-ids"]}

**Comment by jkasten2** [comment]
@bugrevealingbme You should not place the OneSignal REST API key in your app as it is used for sending notifications to all users and changing other settings. You can only send notifications with `include_player_id` without the OneSignal REST API key.
