### ISSUE TITLE
Deprecated version of Android embedding

### ISSUE THREAD

**Issue by Princewil** [OneSignal/OneSignal-Flutter-SDK#502]
Pls update your Android embedding. Thanks

**Comment by jkasten2** [comment]
@Princewil Thanks for reporting, could you make sure are using the 3.2.4 version of OneSignal?
We updated to Android v2 embedding in this version. See the release notes:
https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.2.4

If you are still seeing an issue please provide the exact errors and warnings you are seeing.

**Comment by Princewil** [comment]
Thanks alot. Problem solved.
