### ISSUE TITLE
Set external user id at startup

### ISSUE THREAD

**Issue by tainanfochesatto** [OneSignal/OneSignal-Flutter-SDK#504]
Hi guys.

Is there a way to set the external user id at startup? Today I need to call the init method and then I call setExternalUserId. Is it possible to be implemented?

**Comment by jkasten2** [comment]
@tainanfochesatto You can call `setExternalUserId` right after you initialize the OneSignal. You don't need to await for any event, the OneSignal SDK will set the id when the player is created for you.
