### ISSUE TITLE
Library not found fo -lonesignal

### ISSUE THREAD

**Issue by bbofrk** [OneSignal/OneSignal-Flutter-SDK#51]
**Description:**

App fails to build on iOS on actual device, comes up with 

ld: library not found for -lonesignal
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Have tried repo deintegrate, the pod install again.

**Environment**

Follow the instructions in https://documentation.onesignal.com/v5.0/docs/flutter-sdk-setup, but had to do pod repo update before pod install, otherwise errors saying cannot find the package or something like that.

in pubspec.yaml.
onesignal: ^1.0.5 

Flutter Doctor: 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-NZ)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.30.2)
[!] Connected device
    ! No devices available

pod version: 1.5.3

**Steps to Reproduce Issue:**

exactly as the set-up 
1. Generate an iOS Push Certificate
2. install dependency in pubspec.yml
3. Add Notification Service Extension  and press cancel on the Activate Scheme
4. Change deployment type for OneSignal expansion target to 10.0 (have tried changing the Runner target as well to 10.0)
5 Change pod.file and run "pod repo update" then run "pod install"
6. Change the entire NotificationService.m file. 
7. added  App Group 
8. enable Capabilities

**Anything else:**
Ld /Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension normal arm64
    cd /Users/shareclarity/Developer/flutter_project/shareclarity_app/ios
    export IPHONEOS_DEPLOYMENT_TARGET=10.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/FirebaseCore -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/GTMSessionFetcher -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/GoogleAPIClientForREST -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/GoogleToolboxForMac -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/GoogleUtilities-00567490 -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/Protobuf -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/Stripe -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/device_info -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/flutter_inapp_purchase -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/flutter_webview_plugin -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/nanopb -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/onesignal -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/shared_preferences -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/stripe_widget -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/textdetect_widget -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/voice_recognition -L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/GoogleUtilities-7afea142 -F/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos -F/Users/shareclarity/Developer/flutter_project/shareclarity_app/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/shareclarity/Developer/flutter_project/shareclarity_app/ios/Pods/FirebaseInstanceID/Frameworks -F/Users/shareclarity/Developer/flutter_project/shareclarity_app/ios/Pods/FirebaseMLCommon/Frameworks -F/Users/shareclarity/Developer/flutter_project/shareclarity_app/ios/Pods/FirebaseMLVision/Frameworks -F/Users/shareclarity/Developer/flutter_project/shareclarity_app/ios/Pods/FirebaseMLVisionTextModel/Frameworks -F/Users/shareclarity/Developer/flutter_project/shareclarity_app/ios/Pods/../.symlinks/flutter/ios -F/Users/shareclarity/Developer/flutter_project/shareclarity_app/ios/Pods/GoogleAppMeasurement/Frameworks -F/Users/shareclarity/Developer/flutter_project/shareclarity_app/ios/Pods/GoogleMobileVision/Detector/Frameworks -F/Users/shareclarity/Developer/flutter_project/shareclarity_app/ios/Pods/GoogleMobileVision/TextDetector/Frameworks -F/Users/shareclarity/Developer/flutter_project/shareclarity_app/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework -filelist /Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -miphoneos-version-min=10.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -fapplication-extension -ObjC -lFirebaseCore -lGTMSessionFetcher -lGoogleAPIClientForREST -lGoogleToolboxForMac -lGoogleUtilities-00567490 -lProtobuf -lStripe -lc++ -ldevice_info -lflutter_inapp_purchase -lflutter_webview_plugin -lnanopb -lonesignal -lshared_preferences -lsqlite3 -lstripe_widget -ltextdetect_widget -lvoice_recognition -lz -framework AVFoundation -framework Accelerate -framework AddressBook -framework CoreGraphics -framework CoreImage -framework CoreLocation -framework CoreMedia -framework CoreVideo -framework FIRAnalyticsConnector -framework FirebaseAnalytics -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework FirebaseMLCommon -framework FirebaseMLVision -framework FirebaseMLVisionTextModel -framework Flutter -framework Foundation -framework GoogleAppMeasurement -framework GoogleMobileVision -framework LocalAuthentication -framework OneSignal -framework PassKit -framework Security -framework StoreKit -framework SystemConfiguration -framework TextDetector -framework UIKit -framework UserNotifications -framework WebKit -weak_framework Contacts -ObjC -lGoogleUtilities-7afea142 -lc++ -lnanopb -lsqlite3 -lz -framework GoogleAppMeasurement -framework OneSignal -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -framework UserNotifications -e _NSExtensionMain -lPods-OneSignalNotificationServiceExtension -Xlinker -dependency_info -Xlinker /Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension_dependency_info.dat -o /Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension

ld: warning: directory not found for option '-L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/onesignal'
ld: warning: directory not found for option '-L/Users/shareclarity/Library/Developer/Xcode/DerivedData/Runner-gxfksahdwwgmmofxvzyzhdwilbht/Build/Products/Debug-iphoneos/voice_recognition'
ld: library not found for -lonesignal
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please let me know if there is anything else I can provide or try

Thanks you.

**Comment by bbofrk** [comment]
[Here it is](https://gist.github.com/bbofrk/684671fdf0621e2e9d8caf8af841097b)

**Comment by bbofrk** [comment]
No, the link gives me an error saying that it is not found as it is an old link.

I followed [This link]( https://documentation.onesignal.com/v5.0/docs/flutter-sdk-setup)

**Comment by l-k22** [comment]
@bbofrk  theres a typo in the link @Nightsd01 posted, missing the 'p' in setup hense why it 404s. https://documentation.onesignal.com/docs/flutter-sdk-setu**p**

**Comment by bbofrk** [comment]
Oh okay then yes that is the one I followed. Thanks @l-k22

**Comment by rgomezp** [comment]
@bbofrk are you opening the .xcworkspace file or .xcodeproj?

**Comment by bbofrk** [comment]
I mainly use VS code and the flutter plugin, but have tried .xcworkspace as well.

**Comment by rgomezp** [comment]
@bbofrk Looks like your paths are breaking for some reason. You may have made a mistake when setting up the notification extension service. Can you check the frameworks path in XCode? make sure it contains OneSignal and the path is correct. You can also try to reproduce the issue in a blank project and send it to us so we can gain more visibility into the issue

**Comment by bbofrk** [comment]
@rgomezp it is a company project and I have since moved onto a different project. It is definitely something that we will have to look into again, but since I am not sure of a timeframe to try the suggested, happy for the issue to be close for now and will take another look as soon as permitted.

Thanks guys for your help.
