### ISSUE TITLE
Impossible execute OneSignal on iPhone simulator with Mac M1.

### ISSUE THREAD

**Issue by adfdev** [OneSignal/OneSignal-Flutter-SDK#510]
**Description:**

Impossible execute OneSignal on iPhone simulator with Mac M1.

**Environment**

OneSignal Flutter SDK: 3.2.6 added by PUB

**Steps to Reproduce Issue:**

1. Install the OneSignal Flutter SDK using pub into your project
2. Configure iOS SDK for flutter
3. Run in Ios emulator

**Anything else:**

this is the error on debug console:

```
/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-3.2.6/ios/Classes/OSFlutterCategories.h:28:9: fatal error: 'OneSignal/OneSignal.h' file not found
    #import <OneSignal/OneSignal.h>
```

**Comment by GeceGibi** [comment]
Same here !

**Comment by adfdev** [comment]
> Same here !

Have you try a solution?

**Comment by thenixoncompany** [comment]
this is not a problem only for M1 Mac. i have the same error with Mac Intel. I can run my app with success in the iPhone simulator if i launch the run from xcode but when i lunch the from Android Studio i have the error you speak of:

    /Users/XXXXX/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-3.2.6/ios/Classes/OSFlutterTagsController.m:29:9: fatal error: 'OneSignal/OneSignal.h' file not found
    #import <OneSignal/OneSignal.h>
            ^~~~~~~~~~~~~~~~~~~~~~~

**Comment by chrystoffer** [comment]
same problem.

**Comment by jkasten2** [comment]
Thanks for reporting, this issue only seems to apply to the latest OneSignal-Flutter 3.2.6 version (OneSignal-iOS-SDK 3.9.0) when building for the simulator on M1 macs. We are looking into address this soon, you can use the previous version to work around the issue in the mean time.

**Comment by GeceGibi** [comment]
> > Same here !
> 
> Have you try a solution?

im working with real device for now :)

**Comment by jkasten2** [comment]
This has now been fixed in the [OneSignal-Flutter-SDK 3.2.7 ](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.2.7) release! Thanks to everyone who reported the issue.

**Comment by rokk4** [comment]
@jkasten2 
It is now happening again.
With SDK 3.3.0 .

**Comment by jkasten2** [comment]
@rokk4 Thanks for reporting however there we can confirm all the architectures are present in the 3.3.0 SDK. Was anything else changed in your project recently?

**Comment by itwondersteam** [comment]
we also facing the same issue. Any info needs to fix this?
