### ISSUE TITLE
Notification not show as pop up, just only in status bar in android

### ISSUE THREAD

**Issue by qais-abumwais** [OneSignal/OneSignal-Flutter-SDK#512]
**Description:**

Notification not show as pop up, just only in status bar in android

**Environment**
onesignal_flutter: ^3.2.4
android all devices (real devices and emulators)

**Comment by hugoyair** [comment]
You need to follow those instructions 
https://documentation.onesignal.com/docs/android-notification-categories

**Comment by jkasten2** [comment]
@qais-abumwais Thanks for you question. @hugoyair Is correct, after you setup a notification category / channels with a higher priority and use it on your notifications they will show up as banners at the top of the screen.

**Comment by hugoyair** [comment]
Yeah, I´m sorry for don´t help you so well, I´m learning English, but It´s great that you could fix your problem :)

**Comment by harguus** [comment]
> @qais-abumwais Thanks for you question. @hugoyair Is correct, after you setup a notification category / channels with a higher priority and use it on your notifications they will show up as banners at the top of the screen.

I did as in the link but I'm having the same problem, because the notifications only appear in the status bar as Silent Notifications.

How do I solve this problem.

I'm running on Android 10 and 11.

**Comment by faiz-faizal** [comment]
@harguus hi you need to set category type as urgent

**Comment by kevintruman** [comment]
- create notification channel categories to settings > messaging > android notification channels
- copy channel ID
- if you using rest api, add attribute "android_channel_id": "<channel ID>"

**Comment by darshan-destinysolutions** [comment]
i have same issue. i use firebase notification. anyone have solution?
