### ISSUE TITLE
OneSignal.shared.setNotificationReceivedHandler (not available ^3.2.7)

### ISSUE THREAD

**Issue by ArivhaySoft** [OneSignal/OneSignal-Flutter-SDK#513]
```
V/OneSignal(21428): initWithContext called with: android.app.ReceiverRestrictedContext@39a85aa
V/OneSignal(21428): Starting OneSignal initialization!
V/OneSignal(21428): No class found, not setting up OSRemoteNotificationReceivedHandler
D/OneSignal(21428): OneSignal SDK initialization already completed.

```
I'm using version of onesignal_flutter: ^3.2.7 but for function **setNotificationReceivedHandler** I can't implement, I need this to give first action if any push come in

this is the code i usually use : 
```dart
OneSignal.shared.setNotificationReceivedHandler((OSNotification notification) {
      this.setState(() {
        _debugLabelString = "Received notification: \n${notification.jsonRepresentation().replaceAll("\\n", "\n")}";
        print(_debugLabelString);

      });
    });
```

thanks in advance for the developers

**Comment by jkasten2** [comment]
@ArivhaySoft The `setNotificationReceivedHandler()` was replaced by `setNotificationWillShowInForegroundHandler()`. See the OneSignal Flutter 3.x.x migration guide for more details on this new method.
https://documentation.onesignal.com/docs/flutter-30-api-reference#removed-functions

**Comment by Veloz-X** [comment]
Also, I have the same problem, I can't get data from the foreground notification.
It only allows me to receive data if I open the notification.

**Comment by emawby** [comment]
@Veloz-X Hello can you clarify what you mean by "receive data". Did you register a handler with `setNotificationWillShowInForegroundHandler`?

**Comment by hugoquintalcr** [comment]
There are two methods to use with notifications in one signal 

setNotificationWillShowInForeground is a listener that It´s only used when you are into the app. But if you are outside of the app, you need to use setNotificationOpenedHandler but you need to press to the notification to listen it.

**Comment by emawby** [comment]
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen
