### ISSUE TITLE
Not working on TestFlight

### ISSUE THREAD

**Issue by marcoberetta96** [OneSignal/OneSignal-Flutter-SDK#514]
**Description:**
Cannot receive notifications when app is installed from TestFlight.
Notifications are working fine when application is directly installed.

From Xcode, the signing for release are manually set to 2 different provisioning profiles: one for main application and one for OneSignalNotificationServiceExtension.

**Environment**
- Flutter version 2.5.3
- onesignal_flutter: ^3.2.7

Anyone has suggestions?

**Comment by jkasten2** [comment]
@marcoberetta96 TestFlight is the same as a production environment as far as signing and certificates go.

Are you seeing an issue with the devices registering and subscribing?
  - The All Users page on the OneSignal dashboard will report the reason why the are not subscribed. You may need to re-sync your Apple account in Xcode to get the new capabilities for push if you didn't enable it locally on your machine.

Or are you getting failures sending?
  - Make sure you have uploaded a production .p12 file to OneSignal, a sandbox one won't be able to send to test flight.

**Comment by marcoberetta96** [comment]
I had a sandbox certificate, thanks @jkasten2

**Comment by yarodevuci** [comment]
Having same issue though..

**Comment by yarodevuci** [comment]
@jkasten2 where did you see sandbox cert?

**Comment by abdulrehman192** [comment]
@marcoberetta96 Can you please guide me how you create two separate provisioning profiles with certificates?

**Comment by marcoberetta96** [comment]
> @marcoberetta96 Can you please guide me how you create two separate provisioning profiles with certificates?

I just followed the old OneSignal documentations.

I abandoned the project 2 years ago. Unfortunately I cannot help you anymore...
