### ISSUE TITLE
OneSignal Flutter Plugin version 2.2.0

### ISSUE THREAD

**Issue by greg-tt** [OneSignal/OneSignal-Flutter-SDK#517]
**Description:**
We have built an app with Flutter 1.17.1, and alongside this we're using the OneSignal Flutter plugin version 2.2.0. However, due to the recent shutdown of JCenter & Bintray we can't build the app as it generates the error 'Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/onesignal/OneSignal/maven-metadata.xml'.  

I can confirm we've tried the upgrade steps at: https://github.com/OneSignal/OneSignal-Android-SDK/issues/1293. Unfortunately the steps have not resolved the issues.

Do you have any guidance on a way we can continue with OneSignal Flutter plugin version 2.2.0 please?

**Environment**
1. Android SDK version 30.0.3
2. Used onesignal_flutter v2.2.0  package

**Steps to Reproduce Issue:**
1. Add onesignal_flutter: ^2.2.0 to our flutter apps pubspec.yaml file. 
2. Run flutter

**Comment by jkasten2** [comment]
@greg-tt Thanks for reporting, I think this is the same issue as https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/516. Please follow up there with the same detail if you can.
