### ISSUE TITLE
error: no such module 'OneSignal'

### ISSUE THREAD

**Issue by alectogeek** [OneSignal/OneSignal-Flutter-SDK#521]
**Description:**

I get the following error when try to build for iOS simulator:
`ios/OneSignalNotificationServiceExtension/NotificationService.swift:3:8: error: no such module 'OneSignal'`

I guess it began after upgrading xCode to the 12.3.1 version. It worked ok before the upgrade.

**Environment**

I use 
- onesignal_flutter: ^3.2.7
- flutter stable channel (v2.8.1)
- xCode 12.3.1

**Steps to Reproduce Issue:**

I can't provide exact steps to reproduce as it seemed to work normally just before upgrading the xCode. 

**Anything else:**

I import using `use_frameworks!`:
```
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
end
```

**Comment by emawby** [comment]
@alectogeek Hello what is the target iOS version for your Notification Service Extension and the platform version in your Podfile?

**Comment by alectogeek** [comment]
@emawby Hello!
- target iOS version for your Notification Service Extension is iOS 10.0
- the platform version in Podfile is 10.0 as well

BUT
I fixed the issue literally a few days ago. Probably it was related to building/excluding architectures stuff, didn't get what actually caused the problem yet. It is soooo weird. 

So for everyone who is stuck with the same issue: try to google issues related to M1 chips. There are many suggestions of how to set excluding architectures and it may work (but not sure yet)

**Comment by iAmWillShepherd** [comment]
@alectogeek it looks like you managed to resolve this on your own. I've had some issues with Flutter on my m1 Mac as well. Hopefully, the Flutter dev experience will improve for Apple silicon devices over the next few months for Apple silicon devices. I'll close this issue now since you appear to no longer be blocked ⚡
