### ISSUE TITLE
Build error when integrating OneSignal following the Flutter SDK Setup guide

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignal/OneSignal-Flutter-SDK#525]
## Description
I followed the getting started guide to get up and running with Flutter, but I get the following error when I attempt to run the app on the Android simulator.

I also want to call out [step 6.1](https://documentation.onesignal.com/docs/flutter-sdk-setup#step-6-initialize-the-onesignal-sdk-all-platforms) as being ambiguous: there is no mention of _where_ in the file the code should be (i.e. Line 1, or the end of the file, or somewhere in between).

## Environment
1. Flutter 2.5.3
2. I followed [this](https://documentation.onesignal.com/docs/flutter-sdk-setup#step-2-add-the-onesignal-flutter-sdk) instruction

## Repro steps
1. Follow the [Flutter SDK Setup](https://documentation.onesignal.com/docs/flutter-sdk-setup)
2. Once at step 7, run the app on Android.

###### Shell output when trying to run on Android
```shell
╭─iamwill@zues ~/code/random/onesignal_flutter_sample/ios 
╰─$ flutter run                                                                                                  1 ↵
Changing current working directory to: /Users/iamwill/code/random/onesignal_flutter_sample
Multiple devices found:
sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 12 (API 31) (emulator)
iPhone 13 Pro Max (mobile)  • C4C4AF46-1101-4FF5-B2D9-82655CDB49CA • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
Chrome (web)                • chrome                               • web-javascript • Google Chrome 96.0.4664.55
[1]: sdk gphone64 arm64 (emulator-5554)
[2]: iPhone 13 Pro Max (C4C4AF46-1101-4FF5-B2D9-82655CDB49CA)
[3]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Using hardware rendering with device sdk gphone64 arm64. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
e: /Users/iamwill/.gradle/caches/transforms-2/files-2.1/a849fb59950567c1b835c07de721603e/work-runtime-2.6.0-api.jar!/META-INF/work-runtime_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Running Gradle task 'assembleDebug'...                             14.2s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by emawby** [comment]
I managed to fix this by upgrading the kotlin version in `build.gradle` from 
```
ext.kotlin_version = '1.3.50'
```
to
```
ext.kotlin_version = '1.4.32'
```

**Comment by iAmWillShepherd** [comment]
It appears that [our Gradle plugin](https://documentation.onesignal.com/docs/flutter-sdk-setup#step-5-set-up-onesignal-for-android) may be the culprit here. The comment above does work to unblock this issue, but we should fix our plugin to work with the default Kotlin version that `flutter create` defaults to.

**Comment by Not-Dhanraj** [comment]
> I managed to fix this by upgrading the kotlin version in `build.gradle` from
> 
> ```
> ext.kotlin_version = '1.3.50'
> ```
> 
> to
> 
> ```
> ext.kotlin_version = '1.4.32'
> ```

I am currently using kotlin version- 1.6.10 but i am still getting same error.

**Comment by westy92** [comment]
Here's a related issue filed on the plugin repo: https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/184

**Comment by emawby** [comment]
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen
