### ISSUE TITLE
License type MIT not recognise

### ISSUE THREAD

**Issue by daviddgl** [OneSignal/OneSignal-Flutter-SDK#526]
**Description:**

We're using a 3rd party software, https://licensebat.com/,  to check the licenses of the libraries we use. This service reads the License files to make sure we use libraries that we allow to use because of its license. The issue with your package is that your license should have some issues as it's not recognized.

You can see it also on the flutter pub page, it says `unknown` where it should say 'MIT'.
https://pub.dev/packages/onesignal_flutter/license

<img width="1180" alt="Screenshot 2022-01-12 at 09 53 15" src="https://user-images.githubusercontent.com/11072221/149095167-6bb223ae-7abf-41dc-9c64-6d88277f1bec.png">

Are you able to fix the license?
Thanks.

**Comment by iAmWillShepherd** [comment]
> Are you able to fix the license?

I'm sure we can. Please give me some time to discuss with the team what the license should be, and I'll see if I can get this addressed quickly.

**Comment by iAmWillShepherd** [comment]
@daviddgl 

Just following up. We do use a modified MIT license ([license](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/LICENSE)). My assumption for why it's listed as unknown on https://pub.dev  is that our license is written as if it were a multi-line comment and the site you refer to must be doing basic pattern matching to figure out the license.

**Comment by robertohuertasm** [comment]
@daviddgl I've updated the spdx cache from https://github.com/spdx/license-list-data in the latest `licensebat` image. That should do the trick. It detects the license as MIT.

**Comment by daviddgl** [comment]
> @daviddgl I've updated the spdx cache from https://github.com/spdx/license-list-data in the latest `licensebat` image. That should do the trick. It detects the license as MIT.

Thanks Roberto, working now.
