### ISSUE TITLE
Remove jcenter references from gradle build

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignal/OneSignal-Flutter-SDK#528]
@Davete0302 Yes as a work around for now you should be able to replace `jcenter()` with `mavenCentral()` in all your `build.gradle` files. Almost all libraries hosted on jcenter are also on Maven Central. OneSignal will be making an update to remove all `jcenter()` references soon as well.

_Originally posted by @jkasten2 in https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/516#issuecomment-994106098_

**Comment by iAmWillShepherd** [comment]
@jkasten2 I created this issue to track the work you alluded to in #516. People are still running into this issue, with the last report occurring a little over a week ago. If the fix is low effort, I may be able to do it, but I'd be lying if I claimed to have any familiarity with the Java ecosystem of tools.

**Comment by achalkias** [comment]
Replacing jcenter() with mavenCentral() does not fix this
still getting the same error 

Could not GET 'https://google.bintray.com/exoplayer/androidx/cardview/cardview/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
Disable Gradle 'offline mode' and sync project

**Comment by jkasten2** [comment]
This is now fixed and is part of the [OneSignal-Flutter-SDK 3.2.8 Release](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.2.8).
