### ISSUE TITLE
OneSignal Gradle plugin causes build to fail

### ISSUE THREAD

**Issue by iAmWillShepherd** [OneSignal/OneSignal-Flutter-SDK#529]
It appears that [our Gradle plugin](https://documentation.onesignal.com/docs/flutter-sdk-setup#step-5-set-up-onesignal-for-android) may be the culprit here. The comment above does work to unblock this issue, but we should fix our plugin to work with the default Kotlin version that `flutter create` defaults to.

_Originally posted by @iAmWillShepherd in https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/525#issuecomment-1013487532_

**Comment by westy92** [comment]
Here's a related issue filed on the plugin repo: https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/184

**Comment by westy92** [comment]
@iAmWillShepherd should the priority be High instead of Medium? Flutter 2.10 apps cannot build or run at all.

**Comment by iAmWillShepherd** [comment]
> @iAmWillShepherd should the priority be High instead of Medium? Flutter 2.10 apps cannot build or run at all.

I think so, but prioritization isn't actually on me. The SDK owns these repos, so they decide how things should be prioritized. I added the priority label before I knew this, but I forgot to take it off.

**Comment by adityarath302** [comment]
When will this be solved?
Anyone having any breakthroughs?

**Comment by dgilperez** [comment]
Another team impacted here - any known workaround? Is "Medium prio" a reasonable label since this should apparently impact all users with latest platform versions?

**Comment by docfaii** [comment]
https://flutterhq.com/questions-and-answers/1335/flutter-cannot-run-projectafterevaluateclosure-when-the-project-is-already-evaluated

Does this solve this issue ?

**Comment by emawby** [comment]
The gradle plugin is no longer used in the flutter sdk
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen
