### ISSUE TITLE
MacOS / Windows support?

### ISSUE THREAD

**Issue by albert0m** [OneSignal/OneSignal-Flutter-SDK#530]
Just wondering if macos and windows are going to be supported by this plugin, I see that you can do it natively, but the flutter plugin is for macos/android only.
Thank you!

**Comment by jkasten2** [comment]
@albert0m This SDK only works for apps that target iOS and Android currently.
However due note that new macs with [Arm chips (M1) do support running iOS apps](https://developer.apple.com/documentation/apple-silicon/running-your-ios-apps-on-macos) if you enable this when submitting your app to the App Store. Also Intel macs do support  iOS apps if you target [Mac Catalyst](https://developer.apple.com/mac-catalyst/).
Also note [Windows 11](https://blogs.windows.com/windows-insider/2021/10/20/introducing-android-apps-on-windows-11-to-windows-insiders/) will soon allow running Android apps directly in Windows.

As far as native builds for macOS and Windows goes, there isn't a near term plan for this SDK. OneSignal's does support sending notifications to macOS and Windows apps, but does require you to write native code with their APIs and OneSignal's REST API as well:
* https://documentation.onesignal.com/docs/macos-app-sdk-setup
* https://documentation.onesignal.com/docs/windows-app-sdk-setup

**Comment by Toolenaar** [comment]
Any plans to add this in the near future?
