### ISSUE TITLE
how to prevent getting notifications when my app detached

### ISSUE THREAD

**Issue by X-SLAYER** [OneSignal/OneSignal-Flutter-SDK#536]
**Description:**
whenever my app is detached I keep receiving notifications so I'm looking for a way to stop getting notifications whenever the app is completely closed

**Environment**

1.  onesignal latest version ^3.2.8
2. run on an android real device

**Comment by jkasten2** [comment]
@X-SLAYER Thanks for you question. By "detached" do you mean closed?

Push notifications are useful to reach your users while they are not using your app to notify them of information. Could you let us know the use case for disabling push notification every time they leave your app?

However if you do want to disable OneSignal push notifications for your app you can call [`disablePush`](https://documentation.onesignal.com/docs/sdk-reference#disablepush-method) to do so.

**Comment by X-SLAYER** [comment]
@jkasten2 thanks for ur response yes i meant by detached closing 
i know it's useful to get notifications while ur app is closed but the client don't want it

**Comment by emawby** [comment]
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen
