### ISSUE TITLE
setNotificationWillShowInForegroundHandler not triggered in Huawei

### ISSUE THREAD

**Issue by Lawati97** [OneSignal/OneSignal-Flutter-SDK#537]
**Description:**

I have tried using OneSignal in all devices and it worked perfectly except for Huawei, in Huawei I would receive a notification but this function setNotificationWillShowInForegroundHandler is never triggered not sure why!

**Environment**
Using Flutter 2.8.0
One Signal ^3.2.8

**Comment by hugoquintalcr** [comment]
Have you configured huawei hms into one signal website?

**Comment by hugoquintalcr** [comment]
Remember, some huawei devices don´t support firebase (GMS) so, yo need to use HMS and configure some things.

**Comment by Lawati97** [comment]
@hugoquintalcr everything was done there is a bug in the package managed to solve it

**Comment by hugoquintalcr** [comment]
Great !!!!, I thought It was a problem with configurations, I just trying to help when someone has a problem :)

**Comment by Lawati97** [comment]
@hugoquintalcr thank you though!

**Comment by ChoyCheeWei** [comment]
@Lawati97  @hugoquintalcr any updates on this?
