### ISSUE TITLE
sendTags: PlatformException(OneSignal, Encountered an error updating tags (-1): Unable to update tags: the current user is not registered with OneSignal, null, null)

### ISSUE THREAD

**Issue by OHeroJ** [OneSignal/OneSignal-Flutter-SDK#538]
PlatformException(OneSignal, Encountered an error updating tags (-1): Unable to update tags: the current user is not registered with OneSignal, null, null)

**Comment by nan-li** [comment]
Hi @OHeroJ,

This error comes from there being a `null` `userId` in the `sendTags` request. It could be the device player hasn't finished being created yet. 

Can you share your OneSignal setup code and where you are making this `sendTags` call? Or any other information for us to look at?

**Comment by nan-li** [comment]
Closing due to no response.
