### ISSUE TITLE
Error on iOS plugin

### ISSUE THREAD

**Issue by Luizdre** [OneSignal/OneSignal-Flutter-SDK#544]
Hi, good night, I'm trying to use flutter one signal package and I get this error:

WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead

I was using the package as  2 months ago and don't haved any problem, someone can help, please?

**Comment by jkasten2** [comment]
@Luizdre Thanks for reporting, however there is a duplicate issue already create for this:
https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/68

In summary you can most likely ignore the warning, it would only be an issue if you directly using `application:didReceiveLocalNotification:` in your code or your are using an old plugin that hasn't setup `UNUserNotificationCenter` at all.
