### ISSUE TITLE
How to prevent from opening link on browser

### ISSUE THREAD

**Issue by kodol73** [OneSignal/OneSignal-Flutter-SDK#546]
Hi,

We currently use webview as well as oneSignal, so we want to open the link on webview when press the oneSignal notification.
However it automatically opens the link on webbrowser.

I know how to open it on webview using launchUrl in OneSignal.shared.setNotificationOpenedHandler(),
but oneSignal still automatically opens webbrowser as well.

How can we prevent oneSignal from automatically opening the link on webbrowser?

The version of onesignal_flutter is 3.3.0

We currently tests on Android.

Thanks in advance

**Comment by jkasten2** [comment]
@kodol73 Check out the OneSignal docs on [URLs, Links and Deep Links](https://documentation.onesignal.com/docs/links), there are options to disable this behavior. If the doc isn't clear let us know.

**Comment by kodol73** [comment]
> URLs, Links and Deep Links

> @kodol73 Check out the OneSignal docs on [URLs, Links and Deep Links](https://documentation.onesignal.com/docs/links), there are options to disable this behavior. If the doc isn't clear let us know.


It works ok on Android, Thanks
