### ISSUE TITLE
Not receiving background notifications on Android

### ISSUE THREAD

**Issue by dovahkiin98** [OneSignal/OneSignal-Flutter-SDK#549]
I'm using the latest version of OneSignal for flutter (3.3.0).

As far as I know, OneSignal uses Firebase to send notifications to mobile, but for some reason, it only works while the app is in the foreground?

If you close the app then swipe it, or force close it, you never receive a notification. I even tried implementing the NotificationExtender, still nothing.

In Firebase, the notification is supposed to be handled by the system, but OneSignal doesn't seem to handle background notifications when the app is terminated.

Any solution to that?

**Comment by jkasten2** [comment]
@dovahkiin98 Thanks for reporting, you do not need to setup the OneSignal NotificationServiceExtension in order for notifications to display.

How are you "force closing" the app?

Could you capture the full logcat from the device when you send a notification? (Do not filter, make sure it show verbose as well, and not limited to your app so it shows system entries)

Could you share the Android versions and device models you have tested this scenario on?

**Comment by dovahkiin98** [comment]
@jkasten2 Either with the Android's "Force Close" in the settings, or simply just swiping the application in the Recent Apps

**Comment by nawzhin95** [comment]
still have same error .....

**Comment by davetebonfire0302** [comment]
Same still have the issue

**Comment by apoorvpandey0** [comment]
same issue

**Comment by jkasten2** [comment]
Please share the device model and Android version that is having this specific issue so we can look into it.

**Comment by Davete0302** [comment]
Happening on all android device model and android version

> Please share the device model and Android version that is having this specific issue so we can look into it.

**Comment by MingSern** [comment]
It works previously, now seems like not working again for some reason

**Comment by jennantilla** [comment]
Hello everyone! Apologies this issue has gone stale. If anyone is still having issues with receiving background notifications on the [latest SDK version](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5), please open a new issue and provide the [full log](https://documentation.onesignal.com/docs/capturing-a-debug-log) from the device reproducing the issue.

Note that our latest SDK is a major release bump and includes breaking changes. Please see our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details. 

Thanks!
