### ISSUE TITLE
Multiple commands produce

### ISSUE THREAD

**Issue by FoloosiApps** [OneSignal/OneSignal-Flutter-SDK#551]
**Issue:**

Multiple commands produce '/Users/admin/Library/Developer/Xcode/DerivedData/Runner-dpyjwukbvwjjmfhhlbogqotonlpd/Build/Products/Debug-iphoneos/Runner.app/Frameworks/OneSignal.framework'

How can i fix this issue?

**Note:**

My XCode Version 13.3.1

**Comment by jkasten2** [comment]
@FoloosiApps Closing due to no response.

If the above does not help please add the full contains of your `Podfile` and confirm you are only using Cocoapods and not SwiftPM.

**Comment by ImranKaagga** [comment]
Any update on this ?
Facing same issue multiple commands at 4 places.
Any help ?

Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignal.framework'

Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalCore/OneSignalCore.framework'

Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalExtension/OneSignalExtension.framework'

Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalOutcomes/OneSignalOutcomes.framework'

**Comment by nan-li** [comment]
Hi @ImranKaagga,

Did you try the [suggestion above](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/551#issuecomment-1122720017)?  

> If you add Onesignal via "Pod" & "Swift package", please remove one for consistency.
I solved this issue by removing "pod onesignal" that made the multiple commands issue.
hope this help the issue.

If the above does not help please add the full contains of your `Podfile` and confirm you are only using Cocoapods and not SwiftPM.

**Comment by novgunawan** [comment]
hi there, i had the same issue and i had made sure that i add onesignal only using cocoapods. 

Here's my Podfile : 

`# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  # use_modular_headers!
  pod 'GoogleUtilities'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'SatwakuIDNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
   end
end`

**Comment by DanMossa** [comment]
> If you add Onesignal via "Pod" & "Swift package", please remove one for consistency. I solved this issue by removing "pod onesignal" that made the multiple commands issue. hope this help the issue.

How would I actually go about doing this?
I also get this error.

**Comment by rezvalari** [comment]
> Any update on this ? Facing same issue multiple commands at 4 places. Any help ?
> 
> Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignal.framework'
> 
> Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalCore/OneSignalCore.framework'
> 
> Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalExtension/OneSignalExtension.framework'
> 
> Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalOutcomes/OneSignalOutcomes.framework'

I'm using React Native but I am also getting this issue.

**Comment by rezvalari** [comment]
> > Any update on this ? Facing same issue multiple commands at 4 places. Any help ?
> > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignal.framework'
> > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalCore/OneSignalCore.framework'
> > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalExtension/OneSignalExtension.framework'
> > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalOutcomes/OneSignalOutcomes.framework'
> 
> I'm using React Native but I am also getting this issue.

I was able to solve this by using
`use_frameworks! :linkage => :static` instead of `use_frameworks` inside the notification target
```
target 'OneSignalNotificationServiceExtension' do
  use_frameworks! :linkage => :static
  pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
end

**Comment by ridvanaltun** [comment]
> > > Any update on this ? Facing same issue multiple commands at 4 places. Any help ?
> > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignal.framework'
> > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalCore/OneSignalCore.framework'
> > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalExtension/OneSignalExtension.framework'
> > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalOutcomes/OneSignalOutcomes.framework'
> > 
> > 
> > I'm using React Native but I am also getting this issue.
> 
> I was able to solve this by using `use_frameworks! :linkage => :static` instead of `use_frameworks` inside the notification target
> 
> ```
> target 'OneSignalNotificationServiceExtension' do
>   use_frameworks! :linkage => :static
>   pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
> end
> ```

Works like a charm! Thanks!

**Comment by Chirag-kalsariya** [comment]
> > > Any update on this ? Facing same issue multiple commands at 4 places. Any help ?
> > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignal.framework'
> > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalCore/OneSignalCore.framework'
> > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalExtension/OneSignalExtension.framework'
> > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalOutcomes/OneSignalOutcomes.framework'
> > 
> > 
> > I'm using React Native but I am also getting this issue.
> 
> I was able to solve this by using `use_frameworks! :linkage => :static` instead of `use_frameworks` inside the notification target
> 
> ```
> target 'OneSignalNotificationServiceExtension' do
>   use_frameworks! :linkage => :static
>   pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
> end
> ```

This does not work for me. any other solution?

**Comment by Sega-Zero** [comment]
Fixed this by specifying differend pods in app and extension, like this
```ruby
target 'App' do
  use_frameworks! 
  pod 'OneSignal', '>= 3.0', '< 4.0'
end
target 'OneSignalNotificationServiceExtension' do
  use_frameworks! :linkage => :static
  pod 'OneSignalXCFramework/OneSignalExtension', '>= 3.4.3', '< 4.0'
end
```

**Comment by Chirag-kalsariya** [comment]
For this error, I follow these steps
step-1: remove ^ in pubspec.yaml
```
  # PUSH NOTIFICATION
  onesignal_flutter: 3.4.1

```

step-2: open Xcode in making this change
```
Open Targets -> Runner -> General -> Frameworks, Libraries, and Embedded Content
// Only Add This One, Remove all other Onesignals Names
Name: OnesignalNotificationServiceExtension.appex 
Embed: Embed Without Signing
```

step-3: Open podefile 
```
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
end
```

step-4: use this commands
```
flutter clean
flutter pub get
```

step-5: delete Pods folder and Podfile.lock on ios folder and use this commands
```
cd ios/
pod install
```

All these step works for me

**Comment by moneer-muntazah** [comment]
I'm having the same issue it appears that it started happening after upgrading to 3.5 but now even downgrading doesn't help so frustrated

**Comment by Brechard** [comment]
I am having the same issue, I just got a MacBook, pulled the repo that is working correctly on my college's M1 Mac (I have M2 but should not have a difference) and I get the error:

Error (Xcode): Multiple commands produce
'/Users/brechard/dev/flutter/front-end-mobile-app/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/OneSignalOutcomes.framework'


Error (Xcode): Multiple commands produce
'/Users/brechard/dev/flutter/front-end-mobile-app/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/OneSignalCore.framework'

the Podfile looks like this:

```
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

I have tried as suggested above but it is still not working. 

I am using COCOAPODS: 1.12.0 and one onesignal_flutter: ^3.5.0

The only place I have found a duplication of OneSignalCore.xcframework and OneSignalOutcomes.xcframework  is in the file project.pbxproj in the section:

```
/* Begin PBXBuildFile section */
		1498D2341E8E89220040F4C2 /* GeneratedPluginRegistrant.m in Sources */ = {isa = PBXBuildFile; fileRef = 1498D2331E8E89220040F4C2 /* GeneratedPluginRegistrant.m */; };
		3B3967161E833CAA004F5970 /* AppFrameworkInfo.plist in Resources */ = {isa = PBXBuildFile; fileRef = 3B3967151E833CAA004F5970 /* AppFrameworkInfo.plist */; };
		74858FAF1ED2DC5600515810 /* AppDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = 74858FAE1ED2DC5600515810 /* AppDelegate.swift */; };
		8C7A907B6F7F6D2D5026B139 /* GoogleService-Info.plist in Resources */ = {isa = PBXBuildFile; fileRef = 83EB99D0D807307C9093F506 /* GoogleService-Info.plist */; };
		9544155A2976DF8C0000776D /* OneSignalOutcomes.xcframework in Frameworks */ = {isa = PBXBuildFile; fileRef = 954415592976DF8C0000776D /* OneSignalOutcomes.xcframework */; };
		9544155B2976DF8C0000776D /* OneSignalOutcomes.xcframework in Embed Frameworks */ = {isa = PBXBuildFile; fileRef = 954415592976DF8C0000776D /* OneSignalOutcomes.xcframework */; settings = {ATTRIBUTES = (CodeSignOnCopy, RemoveHeadersOnCopy, ); }; };
		9544155E2976DF9C0000776D /* OneSignalCore.xcframework in Frameworks */ = {isa = PBXBuildFile; fileRef = 9544155D2976DF9C0000776D /* OneSignalCore.xcframework */; };
		9544155F2976DF9C0000776D /* OneSignalCore.xcframework in Embed Frameworks */ = {isa = PBXBuildFile; fileRef = 9544155D2976DF9C0000776D /* OneSignalCore.xcframework */; settings = {ATTRIBUTES = (CodeSignOnCopy, RemoveHeadersOnCopy, ); }; };
		95C6B5BD2972CCB800098EB1 /* NotificationService.m in Sources */ = {isa = PBXBuildFile; fileRef = 95C6B5BC2972CCB800098EB1 /* NotificationService.m */; };
		95C6B5C12972CCB800098EB1 /* OneSignalNotificationServiceExtension.appex in Embed Foundation Extensions */ = {isa = PBXBuildFile; fileRef = 95C6B5B92972CCB800098EB1 /* OneSignalNotificationServiceExtension.appex */; settings = {ATTRIBUTES = (RemoveHeadersOnCopy, ); }; };
		97C146FC1CF9000F007C117D /* Main.storyboard in Resources */ = {isa = PBXBuildFile; fileRef = 97C146FA1CF9000F007C117D /* Main.storyboard */; };
		97C146FE1CF9000F007C117D /* Assets.xcassets in Resources */ = {isa = PBXBuildFile; fileRef = 97C146FD1CF9000F007C117D /* Assets.xcassets */; };
		97C147011CF9000F007C117D /* LaunchScreen.storyboard in Resources */ = {isa = PBXBuildFile; fileRef = 97C146FF1CF9000F007C117D /* LaunchScreen.storyboard */; };
		DB951E8DE7A8FAE53AE6B77F /* Pods_OneSignalNotificationServiceExtension.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 63806D98F93A2B561549810D /* Pods_OneSignalNotificationServiceExtension.framework */; };
		E5AEC3BFC89334C561C42F14 /* Pods_Runner.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = E80EF9DB7634D149E8AA1F11 /* Pods_Runner.framework */; };
```

where If I remove the lines:
- OneSignalCore.xcframework in Embed Frameworks
- OneSignalOutcomes.xcframework in Embed Frameworks

then the app runs but the notifications are not received in the emulator
and I remove the lines :
- OneSignalCore.xcframework in Frameworks
- OneSignalOutcomes.xcframework in Frameworks

I keep getting the same error messages

**Comment by Chirag-kalsariya** [comment]
Don't remove anything make onesignal_flutter: 3.4.1 in pubspec.yaml, and reinstall the pod for that refer step-4 and 5 (https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/551#issuecomment-1351728448)

**Comment by milan-ciganovic** [comment]
In my case this fixed it, i had **OneSignalOutComes.xcframework** and **OneSignalCore.xcframework** in my Runner.app located in Frameworks and Libraries.
I just removed it from the main Runner.app and added all 3 to the **OneSignalNotificationServiceExtension** target.

<img width="555" alt="Screenshot 2023-03-24 at 10 46 20" src="https://user-images.githubusercontent.com/79977833/227485452-02f9c676-8a94-42c6-bfbb-0b22f4af4af6.png">

**Comment by FoundersApproach** [comment]
Hello,

I faced Multiple Commands produce issue in my react native app. I upgraded xcode from 13 to 14 and start facing this error.

Above solution helps and guided me to fix the issue. So thank you!

Below is the solution are applied: 

Choose your target > Build Phase > [CP] Embed Pods Framework > Output files.
REMOVE > OneSignalCore.framework
REMOVE > OneSignalOutComes.framework

<img width="901" alt="Screenshot 2023-04-07 at 9 28 20 PM" src="https://user-images.githubusercontent.com/35708450/230641006-ecfbc2ae-44e3-4861-ac21-afe5b1ff2f56.png">

Also make sure to add those library to "Framework, Libraries, and Embedded Content"
<img width="859" alt="Screenshot 2023-04-07 at 9 40 18 PM" src="https://user-images.githubusercontent.com/35708450/230641414-2def13ab-3235-484e-9807-cd3e183c7af7.png">

Hope this save your time! Thank you.

**Comment by RaoSaqib7860** [comment]
a version of the OneSignal and the target version of the project should be the same.

**Comment by RaoSaqib7860** [comment]
<img width="814" alt="Screenshot 2023-04-10 at 12 56 53 AM" src="https://user-images.githubusercontent.com/69755012/230793997-7f255ff5-898f-48a3-9eda-c594de72d534.png">
![Uploading Screenshot 2023-04-10 at 12.59.56 AM.png…]()

**Comment by RaoSaqib7860** [comment]
Version of one signal and the target version should be same

**Comment by RaoSaqib7860** [comment]
<img width="814" alt="Screenshot 2023-04-10 at 12 59 56 AM" src="https://user-images.githubusercontent.com/69755012/230794070-315ab9d9-efc8-43c6-8cfe-6cd0d54f9f5d.png">

**Comment by RaoSaqib7860** [comment]
<img width="814" alt="Screenshot 2023-04-10 at 12 56 53 AM" src="https://user-images.githubusercontent.com/69755012/230794079-fad0e584-15a7-45c9-86b3-a5ffded3149e.png">

**Comment by RaoSaqib7860** [comment]
<img width="814" alt="Screenshot 2023-04-10 at 12 56 53 AM" src="https://user-images.githubusercontent.com/69755012/230794142-a7c1d7f7-f702-4a52-ab8a-18d35aa2c5b3.png">

**Comment by christofkost** [comment]
Hey everybody!
I can fix this issue by deleting OneSignalOutcomes and OneSignalCore:
![image](https://user-images.githubusercontent.com/62931248/231725740-c8a3ae71-88eb-49bd-959a-3c638802e492.png)
Now the build passes, but app immediately crashes when being started due to this issue: https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/608

Now I am in some kind of deadlock. Having the needed framework inside project results in "Multiple Commands"-error, having them not results in crash on app startup. I am sad and desperate :( Does anybody know a solution?

**Comment by Brechard** [comment]
I think I finally found out when this is happening. It is when you update CocoaPods to version 1.12.0. My colleague's laptop was using 1.11.3 and was not having all these issues but I had. He just updated his CocoaPods to 1.12.0 and this error happened to him. Doing these changes on his laptop and mine made it work again. 

Thanks a lot for your help!

> For this error, I follow these steps step-1: remove ^ in pubspec.yaml
> 
> ```
>   # PUSH NOTIFICATION
>   onesignal_flutter: 3.4.1
> ```
> 
> step-2: open Xcode in making this change
> 
> ```
> Open Targets -> Runner -> General -> Frameworks, Libraries, and Embedded Content
> // Only Add This One, Remove all other Onesignals Names
> Name: OnesignalNotificationServiceExtension.appex 
> Embed: Embed Without Signing
> ```
> 
> step-3: Open podefile
> 
> ```
> target 'OneSignalNotificationServiceExtension' do
>   use_frameworks!
>   pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
> end
> ```
> 
> step-4: use this commands
> 
> ```
> flutter clean
> flutter pub get
> ```
> 
> step-5: delete Pods folder and Podfile.lock on ios folder and use this commands
> 
> ```
> cd ios/
> pod install
> ```
> 
> All these step works for me

**Comment by hasanozkaynak26** [comment]
> I think I finally found out when this is happening. It is when you update CocoaPods to version 1.12.0. My colleague's laptop was using 1.11.3 and was not having all these issues but I had. He just updated his CocoaPods to 1.12.0 and this error happened to him. Doing these changes on his laptop and mine made it work again.
> 
> Thanks a lot for your help!
> 
> > For this error, I follow these steps step-1: remove ^ in pubspec.yaml
> > ```
> >   # PUSH NOTIFICATION
> >   onesignal_flutter: 3.4.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > step-2: open Xcode in making this change
> > ```
> > Open Targets -> Runner -> General -> Frameworks, Libraries, and Embedded Content
> > // Only Add This One, Remove all other Onesignals Names
> > Name: OnesignalNotificationServiceExtension.appex 
> > Embed: Embed Without Signing
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > step-3: Open podefile
> > ```
> > target 'OneSignalNotificationServiceExtension' do
> >   use_frameworks!
> >   pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > step-4: use this commands
> > ```
> > flutter clean
> > flutter pub get
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > step-5: delete Pods folder and Podfile.lock on ios folder and use this commands
> > ```
> > cd ios/
> > pod install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > All these step works for me

this solution worked for me. Thank you !

**Comment by emawby** [comment]
Closing issue as stale. If this is still happening in 2024 feel free to tag me to reopen

**Comment by VeArnold** [comment]
@emawby haha literally having this issue as of now :)

**Comment by josancamon19** [comment]
Same @emawby

**Comment by mdmohsin7** [comment]
I too had this issue today, after a lot of messing around, I finally fixed it by doing the following changes:

1. In Targets -> OneSignalNotificationServiceExtension -> General -> Frameworks and Libraries, remove the existing `pod_OneSignalNotificationServiceExtension.framework` and add the following
```
OneSignalCore.xcframework
OneSignalExtension.xcframework
OneSignalOSCore.xcframework
OneSignalOutcomes.xcframework
```
This is how your `Frameworks and Libraries` section should look after the above changes
<img width="681" alt="Screenshot 2024-06-23 at 12 35 10 AM" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/59914433/1be24021-8b67-4d19-b1c0-28c1c3167835">

2. Now open the `podfile` and remove the following lines which were added while following the docs
```
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
end
```

3. In pubspec.yaml file, remove `^` before the version name for One Signal:
```
onesignal_flutter: 5.1.2
```

4. Run `flutter clean && flutter pub get` and then move to the iOS directory and run `pod update`

**Comment by supermnemonic** [comment]
iam using xcode 15.4. this works for me.

1. flutter clean
2. remove file ios/podfile.lock
3. remove folder ios/Pods
4. flutter pub get
5. check build phase order. make sure "Embed Foundation Extensions" order is as follow. 
![Screenshot 2024-08-13 at 16 27 30](https://github.com/user-attachments/assets/c755c15a-9fa5-4bba-8005-bce8313f2995)
6. flutter run

**Comment by Jeadonara** [comment]
> > > > Any update on this ? Facing same issue multiple commands at 4 places. Any help ?
> > > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignal.framework'
> > > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalCore/OneSignalCore.framework'
> > > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalExtension/OneSignalExtension.framework'
> > > > Multiple commands produce '/Users/macbookpro/Library/Developer/Xcode/DerivedData/Runner-guxfrrsooqgfuierbfplcdnromlw/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/OneSignalXCFramework/OneSignalOutcomes/OneSignalOutcomes.framework'
> > > 
> > > 
> > > I'm using React Native but I am also getting this issue.
> > 
> > 
> > I was able to solve this by using `use_frameworks! :linkage => :static` instead of `use_frameworks` inside the notification target
> > ```
> > target 'OneSignalNotificationServiceExtension' do
> >   use_frameworks! :linkage => :static
> >   pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
> > end
> > ```
> 
> Works like a charm! Thanks!

I guess it is the best solution

**Comment by arthurgiani** [comment]
Problem still persists for me

Xcode 15.4
Flutter 3.24
OneSignal 5.2.6

**Comment by arthurgiani** [comment]
> Version of one signal and the target version should be same <img width="814" alt="Screenshot 2023-04-10 at 12 56 53 AM" src="https://user-images.githubusercontent.com/69755012/230794056-1fea17d6-edcc <img alt="Screenshot 2023-04-10 at 12 59 56 AM" width="814" src="https://user-images.githubusercontent.com/69755012/230794059-18a8c779-da8b-4430-ae50-c7b15a6efc12.png"> -4158-81ed-2a74212f6707.png">

This worked for me
Xcode 15.4
Flutter 3.24

**Comment by RootSoft** [comment]
I confirm, updating your iOS deployment target in `Info.plist` and Project & Targets Runners to 15.0 fixed this issue for me.

After that I got a cycle error which was resolved as stated in the documentation:

> You may see this error when building with Xcode 15 or higher, which is caused by a Xcode 15+ default configuration change > affecting cross platform systems.
> 
> Error: Cycle inside SampleProject; building could produce unreliable results.
> 
> In your project, open your XCWorkspace folder in Xcode and open the project directory in the left sidebar.
> Select your app target and navigate to the "Build Phases" tab. You should have a phase called "Embed App Extensions" or "Embed Foundation Extensions". Drag and move this build phase to above "Run Script". Your error should now be resolved.
