### ISSUE TITLE
[Question] Next stable version

### ISSUE THREAD

**Issue by jrb1989** [OneSignal/OneSignal-Flutter-SDK#552]
When will be released the next stable version for flutter with the latest SDK android and iOS updates?

**Comment by jkasten2** [comment]
@jrb1989 Thanks for asking, we should have a release out by next week.

**Comment by Dodalun** [comment]
On sensor Tower there is an iPad that also have the same Apple ID that mine. I use an iPhone 13 pro?

**Comment by jkasten2** [comment]
@jrb1989  [3.3.1 Release](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.3.1) was just released with the latest iOS and Android native libraries updated in them.

**Comment by jrb1989** [comment]
> @jrb1989 [3.3.1 Release](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.3.1) was just released with the latest iOS and Android native libraries updated in them.

Thank you very much for the info, 
great job!!!
