### ISSUE TITLE
[Question] Is there an equivalent to  firebases'  getInitialMessage

### ISSUE THREAD

**Issue by moneer-muntazah** [OneSignal/OneSignal-Flutter-SDK#554]
I noticed that OneSignal uses dynamic linking in push notifications such that clicking on a notification can trigger a dynamic link. I can use this to navigate users to a specific page on my application. Having said that is there a way to check if the application was started by clicking on a push notification and get the additional data? As I rather not use dynamic links in this application for now. For example, in firebase_messaging we have `getInitialMessage` which returns additional data or null.

Thank you

**Comment by jkasten2** [comment]
@moneer-muntazah With OneSignal you only need to call `setNotificationOpenedHandler` to cover both the app starting from a notification (the question you are asking) as well as if the app is already running.

Example:
```dart
OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {
    print('"OneSignal: notification opened: ${result}');
});
```

More documentation:
https://documentation.onesignal.com/docs/sdk-notification-event-handlers#notification-opened-event
