### ISSUE TITLE
Escaped character when setting an external user id on Android

### ISSUE THREAD

**Issue by ipapps** [OneSignal/OneSignal-Flutter-SDK#555]
When setting an external user id starting with the character "$", it is not taken into account in Android but taken into account in iOS.
So, if you set the external id "$toto", the external user id will be "toto" if sent to an Android device.

onesignal_flutter: 3.2.8

Just set an external ID with "$" as first character

OneSignal.shared.setExternalUserId("$something");

**Comment by jkasten2** [comment]
@ipapps Thanks for reporting, we have a fix for this on the OneSignal-Android-SDK side, we will be releasing an update to soon to include this fix. We will come to update this issue once it is released.

**Comment by nan-li** [comment]
Hi @ipapps,

The fix for this was released. From OneSignal-Flutter-SDK [version `3.3.1`](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.3.1), you can use `$` signs in external user IDs.
