### ISSUE TITLE
Mute Specific Channel using OneSignal

### ISSUE THREAD

**Issue by MuhammadAliKust** [OneSignal/OneSignal-Flutter-SDK#560]
**Description:**

Hi, I am using one signal for getting notifications. I have created 3 channels and using channel key to send specific notifications. But now i want that user can mute any of the notification channel so that he will not get notifications of that specific channel. So is there a way to mute specific channel using one signal.

Thanks

**Environment**

1. onesignal_flutter: ^3.3.0
2. Added by using pub.dev

**Comment by jkasten2** [comment]
@MuhammadAliKust Do you mean [Android Notification Channels](https://developer.android.com/training/notify-user/channels)? 
While Android's native APIs let you delete channels they don't allow disabling them from code, only the user can toggle them off.

I would recommend using OneSignal's [Tags](https://documentation.onesignal.com/docs/add-user-data-tags) and [Segments](https://documentation.onesignal.com/docs/segmentation) as a solution, this will work for iOS that way. In summary you will want to set a custom tag if the user wants specific types of notifications, and then when sending ensure you create a Segment with filters on those tags.
