### ISSUE TITLE
Notifications not working when application terminate

### ISSUE THREAD

**Issue by nawzhin95** [OneSignal/OneSignal-Flutter-SDK#561]
Hello Guys 
i ma implement flutter OneSignal for my project.. .

everything work fine but when I closes the app (terminate state) notifications will not show  

there is any solution for this ? 

additional information 
  onesignal_flutter: ^3.3.1

Flutter doctor 

[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.67.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by nawzhin95** [comment]
i am solving it by using workmanager: ^0.5.0 and put the one signal listener to background

**Comment by jkasten2** [comment]
@nawzhin95 Good to hear you got things working! Could you add more details on how you used `workmanager` to solve the issue?

**Comment by wahyu-handayani** [comment]
> i am solving it by using workmanager: ^0.5.0 and put the one signal listener to background

Hi, I get the same case like yours and I open it in https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/587 would you like to take a look
