### ISSUE TITLE
Hi. I have a big problem. Someone used my account to registered an old visa Card of mine, and I think my Apple ID doda.lunde@icloud.com is compromised.

### ISSUE THREAD

**Issue by Dodalun** [OneSignal/OneSignal-Flutter-SDK#562]
Hi. I have a big problem. Someone used my account to registered an old visa Card of mine, and I think my Apple ID doda.lunde@icloud.com is compromised.

__Originally posted by @Dodalun in https://github.com/Dodalun/github-slideshow/issues/2__

**Comment by jmadler** [comment]
You'll need to speak with Apple about this.
