### ISSUE TITLE
@Sergozh Could you provide the error or exact issue you are seeing? Please also share your the full contains of your `Podfile` and `Podfile.lock` files.

### ISSUE THREAD

**Issue by Dodalun** [OneSignal/OneSignal-Flutter-SDK#565]
@Sergozh Could you provide the error or exact issue you are seeing? Please also share your the full contains of your `Podfile` and `Podfile.lock` files.

One suggestion is you may need to move `use_frameworks!` to the main target.

__Originally posted by @jkasten2 in https://github.com/OneSignal/OneSignal-iOS-SDK/issues/1093#issuecomment-1133766649__

**Comment by nan-li** [comment]
This issue is a copy of an existing issue comment at https://github.com/OneSignal/OneSignal-iOS-SDK/issues/1093#issuecomment-1133766649. Closing because this is a duplicate comment and does not add any details.
