### ISSUE TITLE
Removing notifications on iOS

### ISSUE THREAD

**Issue by jozsefsallai** [OneSignal/OneSignal-Flutter-SDK#567]
Hello!

Currently, it is possible to remove individual notifications on Android by calling the `.removeNotification(int)` method and there's also a method called `.clearOneSignalNotifications()` which will remove all app notifications (however this also only works on Android).

A few years ago it was mentioned that there will be a major version which will add this functionality to both the Android and iOS SDKs (https://github.com/OneSignal/OneSignal-iOS-SDK/issues/646#issuecomment-605372734), however, currently I can't seem to find any methods I can use for iOS.

Is this still planned or am I missing something obvious? Searching for `removeDeliveredNotifications` in the iOS SDK doesn't yield any results, which makes me assume this functionality wasn't implemented yet.

Are there any workarounds?

**Comment by jkasten2** [comment]
@jozsefsallai Thanks for digging in, there isn't a method in the current OneSignal SDK to clear notifications on iOS. However this can be worked around by setting the app's badge value to something like 1 then back to 0, iOS has a side effect with this where it will clear all notifications for the app. I don't believe Flutter has a way to set the iOS badge value, however a 3rd party library could be used to do so. As an example [flutter_app_badger](https://pub.dev/packages/flutter_app_badger), but I have not used this to confirm it will work.

**Comment by lifenautjoe** [comment]
Hi @jkasten2 , is there a plan to add it? 

Our users are hyper-annoyed that their push notifications never go away.

**Comment by jennantilla** [comment]
Hello everyone!

Just wanted to share that the ability to clear all notifications on iOS is now supported in our User Model SDKs!

Please upgrade to [our latest release](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) to use the `Notifications.clearAll` method. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details!
