### ISSUE TITLE
Confirmed's statistics are incorrect

### ISSUE THREAD

**Issue by OHeroJ** [OneSignal/OneSignal-Flutter-SDK#575]
![image](https://user-images.githubusercontent.com/12316547/178194892-34ebe62f-ff22-4ae0-8ab4-3784a43637aa.png)

* onesignal_flutter: ^3.3.2

We found that Confirmed's numbers kept slipping over the past few days, and then did some testing and found that Confirmed didn't count.

**Comment by jmadler** [comment]
Thanks for the report!  This question could be related to many components other than our SDK.   Could you please reach out to the OneSignal support team?
