### ISSUE TITLE
应该是这行代码：compilation.assets[asset].source = () => source不生效了

### ISSUE THREAD

**Issue by Dodalun** [OneSignal/OneSignal-Flutter-SDK#579]
应该是这行代码：compilation.assets[asset].source = () => source不生效了

__Originally posted by @liumulin614 in https://github.com/huruji/eruda-webpack-plugin/issues/32__

__Originally posted by @Dodalun in https://github.com/webcompat/web-bugs/issues/107896__

**Comment by nan-li** [comment]
Not relevant
