### ISSUE TITLE
CLLocationManager did fail with error: Error Domain=kCLErrorDomain Code=1 "(null)"

### ISSUE THREAD

**Issue by giovannilattanziocrispy** [OneSignal/OneSignal-Flutter-SDK#583]
**Description:**
We're facing a strange behavior implementing OneSignal on one of the iOS devices we have, specifically an iPhone SE 2020 with iOS 15.5.

When the app starts (and OneSignal is instantiated) sometimes this error shows up:
<img width="375" alt="Image_20220802_101553" src="https://user-images.githubusercontent.com/104901398/182343515-7a81a86a-1176-4ab7-b7a7-0ad3e70004ed.png">

It's not just after the OneSignal initialization (this one is handled in the splashscreen page, while this message occurs in the home page, after a navigation), it's asynchronous.

In the OneSignal initialization, we don't call for the `setLocationShared`, because we don't really need that, but we have other plugins that ask for the position ([geolocator](https://pub.dev/packages/geolocator)), although not in the same spot.

Is it a problem we can handle?
Is it a problem we're able to see only because we have the visual log level set to `OSLogLevel.error`? If we set the visual log level to `OSLogLevel.none` (as it is in our production environment), will it be hidden (but not resolved)?

**Environment**
OneSignal plugin version: **onesignal_flutter: ^3.3.2**
Flutter version: **3.0.5**
Dart version: **">=2.14.0 <3.0.0"**

**Comment by jkasten2** [comment]
@giovannilattanziocrispy Thanks for reporting. You are correct, the alert dialog only shows because you have set the OSLogLevel to error for the visual level.

Can you set the log level for logging (first param) to VERBOSE and attach log here so we can look into the specific error?

**Comment by nan-li** [comment]
Closing due to no response and staleness
