### ISSUE TITLE
WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead

### ISSUE THREAD

**Issue by cpellet** [OneSignal/OneSignal-Flutter-SDK#584]
**Description:**
WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by nan-li** [comment]
Hi @cpellet,

Thanks for reaching out about this warning. It is a warning issued by the OneSignal native iOS SDK due to Flutter and can be safely ignored. At this time we don't have an update on the removal of this warning.

Related to https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/68
