### ISSUE TITLE
Directory not found error

### ISSUE THREAD

**Issue by newbieflutter** [OneSignal/OneSignal-Flutter-SDK#59]
I am trying to follow closing this link https://documentation.onesignal.com/docs/flutter-sdk-setup but I found something weird 

1. I dont find this file when comes to this step 2.9 Reopen the Xcode project. In your project, in the OneSignalNotificationServiceExtension/ folder, open NotificationService.m and replace the whole file contents with:
2. Secondly what should I do for this step 2.6 Open the Xcode project settings and select the OneSignalNotificationServiceExtension target. Unless you have a specific reason not to, you should set the Deployment Target to be iOS 10. I put now to be 12.1
3. I have ensure the pod file is correctly done.
4.I am not too sure to open it via .xcodeproj or xcworkspace
5. Lastly when I try to build I keep getting this error 
ld: warning: directory not found for option '-L/Users/*****/Library/Developer/Xcode/DerivedData/Runner-dnappsqahwvqpegshbehdnrpnher/Build/Products/Debug-iphonesimulator/onesignal'
ld: library not found for -lonesignal
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I tried deleting the pod and podlock and reinstall also the same.

**Comment by Nightsd01** [comment]
@newbieflutter you have to open the `.xcworkspace` generates by Cocoapods. 

Please try going back to the beginning steps in our guide and make sure you are actually added the Notification Service Extension target.

**Comment by newbieflutter** [comment]
@Nightsd01 I have to open .xcworkspace is it? Any reason for it. Beside that could anything else be missing ?

**Comment by rgomezp** [comment]
@newbieflutter open up the workspace file (not the original xcode project file) and verify that the notification service extension was set up correctly. Closing for now but please just let us know if you continue encountering issues. Alternatively, you can download our sample project and use that as a starting point for your app
