### ISSUE TITLE
Notifications not working when application terminate please  share the solution 

### ISSUE THREAD

**Issue by krishnapandya** [OneSignal/OneSignal-Flutter-SDK#597]

**Comment by emawby** [comment]
@krishnapandya Can you clarify what you mean by "not working" Please include more details in this issue so that we are properly able to advise/debug!

**Comment by krishnapandya** [comment]
Hello,
I am using   onesignal_flutter: ^3.2.7 version 



 classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.14.0'

implementation 'com.onesignal:OneSignal:4.8.2'

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);
    await OneSignal.shared.setAppId(Config.ONE_SIGNAL_APP_KEY);

    await OneSignal.shared
        .promptUserForPushNotificationPermission(fallbackToSettings: true);

    OneSignal.shared.setNotificationWillShowInForegroundHandler(
        (OSNotificationReceivedEvent event) {
      setNotificationData(event.notification);
      event.complete(event.notification);
    });

    OneSignal.shared.setNotificationOpenedHandler((openedResult) async {
      setNotificationData(openedResult.notification);

        OneSignal.shared
        .setPermissionObserver((OSPermissionStateChanges changes) {});
    OneSignal.shared.setInAppMessageClickedHandler((action) {});

    OneSignal.shared
        .setSubscriptionObserver((OSSubscriptionStateChanges changes) {});

    OneSignal.shared.setEmailSubscriptionObserver(
        (OSEmailSubscriptionStateChanges emailChanges) {});


I am getting issue when app is terminated or close not getting any notification. and some time in foreground  notification generate after 30 min .please help
