### ISSUE TITLE
Notification Received  when app is terminated but redirection not working properly .When I click on notification open splash screen .How to redirect in particular screen?

### ISSUE THREAD

**Issue by krishnapandya** [OneSignal/OneSignal-Flutter-SDK#600]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by krishnapandya** [comment]
I have code in native to received notification and save action data into preference and access that preference data  from flutter to solve this issue.

**Comment by BenFredjSkander** [comment]
@krishnapandya can you post your solution for Android ?

**Comment by krishnapandya** [comment]
Hello,
 Native Android  I save the action response in preference.

  val sharedPreferences: SharedPreferences =
            getSharedPreferences("FlutterSharedPreferences", Context.MODE_PRIVATE)

 OneSignal.setNotificationOpenedHandler { result ->
            println("::::notificationOpened::::::" + result.notification.additionalData.toString())
            try {
                val ac = result.notification.additionalData.getString("ac")
                val myEdit: SharedPreferences.Editor = sharedPreferences.edit()
                myEdit.putString("flutter.payload", result.notification.additionalData.toString())
                myEdit.commit()
                println("::::ac:::$ac")
                println("prefernace valuw" + sharedPreferences.getString("flutter.payload", ""));

            } catch (e: Exception) {
                e.printStackTrace()
                println("::::Exception:::" + e.localizedMessage)
            }
        };

        OneSignal.setNotificationWillShowInForegroundHandler { notificationReceivedEvent: OSNotificationReceivedEvent ->
            val notification = notificationReceivedEvent.notification
            val mutableNotification = notification.mutableCopy()
            notificationReceivedEvent.complete(mutableNotification)
            val myEdit: SharedPreferences.Editor = sharedPreferences.edit()
            myEdit.putString("flutter.payload", notification.additionalData.toString())
            myEdit.commit()
            println("::::notificationWillShowInForeground::::::$notificationReceivedEvent")
            println("prefernace valuw" + sharedPreferences.getString("flutter.payload", ""));
        };


At Flutter side read from prefernce and reset blank

  SharedPreferences prefs = await SharedPreferences.getInstance();
      payLoad = prefs.getString("payload").toString();
      prefs.setString("payload", "");
