### ISSUE TITLE
[question]: Pop-Up Notifications does not appear when publish new posts from my Wordpress Website to my flutter app. Only appear in system tray.

### ISSUE THREAD

**Issue by min-nyein** [OneSignal/OneSignal-Flutter-SDK#602]
### How can we help?

Hi, I'm using onesignal_flutter: ^3.4.1. I am using also OneSignal Push Notifications Plugin for my Wordpress Websites. I can successfully push notifications to my flutter app when publish new posts from my Wordpress Website. In my flutter app I get notification in system tray but I dont get pop-up notification. I already create channel at onesignal (Settings->Messaging->Android Notification Channels->Add Group->Add Channel). And I know that when create new push on onesignal I can choose my channel under tap "Category". My question is how to choose channel when publish new posts from my Wordpress Website to my flutter app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisvidal** [comment]
hey, did you find a solution to your problem?

**Comment by jennantilla** [comment]
Hello everyone! Apologies that this issue has gone stale--I'll be closing it due to inactivity. If this is still a concern on the latest SDK, please open a new issue and we will be happy to investigate further!
