### ISSUE TITLE
How can I add Android Notification Groups and channels using API's or plugin ?

### ISSUE THREAD

**Issue by sadhanDev** [OneSignal/OneSignal-Flutter-SDK#603]
### How can we help?

How can we add the Android Notification channels and groups without going to the website and adding them manually ?

Scenario:
  We have a scenario wherein a user could download some sounds or tunes and set them as notification sounds and we are expecting that adding Android Notification channels and groups through API's or SDK for custom notification sounds would be better rather than adding them manually do guide us on what would be the best approach for this situation .

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @sadhanDev apologies that we missed responding to your question. We appreciate you sharing your use case! Although currently, Android categories must be added via the dashboard, we'll keep your feedback in mind!
