### ISSUE TITLE
Unable to load Maven meta-data from https://jcenter.bintray.com/

### ISSUE THREAD

**Issue by vijayvaghela72** [OneSignal/OneSignal-Flutter-SDK#607]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.razorpay:checkout:1.6.+.
     Required by:
         project :app > project :razorpay_flutter
      > Failed to list versions for com.razorpay:checkout.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/razorpay/checkout/maven-metadata.xml'.
               > Read timed out

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

today i am facing same issue recently .

_Originally posted by @vijayvaghela72 in https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/428#issuecomment-1296560040_

**Comment by vijayvaghela72** [comment]
PS E:\Code\v2.0.8 code of customer\Multivendor-Startt-From-2.0.4-> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.6, on Microsoft Windows [Version 10.0.19044.2130], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.72.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

**Comment by vijayvaghela72** [comment]
i think i have post issue at wrong place thank you

**Comment by ri938** [comment]
I am experiencing the same issue for about 24 hours too.  Preventing app builds.  Is there a workaround for this?

**Comment by ri938** [comment]
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.applovin:applovin-sdk:+.
     Required by:
         project :app
      > Failed to list versions for com.applovin:applovin-sdk.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/applovin/applovin-sdk/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/com/applovin/applovin-sdk/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/com/applovin/applovin-sdk/maven-metadata.xml'.
                  > Read timed out

**Comment by daviddavis83** [comment]
I am having the same issue and I am unable to build.

**Comment by mohitleo03** [comment]
Guys I am also having the same issue anyone got any solution. please tell me.

**Comment by nan-li** [comment]
Thanks for reporting,

It looks like[ JCenter was down](https://status.gradle.com/incidents/9740r6bzx438) which is why you received these errors. However, officially JCenter is deprecated and you should pull dependencies from google repo or maven central instead.

Make sure to search your gradle files for all instances of `jcenter()` and put `google()` and `mavenCentral()` before it. The [OneSignal Android SDK is hosted on Maven Central](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1293). 

I am closing this issue as it is not related to OneSignal.
