### ISSUE TITLE
[Bug]: The operation couldn't be completed. (OneSignalError erreur 400.), null, null)

### ISSUE THREAD

**Issue by oussemaRidene** [OneSignal/OneSignal-Flutter-SDK#610]
### What happened?

Everything works fine, I receive notifications without any problem, I'm just facing this exception every time when I open the application. It's only on IOS

### Steps to reproduce?

```Markdown
.
```

### What did you expect to happen?

.

### OneSignal Flutter SDK version

onesignal_flutter: ^3.4.2

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
2022-11-04 15:17:22.070122+0100 AppName[2085:259923] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(400, L’opération n’a pas pu s’achever. (OneSignalError erreur 400.), null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296)
<asynchronous suspension>
#2      OneSignal.sendTags (package:onesignal_flutter/onesignal_flutter.dart:243)
<asynchronous suspension>
#3      OneSignal.sendTag (package:onesignal_flutter/onesignal_flutter.dart:233)
<asynchronous suspension>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @oussemaRidene and @Remas-Safi, apologies for the delayed response. This issue is now stale, do you still need assistsance?
