### ISSUE TITLE
[question]: IOS Encountered error during push registration with OneSignal: Error Domain

### ISSUE THREAD

**Issue by ngee147** [OneSignal/OneSignal-Flutter-SDK#615]
### How can we help?

![Screenshot 2022-11-11 at 6 05 59 PM](https://user-images.githubusercontent.com/15373825/201573766-99cf0f3a-142d-4eee-a0ac-5a67438ce9b0.png)

I turn on the Log to verbose. OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.verbose).

It shows the error and is not registered in the onesignal portal -> Audience -> All Users 

Any idea to solve this? Android just work find.

Note: I have tested it multiple times, it shouldn't be the network issues. 

onesignal_flutter: 3.4.1

Flutter 3.3.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 6928314d50 (3 weeks ago) • 2022-10-25 16:34:41 -0400
Engine • revision 3ad69d7be3
Tools • Dart 2.18.2 • DevTools 2.15.0

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3
    
[✓] VS Code (version 1.73.1)
    • VS Code 
    • Flutter extension version 3.52.0

[✓] Connected device (4 available)
    • My iPhone (mobile) • 35c1d7e48b8f73aed62f8cfaa22c832c81d29d91 • ios            • iOS 15.7 19H12
    • iPhone 14 Pro (mobile) • 546D22C4-AC5B-4175-A95B-4858A742370C     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0
    
MacBook Pro (13-inch, M2, 2022)

Thank you 🙏 😊 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@ngee147 Thanks for reporting, the error message says there was a timeout to `api.onesignal.com/players`. I recommend making sure the device can open https://onesignal.com in a browser app on the device to ensure nothing is blocking your connection, such as a firewall or VPN setting.

If that works but you are still seeing the same timeout error also try opening https://api.onesignal.com/ in the browser on the device to ensure it isn't timing out. (note: Seeing `{"errors":["Header 'Accept: application/vnd.onesignal.v1+json' is required"]}` on this page is normal if opening it in a browser).

**Comment by ngee147** [comment]
Hi @jkasten2 , thanks for the tip. After switched to other network, it works properly now. I will close this case.
