### ISSUE TITLE
[question]: How to call separated functions for notification action buttons without opening the app?

### ISSUE THREAD

**Issue by ShehanYjoz** [OneSignal/OneSignal-Flutter-SDK#620]
### How can we help?

In notifications, we can receive action buttons with action IDs, Whenever the user clicks that app will open and we can call the function by checking the action ID. But we need to do action without opening the app. Documentation shows some webhook approaches, but not clear. Is there any way to call the separated function by clicking on the action button without opening the app?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShehanYjoz** [comment]
Hi, @rgomezp is there any progress on this?

**Comment by jennantilla** [comment]
@ShehanYjoz apologies that we missed your question. Since it has been quite some time since it was opened, I'm going to close this issue.

If this is something you'd still like to discuss, please let me know here!
