### ISSUE TITLE
I recently implemented this widget on the following website `alexisknight.co.uk`.

### ISSUE THREAD

**Issue by Dodalun** [OneSignal/OneSignal-Flutter-SDK#626]
I recently implemented this widget on the following website `alexisknight.co.uk`.

Unfortunately, it looks like the widget is not showing. When I used the browser inspector I can see that the widget has the CSS rule display:none. I checked on another website and I can also see that this rule gets overwritten by display: inline-block, presumeable this gets applied by JavaScript. I cannot figure out why this is not working for this website.

__Originally posted by @mikey242 in https://github.com/Automattic/eu-cookie-law-widget/issues/5__

__Originally posted by @Dodalun in https://github.com/Anita-Lunde/demo-repository/issues/2__

**Comment by nan-li** [comment]
Closed due to irrelevance.
