### ISSUE TITLE
[question]: Why remoteNotificationReceived in NotificationServiceExtension is not working in Android?

### ISSUE THREAD

**Issue by MingSern** [OneSignal/OneSignal-Flutter-SDK#627]
### How can we help?

So currently I am implementing incoming call notifications for both Android and iOS. And I have already completed the Voip notification on iOS side, but now I am stuck on Android side.

Based on this [documentation](https://documentation.onesignal.com/docs/service-extensions#android-notification-service-extension), I need to implement the Notification Service Extension on Android side to override the incoming notification setting so that the notification will look like an incoming call (e.g. WhatsApp call notification). _Please correct me if I am wrong at this point._

So I followed the documentation by adding a `NotificationServiceExtension.java` beside `MainActivity.kt` as such:
```java
package com.xxx.yyy;

import android.content.Context;
import android.graphics.Color;
import android.text.Spannable;
import android.text.SpannableString;
import android.text.style.ForegroundColorSpan;
import android.util.Log;
import org.json.JSONObject;

import com.onesignal.OSNotification;
import com.onesignal.OSMutableNotification;
import com.onesignal.OSNotificationReceivedEvent;
import com.onesignal.OneSignal.OSRemoteNotificationReceivedHandler;

import java.math.BigInteger;

@SuppressWarnings("unused")
public class NotificationServiceExtension implements OSRemoteNotificationReceivedHandler {

    @Override
    public void remoteNotificationReceived(Context context, OSNotificationReceivedEvent notificationReceivedEvent) {
        OSNotification notification = notificationReceivedEvent.getNotification();
        OSMutableNotification mutableNotification = notification.mutableCopy();

        mutableNotification.setExtender(builder -> {
            builder.setColor(new BigInteger("FF00FF00", 16).intValue());

            //  I changed to this title for testing
            Spannable spannableTitle = new SpannableString("Title has been overriden"); 
            spannableTitle.setSpan(new ForegroundColorSpan(Color.RED),0,notification.getTitle().length(),0);
            builder.setContentTitle(spannableTitle);

            //  I changed to this body for testing
            Spannable spannableBody = new SpannableString("Body has been overriden"); 
            spannableBody.setSpan(new ForegroundColorSpan(Color.BLUE),0,notification.getBody().length(),0);
            builder.setContentText(spannableBody);

            builder.setTimeoutAfter(30000);

            return builder;
        });

        notificationReceivedEvent.complete(mutableNotification);
    }
}
```

And also added the metadata in `AndroidManifest.xml` file as such:
```xml
<application ...> 
  <!-- name doesn't change, value = your class fully name spaced-->
  <meta-data 
          android:name="com.onesignal.NotificationServiceExtension"
          android:value="com.xxx.yyy.NotificationServiceExtension" />
</application>
```

So when I push a normal notification as such:
``` json
{
    "app_id": "MY_APP_ID",
    "include_player_ids": ["MY_PLAYER_ID"]
    "headings": {
        "en": "Original title"
    },
    "contents": {
        "en": "Original body"
    },
    "apns_push_type_override": "voip",
    "data": {
        ...
    },
}
```
I was expecting the `title` and `body` of the notification would be overridden to the one that I have defined in `NotificationServiceExtension`, but it didn't, it still shows the original notification.

What am I missing? There's not much documentation/video/article about this, I have tried many ways, and seems like the `remoteNotificationReceived` is not triggered and I can't get it working. I'm not familiar with native Android and would be happy if someone could help me a little on this one. 

Flutter doctor: `All good`
Flutter version: `3.3.9`
Package version: `onesignal_flutter: ^3.5.0`

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@MingSern I checked the details you provided and they all seem correct so your code in `remoteNotificationReceived` should be running.
* With one exception to how you are overriding the text, see https://github.com/OneSignal/OneSignal-Android-SDK/issues/717#issuecomment-472585280
    * This other issue refers to an older OneSIgnal SDK, but the same override rules apply.

If the above still doesn't help, can you print to the logcat ensure your `remoteNotificationReceived` is running?

**Comment by MingSern** [comment]
@jkasten2 Well, I've tried that before, it did not print into my logcat and it seems like it is not triggering `remoteNotificationReceived` at all, so I must be missing our something somewhere, this is how I did it:
```java
package com.xxx.yyy;

import android.content.Context;
import android.util.Log;

import com.onesignal.OSNotification;
import com.onesignal.OSMutableNotification;
import com.onesignal.OSNotificationReceivedEvent;
import com.onesignal.OneSignal.OSRemoteNotificationReceivedHandler;

@SuppressWarnings("unused")
public class NotificationServiceExtension implements OSRemoteNotificationReceivedHandler {

    @Override
    public void remoteNotificationReceived(Context context, OSNotificationReceivedEvent notificationReceivedEvent) {
        // This is where I add
        Log.d("NotificationServiceExtension", "This function has been triggered");
        
        OSNotification notification = notificationReceivedEvent.getNotification();
        
        OSMutableNotification mutableNotification = notification.mutableCopy();
        
        notificationReceivedEvent.complete(mutableNotification);
    }
}
```
I also added a `Log.d` in the `MainActivity.kt` just to check if my logcat is working and it is. So I'm not sure why `remoteNotificationReceived` is not triggered.

**Comment by MingSern** [comment]
@jkasten2 Okay, i can confirm this issue only happens to huawei devices, tested on android simulator and this code works. So what do we do on the huawei devices?

**Comment by MingSern** [comment]
Adding `huawei_msg_type: data` to onesignal API solved the issue, all good! For anyone that do now know where to find the API documentation, click [here](https://documentation.onesignal.com/reference/push-channel-properties)
