### ISSUE TITLE
[question]: How to show / hide scheduled notification based on condition ?

### ISSUE THREAD

**Issue by Jos-Sea** [OneSignal/OneSignal-Flutter-SDK#628]
### How can we help?

How can I show / hide scheduled notification based on condition?

Example Use case - 

Let's say To-Do tasks notifications are scheduled for 10 users at a specific time of 1:30 PM 
and some users have already completed the task before 1:30 PM.

Now scheduled notification are sent at 1:30 PM 
And I don't want to show notification to those users who have completed their task already ( before 1:30 PM )
and want to show only to those users who haven't completed the task yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @Jos-Sea apologies that your question was missed.

It sounds like segmenting your users by applying a data tag indicating whether they have completed their task might best suit your use case.

Please see our [Segments guide](https://documentation.onesignal.com/docs/segmentation) for more details and let us know if you have any additional questions or concerns!
