### ISSUE TITLE
[Bug]: Shared instance used in 'complete' method

### ISSUE THREAD

**Issue by ilia-grishakov-m10** [OneSignal/OneSignal-Flutter-SDK#630]
### What happened?

When use ur own instance of OneSignal through constructor instead of .shared instance there is method, that use forced .shared instance

### Steps to reproduce?

```Markdown
1. notification.dart file, 392 line
```

### What did you expect to happen?

use not shared instance instead

### OneSignal Flutter SDK version

3.4.1

### Which platform(s) are affected?

- [X] iOS
- [x] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
@ilia-grishakov-m10 the general expectation is that you use `OneSignal.shared` to access the SDK, as the underlying native SDKs are also static.  Can you help us understand the scenario you are trying to cover by creating your own instance?

Regarding `notification.dart line 392` using `OneSignal.shared` to complete the notification, is there an underlying issue that you are seeing? 

Thanks!

**Comment by jennantilla** [comment]
Closing due to no response.
