### ISSUE TITLE
[question]: Why I am faced in Huawei device "invalid_player_id" while send notification?

### ISSUE THREAD

**Issue by FoloosiApps** [OneSignal/OneSignal-Flutter-SDK#634]
Unhandled Exception: PlatformException(OneSignal, Encountered an error attempting to postNotification {"id":"","recipients":0,"errors":{"invalid_player_ids":["6df8e452-e007-48f1-a5cf-427cfbd51e61"]}}, {recipients: 0, id: , errors: {invalid_player_ids: [6df8e452-e007-48f1-a5cf-427cfbd51e61]}}, null)

`await OneSignal.shared.postNotification(OSCreateNotification(playerIds: [playerID],
content: "this is a test from OneSignal's Flutter SDK",
heading: "Test Notification",
buttons: [
OSActionButton(text: "test1", id: "id1"),
OSActionButton(text: "test2", id: "id2")
]
));`

**Note**
This case working fine in Android devices. I faced invalid_player_id error only in huawei device

**Comment by remakerich** [comment]
I'm trying to set up huawei push notifications in my flutter app as well. 
It refuses to work.
I tried this guide: https://documentation.onesignal.com/docs/authorize-onesignal-to-send-huawei-push but it does nothing... =(

Any ideas on how to make huawei work?

**Comment by remakerich** [comment]
Does OneSignal Flutter SDK support Huawei push kit at all?

**Comment by remakerich** [comment]
I made Huawei notifications work by adding this code to my `MainActivity.kt`:
```
package *my_package_name*

import io.flutter.embedding.android.FlutterActivity
import com.onesignal.OneSignal
import androidx.annotation.NonNull
import io.flutter.embedding.engine.FlutterEngine

const val ONESIGNAL_APP_ID = "*my_app_id*"

class MainActivity: FlutterActivity() {

    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
         // Logging set to help debug issues, remove before releasing your app.
      OneSignal.setLogLevel(OneSignal.LOG_LEVEL.VERBOSE, OneSignal.LOG_LEVEL.NONE)
      
      // OneSignal Initialization
      OneSignal.initWithContext(this)
      OneSignal.setAppId(ONESIGNAL_APP_ID)
    }
   
}
```

I dont know if its a right way though

- Also make sure that you have your `agconnect.json` in android/app folder
- theese implementations added to android/app/build.gradle
```
    implementation 'com.huawei.agconnect:agconnect-core:1.5.2.300'
    implementation 'com.huawei.hms:push:6.3.0.304'
    implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'
```
- this line added to the end of android/app/build.gradle
`apply plugin: 'com.huawei.agconnect'`
- in android/build.gradle add
`maven { url 'https://developer.huawei.com/repo/' }` to all repositories
`classpath 'com.huawei.agconnect:agcp:1.5.2.300'` to dependencies

**Comment by brismithers** [comment]
Hi @FoloosiApps / @remakerich .  In addition to the dashboard [Huawei authorization](https://documentation.onesignal.com/docs/authorize-onesignal-to-send-huawei-push) you linked to, there is also device-specific setup documented [here](https://documentation.onesignal.com/docs/huawei-flutter-sdk-setup).

@remakerich you should be able to do the OneSignal initialization in your `main.dart` file as described [here](https://documentation.onesignal.com/docs/flutter-sdk-setup#step-6-initialize-the-onesignal-sdk-all-platforms), rather than in an Android-specific file.

If there is something missing in the docs, or you are still experiencing issues, please let us know!

**Comment by brismithers** [comment]
Hi, just checking in to see if there are any remaining questions for this issue.  Please let me know, otherwise I will close this. Thanks!
