### ISSUE TITLE
[question]: Which kind of new App should we create for flutter?

### ISSUE THREAD

**Issue by Brechard** [OneSignal/OneSignal-Flutter-SDK#637]
### How can we help?

Following the guide on how to integrate the SDK, step 6 says to use an OneSignal APP ID:

https://documentation.onesignal.com/docs/flutter-sdk-setup#step-6-initialize-the-onesignal-sdk-all-platforms

though when I go to create a new project in OneSignal web, there is no flutter option, the options are: Apple iOs, Android, Web, Email, SMS, Windows, macOS, Huawei Android, Chrome extensions, or Amazon Fire. Which one should we choose?

If we want to use it on iOs and Android, do we need to create two apps and change the APP ID before doing the release? That seems pretty inconvenient.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @Brechard.  You will typically use the same app for both both iOS and Android, so one APP ID.  On the OneSignal dashboard you will need to configure both `Apple iOS (APNs)` and `Google Android (FCM)`.  When creating the app you can start your configuration with either, but be sure to configure the other through the "Settings" menu item.  In the "Settings" page you will have the option to configure other channels like Email, SMS, etc if desired.

Hope this helps!
