### ISSUE TITLE
[Bug]: The picture sometimes does not come in the OneSignal push notification Flutter Android

### ISSUE THREAD

**Issue by AurelVU** [OneSignal/OneSignal-Flutter-SDK#643]
### What happened?

I ran into a problem that from time to time a picture in a OneSignal push notification does not come to the same device. This issue only reproduces on the android platform when the application is turned off. At first, the image may not come to the same device, then literally after 10 minutes it will come, while the device is connected to Wi-Fi and has a good connection speed. This issue only reproduces on the android platform when the application is turned off. At first, the image may not come to the same device, then literally after 10 minutes it will come, while the device is connected to Wi-Fi and has a good connection speed. The image weighs 56 kilobytes, has a resolution of 800 by 800 pixels in jpg format.
![logs](https://user-images.githubusercontent.com/33979689/217239717-60c44050-87ab-40ae-af95-739ee88bba03.png)
![qa-проверки-качества-логотипа-испытывая-мазки-с-щеткой-vecto-107964023](https://user-images.githubusercontent.com/33979689/217239725-0022783c-0c86-4eeb-9d98-84ed671c93dc.jpg)

### Steps to reproduce?

```Markdown
1. add OneSignal 3.5.0 to flutter project (flutter 3.7.0)
2. start app, accept notification permission request
3. close app
4. send test push with this image: https://www.filepicker.io/api/file/0dq8DwUXTnOINlebY5IW?filename=name.jpg
```

### What did you expect to happen?

Stable image display in push notifications

### OneSignal Flutter SDK version

I use OneSignal v 3.5.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
2023-02-07 14:44:23.418  9756-9826  OneSignal         W  remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification
2023-02-07 14:44:23.451  9756-9826  OneSignal         W  Could not download image!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @AurelVU . If I understand correctly, are you saying when you send a push notification with an image URL *and* the device does not have a reliable internet connection, the image may not display?

If I got that right, this is expected behavior.  When you provide a URL for the image the device is pulling the image from that URL when the notification is to be displayed to the user.  We have a troubleshooting guide [here](https://documentation.onesignal.com/docs/notification-images-not-showing) which might help you out.

Let me know if this helps!

**Comment by AurelVU** [comment]
Hello. The problem is that at the moment I am describing, the device is connected to a stable wifi ~ 70 mbps. However, a push notification is ~70% likely to arrive without an image if the app has been shut down for more than 10 minutes

**Comment by brismithers** [comment]
@AurelVU is there a stack trace after the `Could not download image!` message in the log?  [This](https://github.com/OneSignal/OneSignal-Android-SDK/blob/427e55e1b36634d7e1b12d475bd0bcb088e4ee50/OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java#L934) is the source of that message, and we are capturing the exception that occurs in the log.

**Comment by AurelVU** [comment]
Unfortunately no. I tried to get more detailed logs, but did not figure out how to do it. I will try within 24 hours to try to get more detailed debug information for you. Can you please suggest how I could get more information without attaching a debugger? (because the problem is relevant for an application that is not running)

**Comment by brismithers** [comment]
@AurelVU I found an older [Android issue](https://issuetracker.google.com/issues/36934828?pli=1) that suggests the stack trace will **not** be printed out to the log when the exception is an `UnknownHostException`.

To aid with your debugging you can call `OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.warn);`prior to your call to `await OneSignal.shared.setAppId("YOUR_APP_ID");`.  This should *not* be done in a production setting! 

This will update the visual log level to "warn", meaning you'll see a popup in your app with a log message/exception whenever there is a warning logged, and this will include the stack trace.

When I started my test app in airplane mode I got a visual alert with below, I'm curious what your stack trace will say.

```
Could not download image!
Unable to resolve host "img.onesignal.com": No address associated with hostname
java.net.UnknownHostException: Unable to resolve host "img.onesignal.com": No address associated with hostname
...
```


https://img.onesignal.com/tmp/44fdc303-3142-4134-b6c3-61165517fd70.jpg

**Comment by AurelVU** [comment]
The team and I were indeed getting an UnknownHostException. Through experiments, we came to the conclusion that it was necessary to disable the optimization mode, which was in the firmware of the android device of the Chinese manufacturer. At the moment, the problem is not reproduced, I think that you can close the issue
