### ISSUE TITLE
[question]: Is it working for iOS 16?

### ISSUE THREAD

**Issue by jlno** [OneSignal/OneSignal-Flutter-SDK#644]
### How can we help?

I'm not getting notifications for iOS, just on Android.
```
iOS 16.3
Xcode 14.2
onesignal_flutter 3.5.0
```
`WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jefferyleo** [comment]
@jlno any solution on this? As I'm encountering it now

**Comment by chrisvidal** [comment]
same here
