### ISSUE TITLE
[question]: How can i remove badge from my app icon?

### ISSUE THREAD

**Issue by divyaEncodework** [OneSignal/OneSignal-Flutter-SDK#655]
### How can we help?

I want to remove the badge of notification. 
When a notification arrives it will only be shown on top of the device I don't want to show it on my app icon, so what can I do about this?

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @divyaEncodework apologies your question was missed!

Please see our [documentation](https://documentation.onesignal.com/docs/badges) for more information on how to remove badges.

Let us know if you have any additional questions or concerns!
