### ISSUE TITLE
Couldn't read values in CFPrefsPlistSource<0x283f25400> (Domain: group.com.*.onesignal, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd

### ISSUE THREAD

**Issue by BunnyBuddy** [OneSignal/OneSignal-Flutter-SDK#657]
### What happened?

We are using Onesignal in our Flutter App and it was working fine, but a few days ago it started showing this exception while the App still works. 

`(lldb) 2023-02-20 15:02:21.526768+0500 Runner[3800:1252662] [User Defaults] Couldn't read values in CFPrefsPlistSource<0x283f25400> (Domain: group.com.*.onesignal, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd`

### Steps to reproduce?

```Markdown
Whenever we build our app for the first time.
```

### What did you expect to happen?

I expect this is not a big issue and its just a warning of some sort

### OneSignal Flutter SDK version

Release 3.2.3

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
Installing and launching...
(lldb) 2023-02-20 15:02:21.526768+0500 Runner[3800:1252662] [User Defaults] Couldn't read values in CFPrefsPlistSource<0x283f25400> (Domain: group.com.*****.onesignal, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
[SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felipecastrosales** [comment]
any news about this? I'm facing with this problem also.

**Comment by nan-li** [comment]
Hi @BunnyBuddy and @felipecastrosales,

I apologize for the delay, this is an xcode warning that can be ignored. Please see this answer by an Apple Developer Tools Engineer team member in [this thread](https://developer.apple.com/forums/thread/51348?page=2):

> It's unfortunate that there is a visible log message here, because it's unrelated to virtually all of the issues reported in this thread. The logged message is **spurious** unless you're doing very specific things that I don't think are possible without using private functions (it was added to catch misuse of those functions, but unfortunately also caught a normal usage case).
> 
> Any bugs you and other people in the thread seeing are separate, and fairly likely to be unrelated to each other as well. e.g. irregularly not seeing user defaults is almost certainly due to a bug in user defaults, not due to something your app is doing. Crashing is likely unrelated to user defaults entirely, and should be diagnosed via the crashlog, not the logged message.

Are you experiencing a problem with the SDK?

**Comment by ChoyCheeWei** [comment]
> Hi @BunnyBuddy and @felipecastrosales,
> 
> I apologize for the delay, this is an xcode warning that can be ignored. Please see this answer by an Apple Developer Tools Engineer team member in [this thread](https://developer.apple.com/forums/thread/51348?page=2):
> 
> > It's unfortunate that there is a visible log message here, because it's unrelated to virtually all of the issues reported in this thread. The logged message is **spurious** unless you're doing very specific things that I don't think are possible without using private functions (it was added to catch misuse of those functions, **but unfortunately also caught a normal usage case**).
> > Any bugs you and other people in the thread seeing are separate, and fairly likely to be unrelated to each other as well. e.g. irregularly not seeing user defaults is almost certainly due to a bug in user defaults, not due to something your app is doing. Crashing is likely unrelated to user defaults entirely, and should be diagnosed via the crashlog, not the logged message.
> 
> Are you experiencing a problem with the SDK?

Hi @nan-li,  I have the same issue also, based on the [this thread](https://developer.apple.com/forums/thread/51348?page=2) is that mean we have to change the **group.com.*.onesignal** to **teamNumber.group.com.*.onesignal** ?

**Comment by nan-li** [comment]
Hi, we have had no further reports of this. Please upgrade the OneSignal SDK if you or anyone is still having this issue. If this is still an issue, please open a new report with updated information.
