### ISSUE TITLE
iOS badge count not cleared

### ISSUE THREAD

**Issue by lifenautjoe** [OneSignal/OneSignal-Flutter-SDK#66]
When increasing the badge count, opening the notification/app does not clear the count and consequent notifications increase the badge count.

![badge-bug](https://user-images.githubusercontent.com/12737509/54025462-e8eb1400-419a-11e9-86b2-2378512b2a02.gif)

**Environment**

`Flutter doctor -v`
````
[✓] Flutter (Channel master, v1.2.3-pre.32, on Mac OS X 10.14.2 18C54, locale
    en-NL)
    • Flutter version 1.2.3-pre.32 at
      /Users/lifenautjoe/Documents/code/libraries/flutter
    • Framework revision 1a182bf7bf (9 days ago), 2019-02-25 02:40:28 -0500
    • Engine revision 502c9c4002
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/lifenautjoe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5901

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28)
      (emulator)

• No issues found!
````

OneSignal SDK Version
````
  onesignal: ^1.0.5
````

**Comment by Nightsd01** [comment]
@lifenautjoe did you set up the Extension and App Group? Can you post screenshots of the App Group capability for **both** the main app target and the Extension target?

**Comment by lifenautjoe** [comment]
Hi Brad, thanks for reaching back. Here are the screens.

![image](https://user-images.githubusercontent.com/12737509/54043848-dccc7a00-41cd-11e9-8248-bb974b2172ce.png)

![image](https://user-images.githubusercontent.com/12737509/54043867-e81fa580-41cd-11e9-8e86-61c2d3e1706c.png)

**Comment by lifenautjoe** [comment]
Here's one of the bundle id

![image](https://user-images.githubusercontent.com/12737509/54043950-14d3bd00-41ce-11e9-9b41-c37841fe4ae9.png)

**Comment by Nightsd01** [comment]
@lifenautjoe please add this key/value to **both** `Info.plist` files for your main app and Extension targets:

`OneSignal_app_groups_key` = `group.social.openbook.app`

Then try it again

**Comment by Nightsd01** [comment]
Oh. @lifenautjoe you are supposed to add `.onesignal` to the end of the app group name that’s why it’s not working.

**Comment by lifenautjoe** [comment]
It works! Thanks a lot Brad.
