### ISSUE TITLE
[question]: How do i Pass ios_interruption_level in OSCreateNotification

### ISSUE THREAD

**Issue by bvschie** [OneSignal/OneSignal-Flutter-SDK#661]
### How can we help?

I think the class OSCreateNotification misses the interruption level, available in the class OSNotification.

How to send an OSNotification to postNotification with the ios_interruption_level set (['active', 'passive', 'time_sensitive', 'critical'])

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @bvschie apologies your question was missed!

Please see our [iOS Focus Modes & Interruption Levels documentation](https://documentation.onesignal.com/docs/ios-focus-modes-and-interruption-levels) for more information and let us know if you have any additional questions or concerns!

Also--we have released major updates to the [Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) which includes many improvements and enhancements. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details!
