### ISSUE TITLE
How to show custom notification dialog when notifications are not allowed?

### ISSUE THREAD

**Issue by burhanaksendir** [OneSignal/OneSignal-Flutter-SDK#671]
### How can we help?

How can I customize the Onesignal default alert display when notifications are not allowed? I want to change the title, text etc.
By default, Onesignal settings show the following alert screen.

<img width="270" alt="onesignal" src="https://user-images.githubusercontent.com/8548639/226735626-a847238a-301a-447e-ac3d-13f546ac203c.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lord-tx** [comment]
This is not a OneSignal alert display, this is the iOS Default Alert for helping users understand their current setting state.

**Comment by burhanaksendir** [comment]
Hello @lord-tx
 Thanks. If I didn't allow notifications, this warning screen keeps popping up. How can I cancel this?

**Comment by burhanaksendir** [comment]
This alert display appears because I gave the fallbackToSettings setting as true. I set it to false and it no longer pops up constantly.
```
await OneSignal.shared
          .promptUserForPushNotificationPermission(fallbackToSettings: true)
```
