### ISSUE TITLE
[Bug]: Users get unsubscribe status after sending a notification

### ISSUE THREAD

**Issue by D2Wirexia** [OneSignal/OneSignal-Flutter-SDK#673]
### What happened?

**I saw a similar thread on React-Native, but what exactly caused it was not established!**

On initialization app I do:
```
await OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);
await OneSignal.shared.setAppId(appId);
await OneSignal.shared.disablePush(false);
await OneSignal.shared.setExternalUserId(MyApp.store.state.userModel.uid);
```
On logout I do:
`await OneSignal.shared.disablePush(true);`
This sets the status "User Opted Out" on the table, and it's good, because I don't wont get notification if user not logged in.

When i send a message through the dashboard, some users get a status of "Not Subscribed" and notification don't arrive.
![image](https://user-images.githubusercontent.com/34273306/227606026-0a805db2-0041-422a-b555-75e0b878f530.png)

When you restart the app or log in again, then the status will be change to:
![image](https://user-images.githubusercontent.com/34273306/227606592-00544d58-894d-4a8a-bc0f-4104a7b3671a.png)

but when u will sent notification again, this again change your status to "Not Subscribed".
Also, I can't track it with `OneSignal.shared.setSubscriptionObserver`.

Addition I'm using API `POST https://onesignal.com/api/v1/notifications?app_id=$appId&offset=0` for get the latest messages,

### Steps to reproduce?

```Markdown
Open app > Sent notification from dashboard
```

### What did you expect to happen?

If it's a new user, then he may receive several messages, but over time he will also be blocked and I don't understand why? Notifications should always be received only if the user does not have a status of "User Opted Out"

### OneSignal Flutter SDK version

3.5.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

When connected to OneSignal. Seems it's ok, because it's worked before

```Shell
V/OneSignal(22002): Initializing the OneSignal Flutter SDK (3.3.2)
V/OneSignal(22002): initWithContext called with: com.myapp.MainActivity@76d95e4
V/OneSignal(22002): Starting OneSignal initialization!
V/OneSignal(22002): No class found, not setting up OSRemoteNotificationReceivedHandler
D/OneSignal(22002): OneSignal SDK initialization already completed.
V/OneSignal(22002): Starting OneSignal initialization!
V/OneSignal(22002): No class found, not setting up OSRemoteNotificationReceivedHandler
D/OneSignal(22002): OneSignal SDK initialization already completed.
D/OneSignal(22002): UserStateSynchronizer internalSyncUserState from session call: true jsonBody: {"app_id":app_id"}
D/OneSignal(22002): OneSignalRestClient: Making request to: https://api.onesignal.com/players/1fde5a9c-59aa-4d97-9eea-0ddb47a5babd/on_session
D/OneSignal(22002): OneSignalRestClient: POST SEND JSON: {"app_id":app_id}
V/OneSignal(22002): OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players/1fde5a9c-59aa-4d97-9eea-0ddb47a5babd/on_session
D/OneSignal(22002): OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/players/1fde5a9c-59aa-4d97-9eea-0ddb47a5babd/on_session
D/OneSignal(22002): OneSignalRestClient: POST RECEIVED JSON: {"success":true,"id":"1fde5a9c-59aa-4d97-9eea-0ddb47a5babd"}
D/OneSignal(22002): doCreateOrNewSession:response: {"success":true,"id":"1fde5a9c-59aa-4d97-9eea-0ddb47a5babd"}
I/OneSignal(22002): Device registered, UserId = 1fde5a9c-59aa-4d97-9eea-0ddb47a5babd
D/OneSignal(22002): UserStateSynchronizer internalSyncUserState from session call: false jsonBody: null
V/OneSignal(22002): Completed request to update external user id for channel: push and success: true
I/flutter (22002): Open Signal is accepted permission: true

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by D2Wirexia** [comment]
I seem to have found the problem, it worked for me. I delete FB token at logout, and a new one is created at login, but OneSignal does't pull it up. I don't think this is a feature of this service, this is a very critical bug for me, since I use FB with other services....
Also problem when connecting with setting `setExternalUserId`, it's also causes my app to crash, when I don't deleted FB token...
The service is interesting, but I was left with a very bad impression of his work 😞

**Comment by emawby** [comment]
@D2Wirexia So you are deleting the push token when logout is called? Could you post a stack trace for your setExternalUserId crash?

**Comment by jennantilla** [comment]
Closing due to no response. 

We have released major updates to the [Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) which includes many improvements and enhancements. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details!

@D2Wirexia if this is still an problem for you after upgrading please feel free to open a new issue and we'll resume investigation!
