### ISSUE TITLE
[Bug]: Deprication warnings

### ISSUE THREAD

**Issue by balazsbokanyi** [OneSignal/OneSignal-Flutter-SDK#680]
### What happened?

With the currently most recent SDK, onesignal_flutter-3.5.1 there are multiple deprecation warnings when building the app (with previous versions as well, but I updated to the most recent before filing this report). Namely io.flutter.plugin.common.PluginRegistry.Registrar and io.flutter.view.FlutterNativeView.

Is there any chance for these to be resolved?

### Steps to reproduce?

```Markdown
Create a Flutter app with this plugin and run on Android.
```

### What did you expect to happen?

No deprecation warnings.

### OneSignal Flutter SDK version

Release 3.5.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
C:\Users\...\AppData\Local\Pub\Cache\hosted\pub.dev\onesignal_flutter-3.5.1\android\src\main\java\com\onesignal\flutter\OneSignalInAppMessagingController.java:13: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;

C:\Users\...\AppData\Local\Pub\Cache\hosted\pub.dev\onesignal_flutter-3.5.1\android\src\main\java\com\onesignal\flutter\OneSignalOutcomeEventsController.java:15: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;

C:\Users\....\AppData\Local\Pub\Cache\hosted\pub.dev\onesignal_flutter-3.5.1\android\src\main\java\com\onesignal\flutter\OneSignalPlugin.java:42: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;

C:\Users\...\AppData\Local\Pub\Cache\hosted\pub.dev\onesignal_flutter-3.5.1\android\src\main\java\com\onesignal\flutter\OneSignalPlugin.java:43: warning: [deprecation] FlutterNativeView in io.flutter.view has been deprecated
import io.flutter.view.FlutterNativeView;

C:\Users\...\AppData\Local\Pub\Cache\hosted\pub.dev\onesignal_flutter-3.5.1\android\src\main\java\com\onesignal\flutter\OneSignalTagsController.java:20: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by manuelduarte077** [comment]
what version of flutter are you using?

**Comment by balazsbokanyi** [comment]
Currently 3.7.12, but the warnings were present in previous versions as well.

**Comment by jennantilla** [comment]
Hello everyone! On our [latest SDK version](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5), there shouldn't be any deprecation warnings. Please upgrade and let us know if you still see anything! 

Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details.

Thanks!
