### ISSUE TITLE
[Bug]: App is not opening in iOS

### ISSUE THREAD

**Issue by micaelsn** [OneSignal/OneSignal-Flutter-SDK#683]
### What happened?

I followed all the steps of the documentation but isn't working. Somebody could help me?

### Steps to reproduce?

```Markdown
I followed all steps from documentation
1- flutter run
```

### What did you expect to happen?

Open the app

### OneSignal Flutter SDK version

3.5.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
unning pod install...                                              5,2s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        15,3s
Xcode build done.                                           113,7s
(lldb) dyld[22601]: Library not loaded: @rpath/OneSignalExtension.framework/OneSignalExtension
  Referenced from: <DDA5BC20-90BA-3587-B305-5FC2B70BDF21> /private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Runner
  Reason: tried: '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/preboot/Cryptexes/OS@rpath/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/System/Library/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache)
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001bc81cebc dyld`__abort_with_payload + 8
dyld`:
->  0x1bc81cebc <+8>:  b.lo   0x1bc81cedc               ; <+40>
    0x1bc81cec0 <+12>: pacibsp 
    0x1bc81cec4 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1bc81cec8 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Installing and launching...                                        40,8s
Error launching application on micael’s iPhone.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wahyu-handayani** [comment]
> ### What happened?
> I followed all the steps of the documentation but isn't working. Somebody could help me?
> 
> ### Steps to reproduce?
> ```
> I followed all steps from documentation
> 1- flutter run
> ```
> 
> ### What did you expect to happen?
> Open the app
> 
> ### OneSignal Flutter SDK version
> 3.5.1
> 
> ### Which platform(s) are affected?
> * [x]  iOS
> * [ ]  Android
> 
> ### Relevant log output
> ```shell
> unning pod install...                                              5,2s
> Running Xcode build...                                                  
>  └─Compiling, linking and signing...                        15,3s
> Xcode build done.                                           113,7s
> (lldb) dyld[22601]: Library not loaded: @rpath/OneSignalExtension.framework/OneSignalExtension
>   Referenced from: <DDA5BC20-90BA-3587-B305-5FC2B70BDF21> /private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Runner
>   Reason: tried: '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/preboot/Cryptexes/OS@rpath/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/private/var/containers/Bundle/Application/5CEC3623-F244-48F9-8657-59C11783A78D/Runner.app/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2), '/System/Library/Frameworks/OneSignalExtension.framework/OneSignalExtension' (errno=2, not in dyld cache)
> * thread #1, stop reason = signal SIGABRT
>     frame #0: 0x00000001bc81cebc dyld`__abort_with_payload + 8
> dyld`:
> ->  0x1bc81cebc <+8>:  b.lo   0x1bc81cedc               ; <+40>
>     0x1bc81cec0 <+12>: pacibsp 
>     0x1bc81cec4 <+16>: stp    x29, x30, [sp, #-0x10]!
>     0x1bc81cec8 <+20>: mov    x29, sp
> Target 0: (Runner) stopped.
> Installing and launching...                                        40,8s
> Error launching application on micael’s iPhone.
> ```
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Hi I have the same case like yours, did u find any solution ?
