### ISSUE TITLE
Notification click is not redirecting to app, if app is in background or closed.

### ISSUE THREAD

**Issue by rituapplocum** [OneSignal/OneSignal-Flutter-SDK#684]
### What happened?

Added onesignal_flutter: ^3.5.1

Notification click redirection not working if the app is in the background.

### Steps to reproduce?

```Markdown
Added onesignal_flutter: ^3.5.1 in pubspec.yaml
Initialized the SDK 
close the app 
Trigger push notification from back-end
Click on the push notification
```

### What did you expect to happen?

Redirection should work even if the app is closed or in background.

### OneSignal Flutter SDK version

3.5.1

### Which platform(s) are affected?

- [ ] iOS
- [x] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @rituapplocum,

Thanks for reporting, can you explain more about the issue?

When you say notification click redirection is not working, do you mean tapping on the notification is not opening the app? Or, is it related to deep links or launch URLs?

**Comment by rituapplocum** [comment]
It is resolved now

**Comment by tovidd** [comment]
How do you resolving this issue @rituapplocum

**Comment by MuhamadHaydar** [comment]
I got same issue, could you provider the solution? 
@rituapplocum

**Comment by jennantilla** [comment]
@MuhamadHaydar are you still having issues with this?

**Comment by jennantilla** [comment]
Closing due to no response. If anyone is still having issues on the [latest SDK version](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5), please open a new issue. Thanks!
