### ISSUE TITLE
[Bug]: Xcode 15 beta cant run example app

### ISSUE THREAD

**Issue by Mayb3Nots** [OneSignal/OneSignal-Flutter-SDK#685]
### What happened?

When using Xcode 15 beta cloning and running the beta app wont start. Instead such error will appear
```
Error (Xcode): Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ Target 'Runner': CodeSign /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app
○ That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
○ Target 'Runner' has copy command from '/Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex' to '/Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex'
○ That command depends on command in Target 'Runner': script phase “Thin Binary”
○ Target 'Runner' has process command with output '/Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/Info.plist'
○ Target 'Runner' has copy command from '/Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex' to '/Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex'


Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node: /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/_CodeSignature ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:CodeSign /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app ->

node: /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/OneSignal.framework/ ->

directoryTreeSignature: } ->

directoryContents: /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/OneSignal.framework ->

node: /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/OneSignal.framework ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution [CP] Embed Pods Frameworks /Users/samuel/Library/Developer/Xcode/DerivedData/Runner-fpkmtpdgwretavetcemvayxmicfq/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-DC908A9224BCC3ECD7BDF295.sh ->

node: /Users/samuel/Library/Developer/Xcode/DerivedData/Runner-fpkmtpdgwretavetcemvayxmicfq/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-DC908A9224BCC3ECD7BDF295.sh ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile /Users/samuel/Library/Developer/Xcode/DerivedData/Runner-fpkmtpdgwretavetcemvayxmicfq/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-DC908A9224BCC3ECD7BDF295.sh ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5-copy-files> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5-copy-files ->

node: <Copy /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex> ->

CYCLE POINT ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary ->

node: <execute-shell-script-18c1723432283e0cc55f10a6dcfd9e02f1eee2015e8ff5ebcd27678f788c2826-target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-> ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution Thin Binary /Users/samuel/Library/Developer/Xcode/DerivedData/Runner-fpkmtpdgwretavetcemvayxmicfq/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B06AD1E1E4923F5004D2608.sh ->

node: /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/Info.plist/ ->

directoryTreeSignature: i ->

directoryContents: /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/Info.plist ->

node: /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/Info.plist ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ProcessInfoPlistFile /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/Info.plist /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/ios/Runner/Info.plist ->

node: /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex /Users/samuel/Flutter/OneSignal-Flutter-SDK/example/build/ios/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
Exited
```

I managed to solve it by removing the `OneSignalNotificationServiceExtension.appex` from the Embed App Extension

<img width="768" alt="Screenshot 2023-06-13 at 9 46 58 PM" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/68549184/c4c162bf-6c30-40a1-8bf9-ccbf64ac6d66">

### Steps to reproduce?

```Markdown
1. Download macOS Sonoma and Xcode 15 beta.
2. Clone and run the example app.
```

### What did you expect to happen?

Able to run

### OneSignal Flutter SDK version

3.5.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Thank you for reporting we have not yet released SDKs that have been tested against Xcode 15, but it is good to know that there are issues! We will investigate

**Comment by Mamun-Lab** [comment]
Facing the same issue. Any update?

**Comment by emawby** [comment]
It looks like this is a [flutter bug](https://github.com/flutter/flutter/issues/128947) with any kind of extensions in an iOS app

**Comment by mshere9** [comment]
hey, we are facing the same issue here with xcode 15 beta 2 with ios 17 beta 2

**Comment by kmrinmoy07** [comment]
We are also facing the issue, any workaround or solution for it

**Comment by yanglindevops** [comment]
mark

**Comment by Tolulope05** [comment]
Still dosnt work for beta 15, cant run flutter projects

**Comment by thesheps** [comment]
Hopefully this isn't a ME TOO, but wanted to share my own experience here.

Having foolishly upgraded my silicon M2 to Sonoma, I was then confronted with the fact that xcode 14 "isn't compatible" with Sonoma, so was forced into upgrading to 15 beta, which in turn doesn't appear as yet to be compatible with flutter.

If you're in the same position as me, you CAN continue to run xcode 14 on Sonoma, just via the terminal instead...


Hope this helps somebody

**Comment by Mayb3Nots** [comment]
Hey guys this is an Apple bug that has been acknowledged by the Apple team and is not related to Flutter or OneSignal. In order to fix it temporally you should add -ld64 to your project's Other Linker Flags build setting.  See https://github.com/firebase/firebase-ios-sdk/issues/11413#issuecomment-1624180664 for more info.

**Comment by wahyu-handayani** [comment]
> Hey guys this is an Apple bug that has been acknowledged by the Apple team and is not related to Flutter or OneSignal. In order to fix it temporally you should add -ld64 to your project's Other Linker Flags build setting. See [firebase/firebase-ios-sdk#11413 (comment)](https://github.com/firebase/firebase-ios-sdk/issues/11413#issuecomment-1624180664) for more info.

I have added ```-ld64``` in Other Linker Flags but I still get the same error log. The error log is like what you share earlier

**Comment by Isroiljoncyber** [comment]
I am facing the same with Xcode 15. Any solutions?

**Comment by lmshek** [comment]
I am facing the same with Xcode 15 as well. Adding -ld64 to the Other Linker Flags does not help.

**Comment by kienvtqhi** [comment]
Facing the same issue

**Comment by Mayb3Nots** [comment]
Hey guys I recommend opening a new issue with a reproduction code as this issue is related to xcode 15 beta and xcode recently released its stable version and it may not be related to this issue.

**Comment by wahyu-handayani** [comment]
> Hey guys I recommend opening a new issue with a reproduction code as this issue is related to xcode 15 beta and xcode recently released its stable version and it may not be related to this issue.

I have the same case like yours (the error log is the same like mine, but after I remove onesignal from my project (also remove all configuration in xcode) it was okey right now)

**Comment by wahyu-handayani** [comment]
> In my case, seems to resolve if you move up "Embed Foundation Extensions" just right bellow "Copy Bundle Resources" in the Build Phases.

Thank you so much, I have tried your solution and it works, thank you sooooo much

**Comment by wahyu-handayani** [comment]
btw after I do the solution from @cerealexx or @metalwings I can run my project from xcode, it goes really really wel. But when I try to do debugging from my code, it always stuck in keep ```Launching...``` (Xcode build done) ant finally after waiting for so long I get this error log
```
Exception: Unable to launch project.halo.haloo on 28D5405B-43B3-4B64-9A7C-1D05E2C8A44A:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
Simulator device returned an error for the requested operation.
The request was denied by service delegate (SBMainWorkspace).
Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=1):
	The request to open "project.halo.haloo" failed.
	The request was denied by service delegate (SBMainWorkspace).
  Command: xcrun simctl launch 28D5405B-43B3-4B64-9A7C-1D05E2C8A44A project.halo.haloo --enable-dart-profiling --start-paused --enable-checked-mode --verify-entry-points
Error launching application on iPhone 15 Pro Max
```
Is there a way to solve this

**Comment by simon-jo8** [comment]
Ok this is a joke :'( 
I Spend three days looking for a solution and it was just as simple as moving "Embed Foundation Extensions" up like @cerealexx suggested 😭

**Comment by wemgl** [comment]
@cerealexx your solution worked perfectly for me, thanks for sharing!

**Comment by Isroiljoncyber** [comment]
rror (Xcode): ../../.pub-cache/hosted/pub.dev/onesignal_flutter-5.0.1/lib/onesignal_flutter.dart:6:8: Error: Error when reading '../../.pub-cache/hosted/pub.dev/onesignal_flutter-5.0.1/lib/src/notifications_entity.dart': No such file or directory 
i am facing new issue . Is there anyone faced

**Comment by dirablue** [comment]
@cerealexx 
Thanks ! it's solved with this solution.

**Comment by danielshaffer** [comment]
> In my case, seems to resolve if you move up "Embed Foundation Extensions" just right bellow "Copy Bundle Resources" in the Build Phases.

Thank!!! This worked for me.

**Comment by microinginer** [comment]
> just right bellow

Thanks, save my day

**Comment by sejun2** [comment]
> In my case, seems to resolve if you move up "Embed Foundation Extensions" just right bellow "Copy Bundle Resources" in the Build Phases.

Thanks a lot. You saved my life.

**Comment by fabioselau077** [comment]
> In my case, seems to resolve if you move up "Embed Foundation Extensions" just right bellow "Copy Bundle Resources" in the Build Phases.

resolved, thanks!!!!

**Comment by subhanAnjum** [comment]
> btw after I do the solution from @cerealexx or @metalwings I can run my project from xcode, it goes really really well. But when I try to do debugging from my code, it always stuck in keep `Launching...` (Xcode build done) and finally after waiting for so long I get this error log
> 
> ```
> Exception: Unable to launch project.halo.haloo on 28D5405B-43B3-4B64-9A7C-1D05E2C8A44A:
> ProcessException: Process exited abnormally:
> An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
> Simulator device returned an error for the requested operation.
> The request was denied by service delegate (SBMainWorkspace).
> Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=1):
> 	The request to open "project.halo.haloo" failed.
> 	The request was denied by service delegate (SBMainWorkspace).
>   Command: xcrun simctl launch 28D5405B-43B3-4B64-9A7C-1D05E2C8A44A project.halo.haloo --enable-dart-profiling --start-paused --enable-checked-mode --verify-entry-points
> Error launching application on iPhone 15 Pro Max
> ```
> 
> Is there a way to solve this

Facing same issue, if anyone has found a work around please let me know.

**Comment by joeboylson** [comment]
> In my case, seems to resolve if you move up "Embed Foundation Extensions" just right bellow "Copy Bundle Resources" in the Build Phases.

Absolute lifesaver! Thank you @cerealexx !

**Comment by orionnuri** [comment]
> > bu arada çözümü yaptıktan sonra@cerealexxveya@metalwingsProjemi xcode'dan çalıştırabiliyorum, gerçekten çok iyi gidiyor. Ancak kodumdan hata ayıklama yapmaya çalıştığımda, her zaman saklamada kalıyor `Launching...`(Xcode derlemesi tamamlandı) ve sonunda bu kadar bekledikten sonra bu hata günlüğünü alıyorum
> > ```
> > Exception: Unable to launch project.halo.haloo on 28D5405B-43B3-4B64-9A7C-1D05E2C8A44A:
> > ProcessException: Process exited abnormally:
> > An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
> > Simulator device returned an error for the requested operation.
> > The request was denied by service delegate (SBMainWorkspace).
> > Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=1):
> > 	The request to open "project.halo.haloo" failed.
> > 	The request was denied by service delegate (SBMainWorkspace).
> >   Command: xcrun simctl launch 28D5405B-43B3-4B64-9A7C-1D05E2C8A44A project.halo.haloo --enable-dart-profiling --start-paused --enable-checked-mode --verify-entry-points
> > Error launching application on iPhone 15 Pro Max
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Bunu çözmenin bir yolu var mı
> 
> Aynı sorunla karşı karşıyayım, eğer birileri bir çözüm bulursa lütfen bana bildirin.


I'm getting this error too, did you find any solution?

**Comment by LGByte** [comment]
> In my case, seems to resolve if you move up "Embed Foundation Extensions" just right bellow "Copy Bundle Resources" in the Build Phases.

thank you  it's works ,what the reason
