### ISSUE TITLE
[question]: [!] Unable to find a target named `OneSignalNotificationServiceExtension` in project `Runner.xcodeproj`, did find `Runner` and `OneSignalServiceNotificationExtension`.

### ISSUE THREAD

**Issue by Arpithaarha** [OneSignal/OneSignal-Flutter-SDK#691]
### How can we help?

[!] Unable to find a target named `OneSignalNotificationServiceExtension` in project `Runner.xcodeproj`, did find `Runner` and `OneSignalServiceNotificationExtension`.
after adding onesignalnotification extension in podfile and running pod install getting this error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elhe26** [comment]
Same

**Comment by benjaminhorner** [comment]
Same here. Any solution?

**Comment by Anderson-Andre-P** [comment]
Can you see if you are experiencing the same issue as issue 750?  If it's the same problem, we can work together on it and when there is a solution, we use it.

https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/750

**Comment by benjaminhorner** [comment]
@Anderson-Andre-P I am building on a Mac and I get the error when running `Pod install` inside the **ios** folder.

**Comment by babar7** [comment]
first follow `[Notification Service Extension](https://documentation.onesignal.com/docs/react-native-sdk-setup#notification-service-extension)` setup steps from the documentation after that run 
`pod install --repo-update`

**Comment by benjaminhorner** [comment]
@babar7 Thank you so much! I can't believe I missed that. However, this doesn't entirely solve the issue as now I am getting the following error: `The 'Pods-Runner' target has frameworks with conflicting names: onesignalframework.xcframework, onesignalcore.xcframework, onesignalextension.xcframework, onesignalinappmessages.xcframework, onesignalnotifications.xcframework, onesignaloscore.xcframework, onesignaloutcomes.xcframework, and onesignaluser.xcframework`

**Comment by xavidram** [comment]
But was your application able to be built on xcode? Following the steps in the issues linked in this thread, sure the app runs on flutter. But upon getting the application ready for deployment to test-flight. Xcode is unable to find `OneSignal`

<img width="415" alt="Screenshot 2023-10-14 at 3 12 46 AM" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/1348719/68cda4ed-6fdb-4a9f-9f4e-e34c15b3a355">

**Comment by Marcel0Henrique** [comment]
@Arpithaarha I faced the same issue and resolved it as follows: I manually created the target. In Xcode, go to "File" > "New" > "Target" > "Notification Service Extension." Fill in the necessary information, and then click "Cancel" when prompted to activate the scheme. This allows you to execute the `pod install` command and proceed with the installation guide.

If, when running `flutter run`, you encounter an error related to multiple build configurations, make sure to check the "Runner" and "OneSignal" targets. I resolved the issue by following these steps.

**Comment by bugrevealingbme** [comment]
same++

**Comment by jennantilla** [comment]
Appreciate the discussion and solutions provided here!

@bugrevealingbme since you are the only recent commenter--did the above workarounds help?

If not, please open a new issue with updated information on the problem you're facing.

Thanks!
