### ISSUE TITLE
[question]: How to close setNotificationWillShowInForegroundHandler & setNotificationOpenedHandler listener

### ISSUE THREAD

**Issue by tovidd** [OneSignal/OneSignal-Flutter-SDK#692]
### How can we help?

is there a way to close/remove `OneSignal.shared.setNotificationWillShowInForegroundHandler` & `OneSignal.shared.setNotificationOpenedHandler` listeners ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@tovidd apologies that your question was missed! I'm not sure what you mean by "closed" here; could you please provide some additional details on what you are wishing to accomplish?

We have released major updates to the [Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) which includes many improvements and enhancements. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details!

**Comment by jennantilla** [comment]
Closing due to no response.
