### ISSUE TITLE
[question]: How to disable ios PlatformException

### ISSUE THREAD

**Issue by Remas-Safi** [OneSignal/OneSignal-Flutter-SDK#693]
### How can we help?

I am using different methods of Onesignal, where I may for sure get errors, for example, `sendTags` will throw an error if the account is not upgraded, whereas for my app I have the account upgraded for the production environment but not the dev, so I need to disable logging for dev. 

For this and different kinds of errors I am handling it using `try.. catch` something like this:
```
         try {
          await oneSignalShared.sendTags({
            "name": user.fullName,
            "id": user.id.toString(),
          }).catchError((e) {
            log(e.toString());
            return {'': ''};
          });
        } catch (_) {}
```

**However, OneSignal is still throwing PlatformException for this, How can I disable this?** 

FYI, Not sure if this helps, but I've set the logs level to 
```
  oneSignalShared
        .setLogLevel(OSLogLevel.none, OSLogLevel.none)
```

Also the method `setAppId` says `The initializer for OneSignal. Note that this initializer accepts an iOSSettings object, in Android you can pass null.` but it only accepts the app id, and so far I can't find a way to disable this PlatformException, any hint will be a great help

**Comment by nan-li** [comment]
Hi @Remas-Safi,

Thanks for reaching out. It looks like there are a few things you are asking about.

1. For this question:

> However, OneSignal is still throwing PlatformException for this, How can I disable this?

Can you share the exception you are getting? For example:

```
Error: PlatformException(OneSignal, Encountered an error updating tags (400): {"errors":["App is limited to a maximum of 20 tags on a given player"],"success":false}, null, null)
```

2. I recommend during testing and debugging, you set `OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none)`. You will see more logs to figure out any errors. Then you can set it back to `OSLogLevel.none` for production.

3. I am sorry that this comment of `The initializer for OneSignal. Note that this initializer accepts an iOSSettings object, in Android you can pass null` is outdated and incorrect. You should only pass a `string` app ID. Is this method giving you an error?

**Comment by nan-li** [comment]
Hi @Remas-Safi My apologies that this question has gone stale.

I believe you should be able to find the source of the error in logs further up, in particular any logs that point out why "the current user is not registered with OneSignal". Perhaps some server requests previously failed.

If this question is still a current concern, please ping me.
