### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by figengungor** [OneSignal/OneSignal-Flutter-SDK#70]
**Description:**
Most of the packages are upgraded with AndroidX migration and OneSignal is the only one that is blocking me to migrate to AndroidX. Could you migrate to AndroidX, please? 

**Environment**
onesignal: ^1.1.0

**Comment by jkasten2** [comment]
@figengungor Can you try the suggestion here for your project?
https://github.com/OneSignal/OneSignal-Android-SDK/issues/687#issuecomment-452526164

I don't have specific Flutter instructions but I believe this file should be the same in your project. We will also look if there is a way to auto flag on Jetifier so this extra step won't be required.

**Comment by figengungor** [comment]
Huge thanks! We can close this now;)
