### ISSUE TITLE
[Bug]: I had a problem in Opening The App

### ISSUE THREAD

**Issue by mrsfoundations** [OneSignal/OneSignal-Flutter-SDK#705]
### What happened?

I integrate onesignal in wordpress and make notification to the flutter app when the new post is add in site. But The Main Issue is I got notification but when i click the notification but the app is not opening automatically instead of the wordpress site login page is opening.

### Steps to reproduce?

```Markdown
I Try to Block to block the url which opens the app automatically. But I can't do t. I made may functions but non of them dosen't working properly.
```

### What did you expect to happen?

I just Want to open the app automatically by clicking the notification.

### OneSignal Flutter SDK version

OneSignal Flutter SDK (3.3.2)

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mrsfoundations** [comment]
Please Fix The Bug As Soon As Possible!

**Comment by emawby** [comment]
@mrsfoundations Is there a launch url in your notification you are sending to the flutter app?

**Comment by mrsfoundations** [comment]
@emawby Yes Dude, the notification is coming from wordpress,if there is any post added or old post is updated means notification will reach the user. Becz all the post are showing in the app.

**Comment by emawby** [comment]
The purpose of the launch url is to deep link from the notification to the url. Since you set the launch url to be the wordpress site it will launch the site not your app

**Comment by mrsfoundations** [comment]
@emawby Thanks dude now I fix it. But the app is not automatically launched when I click the notification how to fix this?

**Comment by emawby** [comment]
@mrsfoundations What happens now when you tap the notification? Does a url open or does nothing happen at all?

**Comment by jennantilla** [comment]
Closing due to no response. @mrsfoundations if you are still having problems please submit a new issue and we'll be happy to resume investigation!
