### ISSUE TITLE
How to pass argument with route name?

### ISSUE THREAD

**Issue by vniroshan** [OneSignal/OneSignal-Flutter-SDK#706]
How to pass argument with route name?

{
  "app_id": "YOUR_APP_ID",
  "included_segments": ["All"],
  "data": {
    "target": "specific_page",
    "page_id": "page_identifier"
  },
  "contents": {
    "en": "Notification message"
  }
}

**Comment by jennantilla** [comment]
Hello @vniroshan, I'm going to close this issue as it has become stale. If you are still having any problems, please open a new issue and we'll be happy to assist!
