### ISSUE TITLE
[question]: get tags in new sdk?

### ISSUE THREAD

**Issue by zvikarp** [OneSignal/OneSignal-Flutter-SDK#708]
### How can we help?

I can't figure out how to get the user's tags in the new SDK `5.0.0`, the old method was `OneSignal.shared.getTags()`.

Looked through the docs and the migration guide.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giangdk** [comment]
same issue

**Comment by agarwalrohit2503** [comment]
Same issue

**Comment by malsharaf** [comment]
same issue

**Comment by GauthierDepierre** [comment]
same issue

**Comment by hosaysg** [comment]
It is now 5.0.4 and gettags is still not supported???

**Comment by nan-li** [comment]
Hi all,

The method `getTags` was deliberately removed in `v5` to discourage the use of OneSignal as a data store. User data should primarily be managed by the app developer and live on the app developer's servers.

However, from feedback we received, we added `getTags` back to our native Android and iOS SDKs, and will be available in the next release of the Flutter SDK. It will return the local tags and will not result in a server fetch, so tags added via the REST API may not be reflected until the SDK pulls data.

**Comment by GauthierDepierre** [comment]
Great news! Thanks for the update.
Would you have any release timeline to share for this?

**Comment by GauthierDepierre** [comment]
Hello @nan-li and thanks again or your feedback. I've started to see the getTags() method appearing back in documentation but not yet for Flutter. Any chance you have a release timeline in mind for Flutter SDK 5.0.5 integrating this method? Many thanks.

**Comment by dgilperez** [comment]
Hi! Just wondering when this would be available, as it's blocking our sdk upgrade.

**Comment by jennantilla** [comment]
Hello everyone! Apologies that we missed updating this issue but `getTags` is now available on our Flutter User Model SDK. Please upgrade to our [latest version](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) to begin using it! 

Thanks!
