### ISSUE TITLE
[Bug]: lambda expressions are not supported in -source 7

### ISSUE THREAD

**Issue by giangdk** [OneSignal/OneSignal-Flutter-SDK#710]
### What happened?

/Users/mac/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-5.0.0/android/src/main/java/com/onesignal/flutter/OneSignalNotifications.java:77: error: lambda expressions are not supported in -source 7
        OneSignal.getNotifications().requestPermission(fallback, Continue.with(permissionResult -> {
                                                                                          ^
  (use -source 8 or higher to enable lambda expressions)

### Steps to reproduce?

```Markdown
1. install onesignal 5.0.0
2. setup onesignal for android
3. build app
4. error:
/Users/mac/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal_flutter-5.0.0/android/src/main/java/com/onesignal/flutter/OneSignalNotifications.java:77: error: lambda expressions are not supported in -source 7
        OneSignal.getNotifications().requestPermission(fallback, Continue.with(permissionResult -> {
                                                                                          ^
  (use -source 8 or higher to enable lambda expressions)
```

### What did you expect to happen?

not error

### OneSignal Flutter SDK version

5.0.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
private void requestPermission(MethodCall call, Result result) {
        boolean fallback = (boolean) call.argument("fallbackToSettings");
        OneSignal.getNotifications().requestPermission(fallback, Continue.with(permissionResult -> {
            replySuccess(result, permissionResult.getData());
        }));
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by talkbiz** [comment]
I just face similar issue. Any solution?

**Comment by wupengbigMarker** [comment]
I got the same issue. Did you fix this? @giangdk @talkbiz

**Comment by talkbiz** [comment]
> I got the same issue. Did you fix this? @giangdk @talkbiz 

I abandoned the plugin
