### ISSUE TITLE
[Feedback]: Migration guide from 3.5.1 to 5.0.0

### ISSUE THREAD

**Issue by Fudal** [OneSignal/OneSignal-Flutter-SDK#711]
### What's on your mind?

We need migration guide from 3.5.1 to 5.0.0.

A lot of methods have been added or changed. The version jump itself testifies to this, but no migration guide has been presented to us, so users are confused.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petodavid** [comment]
Here is the migration guide:

https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/user_model/main/MIGRATION_GUIDE.md

**Comment by Fudal** [comment]
@petodavid okay, thanks. But I can't see anywhere what should I replace these methods:
1. `OneSignal.shared.setExternalUserId(userId)`
2. `OneSignal.shared.setNotificationWillShowInForegroundHandler((OSNotificationReceivedEvent event)`
3. `OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result)`
4. `OneSignal.shared.promptUserForPushNotificationPermission()`

**Comment by xunreal75** [comment]
Please update docs and example

```
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '5.0.1'
end
```

is necessary for iOS to get Pod installed

**Comment by emawby** [comment]
Thank you for the feedback we will work on clarifying the migration steps!

**Comment by wahyu-handayani** [comment]
> @petodavid okay, thanks. But I can't see anywhere what should I replace these methods:
> 
> 1. `OneSignal.shared.setExternalUserId(userId)`
> 2. `OneSignal.shared.setNotificationWillShowInForegroundHandler((OSNotificationReceivedEvent event)`
> 3. `OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result)`
> 4. `OneSignal.shared.promptUserForPushNotificationPermission()`

I have the same case like yours, did you find any solution ?

**Comment by Fudal** [comment]
@wahyu-handayani no, I'm still using 3.5.1 version

**Comment by huszm** [comment]
@Fudal @wahyu-handayani 
The solution from me are
change `OneSignal.shared.setNotificationOpenedHandler`  to `OneSignal.Notifications.addClickListener`

**Comment by xunreal75** [comment]
Hi this should help you to get started Onesignal V5.0.0

```dart
  if (kDebugMode) {
        OneSignal.Debug.setAlertLevel(OSLogLevel.none);
        OneSignal.Debug.setLogLevel(OSLogLevel.verbose);
      } else {
        OneSignal.Debug.setAlertLevel(OSLogLevel.none);
        OneSignal.Debug.setLogLevel(OSLogLevel.none);
      }

      OneSignal.initialize(oneSignalAppId); //init with your appid
      OneSignal.Location.setShared(false); //avoid location sharing

      OneSignal.Notifications.addForegroundWillDisplayListener((event) {
      });

      OneSignal.Notifications.addPermissionObserver((state) {
         //log.i(text: 'Accepted Onesignal permission: $state');
      });

      OneSignal.InAppMessages.addWillDisplayListener((event) {
        //log.i(text: 'inAppMessage ${event.message}');
      });


      OneSignal.Notifications.addClickListener((event) {
        //var json = action.jsonRepresentation();
        var clickName = event.result.actionId;
        var clickURL = event.notification.launchUrl;
        var title = event.notification.title;
        var body = event.notification.body;
        ...
        }
```

**Comment by wahyu-handayani** [comment]
> @wahyu-handayani no, I'm still using 3.5.1 version

I try to install onesignal using this version, may I take a look your ```Podfile``` and ```NotificationService.m``` (inside ios/OneSignalNotificationServiceExtension/ folder)

**Comment by Fudal** [comment]
@wahyu-handayani 

Sure, here is `NotificationService.m`:
```
//
//  NotificationService.m
//  OneSignalNotificationServiceExtension
//
//  Created by Brad Hesse on 7/13/18.
//  Copyright © 2018 The Chromium Authors. All rights reserved.
//

#import <OneSignal/OneSignal.h>

#import "NotificationService.h"

@interface NotificationService ()

@property (nonatomic, strong) void (^contentHandler)(UNNotificationContent *contentToDeliver);
@property (nonatomic, strong) UNNotificationRequest *receivedRequest;
@property (nonatomic, strong) UNMutableNotificationContent *bestAttemptContent;

@end

@implementation NotificationService

- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {
    self.receivedRequest = request;
    self.contentHandler = contentHandler;
    self.bestAttemptContent = [request.content mutableCopy];
    
    [OneSignal didReceiveNotificationExtensionRequest:self.receivedRequest withMutableNotificationContent:self.bestAttemptContent withContentHandler:self.contentHandler];
}

- (void)serviceExtensionTimeWillExpire {
    // Called just before the extension will be terminated by the system.
    // Use this as an opportunity to deliver your "best attempt" at modified content, otherwise the original push payload will be used.
    
    [OneSignal serviceExtensionTimeWillExpireRequest:self.receivedRequest withMutableNotificationContent:self.bestAttemptContent];
    
    self.contentHandler(self.bestAttemptContent);
}

@end

```

here `Podfile`:
```
# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|

   target.build_configurations.each do |config|
        # Here are some configurations automatically generated by flutter
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',

          ## dart: PermissionGroup.calendar
          # 'PERMISSION_EVENTS=0',

          ## dart: PermissionGroup.reminders
          'PERMISSION_REMINDERS=0',

          ## dart: PermissionGroup.contacts
          # 'PERMISSION_CONTACTS=0',

          ## dart: PermissionGroup.camera
          'PERMISSION_CAMERA=1',

          'PERMISSION_ACTIVITY_RECOGNITION=1',

          ## dart: PermissionGroup.microphone
          # 'PERMISSION_MICROPHONE=1',

          ## dart: PermissionGroup.speech
          # 'PERMISSION_SPEECH_RECOGNIZER=0',

          ## dart: PermissionGroup.photos
          'PERMISSION_PHOTOS=0',

          ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
          # 'PERMISSION_LOCATION=0',

          ## dart: PermissionGroup.notification
          'PERMISSION_NOTIFICATIONS=1',

          ## dart: PermissionGroup.mediaLibrary
          'PERMISSION_MEDIA_LIBRARY=0',

          ## dart: PermissionGroup.sensors
          # 'PERMISSION_SENSORS=1',

          ## dart: PermissionGroup.bluetooth
          # 'PERMISSION_BLUETOOTH=0',
        ]
      end
    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by wahyu-handayani** [comment]
> 

Hi thank you so much for your help, I am really really really sorry for disturbing you but can I take a look at your xcode configuration (part ```build setting``` of ```OneSignalNotificationServiceExtension```) ? because I have this log when running pod install:
```
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[!] The `OneSignalNotificationServiceExtension [Debug]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `OneSignalNotificationServiceExtension [Release]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `OneSignalNotificationServiceExtension [Profile]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.profile.xcconfig'. This can lead to problems with the CocoaPods installation
```
and here is my xcode configuration :
<img width="1132" alt="Screenshot 2023-09-06 at 14 14 16" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/55479207/7acbbf6a-4bd9-49e7-8b8f-6957002ac076">

**Comment by Fudal** [comment]
@wahyu-handayani  No problem ;)

I don't have that target 
![Zrzut ekranu 2023-09-6 o 09 20 55](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/13346676/4801d8b0-1ced-4aaf-bd0a-901d3544e127)

**Comment by wahyu-handayani** [comment]
> @wahyu-handayani No problem ;)
> 
> I don't have that target ![Zrzut ekranu 2023-09-6 o 09 20 55](https://user-images.githubusercontent.com/13346676/265926604-4801d8b0-1ced-4aaf-bd0a-901d3544e127.png)

Thank you so so sooooooooo much @Fudal for your help, I am still strugling to fix one error left, your helps really makes my day

**Comment by tovidd** [comment]
1. Not sure about this `OneSignal.shared.setExternalUserId`
2. `OneSignal.shared.setNotificationWillShowInForegroundHandler` to `OneSignal.Notifications.addForegroundWillDisplayListener`
3. `OneSignal.shared.setNotificationOpenedHandler` to `OneSignal.Notifications.addClickListener`
4. `OneSignal.shared.promptUserForPushNotificationPermission` to `await OneSignal.Notifications.requestPermission(true)`

I still have problem with android background notification, don't know why `NotificationServiceExtension` is error.

**Comment by husainazkas** [comment]
Please update migration guide as described on the comment reference. All of these methods are missing without any replacement instruction.

> @petodavid okay, thanks. But I can't see anywhere what should I replace these methods:
> 
> 1. `OneSignal.shared.setExternalUserId(userId)`
> 2. `OneSignal.shared.setNotificationWillShowInForegroundHandler((OSNotificationReceivedEvent event)`
> 3. `OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result)`
> 4. `OneSignal.shared.promptUserForPushNotificationPermission()`

**Comment by michael-joseph-payne** [comment]
I have yet to get iOS to finish building using this guide or any of the pending PR changes to it.

**Comment by Fudal** [comment]
@emawby  We are still waiting for more information about right migration from 3.5.1 version.

**Comment by lukeurban** [comment]
Deprecation would be nice first. Throwing braking changes randomly to a product is a weak move NGL.

**Comment by elsegund0** [comment]
how can i fix this?

The getter 'shared' isn't defined for the type 'OneSignal'.
Undefined class 'OSNotificationOpenedResult'.
Undefined class 'OSNotificationReceivedEvent'.

**Comment by Fudal** [comment]
@emawby or @nan-li can you help us?
I didn't find solution in example file.

**Comment by rignaneseleo** [comment]
How do I disable the foreground notifications in the new SDK? 
In the old one, it was:
```
OneSignal.shared.setNotificationWillShowInForegroundHandler((OSNotificationReceivedEvent event) {
  // Display Notification, send null to not display, send notification to display           
  event.complete(event.notification);      
}); 
```

In the new SDK `event` doesn't have the `complete` func.

**Comment by nandakista** [comment]
> How do I disable the foreground notifications in the new SDK? In the old one, it was:
> 
> ```
> OneSignal.shared.setNotificationWillShowInForegroundHandler((OSNotificationReceivedEvent event) {
>   // Display Notification, send null to not display, send notification to display           
>   event.complete(event.notification);      
> }); 
> ```
> 
> In the new SDK `event` doesn't have the `complete` func.

Same problem here, there is `event.preventDefault` but its completely blocks push notification. I need the app still get notification but not showing in the foreground.
Is there any solution please ?

**Comment by hosaysg** [comment]
How to retrieve tags?

**Comment by nan-li** [comment]
Hi all,

I apologize we don't have a direct v3 -> v5 migration guide yet showing the appropriate replacements. All available methods of the major release are outline [here](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/user_model/main/MIGRATION_GUIDE.md).

@tovidd is correct about the methods and the replacement for `setExternalUserId` is the `OneSignal.login("EXT_ID")` method.

To address this comment
> Deprecation would be nice first. Throwing braking changes randomly to a product is a weak move NGL.

The `v3.x.x` OneSignal Flutter SDK is still supported, but the **major release** of `v5.x.x` does introduce breaking changes if you upgrade.

@rignaneseleo you can call `preventDefault` to disable foreground notifications. Please see the [guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/user_model/main/MIGRATION_GUIDE.md) for how to use.

@nandakista Can you tell me more about this issue you are running into?

**Comment by caini1213** [comment]
hi, would like to ask what's the replacement for OneSignal.shared.getDeviceState() ?

**Comment by shanelau** [comment]
How to call `event.complete(null)` in version 5.0.4?
I need the app still get notification but not showing in the foreground.

**Comment by bugrevealingbme** [comment]
Login method is not working instead of setExternalUserId. I don't know what it does but nothing happens. Android/ios. This is important bug

**Comment by nan-li** [comment]
Hi @shanelau I apologize for the delay, we have an example in the migration guide on the [Notification Will Display Listener](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/user_model/main/MIGRATION_GUIDE.md#notification-will-display-listener):
```
OneSignal.Notifications.addForegroundWillDisplayListener((event) {
	/// preventDefault to not display the notification
	event.preventDefault();

	/// Do async work

	/// notification.display() to display after preventing default
	event.notification.display();
});
```

**Comment by nan-li** [comment]
Hi @bugrevealingbme,

Can you share more details about Login method is not working?

**Comment by shanelau** [comment]
> Hi @shanelau I apologize for the delay, we have an example in the migration guide on the [Notification Will Display Listener](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/user_model/main/MIGRATION_GUIDE.md#notification-will-display-listener):
> 
> ```
> OneSignal.Notifications.addForegroundWillDisplayListener((event) {
> 	/// preventDefault to not display the notification
> 	event.preventDefault();
> 
> 	/// Do async work
> 
> 	/// notification.display() to display after preventing default
> 	event.notification.display();
> });
> ```

Nice work. It works on  onesignal_flutter: ^5.1.0

**Comment by Parvxi** [comment]
> event.complete(null)

did u fine a solution?

**Comment by jhandaya** [comment]
Where is postNotification method ?



    final notification = OSCreateNotification(
        playerIds: listOneSignalUserId,
        androidSmallIcon: 'ic_stat_one_signal_default',
        androidLargeIcon: 'ic_stat_one_signal_default',
        content: message,
        androidSound: sound,
        heading: title,
        languageCode: 'en',
        iosAttachments: {
          "id1": imgUrlString
        },
        //url: url,
        //bigPicture: imgUrlString,
        buttons: [
          OSActionButton(text: "OK", id: "id1"),
        ]);

    var response = await OneSignal.shared.postNotification(notification);

**Comment by michelemanniello** [comment]
same problem, any solution?

**Comment by sherwinski** [comment]
> Where is postNotification method ?
> 
> ```
> final notification = OSCreateNotification(
>     playerIds: listOneSignalUserId,
>     androidSmallIcon: 'ic_stat_one_signal_default',
>     androidLargeIcon: 'ic_stat_one_signal_default',
>     content: message,
>     androidSound: sound,
>     heading: title,
>     languageCode: 'en',
>     iosAttachments: {
>       "id1": imgUrlString
>     },
>     //url: url,
>     //bigPicture: imgUrlString,
>     buttons: [
>       OSActionButton(text: "OK", id: "id1"),
>     ]);
> 
> var response = await OneSignal.shared.postNotification(notification);
> ```
> 
> any solution to post a notification from version 5 ?

My understanding is that the method was removed partly for security reasons, since the SDK could be used to send notifications to other users. In this case, the team recommends using the REST API instead.

**Comment by sherwinski** [comment]
I'm going to close this issue now but will encourage any users who have similar questions about the migration guide to open a separate issue per question. Thanks
