### ISSUE TITLE
[Bug]: Getting crash when running release build

### ISSUE THREAD

**Issue by dchandrani** [OneSignal/OneSignal-Flutter-SDK#713]
### What happened?

Implemented OneSignal version 5.0.0 in Flutter app, but when tried to run the app in release mode I got a FATAL EXCEPTION saying Unable to start receiver com.onesignal.notifications.receivers.UpgradeReceiver: java.lang.Exception: Service class e7.b could not be instantiated.

### Steps to reproduce?

```Markdown
1. Install onesignal_flutter: ^5.0.0

2. Launch the Android app in release mode

3. Note the crash in debug console
```

### What did you expect to happen?

I expected to receive call back of OneSignal.User.pushSubscription.addObserver to get user id.

### OneSignal Flutter SDK version

5.0.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
E/AndroidRuntime(11216): FATAL EXCEPTION: main
E/AndroidRuntime(11216): Process: com.voliz, PID: 11216
E/AndroidRuntime(11216): java.lang.RuntimeException: Unable to start receiver com.onesignal.notifications.receivers.UpgradeReceiver: java.lang.Exception: Service class e7.b could not be instantiated
E/AndroidRuntime(11216):        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4485)
E/AndroidRuntime(11216):        at android.app.ActivityThread.access$1900(ActivityThread.java:254)
E/AndroidRuntime(11216):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2195)
E/AndroidRuntime(11216):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(11216):        at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(11216):        at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(11216):        at android.app.ActivityThread.main(ActivityThread.java:8212)
E/AndroidRuntime(11216):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11216):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(11216):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/AndroidRuntime(11216): Caused by: java.lang.Exception: Service class e7.b could not be instantiated
E/AndroidRuntime(11216):        at u6.c.i(ServiceProvider.kt:59)
E/AndroidRuntime(11216):        at f8.a.l(OneSignalImp.kt:79)
E/AndroidRuntime(11216):        at o6.d.j(OneSignal.kt:13)
E/AndroidRuntime(11216):        at com.onesignal.notifications.receivers.UpgradeReceiver.onReceive(UpgradeReceiver.kt:18)
E/AndroidRuntime(11216):        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4469)
E/AndroidRuntime(11216):        ... 9 more
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Wiwo99** [comment]
me too

**Comment by rafaelbarbosadrip** [comment]
me too

**Comment by Jakoo13** [comment]
I am seeing this as well. In version 5 after all proper migration and app working in debug, in release build the OneSignal.initialize(appId) is not working.

**Comment by sur2548** [comment]
Same for me as well, all the classes from the OneSignal are getting removed in the production build.

**Comment by Kuodster** [comment]
Same problem here, only after building the apk.

**Comment by Chhay67** [comment]
any solution ???

**Comment by dchandrani** [comment]
Try the above solution by @sur2548

**Comment by PhamChiNang151020** [comment]
> @Chhay67 You can try the above solution by @sur2548

I tried to try, but now my Apk file is still not registered for OneSignal control version

![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/87531241/83400bbb-39bd-49ec-8f67-ba72c99fc9e6)
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/87531241/a8488f8e-da01-4b28-9d4e-14c137e00a8d)

**Comment by sur2548** [comment]
> > @Chhay67 You can try the above solution by @sur2548
> 
> I tried to try, but now my Apk file is still not registered for OneSignal control version
> 
> ![image](https://user-images.githubusercontent.com/87531241/263663693-83400bbb-39bd-49ec-8f67-ba72c99fc9e6.png) ![image](https://user-images.githubusercontent.com/87531241/263663794-a8488f8e-da01-4b28-9d4e-14c137e00a8d.png)

@PhamChiNang151020  Do not initialize directly in the main function.

https://documentation.onesignal.com/docs/flutter-sdk-setup#step-5-set-up-onesignal-for-android

**Comment by PhamChiNang151020** [comment]
> 

Sorry, But I initialize by `main.dart` 

And, `buildTypes` in the path `android/app/build.gradle`

If I'm doing something wrong, please help. Thank you!

**Comment by sur2548** [comment]
@PhamChiNang151020 You can follow the official doc or Could you move the initialization to the app level?

Anyway there is a PR for this, you can check that as well

https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/716

**Comment by emawby** [comment]
The latest release 5.0.1 adds the proguard rules to Android release builds that should resolve this issue. If that is not the case please tag me here!

**Comment by edisonlsm** [comment]
@emawby I keep getting errors related to the flutter **plugin** android code on Crashlytics. Maybe those should also not be minified?

(Those crashes happened on version 5.0.4)
![Captura de Tela 2024-02-01 às 13 17 44](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/4001673/bda53bf1-1e73-42fe-9dab-bc9a4c385770)

Checking on mapping.txt after a release build, it seems that the plugin code are getting minified
![Captura de Tela 2024-02-01 às 13 19 06](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/4001673/4e8ac91b-87da-481d-b7fe-90df06f63830)

**Comment by sur2548** [comment]
> @emawby I keep getting errors related to the flutter **plugin** android code on Crashlytics. Maybe those should also not be minified?
> 
> (Those crashes happened on version 5.0.4) ![Captura de Tela 2024-02-01 às 13 17 44](https://private-user-images.githubusercontent.com/4001673/301571401-bda53bf1-1e73-42fe-9dab-bc9a4c385770.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODI2MDIsIm5iZiI6MTcwNjg4MjMwMiwicGF0aCI6Ii80MDAxNjczLzMwMTU3MTQwMS1iZGE1M2JmMS0xZTczLTQyZmUtOWRhYi1iYzlhNGMzODU3NzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTM1ODIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmI4ODA2ZGJjYWM1Y2U3M2VkOTgyZGY1YmZhMWFkYTA0MDczZTQ1NjQ0YzQzNjRlOGQyNmQ2ZDAyZDIyYTVhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZznW6zcC6ZTxaN0iyj_GiDR3hXOEqafIGIr46IkelQE)
> 
> Checking on mapping.txt after a release build, it seems that the plugin code are getting minified ![Captura de Tela 2024-02-01 às 13 19 06](https://private-user-images.githubusercontent.com/4001673/301571845-4e8ac91b-87da-481d-b7fe-90df06f63830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODI2MDIsIm5iZiI6MTcwNjg4MjMwMiwicGF0aCI6Ii80MDAxNjczLzMwMTU3MTg0NS00ZThhYzkxYi04N2RhLTQ4MWQtYjdmZS05MGRmMDZmNjM4MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTM1ODIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2U2YzgxZmU5MjhlMDkyMmRjYTViZTc4OGEwNTk0MDE1MGU0NGM4NWZiMThlY2QzMjBlZmJhNjYyZjI5NzZiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4v9662StXtxy_hWd5zhcMg40ibvrHC6glJxp_iIKGto)

Same for me as well, for some devices it is crashing

**Comment by rickgrotavi** [comment]
> @emawby I keep getting errors related to the flutter **plugin** android code on Crashlytics. Maybe those should also not be minified?
> 
> (Those crashes happened on version 5.0.4) ![Captura de Tela 2024-02-01 às 13 17 44](https://private-user-images.githubusercontent.com/4001673/301571401-bda53bf1-1e73-42fe-9dab-bc9a4c385770.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzA5OTQsIm5iZiI6MTcxMjkzMDY5NCwicGF0aCI6Ii80MDAxNjczLzMwMTU3MTQwMS1iZGE1M2JmMS0xZTczLTQyZmUtOWRhYi1iYzlhNGMzODU3NzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTQwNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjk4ZDRiNTkwNmI4YTNkMWJkZTk1YmM1YWQ1OWMwZTNiZTYzMDQyODEyMmUxMWU3MjFkNzViMjBmNjQ3NTc3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PqcYGrU1GrpsDTU4Lwf1U3-onNCH5cQQDAaR8qMDzm8)
> 
> Checking on mapping.txt after a release build, it seems that the plugin code are getting minified ![Captura de Tela 2024-02-01 às 13 19 06](https://private-user-images.githubusercontent.com/4001673/301571845-4e8ac91b-87da-481d-b7fe-90df06f63830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MzA5OTQsIm5iZiI6MTcxMjkzMDY5NCwicGF0aCI6Ii80MDAxNjczLzMwMTU3MTg0NS00ZThhYzkxYi04N2RhLTQ4MWQtYjdmZS05MGRmMDZmNjM4MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTQwNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzI5MzkzMjVmMTJkZDE3YWQyMGJmY2JhMWY5YTNhYmFiY2E2ZTkzMDlkOWI1ODZiNGMyY2EyNmEwNTM3ZWI5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x7cYJtsf9AdGb3lCitheljWse7FeYnTKIXzHwzWocpE)

Got the same on Huawei device. On other devices with google - is ok.

**Comment by jkasten2** [comment]
@edisonlsm @sur2548 @rickgrotavi can you share the version of OneSignal you are using and the proguard / minification rules you are using in your app?

**Comment by rickgrotavi** [comment]
> @edisonlsm @sur2548 @rickgrotavi can you share the version of OneSignal you are using and the proguard / minification rules you are using in your app?

onesignal_flutter: 5.1.4

 ` -keep class com.onesignal.** {*;}`  in proguard-rules.pro

app/build.gradle
`   buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
}`

**Comment by alikamal1** [comment]
include in `proguard-rules.pro`
```
-keepattributes Signature
-keep class com.onesignal.** { *; }
```
