### ISSUE TITLE
[Bug]: IOS not displaying buttons in push notification

### ISSUE THREAD

**Issue by felixmede** [OneSignal/OneSignal-Flutter-SDK#715]
### What happened?

When sending a push notifications with buttons those are not getting displayed in the notification

Happened on an iPhone 13 IOS 16.6

### Steps to reproduce?

```Markdown
1. setup an app with sdk version 5.0.0
2. start up the app
3. send a push notification with one or more buttons
4. check the notification on the phone
```

### What did you expect to happen?

displaying the buttons in the notification

### OneSignal Flutter SDK version

5.0.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@felixmede Hello I am not able to reproduce this. When I tap and hold on the notification the buttons are displaying for me. Are you able to print the description of the notification to see if the buttons were properly attached?
