### ISSUE TITLE
[question]: After updating to onesignal_flutter 5.0.0, Android Studio fails when runs the app on ios simulator

### ISSUE THREAD

**Issue by robisoft** [OneSignal/OneSignal-Flutter-SDK#717]
### How can we help?

When I try to launch the app to ios simulator with Android Studio, I obtain this error:
Found bundle at /Users/robi/Library/Developer/CoreSimulator/Devices/2B45D66C-F987-40E0-A65F-0F3925E7CF97/data/Library/Caches/com.apple.mobile.installd.staging/temp.tzb4qC/extracted/Payload/Runner.app/Frameworks/OneSignalFramework.framework with the same identifier (com.onesignal.OneSignal-Dynamic) as bundle at /Users/robi/Library/Developer/CoreSimulator/Devices/2B45D66C-F987-40E0-A65F-0F3925E7CF97/data/Library/Caches/com.apple.mobile.installd.staging/temp.tzb4qC/extracted/Payload/Runner.app/Frameworks/OneSignal.framework
Underlying error (domain=IXUserPresentableErrorDomain, code=1):

OneSignalFramework.framework vs OneSignal.framework ??

Compile APK in Android Studio -> ok
Compile the app in xcode -> ok
Run on ios simulator with xcode -> ok
Run on ios simulator with Android Studio -> error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WaiChungK** [comment]
Hey I had the same issue and I managed to fix it by deleting the build folder and trying to run it again

**Comment by jennantilla** [comment]
Hello @robisoft! Was the previous response helpful? I'm going to close out this issue but if you are still having problems upgrading please let us know.

Here is our full [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for all upgrade details.

Thanks!
