### ISSUE TITLE
[question]: [Flutter] - .apk file cannot be registered on OneSignal

### ISSUE THREAD

**Issue by PhamChiNang151020** [OneSignal/OneSignal-Flutter-SDK#718]
### How can we help?

I go into debug mode, my console still shows "**Subscriptions**".

But when I build the .apk. Then the OneSignal dashboard is not showing and find "**Subscriptions**" on. I have tried deleting and reinstalling but still not working.

Information:

```
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version
    10.0.19045.3324], locale en-US)
    • Flutter version 3.7.7 on channel stable at D:\Enviroments\flutter       
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (6 months ago), 2023-03-08 09:41:59 -0800 
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
```

In `pubspec.yaml` : 

`onesignal_flutter: ^5.0.0`

In `main.dart`

```
  OneSignal.initialize(keyOneSignalNotifier.value);
  OneSignal.Notifications.requestPermission(true);
```

![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/87531241/dd3e3361-d493-45d7-894a-e9d97511a378)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wesleytoshio** [comment]
Same problem... this error only in release mode
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/7057737/dbac7992-820c-4661-823a-3c550fc2f2ca)

**Comment by pnilkanth12** [comment]
Hi @wesleytoshio 
I face same problem in release mode
Have you find any solution?

**Comment by VanToan08** [comment]
Hi @wesleytoshio @pnilkanth12
I face same problem in release mode
Have you find any solution?

**Comment by andredealmei** [comment]
same here in release

**Comment by Aksoyhlc** [comment]
Add the permission line above the initialize line and put await at the beginning. Run initialize if user allows, otherwise don't run.

**Comment by wahyu-handayani** [comment]
I have the same problem, is there any update ?

**Comment by sherwinski** [comment]
Hello! Apologies that this question has gone stale.
If this question is still a current concern, please feel free to ping me or open a new issue with updated information that we can use to investigate.
