### ISSUE TITLE
Notification badge does not go away on android

### ISSUE THREAD

**Issue by lifenautjoe** [OneSignal/OneSignal-Flutter-SDK#72]
For android, the notification badge icon on the menu never goes away, even when opening the app like it does for iOS. Is this intended?

**Comment by lifenautjoe** [comment]
I've seen some people stating the notifiaction has to be cancelled on the phone. I don't see this method in the flutter SDK...

**Comment by romatroskin** [comment]
Having the same issue on some phones like Samsung S9 Plus with android 8.0.0

**Comment by rgomezp** [comment]
That's correct. This is something that Android has made the standard behavior and we follow that standard. If you want to take control of the badges yourself, you can do so but you will have to manage them entirely yourself. We use the library [ShortcutBadger](https://github.com/leolin310148/ShortcutBadger) which you can also use if you would like.

See our docs for more info on [disabling badges](https://documentation.onesignal.com/docs/android-native-sdk#section-disable-badges)
