### ISSUE TITLE
[Bug]: 3.5.1 not working for IOS (simulator and real device) platfrom at all!

### ISSUE THREAD

**Issue by DevTwana** [OneSignal/OneSignal-Flutter-SDK#722]
### What happened?

ok, so I have a big project which is very old and I want to make it work for IOS devices also, but seems like version 3.5.1 doesn't work for ios, please don't provide me notification about oneSignal flutter SDK, because I have tried all and it doesn't work. if there is any solutions please provide me with anything, I would really appreciate it.
note: for version 5.0.0 it works, but not for 3.5.1.

### Steps to reproduce?

```Markdown
1. Requirements
2. Add the OneSignal Flutter SDK
3. Add an iOS Service Extension (iOS Apps Only)
...etc
```

### What did you expect to happen?

I expected the app to work for ios and get notification either on real device or simulator.

### OneSignal Flutter SDK version

Release 3.5.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- @brayden-onesignal

**Comment by emawby** [comment]
@DevTwana Hello can you clarify what you mean by "doesn't work". What is not working? Are you able to get a device subscribed in the dashboard and it is just not receiving push notifications or are you not able to setup OneSignal at all?

**Comment by jennantilla** [comment]
Closing due to no response. @DevTwana if you are still having problems please submit a new issue and we'll be happy to take a look. Thanks!
