### ISSUE TITLE
Xcode Cloud build failed for Flutter with 'OneSignal/OneSignal.h' file not found error

### ISSUE THREAD

**Issue by VikramZala93** [OneSignal/OneSignal-Flutter-SDK#726]
### How can we help?

I am integrating of Xcode Cloud with Flutter iOS project with OneSignal. But getting the following error while uploading the TestFlight with OneSignal integration. Kindly review the attached screenshots for your reference and share the your valuable suggestions. Thanks!

![Screenshot 2023-09-01 at 8 59 17 PM](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/115026584/d9e68388-1acb-4cdd-b259-4c642990b311)

![Screenshot 2023-09-01 at 8 59 06 PM](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/115026584/3202a97a-8036-4d19-9eae-a8da4b70ec50)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by hnvn** [comment]
Use `OneSignalFramework` instead of `OneSignal`
https://stackoverflow.com/a/76936307/3693334

**Comment by emawby** [comment]
Correct! Updated migration steps are added to the migration guide to clarify the new iOS setup in #744
