### ISSUE TITLE
[Bug]: OneSignal.Notifications.permission is not updated until next session [iOS]

### ISSUE THREAD

**Issue by cgutierr-zgz** [OneSignal/OneSignal-Flutter-SDK#734]
### What happened?

In **iOS**, when you ask for permissions and they get accepted, `OneSignal.Notifications.permission` keeps on giving `false` until the next session.

(I have not tested this in any other platform apart of iOS)

### Steps to reproduce?

```Markdown
1. Initialize OneSignal

2. Check the Notifications permissions:
final granted = OneSignal.Notifications.permission;
granted = false

3. Request Permissions:
final requestGranted = await OneSignal.Notifications.requestPermission(false);
requestGranted = true

3. Check the Notifications permissions again:
final granted = OneSignal.Notifications.permission;
granted = false

---

It's not until you re-launch the app when we get:
final granted = OneSignal.Notifications.permission;
granted = true
```

### What did you expect to happen?

After the permissions have been accepted the value that `OneSignal.Notifications.permission` should be updated to true (if accepted)

### OneSignal Flutter SDK version

5.0.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@cgutierr-zgz Thank you for reporting we are working on a fix for this!

**Comment by emawby** [comment]
Closing with the release of 5.0.1

**Comment by burhanaksendir** [comment]
@emawby  I am using onesignal_flutter 5.1.0. The same issue persists. I would appreciate it if you could help.

**Comment by nan-li** [comment]
Hi @burhanaksendir can you share your reproduction steps?
Are they exactly the same steps as the original reporter?
Also, can you try with a delay between accepting permission and checking for permission? Seeing if it could be a race condition.

**Comment by burhanaksendir** [comment]
Hi @nan-li ,
Yes, as in the original reporter's steps. I followed these steps:
Executed Prompt for Push Permission: OneSignal.Notifications.requestPermission(true);
Granted permission for notifications.
Then printed OneSignal.Notifications.permission using print: Result returned as true.
Subsequently, closed and reopened the application.
Upon printing OneSignal.Notifications.permission again, it returned 'false'.

Both Android and iOS platforms exhibit the same issue.

```
Flutter (Channel stable, 3.19.0, on macOS 14.3.1 23D60 darwin-arm64, locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.2)
[✓] Network resources
```
