### ISSUE TITLE
getDeviceState is missing

### ISSUE THREAD

**Issue by berkaymazlumlar** [OneSignal/OneSignal-Flutter-SDK#736]
Can't use getDeviceState method with new version. I looked documentation but didn't see any information about this. What could I use instead?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@berkaymazlumlar Hello what data from the device state are you looking for? You are able to use the permission and subscription observers to be updated when data on either of those objects change.

**Comment by harrynguyen2510** [comment]
```
OneSignal.shared.getDeviceState().then((deviceState) async {
    debugPrint("initOnesignalNormalPush DeviceState: ${deviceState?.jsonRepresentation()}");
    String? playerId = deviceState?.userId;
}
```
This is from older sdk version. I also look for function similar this to get playerid. Is that for new sdk:

`OneSignal.User.pushSubscription.id`
if so, I got null value of id

**Comment by emawby** [comment]
@harrynguyen2510 Thank you for reaching out `OneSignal.User.pushSubscription.id` should not always return nil so it sounds like either something is going wrong with registering your device or something is going wrong retrieving the value in the SDK. Is the device able to receive push (does it show up in the dashboard)? If not then it is likely an issue registering and if so then it is an issue retrieving the value

**Comment by reynaldi18** [comment]
Any update?

**Comment by ashutosh9152** [comment]
I also receiving null when i am calling.
`OneSignal.User.pushSubscription.id`
I am getting the after some time. I also tried adding await but still it is not working .

This same issue was on OneSignal Cordova but there it is solved by deprecating  `OneSignal.User.pushSubscription.id` and adding `await OneSignal.User.pushSubscription.getIdAsync() ` 

There issue number is #918.

**Comment by jennantilla** [comment]
Hello everyone, apologies that this issue has gone stale. Please upgrade to our latest major release (v5) as this version provides specific methods for getting the push subscription ID (`OneSignal.User.pushSubscription.id`). If it is still returning null after the update, please open a new ticket with [device logs](https://documentation.onesignal.com/docs/capturing-a-debug-log) and we can see what's going on. Thanks!
