### ISSUE TITLE
[question]: Notification can't display more than one at a time

### ISSUE THREAD

**Issue by tovidd** [OneSignal/OneSignal-Flutter-SDK#738]
### How can we help?

I just upgrade onesignal_flutter from v3.5.1 to v5.0.0, both foreground and background notifications worked well on android.

But it can display one notifications only even though I push message many times to android emulator.

I expect the notifications can display more than one at a time. 

<img width="326" alt="Screenshot 2023-09-15 at 00 37 46" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/38039123/ed1d22bb-a577-4a28-b011-2e42588ca9c7">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Hello thank you for reaching out. We are aware of this [issue with the Android Native SDK](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1806) and are working on a fix.

**Comment by tovidd** [comment]
Thanks for the information
