### ISSUE TITLE
[Bug]: Onesignal 5.0.0 dont ask for permission on debug as well as Release mode

### ISSUE THREAD

**Issue by JiyadAhammad** [OneSignal/OneSignal-Flutter-SDK#745]
### What happened?

Onesignal 5.0.0 doesn't ask for permission on debug as well as Release mode
In the previous version, its worked fine

### Steps to reproduce?

```Markdown
1. Initilaize the App id in main.dart
2. Add Request permission line
3. permission is not asking 
4. manually add permission 
5. Still shown permission unavailable
```

### What did you expect to happen?

When asking permission, a permission alert will come 
or permission is need to get the notification

### OneSignal Flutter SDK version

5.0.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
Access denied finding property "ro.vendor.knock.type"
Access denied finding property "ro.vendor.df.effect.conflict"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@JiyadAhammad Hello could you share your OneSignal setup code and where you are requesting permissions?

**Comment by husainazkas** [comment]
same here. I just request permission after initialize but the future request permission never complete. I'd try to get permission native it only shows permission denied.

**Comment by husainazkas** [comment]
I think it caused by OneSignal.initialize is just void not a Future. As you can see this method contains ALL FUTURES but non of them aren't await. Here are scenarios :

1. Check PermissionNative:
```dart
OneSignal.initialize(Env.ONE_SIGNAL_APP_ID);
await Future.delayed(const Duration(milliseconds: 1000)); // This must be added to ensure that initialize has been complete because initialize is not a future

final permission = await OneSignal.Notifications.permissionNative(); // This will works ONLY if initialize is really initialized
print(permission);
```

2. Request permission
```dart
final isGranted = await OneSignal.Notifications.requestPermission(true); // This never ever complete even initialize is really initialized
print(isGranted);
```
