### ISSUE TITLE
[question]: OneSignal 5.0.0 did not collect location

### ISSUE THREAD

**Issue by Suzven** [OneSignal/OneSignal-Flutter-SDK#747]
### How can we help?

Hi! I updated the SDK version in my flutter application and get problem that the user's geolocation not collected. Prompt location request did not show

**I tried:** 
1) checked for isSharedLocation() - in response I received `"true"`:
2) Add to manifest permissions `ACCESS_FINE_LOCATION`, `ACCESS_COARSE_LOCATION`, `ACCESS_BACKGROUND_LOCATION`;
3) add to `build.gradle` implementation of `gms:play-services-location:21.0.1`;
4) rebuild project;
5) tested it on 3 real devices and 4 emulators;
6) downgrade to previous version 3.5.1 of flutter sdk - all works fine;
7) added/removed the `await` modifier.

My code on screenshot:
<img width="667" alt="Знімок екрана 2023-09-19 о 21 08 33" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/76104008/73fe17c5-8298-4d4b-9dab-317eaa724a12">

Screenshot from OneSignal Dashbord with examples of test installs:
<img width="982" alt="Знімок екрана 2023-09-19 о 21 14 57" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/76104008/670f85c3-f779-49e6-8286-a9926b93a9b0">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @Suzven, thank you for reaching out with your question.

Did you try setting location shared to `true` before asking for permission? 

You likely need to call `OneSignal.Location.setShared(true)` before calling `OneSignal.Location.requestPermission()`.

**Comment by nan-li** [comment]
closing due to no response
