### ISSUE TITLE
[Bug]: API rate limit exceeded on iOS

### ISSUE THREAD

**Issue by alegos27** [OneSignal/OneSignal-Flutter-SDK#748]
### What happened?

After the app has started on iOS and OneSignal has been initialized, after few seconds this error starts to appear repeatedly in the console:

ERROR: OSPropertyOperationExecutor update properties request failed with error: Optional(Error Domain=OneSignalError Code=429 "(null)" UserInfo={returned={
    errors =     (
        "API rate limit exceeded"
    );
    httpStatusCode = 429;
    limit = "Subscription/User Update Per Device";
}})

From that moment is impossible to update User and User Tags from the app, also the default fields of the Subscription (like LastActive) are not updated. We check if the update requests come from our code but it isn't so we think that there are some errors in the package.

### Steps to reproduce?

```Markdown
1. install v5.0.1
2. run app on iOS device
```

### What did you expect to happen?

The  app should run without these errors and the update methods should work normally.

### OneSignal Flutter SDK version

5.0.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
default	15:36:06.145358+0200	Runner	ERROR: OSPropertyOperationExecutor update properties request failed with error: Optional(Error Domain=OneSignalError Code=429 "(null)" UserInfo={returned={
    errors =     (
        "API rate limit exceeded"
    );
    httpStatusCode = 429;
    limit = "Subscription/User Update Per Device";
}})
default	15:36:06.145884+0200	Runner	ERROR: OSPropertyOperationExecutor update properties request failed with error: Optional(Error Domain=OneSignalError Code=429 "(null)" UserInfo={returned={
    errors =     (
        "API rate limit exceeded"
    );
    httpStatusCode = 429;
    limit = "Subscription/User Update Per Device";
}})
default	15:36:06.146599+0200	Runner	ERROR: OSPropertyOperationExecutor update properties request failed with error: Optional(Error Domain=OneSignalError Code=429 "(null)" UserInfo={returned={
    errors =     (
        "API rate limit exceeded"
    );
    httpStatusCode = 429;
    limit = "Subscription/User Update Per Device";
}})
default	15:36:06.147025+0200	Runner	Task <CFD8747C-B984-4B80-B664-DE5B7AB47F2C>.<7077> received response, status 429 content K
default	15:36:06.147231+0200	Runner	Task <FBA3F0F9-299E-4CB5-8FC8-F569C49177EB>.<7076> received response, status 429 content K
default	15:36:06.147506+0200	Runner	Task <8859B8BA-48F5-4DA5-A40A-CA843D2E9D1B>.<7080> received response, status 429 content K
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @alegos27, thank you for reporting. 

It looks like the SDK may be trying to send too many updates at once. I am not able to reproduce. Can you share some information?

1. This is happening on new app installations, and on the first time the app opens?
2. Can you turn on verbose logging by calling `OneSignal.Debug.setLogLevel(OSLogLevel.verbose)` before calling `OneSignal.initialize("YOUR_APP_ID")` and share the entire log. I would like to see the requests are sent, **what** the requests contain, and **when** they are sent. You can redact any sensitive information.

**Comment by alegos27** [comment]
Hi @nan-li, thanks for your suggestion! I found the problem by setting log level to verbose and it's a problem in our code.

**Comment by ihijazi** [comment]
@alegos27 can you please share what was the issue and how did you fix it?
