### ISSUE TITLE
[question]: How can I configure the files in the ios folder in Flutter without having access to a Macbook?

### ISSUE THREAD

**Issue by Anderson-Andre-P** [OneSignal/OneSignal-Flutter-SDK#750]
### How can we help?

The files that I should configure manually are already configured, but I was unable to configure the ```project.pbxproj``` file which is located inside the ```Runner.xcodeproj``` folder.

Is there any way to create this file without having a MacBook?

I believe that without this file being configured I will not be able to build for iOS through Codemagic...

Below I will leave the error that appears in Codemagic when trying to build because it could be that the problem is elsewhere and I am not able to configure it correctly.

Any help, tip, advice is welcome!

![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/61363255/3cab6ae8-ff1a-483a-8a62-d1ddf4904ade)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anderson-Andre-P** [comment]
When I look for the error in vscode with my project and the example project here at onesignal, I can see that there is 1 very different file, it could be that it is causing this error.

How could I be solving this without having a macbook? I believe that this code from the ```project.pbxproj``` file was not generated manually, so I can't simply copy it...

![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/61363255/837814ef-231f-4a05-a02b-76b5a0548cba)

**Comment by emawby** [comment]
@Anderson-Andre-P That file is intended to be opened in Xcode. You will need to use a program that allows you to work with xcode projects on windows. I am not aware of any GUI editors that allow you to work with it, but you code try some code libraries that allow you to edit projects programmatically if you don't have any access to a mac.

**Comment by Anderson-Andre-P** [comment]
@emawby I understand, I already suspected this, I'm looking to find a solution to solve this problem without a Mac
