### ISSUE TITLE
[Feedback]: Add metadata to pubspec.yaml

### ISSUE THREAD

**Issue by cgutierr-zgz** [OneSignal/OneSignal-Flutter-SDK#757]
### What's on your mind?

Add metadata so it's easier to go to the repo/issues from pub.dev

Example:
<img width="225" alt="Screenshot 2023-10-04 at 14 25 08" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/18635739/8a8331fe-4277-49e8-a586-f36ed658376d">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Great suggestion we will look into this

**Comment by nan-li** [comment]
Hi @cgutierr-zgz,

Thanks for making this issue and corresponding PR. I noticed that these links are already working on https://pub.dev/packages/onesignal_flutter. Are these PR changes still needed?


<img width="277" alt="Screenshot 2024-01-17 at 11 26 02 AM" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/4022291/33a56e91-31c8-4915-a762-dc1b84e49432">

**Comment by jennantilla** [comment]
We'll go ahead and close this issue and corresponding PR #758 since it has been resolved. Thanks!
