### ISSUE TITLE
OneSignal.h not  fount

### ISSUE THREAD

**Issue by htetwaiyan** [OneSignal/OneSignal-Flutter-SDK#76]
In file included from /Users/htetwaiyan/htetwaiyan/flutter_dev/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.1.0/ios/Classes/OneSignalCategories.m:28:
    /Users/htetwaiyan/htetwaiyan/flutter_dev/flutter/.pub-cache/hosted/pub.dartlang.org/onesignal-1.1.0/ios/Classes/OneSignalCategories.h:28:9: fatal error: 'OneSignal/OneSignal.h' file not found
    #import <OneSignal/OneSignal.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by rgomezp** [comment]
Duplicate of #21
