### ISSUE TITLE
[question]: Send notification

### ISSUE THREAD

**Issue by tekink** [OneSignal/OneSignal-Flutter-SDK#769]
### How can we help?

How can i send notification after 5.0.0 update? I checked migration guide but i didn't see it. Example project doesn't have sample code for send notification.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@tekink Sending a notification from the SDK itself is not something that has been kept in the 5.0.0+ versions. Were you using that functionality to send a local notification or send notifications to other users?

**Comment by tekink** [comment]
Before 5.0.0 version, i can send notification like this
var notification = OSCreateNotification(
      playerIds: [token],
      content: body,
      heading: title,
    );
OneSignal.shared.postNotification(notification);

I have my user's token. I send notification sometimes, some user activity.

**Comment by tekink** [comment]
OneSignal offical "live help" answer:

> If you are trying to send a notification from the SDK, this method was deprecated unfortunately as we not have multiple SDK clients available to send HTTP requests with:
> https://documentation.onesignal.com/docs/backend-sdk-reference
> Apologies for the inconvenience here, I'd be happy to request this method is re-added back in if you'd like to share your use case here.
> Thanks
> Dom
