### ISSUE TITLE
How to get the userid in flutter?

### ISSUE THREAD

**Issue by uj** [OneSignal/OneSignal-Flutter-SDK#77]
This is either a documentation omission, or a misunderstanding on my part.

In Flutter, how do you get the userid/playerid at any given time?  I understand that you can use     OneSignal.shared.setSubscriptionObserver() to get the userID initially, but is there really no way at all to get the userID again later?

In some parts of the documentation, I've seen references to getUserId and idsAvailable, but OneSignal.shared.getUserId and OneSignal.shared.idsAvailable are not valid functions.

**Comment by rgomezp** [comment]
Can you try `String onesignalUserId = status.subscriptionStatus.userId;`

**Comment by uj** [comment]
That works, thank you.

**Comment by tanmoy27112000** [comment]
Not able to find it says page not found
