### ISSUE TITLE
[question]: v5 setLanguage not respected by notification

### ISSUE THREAD

**Issue by foramgmits** [OneSignal/OneSignal-Flutter-SDK#770]
### How can we help?

OneSignal.User.setLanguage("en");

I've used this method setLanguage($languageCode).I want to know how it works because I've implemented this whenever user's application language changes but notification always triggered in default langauge  '-en'.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @foramgmits,

Thank you for reaching out to us and I do apologize for the delay. If you are still seeking an answer to your question, `setLanguage($languageCode)`, it attaches your designated language to the current user in the SDK.

> I've implemented this whenever user's application language changes but notification always triggered in default langauge '-en'.

Can you tell me more about this issue you are running into? 

1. What version of the OneSignal Flutter SDK are you using?
2. How are you sending the notification and setting languages?
3. Does this user have the language set when you look at the record in the OneSignal dashboard?
4. Is this affecting iOS, Android, or both?

**Comment by jennantilla** [comment]
Closing due to no response. @foramgmits if you are still having issues, please let us know!

**Comment by mohamedzakaria974** [comment]
Hi @nan-li @jennantilla it happens for me also with different real devices, simulators and emulators

 1. What version of the OneSignal Flutter SDK are you using?
     - latest onesignal_flutter: 5.3.0
2. How are you sending the notification and setting languages?
     - we are sending notification using our backend using oneSignal endpoint `https://onesignal.com/api/v1` with 
      ```"headings": {
    "en": "Title",
    "ar": "العنوان"
  },
  "contents": {
    "en": "content",
    "ar": "المحتوي"
  }```
     - setting language using `await OneSignal.User.setLanguage("en"|"ar");`
3. Does this user have the language set when you look at the record in the OneSignal dashboard?
     - it was working, but suddenly stopped updating the language in user profile
4. Is this affecting iOS, Android, or both?
     - both
