### ISSUE TITLE
[question]: When to use `removeTrigger` ?

### ISSUE THREAD

**Issue by DanMossa** [OneSignal/OneSignal-Flutter-SDK#774]
### How can we help?

I'm having trouble with users not being subscribed to Notifications and my current theory is to try using InAppMessages to enable Notifications.

I want a popup to appear when I want to ask the user to enable permissions.

On OneSignal, I've created an InAppMessage with the following triggers and schedule
![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/10294777/a69fbdfd-22bf-4cc0-8fdb-588a1fef39ab)

In my Code, I'm using the following: 
`await OneSignal.InAppMessages.addTrigger('showPermissionPrompt', "true");`

This then makes the notification appear. 
Do I then have to `await OneSignal.InAppMessages.removeTrigger('showPermissionPrompt');` afterwards unless the Popup will happen every-time the user opens the app?

Just looking for clarification. Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @DanMossa,

Thank you for your question and I do apologize for the delayed response.

Calling `OneSignal.InAppMessages.addTrigger('showPermissionPrompt', "true")` will make the in-app message (IAM) display every time you add the trigger, so yes, if you add the trigger on every app open, it will happen.

The primary purpose of the `removeTrigger` method is for compound events. For example, you may have an IAM display when **two triggers** are satisfied. 

Perhaps you add the first trigger and then add the second trigger, then the IAM will display. 

However, if you add the first trigger, then remove the first trigger, then add the second trigger, the IAM will not display.

Hope this makes sense.
