### ISSUE TITLE
[Bug]: External id issue

### ISSUE THREAD

**Issue by hamzasharif1199** [OneSignal/OneSignal-Flutter-SDK#775]
### What happened?

Earlier external id was working fine and all of a sudden now its not reflecting on one signal dashboard. I have checked console its working fine even the api response is updating put api for external id and removing external id but one signal dashboard not showing it. 
![WhatsApp Image 2023-10-26 at 2 22 02 PM](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/134627134/468ce358-088d-4f08-a345-66f50c1ce6f6)

### Steps to reproduce?

```Markdown
1. when the setExternalId function is set.
2. it will show on one signal dashboard.
3. when the removeExternalId function is clicked.
4. it will be removed from one signal dashboard.
```

### What did you expect to happen?

I expect to show external id on one signal dashboard even i set or remove it must refect.

### OneSignal Flutter SDK version

3.5.0

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Hello @hamzasharif1199 thank you for reaching out. OneSignal has a small set of externalids that are not allowed including "1". The values are:
"NA", "0", "NULL", "1", "-1"
https://documentation.onesignal.com/docs/aliases-external-id#external-id
