### ISSUE TITLE
[question]: Is it possible to send a custom notification for the 25s service extension timeout?

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [OneSignal/OneSignal-Flutter-SDK#777]
### How can we help?

I have some internal logic for Android and iOS to fetch images for notifications but if a user's internet is poor enough it can fail to download the image in time and the service extension times out.

The notifications are end-to-end encrypted so when the original notification is displayed it doesn't contain any useful information.

Is there a way to provide OneSignal with a notification in the service extension to use specifically in case it times out?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@TheMeanCanEHdian This is not something that OneSignal has a built in solution for and not something that I have seen done before, but it may be possible by editing the code in your NotificationService file to manually call the contentHandler with the notification content when the extension is about to time out.
