### ISSUE TITLE
libReachability.a(Reachability.o) does not contain bitcode. After adding OneSignal

### ISSUE THREAD

**Issue by dhimant1990** [OneSignal/OneSignal-Flutter-SDK#78]
Launching lib/main.dart on Dhimant’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: T4NY54ZLUC
Running Xcode build...
Xcode build done.                                            2.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Pods-Runner OF PROJECT Pods WITH CONFIGURATION Debug ===
    ld: '/Users/dhimantdesai/AndroidStudioProjects/Vgyan/snapback_app/build/ios/Debug-iphoneos/Reachability/libReachability.a(Reachability.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/dhimantdesai/AndroidStudioProjects/Vgyan/snapback_app/build/ios/Debug-iphoneos/Reachability/libReachability.a' for architecture arm64
    clang: error: unable to execute command: Segmentation fault: 11
    clang: error: linker command failed due to signal (use -v to see invocation)

Could not build the precompiled application for the device.

Error launching application on Dhimant’s iPhone.

**Comment by dhimant1990** [comment]
> Launching lib/main.dart on Dhimant’s iPhone in debug mode...
> Automatically signing iOS for device deployment using specified development team in Xcode project: T4NY54ZLUC
> Running Xcode build...
> Xcode build done. 2.9s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
> ** BUILD FAILED **
> 
> Xcode's output:
> ↳
> === BUILD TARGET Pods-Runner OF PROJECT Pods WITH CONFIGURATION Debug ===
> ld: '/Users/dhimantdesai/AndroidStudioProjects/Vgyan/snapback_app/build/ios/Debug-iphoneos/Reachability/libReachability.a(Reachability.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/dhimantdesai/AndroidStudioProjects/Vgyan/snapback_app/build/ios/Debug-iphoneos/Reachability/libReachability.a' for architecture arm64
> clang: error: unable to execute command: Segmentation fault: 11
> clang: error: linker command failed due to signal (use -v to see invocation)
> 
> Could not build the precompiled application for the device.
> 
> Error launching application on Dhimant’s iPhone.

When try to build from Xcode

Ld /Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension normal arm64
    cd /Users/dhimantdesai/AndroidStudioProjects/Vgyan/snapback_app/ios
    export IPHONEOS_DEPLOYMENT_TARGET=10.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -L/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos -L/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/Reachability -L/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/connectivity -L/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/crashlytics -L/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/flutter_inapp_purchase -L/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/keyboard_visibility -L/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/onesignal -L/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/shared_preferences -L/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/url_launcher -L/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/video_player -L/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/webview_flutter -F/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos -F/Users/dhimantdesai/AndroidStudioProjects/Vgyan/snapback_app/ios/Pods/../.symlinks/flutter/ios -F/Users/dhimantdesai/AndroidStudioProjects/Vgyan/snapback_app/ios/Pods/Crashlytics/iOS -F/Users/dhimantdesai/AndroidStudioProjects/Vgyan/snapback_app/ios/Pods/Fabric/iOS -F/Users/dhimantdesai/AndroidStudioProjects/Vgyan/snapback_app/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework -filelist /Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -miphoneos-version-min=10.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -fapplication-extension -ObjC -lReachability -lc++ -lconnectivity -lcrashlytics -lflutter_inapp_purchase -lkeyboard_visibility -lonesignal -lshared_preferences -lurl_launcher -lvideo_player -lwebview_flutter -lz -framework Crashlytics -framework Fabric -framework Flutter -framework OneSignal -framework Security -framework SystemConfiguration -framework UIKit -framework UserNotifications -ObjC -lc++ -lz -framework Crashlytics -framework Fabric -framework OneSignal -framework Security -framework SystemConfiguration -framework UIKit -framework UserNotifications -e _NSExtensionMain -lPods-OneSignalNotificationServiceExtension -Xlinker -dependency_info -Xlinker /Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/OneSignalNotificationServiceExtension.build/Objects-normal/arm64/OneSignalNotificationServiceExtension_dependency_info.dat -o /Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension

ld: '/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/Reachability/libReachability.a(Reachability.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/dhimantdesai/Library/Developer/Xcode/DerivedData/Runner-arldhnphxquaeiclswcdfyhuhgqi/Build/Products/Debug-iphoneos/Reachability/libReachability.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by t42ji2ji** [comment]
@dhimant1990  I have the same problem! How to solve them.

**Comment by dhimant1990** [comment]
Click on onesignal target and select general tab and find linked framework
and library and add all library in which you received error. (If possible
then add all library in linked framework and library)

**Comment by dhimant1990** [comment]
did you resolve this issue?
