### ISSUE TITLE
[question]: How can I retrieve the notification data when the application is opened by clicking on the notification received while the application is closed?

### ISSUE THREAD

**Issue by mberktas** [OneSignal/OneSignal-Flutter-SDK#780]
### How can we help?

Hello,

I am working on an application and I need to retrieve notification data when the user opens the application by clicking on a notification that was received while the application was closed. 

Could someone please guide me on how to achieve this?

Thanks in advance!

Version :
onesignal_flutter: ^5.0.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @mberktas, you can use a [notification click listener](https://documentation.onesignal.com/docs/mobile-sdk#setting-notification-click-listeners) that will run whenever the user opens a notification: 

```dart
OneSignal.Notifications.addClickListener((event) {
  print('NOTIFICATION CLICK LISTENER CALLED WITH EVENT: $event');
});
```

Hope this answers you question.

**Comment by mberktas** [comment]
Thank you @nan-li 
Actually, addClickListener was already added, but I thought it didn't work when the app was closed. When I tried it again now, I realized that it works.
When I saw this page in the documentation (https://documentation.onesignal.com/docs/data-notifications), I thought I needed to write native code 😄 "

**Comment by BachirBichri** [comment]
Hello @mberktas have you found a solution to this issue?

**Comment by yourstrulycreator** [comment]
> Hi @mberktas, you can use a [notification click listener](https://documentation.onesignal.com/docs/mobile-sdk#setting-notification-click-listeners) that will run whenever the user opens a notification:
> 
> ```dart
> OneSignal.Notifications.addClickListener((event) {
>   print('NOTIFICATION CLICK LISTENER CALLED WITH EVENT: $event');
> });
> ```
> 
> Hope this answers you question.

did not work, Notification is not a method

**Comment by mberktas** [comment]
Actually, I don't know exactly what fixed it. I changed the package versions and did a few additional things. Problem solved. 

Sometimes changing OneSignal initialize location can solve the problem.
