### ISSUE TITLE
How to get the Onesignal ID on the last version?

### ISSUE THREAD

**Issue by rignaneseleo** [OneSignal/OneSignal-Flutter-SDK#782]
I am trying to get the Onesignal ID to configure RevenueCat via `setOnesignalID(String onesignalID)`

Onesignal ID was previously available in v3.x.x but now only the subscription ID and the token are available from the `Onesignal.User.pushSubscription.id` property.

How can I get it?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @rignaneseleo,
Thanks for asking, this was also asked by others, please see [this response](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/759#issuecomment-1789829959).

You will have to use the REST API or Server SDK, but we are going to add a getter for onesignal ID.

**Comment by MuhammedRefaat** [comment]
**OneSignal id** can be retrieved using:

`String? oneSignalId = await OneSignal.User.getOnesignalId();`
