### ISSUE TITLE
Problem with dependency on androidx.work:work-runtime-ktx:2.7.1

### ISSUE THREAD

**Issue by andy-weinstein** [OneSignal/OneSignal-Flutter-SDK#783]
### How can we help?

The onesignal_flutter package has an indirect dependency on androidx.work:work-runtime-ktx:2.7.1. This Kotlin extension (ktx) library further depends on androidx.work:work-runtime:2.7.1.

In my project, another package depends on androidx.work:work-runtime:2.8.1. While Gradle attempts to resolve this by using version 2.8.1 for work-runtime, it does not do the same for work-runtime-ktx. As a result, we have work-runtime-ktx at 2.7.1 expecting its counterpart to be 2.7.1, but it's actually 2.8.1 due to the other package. This mismatch causes a build conflict.

It would be helpful if onesignal_flutter could update its dependency to a newer version of androidx.work, or make it more flexible, to prevent such conflicts.

As it is, I included the following in my app/build.gradle:
dependencies {
    # leaving out other irrelevant directives here

    implementation('androidx.work:work-runtime-ktx:2.8.1') {
     force = true
    }
}
It seems to be working fine - only did an initial test push, but it worked.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Hello thank you for reaching out. I believe this has already been fixed in our Android SDK [here](https://github.com/OneSignal/OneSignal-Android-SDK/pull/1890), and will be available in the next flutter version release. Thank you for your patience while we get the release out!

**Comment by nan-li** [comment]
[replying]

**Comment by nan-li** [comment]
Hi @andy-weinstein, thanks again for reporting this issue and your patience.

We have released the fix in [Release 5.1.0](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.0).

Please update and reach out if you are still seeing issues. Thanks!
