### ISSUE TITLE
Are we supposed to use the (legacy) package? I see there is a new one which we are supposed to migrate to but there is no documentation

### ISSUE THREAD

**Issue by ember11498** [OneSignal/OneSignal-Flutter-SDK#791]
### How can we help?

All the documentation I see in the repo is about the old package. Am I suppose to use the old package? many of the methods dont work like the "shared" and if you check the example file in this repo nothing works on the new package so I cant learn without any documentation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @ember11498 apologies that this questions was missed.

Apologies if you were unable to find the documentation. Here are some links that might be helpful to you:

- [User Model Migration Guide](https://documentation.onesignal.com/docs/user-model-migration-guide#migration)
- [Flutter Migration Guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md)

For sending notifications, you can do so from the [OneSignal dashboard](https://documentation.onesignal.com/docs/mobile-push-notifications-guide) or via our [API](https://documentation.onesignal.com/reference/create-notification). 

Let us know if you have any additional questions or concerns!
