### ISSUE TITLE
[question]: how to get playerId(userId) in this version? 

### ISSUE THREAD

**Issue by lyfer-bob** [OneSignal/OneSignal-Flutter-SDK#794]
### How can we help?

in old version i can get by  
` var status = await OneSignal.shared.getDeviceState();
var playerId = status!.userId;`
      
but in this version can't call `getDeviceState()` . 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by salamohamad** [comment]
Yes, having same issue. Just updated to ```^5.0.4``` but cant seem to find the player ID for internal keep

**Comment by nan-li** [comment]
Hi @lyfer-bob and @salamohamad, if you are looking for the push subscription ID (most equivalent to the player ID in `v3.x.x`), it can be retreived via `var id = OneSignal.User.pushSubscription.id`.

If you are looking for the user-level `onesignalId`, it will be available in a future release.

**Comment by masreplay** [comment]
Any updates?

**Comment by jennantilla** [comment]
Hello everyone!

Just an update that `onesignalId` is now also available on the Flutter SDK.

Please upgrade to the [latest Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) to use the new methods, `User.getExternalId` and `User.getOnesignalId`. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details!
