### ISSUE TITLE
[question]: I'm getting error with this file "Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex" ?

### ISSUE THREAD

**Issue by tbro2020** [OneSignal/OneSignal-Flutter-SDK#795]
### How can we help?

Failed to build iOS app
Error (Xcode): Cycle inside Runner; building could produce unreliable results.
Cycle details:
→ Target 'Runner': ExtractAppIntentsMetadata
○ Target 'Runner' has copy command from '/Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex' to
'/Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex'
○ That command depends on command in Target 'Runner': script phase “Thin Binary”
○ Target 'Runner' has process command with output '/Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/Runner.app/Info.plist'
○ Target 'Runner' has copy command from '/Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex' to
'/Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex'

Raw dependency cycle trace:

target:  ->

node: <all> ->

command: <all> ->

node:
/Users/tabaro/Library/Developer/Xcode/DerivedData/Runner-alidqpkwwpqtvebycvithtqfhqkh/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-n
ormal/x86_64/ExtractedAppShortcutsMetadata.stringsdata ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ExtractAppIntentsMetadata ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7-copy-files> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase7-copy-files ->

node: <Copy /Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex> ->

CYCLE POINT ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy
/Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex
/Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--copy-pods-resources> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase6--cp--copy-pods-resources ->

node:
/Users/tabaro/Library/Developer/Xcode/DerivedData/Runner-alidqpkwwpqtvebycvithtqfhqkh/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFile
List-E5612CA320E2B586A6F3595B-Pods-Runner-resources-Debug-input-files-9eb5b8bd69f3875fdc14b64578509cff-resolved.xcfilelist ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile
/Users/tabaro/Library/Developer/Xcode/DerivedData/Runner-alidqpkwwpqtvebycvithtqfhqkh/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFile
List-E5612CA320E2B586A6F3595B-Pods-Runner-resources-Debug-input-files-9eb5b8bd69f3875fdc14b64578509cff-resolved.xcfilelist ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase5--cp--embed-pods-frameworks ->

node:
/Users/tabaro/Library/Developer/Xcode/DerivedData/Runner-alidqpkwwpqtvebycvithtqfhqkh/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFile
List-79AB0EB9401A8B9FE7A17FC7-Pods-Runner-frameworks-Debug-input-files-b7b18481911dad3306c5012b8db74907-resolved.xcfilelist ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:WriteAuxiliaryFile
/Users/tabaro/Library/Developer/Xcode/DerivedData/Runner-alidqpkwwpqtvebycvithtqfhqkh/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/InputFile
List-79AB0EB9401A8B9FE7A17FC7-Pods-Runner-frameworks-Debug-input-files-b7b18481911dad3306c5012b8db74907-resolved.xcfilelist ->

node: <target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary> ->

command: P0:::Gate target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49--fused-phase4-thin-binary ->

node:
<execute-shell-script-18c1723432283e0cc55f10a6dcfd9e02f1eee2015e8ff5ebcd27678f788c2826-target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-> ->

command: P2:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:PhaseScriptExecution Thin Binary
/Users/tabaro/Library/Developer/Xcode/DerivedData/Runner-alidqpkwwpqtvebycvithtqfhqkh/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-3B
06AD1E1E4923F5004D2608.sh ->

node: /Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/Runner.app/Info.plist/ ->

directoryTreeSignature: Z ->

directoryContents: /Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/Runner.app/Info.plist ->

node: /Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/Runner.app/Info.plist ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:ProcessInfoPlistFile
/Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/Runner.app/Info.plist /Users/tabaro/StudioProjects/porocab/ios/Runner/Info.plist ->

node: /Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex ->

command: P0:target-Runner-18c1723432283e0cc55f10a6dcfd9e0288a783a885d8b0b3beb2e9f90bde3f49-:Debug:Copy
/Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex
/Users/tabaro/StudioProjects/porocab/build/ios/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex

Could not build the application for the simulator.
Error launching application on iPhone Xs. ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shaunhossain** [comment]
i face the same issue , did you find any solution ?

**Comment by emawby** [comment]
@tbro2020 Hello could you show your podfile as well as the frameworks and libraries section of the Notification service extension target in xcode?

**Comment by emawby** [comment]
Also does this workaround work for you? It appears that this issue is a duplicate
https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/790#issuecomment-1827352021

**Comment by shaunhossain** [comment]
@tbro2020 check you apple provision certificate expired or not , also check your apple config is active or not in onesignal console.

**Comment by tbro2020** [comment]
> @tbro2020 Hello could you show your podfile as well as the frameworks and libraries section of the Notification service extension target in xcode?

# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
end

**Comment by markosole** [comment]
Check this out (as pointed obove) and additional last step that is required.

https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/857#issuecomment-2106307658
