### ISSUE TITLE
[Bug]: Push Notification Modification at run time is not working

### ISSUE THREAD

**Issue by FakharAlyas119** [OneSignal/OneSignal-Flutter-SDK#797]
### What happened?

I am trying to modify the notification title and the body at run time and pass that `OSNotification` object to `notificationEvent.complete(modified)` but it's not working it shows the old notification the one without modification
I am using  `onesignal_flutter: ^3.5.1`

### Steps to reproduce?

```Markdown
1. install onesignal_flutter: ^3.5.1
2. push your notification from the dashboard
3. when you receive a notification at the mobile end modify it like this
    final modified = osNotificationModifier.toOpportunityLaunchNotification(
          notification,
          obj: toAppNotification,
        );
   toAppNotification is my object toOpportunityLaunchNotification function successfully returns the new OSNotification
4.  notificationEvent.complete(modified);
    this will show the un-modified notification
```

### What did you expect to happen?

It should show the modified notification, but it shows an un-modified notification

### OneSignal Flutter SDK version

  onesignal_flutter: ^3.5.1

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @FakharAlyas119, thanks for reporting.

1. Can you share VERBOSE level logs starting right before the notification is received?
2. Are you making a new `OSNotification` object and passing it into `complete`? Can you try modifying the exisitng `OSNotification` received in the event and seeing what happens?
3

**Comment by jkasten2** [comment]
`setNotificationWillShowInForegroundHandler` does not support modifying the notification. It only support omitting the notification.

We will consider this a feature request.

A workaround in the meantime is you can call `complete(null)` and display your own local notification.
