### ISSUE TITLE
clearOneSignalNotifications missing from Flutter SDK

### ISSUE THREAD

**Issue by uj** [OneSignal/OneSignal-Flutter-SDK#80]
In the native android sdk (and in some of the other sdk's), the "clearOneSignalNotifications" method exists to be able to clear notifications from the top bar.

Is there a way to do this with the flutter sdk?  I do not see it documented, and it does not seem to exist in the code.

**Comment by rgomezp** [comment]
Hello,
That is correct. We, unfortunately, don't offer this method in the Flutter SDK. We have made a note internally regarding your feature request but will go ahead and close this issue as it is not something we plan to implement soon. Thanks for bringing this up

**Comment by juppdes** [comment]
I need this feature. Is there any prediction or alternative for this functionality?

**Comment by mubasshir** [comment]
@rgomezp is this implemented now?

**Comment by rgomezp** [comment]
@mubasshir ,
Unfortunately not yet. Thanks for your patience!

**Comment by mubasshir** [comment]
any workaround this?

**Comment by ahmeterdgn** [comment]
did it result ?

**Comment by davidlj95** [comment]
Interested here too!
