### ISSUE TITLE
[question]: Send Notifications

### ISSUE THREAD

**Issue by Arhidev** [OneSignal/OneSignal-Flutter-SDK#801]
### How can we help?

Hello to you !
With older versions of onesignal, it was simple and efficient to send notifications with the following code:
(OneSignal.shared.postNotification(notification)

`  static void sendSimpleMessage({String msg, String playerId}) async {
    var notification = OSCreateNotification(
        playerIds: [playerId],
        content: msg,
        heading: "Cdou",
        buttons: [OSActionButton(text: "voir", id: "id1"),]);
    try {
      await OneSignal.shared.postNotification(notification)
          .then((value) => Constant.alertToast(msg: "Succés!", color: Colors.green)).catchError((er) {});
    }catch (e) {
      // TODO
    }
  }`

But currently impossible, or please tell me how to do it!
Thank you very much

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shepherd-l** [comment]
Closing due to duplicate https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/810
