### ISSUE TITLE
[Bug]: Can't see logs in Flutter console.

### ISSUE THREAD

**Issue by vasilich6107** [OneSignal/OneSignal-Flutter-SDK#802]
### What happened?

I did
await OneSignal.Debug.setLogLevel(OSLogLevel.verbose);

### Steps to reproduce?

```Markdown
1. call await OneSignal.Debug.setLogLevel(OSLogLevel.verbose);
2. check flutter console for logs
```

### What did you expect to happen?

I expected to see the logs.
I can see them only in XCode

### OneSignal Flutter SDK version

5.0.4

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @vasilich6107 thank you for reaching out,

If the native iOS logs are showing in Xcode but not the Flutter console, this sounds like a Flutter platform or Flutter version issue?

Please see [this comment](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/558#issuecomment-1192032351) about a similar issue. I believe if you use the command line to run the app with `flutter run`, the logs will print in the terminal.
