### ISSUE TITLE
The addClickListener method is not launching my application.

### ISSUE THREAD

**Issue by beytt06** [OneSignal/OneSignal-Flutter-SDK#809]
### How can we help?

I use OneSignal for receiving notifications both in my browser and mobile application. 
Therefore, the incoming notification contains a URL key. 
What I want to achieve is to launch my application without asking the user to "Open with" when the notification is clicked on Android or iOS. 
Here are my manifest codes:
 
            meta-data   android:name="com.onesignal.suppressLaunchURLs" android:value="true" />
             meta-data android:name="com.onesignal.open_urls_in_app" android:value="true"/>

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="http" android:host="mywebsite.com" />
                <data android:scheme="https" android:host="mywebsite.com" />
            </intent-filter>
 
Additionally, here are my addClickListener codes:

```
OneSignal.Notifications.addClickListener((event) {
        Map<String, dynamic>? customData = event.notification.rawPayload;
        if (customData != null && customData.containsKey('custom')) {
          String customValue = customData['custom'];
          try {
            var decodedData = jsonDecode(customValue);
            var url = decodedData['u'];
            if (url != null) {
              Uri parsedUrl = Uri.parse(url);
              if (parsedUrl.host == 'mywebsite.com') {
                if (parsedUrl.path == '/advance') {
                  Helper.navigatePush(context, AdvanceMainScreen());
                } else if (parsedUrl.path == '/dashboard') {
                  late ChatNewProvider _chatNewProvider;
                  var chatId = parsedUrl.queryParameters['chat'];
                  var groupId = parsedUrl.queryParameters['group'];
                  Future.delayed(Duration.zero, () async {
                    _chatNewProvider = Provider.of<ChatNewProvider>(context, listen: false);
                    await _chatNewProvider.fetchMessages();
                    var find = _chatNewProvider.searchOnmessages.firstWhereOrNull((e) =>
                    e.from_id == int.parse(chatId ?? "0") ||
                        e.group_id == groupId);
                    if (context.mounted && find != null) {
                      Helper.navigatePush(context, ChatMessageScreen(message: find));
                    }
                  });
                }
              }
            }
          } catch (e) {
            print("Error: $e");
          }
        }
      });
```

However, I couldn't find an update related to this. I would appreciate it if you could assist me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @beytt06 apologies that this issue was missed. Are you still having problems with this?

You can suppress default processing of the launch URLs to handle them programmatically. [Here](https://documentation.onesignal.com/docs/links#suppressing-launch-urls) is some more information on that.

If that doesn't fit your use case or you have any additional questions or concerns, please let us know!
