### ISSUE TITLE
[Bug]: Can't receive notification if body message is empty

### ISSUE THREAD

**Issue by caini1213** [OneSignal/OneSignal-Flutter-SDK#813]
### How can we help?

I was trying to send out a notification with empty body (project required), but it does not receive in devices although it is shown delivered successfully in OneSignal. Once I write some message in body then my device can receive it. 

Does anyone facing this before? thank you

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@caini1213 This is a known limitation of iOS, the notification must include a body to display. OneSignal also made this a requirement for Android, so the behavior matches iOS.
