### ISSUE TITLE
[Bug]: Can't manual show notification after prevent default

### ISSUE THREAD

**Issue by cuong292** [OneSignal/OneSignal-Flutter-SDK#814]
### What happened?

I have to prevent all notification when user on specify screen and display all of it after user leave the screen. I did that by **preventDefault** and then **displayNotification** after it to show all notification but i have a problem that only the latest notification shown but not all the notification

### Steps to reproduce?

```Markdown
1. call preventDefault for 2 notification and save the notifications ids.
2. show all notification
```

### What did you expect to happen?

Expected -> 2 notification show frequently
Result -> only the latest notification show

### OneSignal Flutter SDK version

stable

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
ERROR: OSNotificationWillDisplayEvent.notification.display cannot be called due to timing out or notification was already displayed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@cuong292 Notifications will timeout if they aren't displayed within 30 seconds. Could it be that the previous notifications have timed out? Also if you try saving off the events rather than the notification ids then calling event.notification.display() does that work?

**Comment by nan-li** [comment]
Closing due to no response, 
Please ping us to re-open if you still need help on this issue~
