### ISSUE TITLE
[Bug]:user id and email not save on onesignal dashboard.

### ISSUE THREAD

**Issue by vipul8815** [OneSignal/OneSignal-Flutter-SDK#821]
### What happened?
We call the login function and pass the user id but the dashboard does not show the external user ID and also the same thing for set email.

### Steps to reproduce?

```Markdown
we call functions after the user logins 
check attached functions 
 Future<void> setUserId(String userId) async {
    await OneSignal.login(userId);
    await OneSignal.User.addAlias("user_id", userId);
  }

  void setEmailId(String email) {
    OneSignal.User.addEmail(email);
  }
```

### What did you expect to happen?

we need to save email and external user id 

### OneSignal Flutter SDK version

flutter version 3.16.4
package version 5.0.4

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @vipul8815,

Thank you for reporting this issue.

Can you share your logs when you call your method `setUserId(String userId)` and your method `setEmailId(String email)`?

**Comment by vipul8815** [comment]
now working

**Comment by nan-li** [comment]
Hi @vipul8815,

That's good to hear. This may have been a server bug that has been fixed around attaching external_id after logging in.
I'll close this issue, but please reach out if you encounter any problems again.
