### ISSUE TITLE
[Bug]: Apns Bad Device Token after update from 3.5.0 to 5.0.4

### ISSUE THREAD

**Issue by andreaparadigma** [OneSignal/OneSignal-Flutter-SDK#824]
### What happened?

After update from 3.5.0 to 5.0.4 in iPhone I no longer receive push notifications.

### Steps to reproduce?

```Markdown
1. update to onesignal_flutter: ^5.0.4
2. migrate the code https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/user_model/main/MIGRATION_GUIDE.md
3. launch the app
4. send a notification
5. no notification received and "Apns Bad Device Token" in Dashboard under "Subscription Status"

If revert to 3.5.0 all works correctly

NB: In the iOS config on the OneSignal settings page I don't have any warnings
```

### What did you expect to happen?

I expected to receive a push notification

### OneSignal Flutter SDK version

Release 5.0.4

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-atrule** [comment]
I'm also having the same issue.

**Comment by faisal-atrule** [comment]
I was facing this issue also. I have fixed that by manually setting the 'aps-environment' to 'production'

iOS -> Runner -> Runner.entitlements

**Comment by fabioselau077** [comment]
Same here in new project onesignal
<img width="769" alt="image" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/57275833/1efa90ee-fe03-4157-a231-505eca178968">

**Comment by fabioselau077** [comment]
> I was facing this issue also. I have fixed that by manually setting the 'aps-environment' to 'production'
> 
> iOS -> Runner -> Runner.entitlements

in xcode? same error here

**Comment by fabioselau077** [comment]
> I was facing this issue also. I have fixed that by manually setting the 'aps-environment' to 'production'
> 
> iOS -> Runner -> Runner.entitlements

make but same error :/

**Comment by fabioselau077** [comment]
For OneSignal support, work!

"Hi there,
The error "Apns Bad Device Token" can be fixed following the troubleshooting guide.
Please follow the steps in our [iOS Mismatched User Environment docs](https://documentation.onesignal.com/docs/mismatched-user-environment) if you have not already.
Then try the following:
- uninstall the app on these listed player IDs (if you recognize the player ID)
- click the iOS config on the OneSignal settings page and press save, this will clear the warning
- re-install the app on the device
- open the app and re-subscribe to the prompt. This will give you a new player ID.
- Send yourself a notification and see if the warning appears again
If you don't recognize any of the listed player IDs, just click the iOS config on the OneSignal settings page and press save, this will clear the warning. On the next iOS notification see if the warning shows again.
Let us know if you have any additional questions for us.
Thanks."

**Comment by InfoSpecific** [comment]
https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/828#issuecomment-1937012011

**Comment by petodavid** [comment]
We are facing the same issue, the mentioned steps are not working in our case, any updates?

> For OneSignal support, work!
> 
> "Hi there, The error "Apns Bad Device Token" can be fixed following the troubleshooting guide. Please follow the steps in our [iOS Mismatched User Environment docs](https://documentation.onesignal.com/docs/mismatched-user-environment) if you have not already. Then try the following:
> 
> * uninstall the app on these listed player IDs (if you recognize the player ID)
> * click the iOS config on the OneSignal settings page and press save, this will clear the warning
> * re-install the app on the device
> * open the app and re-subscribe to the prompt. This will give you a new player ID.
> * Send yourself a notification and see if the warning appears again
>   If you don't recognize any of the listed player IDs, just click the iOS config on the OneSignal settings page and press save, this will clear the warning. On the next iOS notification see if the warning shows again.
>   Let us know if you have any additional questions for us.
>   Thanks."

**Comment by wearemeeters** [comment]
we are experiencing the same behaviour but on our Xamarin SDK 4.3.4 and this started to appear on ios 17. Before on ios 16 it worked as expected. And from fellow developer I know that he same happens on the MAUI version. So this does not look like a SDK issue to me.

Tried to fix certificates, to no avail. I am using p8 key to authorize APNS via OneSignal if that helps.

**Comment by jennantilla** [comment]
Hello everyone--apologies that this issue has gone stale. If this is still a concern for anyone, please let us know here!

More information on APNS Bad Device Token troubleshooting can be found [here](https://documentation.onesignal.com/docs/troubleshooting-ios#apns-bad-device-token).

**Comment by pierroo** [comment]
> Hello everyone--apologies that this issue has gone stale. If this is still a concern for anyone, please let us know here!
> 
> More information on APNS Bad Device Token troubleshooting can be found [here](https://documentation.onesignal.com/docs/troubleshooting-ios#apns-bad-device-token).

I am still facing this issue; and your linked documentation no longer exists.
on iOS it no longer works since I updated from v3 to v5, with the Apns Bad Device Token in the onesignal subscription dahsboard.
