### ISSUE TITLE
[Bug]: Apns Bad Device Token

### ISSUE THREAD

**Issue by fabioselau077** [OneSignal/OneSignal-Flutter-SDK#828]
### What happened?

iOS not create Subscription
<img width="772" alt="image" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/57275833/ad481611-4cd5-4ddc-93fd-4fd879d416f6">

### Steps to reproduce?

```Markdown
1. Create new project in OneSignal
2. Create new projeto flutter
3. Follow docs for Flutter SDK Setup: https://documentation.onesignal.com/docs/flutter-sdk-setup
4. Testing in Simulator iOS (ok)
5. Testing in physicist iOS and get "Apns Bad Device Token"
```

### What did you expect to happen?

Subscription physicist iOS in OneSignal for push. Try change 'aps-environment' to 'production' but same error (following this [comment](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/824#issuecomment-1905586929)).

### OneSignal Flutter SDK version

5.0.4

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fabioselau077** [comment]
For OneSignal support, working now!

"Hi there,
The error "Apns Bad Device Token" can be fixed following the troubleshooting guide.
Please follow the steps in our [iOS Mismatched User Environment docs](https://documentation.onesignal.com/docs/mismatched-user-environment) if you have not already.
Then try the following:
- uninstall the app on these listed player IDs (if you recognize the player ID)
- click the iOS config on the OneSignal settings page and press save, this will clear the warning
- re-install the app on the device
- open the app and re-subscribe to the prompt. This will give you a new player ID.
- Send yourself a notification and see if the warning appears again
If you don't recognize any of the listed player IDs, just click the iOS config on the OneSignal settings page and press save, this will clear the warning. On the next iOS notification see if the warning shows again.
Let us know if you have any additional questions for us.
Thanks."

**Comment by InfoSpecific** [comment]
Hello @fabioselau077,

I am facing the same issue only for the AppStore and TestFlight build specifically for the Indian User. For other country, users are able receive the notification that I have send from the one signal push notification. 

When I am runned the app from the XCode then notification is working perfectly fine. But when I am  downloaded the build that I have uploaded in TestFlight in iPhone at that time I am not receiving notification and this scenario is **only happened for the Indian User**. For the other countries user not faced this issue they are receiving notification.

I am waiting for your response. If you have any idea about it please let me know what is the wrong with my configuration or any other mistake.
