### ISSUE TITLE
[Bug]:  Asset validation failed (50) The app references non-public selectors in Payload/Runner.app/Frameworks/OneSignalFramework.framework/OneSignalFramework

### ISSUE THREAD

**Issue by Eddayy** [OneSignal/OneSignal-Flutter-SDK#837]
### What happened?

I face this error when I upload to apple connect, appreciate if anyone can point me the right directions.

### Steps to reproduce?

```Markdown
1. I've setup fastlane to build and upload
2. Run fastlane ios upload_to_testflight
```

### What did you expect to happen?

Upload to apple successfully 

### OneSignal Flutter SDK version

5.1.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
[Application Loader Error Output]: ERROR: [ContentDelivery.Uploader] Asset validation failed (50) The app references non-public selectors in Payload/Runner.app/Frameworks/OneSignalFramework.framework/OneSignalFramework: setSharedInstance: (ID: 9441cb37-725b-40d5-8c46-8519f263404a)
[Application Loader Error Output]: Error uploading '/var/folders/bf/fz1p4pms3k5bjl9x1sqvzf880000gp/T/c44724af-60b7-4e7e-9984-2c49a1e2eed8.ipa'.
[Application Loader Error Output]: Asset validation failed The app references non-public selectors in Payload/Runner.app/Frameworks/OneSignalFramework.framework/OneSignalFramework: setSharedInstance: (ID: 9441cb37-725b-40d5-8c46-8519f263404a) (50)
[Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@Eddayy Thanks for reaching out. I see that this has been posted on the iOS SDK repo as well. I will close this one since discussion has started in that thread. 
https://github.com/OneSignal/OneSignal-iOS-SDK/issues/1370
