### ISSUE TITLE
Failed last request. statusCode: 404 keep looping and not showing in catcherror

### ISSUE THREAD

**Issue by newbieflutter** [OneSignal/OneSignal-Flutter-SDK#84]
I am testing out the one signal implementation and trying to integrate into my application. I have been googling and managed to to integrate somehow. What I notice is some weird things.

1. I have purposely changed my app ID and I notice its not caught in my  .catchError((onError){ but in my debug console its showing as below.

```
E/OneSignal(  631): Please enter a Google Project number / Sender ID on under App Settings > Android > Configuration on the OneSignal dashboard.
W/OneSignal(  631): OneSignalRestClient: POST RECEIVED JSON: {"errors":["App with id: 887772f0-71fa-4c17-824d-0a143c868323 does not exist"]}
W/OneSignal(  631): Failed last request. statusCode: 404
W/OneSignal(  631): response: {"errors":["App with id: 887772f0-71fa-4c17-824d-0a143c868323 does not exist"]}
W/OneSignal(  631): OneSignalRestClient: POST RECEIVED JSON: {"errors":["App with id: 887772f0-71fa-4c17-824d-0a143c868323 does not exist"]}
W/OneSignal(  631): Failed last request. statusCode: 404
W/OneSignal(  631): response: {"errors":["App with id: 887772f0-71fa-4c17-824d-0a143c868323 does not exist"]}
W/OneSignal(  631): OneSignalRestClient: POST RECEIVED JSON: {"errors":["App with id: 887772f0-71fa-4c17-824d-0a143c868323 does not exist"]}
W/OneSignal(  631): Failed last request. statusCode: 404
W/OneSignal(  631): response: {"errors":["App with id: 887772f0-71fa-4c17-824d-0a143c868323 does not exist"]}
W/OneSignal(  631): OneSignalRestClient: POST RECEIVED JSON: {"errors":["App with id: 887772f0-71fa-4c17-824d-0a143c868323 does not exist"]}
W/OneSignal(  631): Failed last request. statusCode: 404
W/OneSignal(  631): response: {"errors":["App with id: 887772f0-71fa-4c17-824d-0a143c868323 does not exist"]}
```
2. Why even there is error but its still able to print my 
 print("user is "+status.subscriptionStatus.userId);

3. Can I get a confirmation if the flow for the integration is correct ? Am I following it correctly? How to catch any other error.  I notice when I open the OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none); it prints a lot of stuff so I want to to catch only the id after it has successfully register with Onesignal backend?

Below is my code snippet

```
Future<void> initPlatformState() async {
    if (!mounted) return;
    print("Before set log");
    //OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);
    print("Before set user privacy");
    OneSignal.shared.setRequiresUserPrivacyConsent(_requireConsent);

    var settings = {
      OSiOSSettings.autoPrompt: false,
      OSiOSSettings.promptBeforeOpeningPushUrl: true
    };
    
    OneSignal.shared.setNotificationReceivedHandler((notification) {
      print("Notify receive ready");
      this.setState(() {
        _debugLabelString =
            "Received notification: \n${notification.jsonRepresentation().replaceAll("\\n", "\n")}";
      });
    });
    
    OneSignal.shared
        .setNotificationOpenedHandler((OSNotificationOpenedResult result) {
      this.setState(() {
        _debugLabelString =
            "Opened notification: \n${result.notification.jsonRepresentation().replaceAll("\\n", "\n")}";
      });
      Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => SplashPage(),
          ),
        );
    });
    
    OneSignal.shared
        .setSubscriptionObserver((OSSubscriptionStateChanges changes) {
      print("SUBSCRIPTION STATE CHANGED: ${changes.jsonRepresentation()}");
    });

    OneSignal.shared.setPermissionObserver((OSPermissionStateChanges changes) {
      print("PERMISSION STATE CHANGED: ${changes.jsonRepresentation()}");
    });

  
    // NOTE: Replace with your own app ID from https://www.onesignal.com
    await OneSignal.shared
        .init("887772f0-71fa-4c17-824d-0a143c868323", iOSSettings: settings)
         
        .then((_) {
            OneSignal.shared.getPermissionSubscriptionState().then((status){
                 var outputJson = status.jsonRepresentation();
                // outputJson = outputJson.replaceAll('', '\\"');
                 print("user is "+status.subscriptionStatus.userId);
            });
        })
         .catchError((onError){
           print("Catch ON Error is "+onError.toString());
         }
         );     
        
    
    OneSignal.shared
        .setInFocusDisplayType(OSNotificationDisplayType.notification);

    bool requiresConsent = await OneSignal.shared.requiresUserPrivacyConsent();
    
    this.setState(() {
      _enableConsentButton = requiresConsent;
    });
  }




  void _handleConsent() {
    print("Setting consent to true");
    OneSignal.shared.consentGranted(true);

    print("Setting state");
    this.setState(() {
      _enableConsentButton = false;
    });
  }

  void _movePage() {
   Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => SplashPage(),
          ),
        );
  }
```

**Comment by rgomezp** [comment]
Hello,
Please keep in mind that other than the `setLogLevel` method, the OneSignal `init` method has to be called before anything else. Otherwise, OneSignal hasn't been initialized yet so you will get plenty of errors. 

To get the UserID, you can use the `subscriptionStatus` object as you are doing. Here are the related [docs](https://documentation.onesignal.com/docs/flutter-sdk#section--getpermissionsubscriptionstate-).

Cheers

**Comment by newbieflutter** [comment]
Hi rgomezp,
                    Should I enable the setLoglevel method then ? So should I call the init immediately right at the top cause in the example is right at the bottom. Beside that should I call this whole code in every page so that it works fine or just one initial page will do. Cause based on my testing I just put in one initial page it works on other page too.

**Comment by rgomezp** [comment]
Hello,
The logging method is optional. However, it does help give insight into what OneSignal is doing behind the scenes. This can be seen through the log. 

You should only put it in one place. Follow our setup instructions in our documentation for Flutter for more info. It doesn't matter if it is at the top of the file or not. Just make sure that there isn't any other OneSignal method being called before the init method.

**Comment by newbieflutter** [comment]
Hi rgomezp,
                    So I enable the logs is not an issue. But when it goes into production how to view those logs in the phone both for Android/ios. 

Currently this how it I setup is this safe ? So in this case I have call the init and I call the then to get the userID and only then below is I call OneSignal.shared.consentGranted(true); etc. Just to confirm is this correct and right to do ?

Future<void> initPlatformState() async {    
    if (!mounted) return;
    print("Before set log");
    //OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);
    print("Before set user privacy");
    //OneSignal.shared.setRequiresUserPrivacyConsent(_requireConsent);

    var settings = {
      OSiOSSettings.autoPrompt: false,
      OSiOSSettings.promptBeforeOpeningPushUrl: true
    };
    
    OneSignal.shared.setNotificationReceivedHandler((notification) {     
      
    });
    
    OneSignal.shared
        .setNotificationOpenedHandler((OSNotificationOpenedResult result) {
      print("Payload only is"+result.notification.payload.jsonRepresentation().toString());
      var fullPayload = result.notification.payload.jsonRepresentation().toString();

      var title  = result.notification.payload.title;
      print('Titlesss, $title');
      
      var decodeRaw = result.notification.payload.rawPayload;

      var alertValue = decodeRaw['alert'].toString();
      print("Alert value is"+alertValue);
      
    });
    
    OneSignal.shared
        .setSubscriptionObserver((OSSubscriptionStateChanges changes) {
      print("SUBSCRIPTION STATE CHANGED: ${changes.jsonRepresentation()}");
    });

    OneSignal.shared.setPermissionObserver((OSPermissionStateChanges changes) {
      print("PERMISSION STATE CHANGED: ${changes.jsonRepresentation()}");
    });

    await OneSignal.shared
        .init("************", iOSSettings: settings)
         
        .then((_) {
            OneSignal.shared.getPermissionSubscriptionState().then((status){
                // var outputJson = status.jsonRepresentation();
                userIDOneSignal = status.subscriptionStatus.userId;
                // outputJson = outputJson.replaceAll('', '\\"');
                 print("user is "+status.subscriptionStatus.userId);
            });
        })
         .catchError((onError){
           print("Catch ONError is "+onError.toString());
         }
         );     
        
    OneSignal.shared.consentGranted(true);
    OneSignal.shared
        .setInFocusDisplayType(OSNotificationDisplayType.notification);

    bool requiresConsent = await OneSignal.shared.requiresUserPrivacyConsent();
    
  }

**Comment by rgomezp** [comment]
You need to put the init call before the others. I'm going to go ahead and close this issue since it sounds more like you're just looking for setup help. I'd point you to our support chat at onesignal.com for this type of thing. Thanks for reaching out
