### ISSUE TITLE
[Bug]: **external_id not registerd**

### ISSUE THREAD

**Issue by salahturkmen** [OneSignal/OneSignal-Flutter-SDK#841]
### What happened?

**User Subscribed in dashboard but  external_id not registerd**

### Steps to reproduce?

```Markdown
Tested in real devices
And two mothed
    OneSignal.login('Odun1');
    OneSignal.loginWithJwt('Odun1','******');
```

### What did you expect to happen?

  **User Subscribed With external_id**

### OneSignal Flutter SDK version

Release 5.1.0

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Relevant log output

```Shell
D/OneSignal(17426): [OpRepo] LoginUserOperationExecutor(operation: [{"name":"login-user","appId":"**-**-**-**-**","onesignalId":"**-**-**-**-**","externalId":"Odun2","existingOnesignalId":"**-**-**-**-**","id":"**-**-**-**-**"}, {"name":"transfer-subscription","appId":"**-**-**-**-**","subscriptionId":"**-**-**-**-**","onesignalId":"**-**-**-**-**","id":"**-**-**-**-**"}])
D/OneSignal(17426): [OpRepo] IdentityOperationExecutor(operations: [{"name":"set-alias","appId":"**-**-**-**-**","onesignalId":"**-**-**-**-**","label":"external_id","value":"Odun2"}])
D/OneSignal(17426): [DefaultDispatcher-worker-5] HttpClient: PATCH apps/**-**-**-**-**/users/by/onesignal_id/**-**-**-**-**/identity - {"identity":{"external_id":"Odun2"}}
D/OneSignal(17426): [DefaultDispatcher-worker-5] HttpClient: PATCH apps/**-**-**-**-**/users/by/onesignal_id/**-**-**-**-**/identity - FAILED STATUS: 401
W/OneSignal(17426): [DefaultDispatcher-worker-5] HttpClient: PATCH RECEIVED JSON: {"errors":[{"code":"auth-1","title":"This operation requires 'Authorization' in the HTTP header"}]}
D/OneSignal(17426): [OpRepo] OperationRepo: execute response = FAIL_UNAUTHORIZED
E/OneSignal(17426): Operation execution failed without retry: [{"name":"login-user","appId":"**-**-**-**-**","onesignalId":"**-**-**-**-**","externalId":"Odun2","existingOnesignalId":"**-**-**-**-**","id":"**-**-**-**-**"}, {"name":"transfer-subscription","appId":"**-**-**-**-**","subscriptionId":"**-**-**-**-**","onesignalId":"**-**-**-**-**","id":"**-**-**-**-**"}]
E/OneSignal(17426): Could not login user
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gitananun** [comment]
Having the same issue. Login with any `external_id` is not working.
After allowing the notifications, a new subscription is there with an empty `external_id`.

**Comment by vydyas** [comment]
@salahturkmen Do you have any other solution?

**Comment by salahturkmen** [comment]
not yet trying to update external id by rest api

**Comment by nan-li** [comment]
Hi @salahturkmen do you have Identity Verification turned on for your app?

The v5 SDKs currently do not support that feature yet so Identity Verification should be off.

**Comment by salahturkmen** [comment]
@nan-li  Identity Verification?

**Comment by vydyas** [comment]
@nan-li  what is Identity Verification?

**Comment by nan-li** [comment]
Hi @vydyas,
I would not expect the error `{"errors":[{"code":"auth-1","title":"This operation requires 'Authorization' in the HTTP header"}]}` if you have Identity Verification turned off.

Is everyone else reporting also seeing this with Identity Verification turned to "off"?

**Comment by salahturkmen** [comment]
> Hi @salahturkmen,
> 
> If you go into the OneSignal Dashboard, go to **Settings** > **Keys & IDs** > **Identity Verification for email + external_id** is a toggle.
> <img alt="Screenshot 2024-02-23 at 10 10 23 AM" width="1008" src="https://private-user-images.githubusercontent.com/4022291/307412811-6f62f45d-f2df-4b8f-b446-c045e4b10c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MjM3MjEsIm5iZiI6MTcwODcyMzQyMSwicGF0aCI6Ii80MDIyMjkxLzMwNzQxMjgxMS02ZjYyZjQ1ZC1mMmRmLTRiOGYtYjQ0Ni1jMDQ1ZTRiMTBjNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMjEyMzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjI0YzRjOGFkNGU3MDNmMDk0NTBlMzIxNzI4ZTY2Yzc4ZDA5M2E4OWI3YzZmYzVkNTY4NDk3ZDk4OGJhZmU2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tjH-1EBQ4k026zAkhHk9hbOQFKbukfUT-zV9dJnLo2c">
> 
> Can you confirm it is set to "off"?

thank no it run

**Comment by gitananun** [comment]
Still having issues with external_id. For one user only, it works fine. But I'm testing with other user's phones, and it doesn't register the external_id for the users.

**Comment by tamiratdereje** [comment]
> Still having issues with external_id. For one user only, it works fine. But I'm testing with other user's phones, and it doesn't register the external_id for the users.

I think you have to reinstall the app, and it will work perfectly.

**Comment by masreplay** [comment]
any updates?
