### ISSUE TITLE
[question]: shared id is not registered

### ISSUE THREAD

**Issue by EngRiaz** [OneSignal/OneSignal-Flutter-SDK#842]
### How can we help?

i want to integrate push notifications for my app , but i am getting error in the code

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@EngRiaz Thanks for reporting but this isn't enough detail for us to investigate. Can you create a new issue filling out a [bug report](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=bug-report.yml&title=%5BBug%5D%3A+)?
