### ISSUE TITLE
[question]: When using Flutter flavor, how can I configure the correct settings on iOS?

### ISSUE THREAD

**Issue by FullstackWEB-developer** [OneSignal/OneSignal-Flutter-SDK#851]
### I checked many issues but I can't find correct solution.
https://github.com/OneSignal/onesignal-expo-plugin/issues/40
https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/696

**Comment by mberktas** [comment]
Hi, @FullstackWEB-developer 

I'm in the same situation.
Did you find a solution?

**Comment by mohammadhassan1497** [comment]
same here

**Comment by FullstackWEB-developer** [comment]
For those experiencing the same problem.

The main issue was that I didn't know much about Xcode settings.
I've been stuck here for a few days.

It was important to read the flavor configuration documentation on iOS carefully.
https://docs.flutter.dev/deployment/flavors
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/92151436/ce8c36cf-cc66-4176-9deb-b37480058adf)
The schema setting part was the problem I missed.
All names visible in buildConfiguration must match.
\ios\Runner.xcodeproj\xcshareddata\xcschemes\production.xcscheme
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/92151436/33e37bd3-8af8-4b2e-9dd0-bf70c2036b90)
