### ISSUE TITLE
[question]: Show notification like WhatsApp

### ISSUE THREAD

**Issue by RogerBrusamarello** [OneSignal/OneSignal-Flutter-SDK#855]
### How can we help?

Is there an option to display notifications on the screen when the app is in the background mode on Android devices?

Like this:
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/34141109/1ad7c89e-ceff-4cdb-9d18-6b2ae673bea0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @RogerBrusamarello,

Are you asking about Android ["heads-up"](https://developer.android.com/develop/ui/views/notifications#Heads-up) notification? 

For Android 8 and newer you will need to create a Notification Category / Channel with a high priority to make it heads up. OneSignal's dashboard has this build in, see the documentation below.
https://documentation.onesignal.com/docs/android-notification-categories
