### ISSUE TITLE
[question]: Problem with geolocation

### ISSUE THREAD

**Issue by Samuelg0ld** [OneSignal/OneSignal-Flutter-SDK#859]
### How can we help?

Hi i have problem with OneSignal geolocation. In my app i made request for geolocation and if geolocation is accepted i will set OneSignal.Location.setShared(true);

Everything works fine in emulator, but when i made build apk and then download apk to my real device, on the real device i accepted geolocation and after that nothing happened. In one signal i saw that i have new subsciption but in location point was nothing...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Samuelg0ld** [comment]
UPDATE - i tried some ways and i found that if i install apk-debug.apk it works fine but if i install apk-release.apk OneSignal.location not working - PLEASE HELP ME FIX

**Comment by nan-li** [comment]
Hey @Samuelg0ld thanks for reporting. Can you test with obfuscation off?

See this comment on how: https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/713#issuecomment-1692991176

**Comment by Samuelg0ld** [comment]
Yeah i tried it but it not working.

**Comment by FullstackWEB-developer** [comment]
I had same issue so I added this code to proguard-rule.pro and then it's also working on release mode
```
# Keep location-related classes and methods
-keep class com.google.android.gms.location.** { *; }
-keep class com.google.android.gms.common.api.** { *; }
-keep class com.google.android.gms.tasks.** { *; }
```

**Comment by jennantilla** [comment]
Looks like this discussion has gone stale, so I'll be closing it out. @Samuelg0ld was the solution above sufficient for you?
