### ISSUE TITLE
[question]:  Can't Disable Launch URL Notification when opened (Flutter)

### ISSUE THREAD

**Issue by lyfer-bob** [OneSignal/OneSignal-Flutter-SDK#863]
### How can we help?

Unable to disable the launch url  in notification when opened.

What can I do to completely remove the launch Url? 

ENV.
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19045.2728], locale th-TH)       
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)

onesignal_flutter  : Release 5.1.2 
Emulator : Android 13 

and add the code in `AndroidManifest.xml`

`<meta-data android:name="com.onesignal.suppressLaunchURLs" android:value="true"/>`

[https://documentation.onesignal.com/docs/links](url)

or

`<application ...>
   <meta-data android:name="com.onesignal.NotificationOpened.DEFAULT" android:value="DISABLE" />
</application>`

[https://documentation.onesignal.com/docs/android-customizations](url)

But It's not working. How can i do that.

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mohamed-Abdelsalamm** [comment]
Hello 
Did you get the solution?

**Comment by jennantilla** [comment]
Hello there--apologies that this question was missed! Please see our [documentation](https://documentation.onesignal.com/v9.0/docs/links#suppressing-launch-urls) on suppressing Android Launch URLs. 

If you have any additional questions or concerns please let us know!
