### ISSUE TITLE
[question]:  Add Custom Notification sound not playing.

### ISSUE THREAD

**Issue by nikunjpanchall** [OneSignal/OneSignal-Flutter-SDK#869]
### How can we help?

I have added a notification sound file to this path (android/app/src/main/res/raw) and also created keep.xml file, but when the notification triggers, it will play the default sound.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@nikunjpanchall please check the following:

1. Confirm you have created an [Android Category / Channel](https://documentation.onesignal.com/docs/android-notification-categories) and are using it on the test notification you sent.
2. Ensure you used [a supported sound file type](https://documentation.onesignal.com/docs/customize-notification-sounds).
3. Extracting the contents of your APK to ensure the sound file is there.

**Comment by jennantilla** [comment]
Closing due to no response.
