### ISSUE TITLE
[question]: both addForegroundWillDisplayListener and addClickListener not triggered with hms (huawei).

### ISSUE THREAD

**Issue by Dicksenz** [OneSignal/OneSignal-Flutter-SDK#870]
### How can we help?

Any fix for that ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @Dicksenz thank you for your patience! Can you share a bit more about how and where you've added these methods? Does anything interesting pop up in the [logs](https://documentation.onesignal.com/docs/capturing-a-debug-log)?

We'll work on trying to reproduce this!

**Comment by tovidd** [comment]
@jennantilla i can confirmed `addForegroundWillDisplayListener` and `addClickListener` never triggered. 

The OneSignal log is printing well when new push notification arrived. 

```flutter
OneSignal.Notifications.addClickListener((event) {
      // this code never called
});
```

I also try to `removeForegroundWillDisplayListener` and `removeClickListener`. Also uninstall the apps. Nothing works.

**Comment by ihijazi** [comment]
Been having similar behavior, not only on cold start.

My app uses some native code for some other SDK. The other SDK had GeneratedPluginRegistrant.register(with: "xxx"), and it was placed AFTER GeneratedPluginRegistrant.register(with: self).

The GeneratedPluginRegistrant.register(with: self) has to be at the very end, for both Android and iOS.

example for swift:
```
        GeneratedPluginRegistrant.register(with: xxx)
        
        GeneratedPluginRegistrant.register(with: self) // this has to be at the very end

        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }

```

Tested with latest 5.2.2 and working fine.. all handlers as expected.

Hope this helps someone.

**Comment by jennantilla** [comment]
Thank you for this solution, @ihijazi!

We'll go ahead and close this issue.
