### ISSUE TITLE
[Feedback]: Leaked App ID on Example

### ISSUE THREAD

**Issue by Dimas-Saputra-Me** [OneSignal/OneSignal-Flutter-SDK#878]
## App ID Leaked
I came to take a look on the example section and there is already written an App ID on [here](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/6c882547186b90d73fd080ac2dbd399b95e4f2a8/example/lib/main.dart#L41). Is it actually App ID for public purpose? or It is not?

Thanks in advance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@Dimas-Saputra-Me Thank you for reaching out that is a default app id that is a placeholder. It should be replaced by your app id.
