### ISSUE TITLE
[question]: How to mock OneSignal

### ISSUE THREAD

**Issue by MarcelGalster** [OneSignal/OneSignal-Flutter-SDK#879]
### How can we help?

Hi, I want to write tests for my OneSingal integration and need to mock OneSignal to do this.
How can I do this as OneSignal only has static members?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @MarcelGalster, it is not easy to mock OneSignal for tests as it does only have static members.

What types of behaviors are you trying to test?

**Comment by jennantilla** [comment]
Closing due to no response.

**Comment by MarcelGalster** [comment]
Hello, sorry for my late reply.

I have a service in which I want to inject OneSignal. In my tests I want to inject a mocked OneSignal service. But dependency injection is not possible because the members are all static and there is no interface that OneSignal implements.

So what are your recommendations to do it as you implemented OneSignal in this way?
