### ISSUE TITLE
No NotificationService.m available but instead only NotificationViewController.m

### ISSUE THREAD

**Issue by newbieflutter** [OneSignal/OneSignal-Flutter-SDK#88]
I am setting up the flutter ios setup via this link https://documentation.onesignal.com/docs/flutter-sdk-setup. I have followed every step carefully till this step.

2.9 Reopen the Xcode project. In your project, in the OneSignalNotificationServiceExtension/ folder, open NotificationService.m and replace the whole file contents with:

What I notice I dont find file NotificationService.m but instead NotificationViewController.m. So I just tried to copy over those suggested codes then I receive error #import "NotificationService.h" file not found?

How best to resolve this or is there any bug somewhere ?

**Comment by rgomezp** [comment]
The file should be there. Not sure why you don't have it. Those are two very different files. I would recommend you clone this repo and take a look at our example project for reference

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by alivevietnam** [comment]
The same issue with React Native

**Comment by truongduy2611** [comment]
Make sure you choose Notification Service instead of Notifcation Content.
