### ISSUE TITLE
[Bug]: Android Push Notification Not subscribed

### ISSUE THREAD

**Issue by bonitoravi** [OneSignal/OneSignal-Flutter-SDK#886]
### What happened?

When I am trying to opt-in for push notifications, I click "allow ", yet its showing "Permission not granted". If i wait for couple of seconds before clicking on "Allow ", its being properly subscribed in One Signal

### Steps to reproduce?

```Markdown
1.Install the App.
2.Login into the app.
3.Click allow for permissions immediatelty when prompt appears.
4.OneSignal dashboard shows "Permission not granted"
```

### What did you expect to happen?

Permission should be granted

### OneSignal Flutter SDK version

5.1.2

### Which platform(s) are affected?

- [ ] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@bonitoravi apologies that this issue was missed--are you still seeing this behavior? Thanks for the update!
