### ISSUE TITLE
[question]: All included players are not subscribed

### ISSUE THREAD

**Issue by RuberDucky** [OneSignal/OneSignal-Flutter-SDK#887]
### How can we help?

I'm getting the issue of All included players are not subscribed from My API call,  anybody knows how to resolve this error

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @RuberDucky thanks for reaching out!

The "All Included Players are not subscribed" warning means that the filter or segment you are targeting does not have any subscribed users to receive push notifications.

You will need to double-check the segment or filter and make sure you are actually targeting subscribed users.

Please check the OneSignal dashboard > Users tab for the subscription status of the devices you tried to target.

Let us know if you have any additional questions or concerns!

**Comment by RuberDucky** [comment]
the OneSignal id we were using is wrong, the actually id we should use is the oneSignal.pushSubcription.id so this will not generate any error

**Comment by suathh** [comment]
I have this issue too.

![image](https://github.com/user-attachments/assets/4fa7ca88-d2f0-481d-8a9e-0ca0caf2e4b1)
I have the user I am trying to reach on my OneSignal dashboard.

But I am getting this error 
![image](https://github.com/user-attachments/assets/38c94a97-27d1-47a0-ba6d-bf027dd5fcde)

```
 const newNotification = new OneSignal.Notification();
  newNotification.app_id = app.id;
  // Name property may be required in some case, for instance when sending an SMS.
  newNotification.name = `Healify - ${Date.now()}`;
  newNotification.contents = {
    en: notification
  }
  newNotification.data = data;

  // required for Huawei
  newNotification.headings = {
    en: "Healify"
  }
  newNotification.include_subscription_ids = [onesignal_id];
  console.log(onesignal_id)
  newNotification.is_ios = true;
  newNotification.is_android = true;
  newNotification.mutable_content = true;
  newNotification.content_available = true;
  
  client.createNotification(newNotification)
  .then((response) => {
    console.log(response);
    if (user) {
      SendLocalNotification(user, notification, seen);
    }
  })
  .catch((e) => {
    console.error(e);
  });
```

And user is subscribed.

![image](https://github.com/user-attachments/assets/9666f4a1-5bdf-46b8-9dfd-29048472123d)
