### ISSUE TITLE
[Bug]: IOS : upload version to store

### ISSUE THREAD

**Issue by osama450** [OneSignal/OneSignal-Flutter-SDK#888]
### What happened?

i get this 2 issues when upload version to store : 

Asset validation failed (90206)
Invalid Bundle. The bundle at 'Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex' contains disallowed file 'Frameworks'. (ID: 53a5c750-38f5-4b2b-ab38-ab2a435d49ed)

Asset validation failed (90205)
Invalid Bundle. The bundle at 'Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex' contains disallowed nested bundles. (ID: 0506a1cf-0cb0-4ffb-ba90-0fc8dcdd8362)

### Steps to reproduce?

```Markdown
1 : try to upload version from xcode
```

### What did you expect to happen?

.

### OneSignal Flutter SDK version

5.1.6

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @osama450, your two error messages look similar to this Apple thread: https://forums.developer.apple.com/forums/thread/17732. 

Can you take a look and see if you are able resolve?

Additionally, you can share your Podfile and what is under the OneSignalNotificationServiceExtension's  **Frameworks and Libraries** section:

![Screenshot 2024-05-16 at 10 37 06 PM](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/4022291/0dfca41e-2f88-4770-ba8b-667023006b0c)

**Comment by osama450** [comment]
hi @nan-li  , I will share with you everything cuz I try all, and no one worked 
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/71011907/3cbee485-dfc2-4c01-be42-0d874ea91d6a)
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/71011907/2c92bdaf-c801-41be-abe0-d9266d668ed3)

**Comment by osama450** [comment]
my podfile :

# Uncomment this line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
       # Start of the permission_handler configuration
       target.build_configurations.each do |config|
       

        # You can enable the permissions needed here. For example to enable camera
        # permission, just remove the `#` character in front so it looks like this:
        #
        # ## dart: PermissionGroup.camera
        # 'PERMISSION_CAMERA=1'
        #
        #  Preprocessor definitions can be found in: https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler_apple/ios/Classes/PermissionHandlerEnums.h

        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
  
          ## dart: PermissionGroup.calendar
          # 'PERMISSION_EVENTS=1',
  
          ## dart: PermissionGroup.reminders
          # 'PERMISSION_REMINDERS=1',
  
          ## dart: PermissionGroup.contacts
          # 'PERMISSION_CONTACTS=1',
  
          ## dart: PermissionGroup.camera
          # 'PERMISSION_CAMERA=1',
  
          ## dart: PermissionGroup.microphone
          # 'PERMISSION_MICROPHONE=1',
  
          ## dart: PermissionGroup.speech
          # 'PERMISSION_SPEECH_RECOGNIZER=1',
  
          ## dart: PermissionGroup.photos
          # 'PERMISSION_PHOTOS=1',
  
          ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
          # 'PERMISSION_LOCATION=1',
  
          ## dart: PermissionGroup.notification
          # 'PERMISSION_NOTIFICATIONS=1',
  
          ## dart: PermissionGroup.mediaLibrary
           'PERMISSION_MEDIA_LIBRARY=1',
  
          ## dart: PermissionGroup.sensors
          # 'PERMISSION_SENSORS=1',   
  
          ## dart: PermissionGroup.bluetooth
          # 'PERMISSION_BLUETOOTH=1',
  
          ## dart: PermissionGroup.appTrackingTransparency
          # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',
  
          ## dart: PermissionGroup.criticalAlerts
          # 'PERMISSION_CRITICAL_ALERTS=1'
        ]
  
      end 
      # End of the permission_handler configuration
  end
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!  # Add this line
  pod 'OneSignalXCFramework', '>= 5.1.6', '< 6.0'
end

**Comment by osama450** [comment]
my podfile :
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/71011907/32f6aaee-01a2-488a-8287-e8f11e0604e8)

**Comment by osama450** [comment]
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/71011907/3dd9241b-da90-4452-a576-0c55840e15c9)

**Comment by osama450** [comment]
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/71011907/688136df-fe78-47b0-92a5-e5291a86b78b)

**Comment by emawby** [comment]
@osama450 I believe the issue is that the cocoapods in the Notification Service Extension target have been set to Embed & Sign. Try changing that to Do Not Embed.

**Comment by osama450** [comment]
@emawby  if i do that he uploads successfully but the service not work

**Comment by chuanpham** [comment]
Hi @osama450, did you solve the problem, how can you solve it? Thanks!

**Comment by osama450** [comment]
hi @chuanpham  hi fixed it by make the build option like tthat :
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/71011907/e3bb674a-328b-4f28-90d7-4ed56dcabaa0)
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/71011907/8a86e8bc-3568-448d-a3d8-a37579867461)
![image](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/71011907/39fd57bd-4b4c-4c11-b952-59b716d91c71)

**Comment by chuanpham** [comment]
@osama450 thank you very much
