### ISSUE TITLE
[question]:   Add Notification to flutterFlow Web

### ISSUE THREAD

**Issue by RodrigoRodriguez1** [OneSignal/OneSignal-Flutter-SDK#894]
### How can we help?

With notification via Android it worked 100%.

How do I add it to work on the web (Google Chome)?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@RodrigoRodriguez1 This repo is for Flutter apps which is different than FlutterFlow.

See this guide for integrating OneSignal into your FlutterFlow app:
https://docs.flutterflow.io/settings-and-integrations/integrations/onesignal
