### ISSUE TITLE
[question]: refresh pushSubscriptionId?

### ISSUE THREAD

**Issue by juarezfranco** [OneSignal/OneSignal-Flutter-SDK#903]
### How can we help?

Is it possible refresh token? for example, when sign in out, I want to refresh token

this token -> `OneSignal.User.PushSubscription.id`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @juarezfranco, the push subscription is tied to the device, and contain the push token.
When users log out, the subscription ID remains the same, but is no longer associated with the user.
