### ISSUE TITLE
Notifications are not being received on the mobile device.

### ISSUE THREAD

**Issue by andersonsantos6** [OneSignal/OneSignal-Flutter-SDK#908]
### What happened?

The device encounters an error when the initialize method is executed. Below is the error message returned in the log:

ERROR  
Operation execution failed without retry: [{"name":"login-user-from-subscription","appId":"99f94cc9-1282-4bb0-8ef7-3ccc4343d2ab","onesignalId":"local-b783f75c-c233-4720-b8d1-a3636d5cbee8","subscriptionId":"48a395ec-b91e-4700-a739-3960f0355520","id":"8d7fbf49-0cb4-479b-b928-4e16c1d0ca25"}]

Software Information:

One UI Version: 6.1
Android Version: 14
Google Play System Update: May 1, 2024
Baseband Version: S918BXXS5CXDE
Kernel Version: 5.15.123-android13-28577312-ab59188BXXS5CXDE #1 Tue May 7 10:30:20 UTC 2024
Build Number: UP1A.231005.007.S918BXXS5CXDE
SE for Android Status: Enforcing SEP_SEPF_S918B_13.0001 Tue May 07 20:13:31 2024
Knox Version:
Knox 3.10
Knox API level 37
Knox ML 1.4
DualDAR 1.6.6
HDM 3.0 - 115
Carrier Software Version: SAOMC_SM-S918B_OYO_ZTO_14_0021 ZTO/ZTO,ZTO/ZTO
Security Software Version:
MDF v3.3 Release 1
VPN Client v2.1.2 Release 2.0
ASK v3.1 Release 2023100
ADP v3.1 Release 202310
FIPS BoringSSL v1.7
FIPS SKC v2.3
FIPS SCrypto v2.7
SMS v3.0 Release 202310
Android Security Patch Level: May 1, 2024

### Steps to reproduce?

```Markdown
The device encounters an error when the initialize method of OneSignal is executed after starting the app. Below is the error message returned in the log:

ERROR
Operation execution failed without retry: [{"name":"login-user-from-subscription","appId":"99f94cc9-1282-4bb0-8ef7-3ccc4343d2ab","onesignalId":"local-b783f75c-c233-4720-b8d1-a3636d5cbee8","subscriptionId":"48a395ec-b91e-4700-a739-3960f0355520","id":"8d7fbf49-0cb4-479b-b928-4e16c1d0ca25"}]
```

### What did you expect to happen?

We expected the OneSignal service to work normally as it does on other devices. Unfortunately, on this specific device, OneSignal requests notification permission, we accept, but it does not receive notifications. Other devices with the same app are functioning normally.

### OneSignal Flutter SDK version

5.2.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
Operation execution failed without retry: [{"name":"login-user-from-subscription","appId":"99f94cc9-1282-4bb0-8ef7-3ccc4343d2ab","onesignalId":"local-b783f75c-c233-4720-b8d1-a3636d5cbee8","subscriptionId":"48a395ec-b91e-4700-a739-3960f0355520","id":"8d7fbf49-0cb4-479b-b928-4e16c1d0ca25"}]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@andersonsantos6 Thanks for reporting. There should have been a few more errors before this one with more detail, can you share those as well?

Also I recommend updating to the latest 5.2.2 as your issue may have been fixed.

**Comment by nan-li** [comment]
Closing due to no response
