### ISSUE TITLE
[Bug]: Found bundle at 

### ISSUE THREAD

**Issue by bugrevealingbme** [OneSignal/OneSignal-Flutter-SDK#920]
### What happened?

Found bundle at /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.5PEvpp/extracted/Runner.app/Frameworks/OneSignal.framework with the same identifier (com.onesignal.OneSignal-Dynamic) as bundle at /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.5PEvpp/extracted/Runner.app/Frameworks/OneSignalFramework.framework

### Steps to reproduce?

```Markdown
Tried running on debug mode
```

### What did you expect to happen?

When trying installing app

### OneSignal Flutter SDK version

5.2.2

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
Found bundle at /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.5PEvpp/extracted/Runner.app/Frameworks/OneSignal.framework with the same identifier (com.onesignal.OneSignal-Dynamic) as bundle at /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.5PEvpp/extracted/Runner.app/Frameworks/OneSignalFramework.framework
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
`com.onesignal.OneSignal-Dynamic` is an older framework, it OneSignal 5.x.x doesn't use that version. Can you ensure you are using the same version of OneSignal in your Podfile for the Notification Service Extension and the main target? You may also need to do a clean build to clean up the older framework.

**Comment by jennantilla** [comment]
@bugrevealingbme just reaching out to see if the suggestion above resolved your issue? Thanks for the update!
