### ISSUE TITLE
[question]: Does onesignal support minimum IPHONEOS_DEPLOYMENT_TARGET = 12 ?

### ISSUE THREAD

**Issue by shafiqruslan** [OneSignal/OneSignal-Flutter-SDK#925]
### How can we help?

Hi, I got this error when i try to release my app.

`warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'OneSignalXCFramework' from project 'Pods').`

My question is does onesignal support minimum IPHONEOS_DEPLOYMENT_TARGET = 12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @shafiqruslan, yes it does.

If you want to remove this warning, you can set your deployment target to 12 (or any version that you want your app to support).

**Comment by shafiqruslan** [comment]
> Hi @shafiqruslan, yes it does.
> 
> If you want to remove this warning, you can set your deployment target to 12 (or any version that you want your app to support).

Hi, thank you for answering my question, I already set deployment target to 12 in my podfile. But when i want to release the app it still shows this error.

`warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'OneSignalXCFramework' from project 'Pods').`

I have already flutter clean, flutter pub get, pod repo update and pod install but nothing works. maybe i miss steps or something?

**Comment by nan-li** [comment]
Hi @shafiqruslan, since the OneSignal SDK supports more versions than you may want to support, you can overwrite the SDK's deployment version. This [StackOverflow post](https://stackoverflow.com/questions/54704207/the-ios-simulator-deployment-targets-is-set-to-7-0-but-the-range-of-supported-d) has some suggestions. 

I typically add this snippet to my Podfile (in this example, the target is set to `13`):
```
post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
```
