### ISSUE TITLE
[question]: How do I get XCTests to run properly (Flutter App)?

### ISSUE THREAD

**Issue by jnovak-SM2Dev** [OneSignal/OneSignal-Flutter-SDK#927]
### How can we help?

How do I get XCTests in RunnerTests to work in a Flutter app? I assume I need to add something to the test build target, but the docs don't mention anything.

Test command (from Firebase Test Lab docs)

```
xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme Runner -xcconfig Flutter/Release.xcconfig -configuration Release -derivedDataPath ../build/ios_integ -sdk iphoneos
```

The error I receive
```
The following build commands failed:
        Ld /Users/username/Projects/my_app/build/ios_integ/Build/Products/Release-iphoneos/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension normal (in target 'OneSignalNotificationServiceExtension' from project 'Runner')
```

Firebase Test Lab docs:

https://github.com/flutter/flutter/tree/main/packages/integration_test#ios-device-testing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @jnovak-SM2Dev thank you for reaching out. Can you share more about what exactly was the build command that failed? 
What is the error for the OneSignalNotificationServiceExtension?

**Comment by jnovak-SM2Dev** [comment]
@nan-li That's all the log has about it. If I do `verbose` it gives me 500 lines, but nothing more about the error. Do I need to add anything to the `RunnerTests` target? That's the only thing I can think of.

**Main Target:**
<img width="1430" alt="Screenshot 2024-08-08 at 3 59 16 PM" src="https://github.com/user-attachments/assets/b0bc31ad-0fcf-475a-89d0-0a489d71bcb3">

**Test Target:**
<img width="1430" alt="Screenshot 2024-08-08 at 3 59 21 PM" src="https://github.com/user-attachments/assets/5cbfbb96-6dbb-4f65-9957-b8c957ad12c1">

**Comment by nan-li** [comment]
The `ld` command is a link editor, also known as a linker. It combines object and archive files to create an executable. Without a failure or error message, I don't know how to help you resolve.
