### ISSUE TITLE
A package may not list itself as a dependency.

### ISSUE THREAD

**Issue by malikdoksoz** [OneSignal/OneSignal-Flutter-SDK#93]
Flutter SDK: 1.5.4.hotfix2
Dart: 2.3

**pubspec.yaml**
`dependencies:
  flutter:
    sdk: flutter

  onesignal: ^1.1.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2`

![2019-05-30](https://user-images.githubusercontent.com/26676061/58632253-6cf4f980-82bb-11e9-8ce7-c164ecedbb92.png)

**Comment by rgomezp** [comment]
Hello,
It looks like this is a problem with your `pubspec.yaml` file. Could you please include it so I can take a look? The screenshot doesn't provide enough info.

**Comment by rgomezp** [comment]
Closing due to no response
