### ISSUE TITLE
Custom Sound and Vibration

### ISSUE THREAD

**Issue by alishahzad331** [OneSignal/OneSignal-Flutter-SDK#931]
### How can we help?

How do i set custom sound or no sound and no vibration on all the notifications of onesignal when notifications receive . 
I do not see any option in the example of this sdk

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @alishahzad331 thanks for reaching out! Please check out our documentation on customizing sounds [here](https://documentation.onesignal.com/docs/customize-notification-sounds). Let us know if you have any additional questions or concerns!
