### ISSUE TITLE
[question]: iam Using  onesignal_flutter: ^5.2.1 but when i build the Project Showing Execution failed for task ':onesignal_flutter:verifyReleaseResources'. > A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action

### ISSUE THREAD

**Issue by devNasih** [OneSignal/OneSignal-Flutter-SDK#936]
### How can we help?

 AAPT: error: resource android:attr/lStar not found.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @devNasih thanks for reaching out! We have a discussion going on [here](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/930) and a PR that will be merged into our next Flutter release. I'm going to close this issue out for consolidation but please follow #930 for updates. Thanks!

**Comment by Ashwin1002** [comment]
Add this line in your android level build.gradle file

```
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

    // add this line for onesignal_flutter to work in android device
    afterEvaluate {
        android {
            compileSdkVersion 34
        }
    }
}
```

**Comment by apoorvpandey0** [comment]
> Add this line in your android level build.gradle file
> 
> ```
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> 
>     // add this line for onesignal_flutter to work in android device
>     afterEvaluate {
>         android {
>             compileSdkVersion 34
>         }
>     }
> }
> ```

This worked thanks!

**Comment by chethan2125** [comment]
thank you it works


subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

    // add this line for onesignal_flutter to work in android device
    afterEvaluate {
        android {
            compileSdkVersion 34
        }
    }
}
