### ISSUE TITLE
[Bug]: Execution failed for task ':onesignal_flutter:parseDebugLocalResources'. > Could not resolve all files for configuration ':onesignal_flutter:androidApis'.    > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.       > Execution failed for PlatformAttrTransform: C:\Users\Srp Technologoies\AppData\Local\Android\sdk\platforms\android-28\android.jar.

### ISSUE THREAD

**Issue by sajidullah-srp** [OneSignal/OneSignal-Flutter-SDK#938]
### What happened?

PS D:\sajid\nurse_staffing_app> flutter run 
Launching lib\main.dart on SM A325F in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':onesignal_flutter:parseDebugLocalResources'.
> Could not resolve all files for configuration ':onesignal_flutter:androidApis'.
   > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for PlatformAttrTransform: C:\Users\Srp Technologoies\AppData\Local\Android\sdk\platforms\android-28\android.jar.
         > C:\Users\Srp Technologoies\AppData\Local\Android\sdk\platforms\android-28\android.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
Running Gradle task 'assembleDebug'...                             42.1s
Error: Gradle task assembleDebug failed with exit code 1

### Steps to reproduce?

```Markdown
1. install API level 28
```

### What did you expect to happen?

solve this

### OneSignal Flutter SDK version

Release 5.2.3

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nextvisionmx** [comment]
It seems to be the problem when updating the flutter version, in this other one they give the solution: 
https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/930

sohyuyuan has a temporary solution

**Comment by jennantilla** [comment]
Hello there! If you upgrade to our latest SDK version, this issue should be resolved. Please let us know if you have any additional questions or concerns!
