### ISSUE TITLE
Not reciving notification after removing Post Notification button from example code.

### ISSUE THREAD

**Issue by TheBossBaby** [OneSignal/OneSignal-Flutter-SDK#96]
I copied the source code as it is to my project, and it worked fine it was receiving the notification from server side.

But as I removed the Post Notification Button from UI I am unable to receive notificarion from server side.

**Comment by rgomezp** [comment]
Hello,
Could you please provide more details regarding what you're actually trying to do here?

Thanks

**Comment by rgomezp** [comment]
Closing due to no response
