### ISSUE TITLE
[Bug]: The archive did not include a dSYM for the OneSignalUser.framework with the UUIDs

### ISSUE THREAD

**Issue by miguelmobilat** [OneSignal/OneSignal-Flutter-SDK#964]
### What happened?

During app submission, receiving an error related to missing dSYM file for OneSignalUser.framework. The error indicates that the archive doesn't include the required dSYM with the expected UUIDs.

Error message:
"The archive did not include a dSYM for the OneSignalUser.framework with the UUIDs [***]. Ensure that the archive's dSYM folder includes a DWARF file for OneSignalUser.framework with the expected UUIDs."

### Steps to reproduce?

```Markdown
1. Build app for release
2. Archive the app
3. Attempt to submit to App Store
4. Error appears during validation regarding missing dSYM file
```

### What did you expect to happen?

Expected the archive to properly include all necessary dSYM files for OneSignal frameworks, allowing successful submission to the App Store.

<img width="759" alt="Screenshot 2024-10-23 at 2 31 29 PM" src="https://github.com/user-attachments/assets/a3da45c3-c557-426a-b5bd-8a5b575af9a5">

### OneSignal Flutter SDK version

5.2.6

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @miguelmobilat thanks for reporting. This is a new warning as of Xcode 16 and can be safely ignored. 

To omit the warning, you can follow the suggestion from this Apple thread: https://forums.developer.apple.com/forums/thread/763731

![Screenshot 2024-10-23 at 11 57 06 AM](https://github.com/user-attachments/assets/5a2dfe99-7e55-45c4-99c6-eeb5aa6ef06e)
