### ISSUE TITLE
[Bug]: Unusual popup occur open app first time flutter

### ISSUE THREAD

**Issue by geeky-dawood** [OneSignal/OneSignal-Flutter-SDK#967]
### What happened?

When app open first time a unusual dialouge box show. That happen only first time after downloading 
I have also reverify my code for this dialouge but their is nothing that can produce this. I am not clear it is releated to one-signal or anyother package

here is my pubspec.yaml
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  get: ^4.6.5
  # Networking
  dio: ^5.3.0
  http: ^0.13.5
  # DataBase
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  # Authentication
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^6.1.3
  flutter_facebook_auth: ^6.0.4
  # Location and Maps
  flutter_place_picker: ^0.0.1-dev.5
  google_maps_flutter: ^2.3.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  map_launcher: ^3.5.0
  # File Handling
  image_picker: ^1.0.1
  permission_handler: ^10.4.3
  file_picker: ^8.1.2
  path_provider: ^2.1.1
  audio_waveforms: ^1.0.4
  just_audio: ^0.9.35
  # image_gallery_saver: ^2.0.3
  open_filex: ^4.3.4
  device_info_plus: ^10.1.2
  # Payment
  flutter_paypal: ^0.2.0
  flutter_stripe: ^11.1.0
  # Crash Info
  firebase_crashlytics: ^4.1.3
  # UI/Widgets
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0
  dropdown_textfield: ^1.1.0
  pinput: ^5.0.0
  flutter_animate: ^4.2.0
  lottie: ^3.0.0
  adaptive_dialog: ^2.2.1+2
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  chat_bubbles: ^1.4.1
  dotted_border: ^2.0.0+3
  # chips_input: ^0.1.0
  image_cropper: ^4.0.1
  # Other
  url_launcher: ^6.2.1
  form_field_validator: ^1.1.0
  intl: ^0.19.0
  webview_flutter: ^4.8.0
  uuid: ^4.5.1
  flutter_local_notifications: ^17.2.3
  flutter_dotenv: ^5.1.0
  socket_io_client: ^3.0.0
  onesignal_flutter: ^5.2.0
  flutter_paypal_checkout: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  image_gallery_saver:
    git:
      url: https://github.com/knottx/image_gallery_saver.git
      ref: knottx-latest
      
![Screenshot_2024-10-29-16-26-00-35_d4809b97f3600e69af52a24373ba7f35](https://github.com/user-attachments/assets/fea6d944-f1cc-4694-b835-79baa8f6bbd8)

### Steps to reproduce?

```Markdown
I didn't how to reproduce it. It happening in development and release mode both. This is happening only the first time after downloading the app. you can check this after downloading the app and wait for 10 second after opening the app no need to login or signup, no need for allow or deny it will occur within 10 seconds.

PlayStore link:
https://play.google.com/store/apps/details?id=com.ustf.ipassengerapp&hl=en

AppStore link:
https://apps.apple.com/us/app/ipassenger/id6468575636
```

### What did you expect to happen?

I expected the app to behave normally

### OneSignal Flutter SDK version

Release 5.2.0

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @geeky-dawood the image from your screenshot is an [in-app message](https://documentation.onesignal.com/docs/in-app-messages). This is configured from the OneSignal dashboard from the Messages > In-App tab. You can deactivate it by clicking 'Pause' from the 3-dot dropdown on the right:
<img width="292" alt="Screenshot 2024-10-30 at 9 41 04 AM" src="https://github.com/user-attachments/assets/0f1e95a8-57a0-4ba5-9a20-4eb43a426c43">

Please let us know if you have any additional questions or concerns!
