### ISSUE TITLE
setNotificationOpenedHandler or setNotificationReceivedHandler never gets called if app is not in forground in Android.

### ISSUE THREAD

**Issue by westlinkin** [OneSignal/OneSignal-Flutter-SDK#98]
```
 OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {
      // will be called whenever a notification is opened/button pressed.
      // todo:
      print("action: ${result.action.type}-${result.action.actionId}, notification: ${result.notification.jsonRepresentation()}");
    });

    OneSignal.shared.setNotificationReceivedHandler((OSNotification notification) {
      // todo:
      print("notification: ${notification.jsonRepresentation()}");
    });
``` 
This code snippet only gets called when app is in foreground. No matter this code is executed in `main` or in `initState` of the app's root widget.

So how can the app opens a certain screen when the user taps on the notification ( when app is closed by user). Default only opens the app.

While Firebase message flutter sdk has `onMessage`, `onLaunch`, and `onResume` [callbacks](https://github.com/flutter/plugins/tree/master/packages/firebase_messaging#receiving-messages). Does OneSignal SDK have an alternative approach?

**Comment by rgomezp** [comment]
Hello,
Well the openedHandler will not get called if the app is in foreground because the notification will not display by default. The onReceived should, however. To open a specific screen, take a look at our [deep linking docs. ](https://documentation.onesignal.com/docs/links)

**Comment by westlinkin** [comment]
There is no Flutter related docs. Should I write native code on iOS and Android platform to handle this?

And, if the flutter app is closed, `openedHandler` and `receivedHandler` will not be called at all. How should I implement business logic when  notification is opened?

**Comment by rgomezp** [comment]
Take a look at our notification behavior [docs](https://documentation.onesignal.com/docs/how-notifications-work) to see how the notifications behave when the app is closed. There are only a couple of cases where they won't show. The opened handler will be called only if the notification is tapped on. Your business logic should go in the opened handler if you want the logic to execute at that time

**Comment by westlinkin** [comment]
But the code/ business logic is not called when the notification is tapped on and the app is closed.

**Comment by dhsont** [comment]
> But the code/ business logic / openedHander is not called when the notification is tapped on and the app is closed.

Check This.
[https://github.com/IhorKlimov/Flutter-One-Signal#notification-open-handler](https://github.com/IhorKlimov/Flutter-One-Signal#notification-open-handler
)

**Comment by aliAhmedJazar** [comment]
> But the code/ business logic / openedHander is not called when the notification is tapped on and the app is closed.

yes I'm facing same problem

**Comment by rgomezp** [comment]
@westlinkin @dhsont @aliAhmedJazar ,
Please comment with a [pastebin](https://pastebin.com) with your logs.
Make sure to use the OneSignal `setLogLevel` [method](https://documentation.onesignal.com/docs/flutter-sdk#section--setloglevel-)

**Comment by rabihmb** [comment]
Hello I cam from https://github.com/flutter/flutter/issues/23549 already applied the https://github.com/IhorKlimov/Flutter-One-Signal#notification-open-handler and still not working, is there any workaround? to open the notification if the app isn't running?

**Comment by rgomezp** [comment]
@rabihmb ,
Please see my previous comment and include your logs

**Comment by rabihmb** [comment]
@rgomezp 
Thank you for touching my comment. Kindly check my code below and the log file when receiving and opening the Notification.

```
    OneSignal.shared.setNotificationReceivedHandler((notification) {
      this.setState(() {
        print(
            "Received notification: \n${notification.jsonRepresentation().replaceAll("\\n", "\n")}");
      });
    });

    OneSignal.shared
        .setNotificationOpenedHandler((OSNotificationOpenedResult result) {
      this.setState(() {
        print(
            "Opened notification: ${result.notification.jsonRepresentation().replaceAll("\\n", "\n")}");

        getJSONData(result.notification.payload.additionalData['id'])
            .then((lResult) async {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => ArticleDetails(lResult[0]),
            ),
          );
        });
      });
    });
```

**Comment by jkasten2** [comment]
Can you try the latest 2.0.1 release? There were a number of threading issue resolved that may have fixed this issue. Make sure to follow the 2.0.0 upgrade guide to get the latest version
https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/2.0.0

**Comment by rabihmb** [comment]
> 
> 
> Can you try the latest 2.0.1 release? There were a number of threading issue resolved that may have fixed this issue. Make sure to follow the 2.0.0 upgrade guide to get the latest version
> https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/2.0.0

I have upgraded to version 2.0.0 then 2.01, with this release, can you confirm that the blank screen and stuck on splash screen are from the onesignal plugin as mentioned in a lot of threads such as 

https://github.com/flutter/flutter/issues/36365
https://stackoverflow.com/questions/54133443/flutter-app-opens-but-is-stuck-on-splash-screen/54133444#54133444
https://github.com/flutter/flutter/issues/22765

**Comment by StrawHt** [comment]
@jkasten2 I am on 2.0.0 and I have this issue for both ios/android. SetNotificationReceivedHandler is never called on tap.

**Comment by rgomezp** [comment]
@StrawHt ,
The notification tap will only trigger the onOpened handler

@rabihmb ,
This doesn't seem related to our SDK. If you could provide some logs that hint at it being related, we could perhaps have a better idea of how to help

**Comment by StrawHt** [comment]
@rgomezp  sorry i meant onOpenedHandler

Here are my logs. What I did: 
1. Launched app registered user.
2. Backgrounded App
3. Trigger notification from new Message from one signal console.
4. opened notification on android. 
5. app is opened; however, none of my breakpoints or print statements are hit.

https://pastebin.com/ZeFLHtVA

Here is my code snippet of my setup
https://pastebin.com/jtBNtb8y


pubspec.yaml
  onesignal_flutter: ^2.0.0

flutter doctor -v
[✓] Flutter (Channel master, v1.8.1-pre.10, on Mac OS X 10.14.5 18F203, locale
    en-US)
    • Flutter version 1.8.1-pre.10 at /Volumes/Data/Sources/flutter
    • Framework revision 556e374e02 (4 weeks ago), 2019-07-02 17:40:55 -0700
    • Engine revision 7d3e722349
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 67ab3be10d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jasonzheng/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9
      (API 28) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X
      10.14.5 18F203
    • Chrome                    • chrome        • web-javascript • Google Chrome
      75.0.3770.142 


• No issues found!


This occurs on iOS devices as well.

Breakpoints in my setNotificationReceivedHandler are not hit as well.

**Comment by rabihmb** [comment]
@rgomezp 

```
1. the app launched and registered.
2. I have 2 scenario:
   1. When I press on back button and then open the notification, it isn't working.
   2. When I press the cetnered button means the app is still running in backgrounded, it worked
```

My Log
https://pastebin.com/J1C1hqfz

My Code
https://pastebin.com/xKEcErQT

> in pubspec.yaml
> onesignal_flutter: ^2.0.1

for 

`flutter doctor -v`

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.239], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\Users\user1\Development\Android\Service\flutter
    • Framework revision 20e59316b8 (12 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\user1\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
```

**Comment by StrawHt** [comment]
await OneSignal.shared
        .setInFocusDisplayType(OSNotificationDisplayType.alert);
    final permissionGranted = await promptUserForPushNotificationPermission();
    print(permissionGranted);
    await OneSignal.shared.setExternalUserId(_userId);


looked into it a bit more and discovered setInFocusDisplayType, promptUserForPushNotificationPermission, setExternalUserId never return from the await.

when i unawaited these, my callbacks are set and hit correctly. I feel like this is a bug in OneSignal unless I'm using these incorrectly.

@rabihmb @rgomezp

**Comment by rgomezp** [comment]
@StrawHt ,
Yes, we are aware of the await issue, but this should have been fixed in the latest release. I will investigate what could have happened here.

@rabihmb ,
Thanks for the logs. We will investigate further

**Comment by rabihmb** [comment]
@StrawHt, I'm not using wait in my code and facing the same issue.

**Comment by mikechoch** [comment]
This will be fixed in the next release of the Flutter SDK. Issue was due to not destroying the callbacks when onDestroy is triggered (onBackPressed). Now we recycle the handlers for notification received, opened, and in app messaging action. Once the app opens up it will trigger with new handlers.

**Comment by christianarduino** [comment]
I've got the same problem. If the app is killed and I click on a notification, the `setNotificationOpenedHandler` callback is not invoked. If, on the other hand, I click on a notification and the app is open, there is no problem and the callback is called. No solution found?
I'm using onesignal ^2.6.3 version
